### ISSUE TITLE
Better syntax for checking file presence in tests

### ISSUE THREAD

**Issue by msarahan** [conda/conda-build#1013]
we currently do a lot of

`IF NOT EXIST <filename> exit 1  # [win]`

and the like.  @ilanschnell had the good idea that we should provide a different section in tests, something like `files_exist`, and remove the need for quite so much shell in meta.yaml.

**Comment by ilanschnell** [comment]
Thanks for writing that up.  Sometimes it is also important that certain files do *not* exist in the package.  So I would suggest having, e.g.:
```
test:
  files_exist:
    - lib/libfoo.la            [unix]
    - Library/lib/foo.a     [win]
  files_not_exist:
    - lib/libfoo.a             [unix]
```
