### ISSUE TITLE
Gotcha: noarch_python and preprocessing selectors [clarify in docs?]

### ISSUE THREAD

**Issue by Korijn** [conda/conda-build#1024]
_I couldn't find the docs on your github, otherwise I'd have opened a PR for this._

The key to understanding this issue, is that preprocessing selectors are executed _before_ the build (but at build-time), even for noarch recipes. For example, let's say I have a pure python package, with the following requirements:

``` yaml
build:
  noarch_python: True
  number: 0

requirements:
  build:
    - python
    - requests
    - futures  # [py2k]

  run:
    - python
    - requests
    - futures  # [py2k]
```

What you'll find is that if you build this recipe using a root conda environment that is based on python 2, the `futures` dependency will be included in the resulting package (stripping off the preprocessing selector in the process). If you build it using a root conda environment that is based on python 3, the `futures` dependency will not be included at all. So, this noarch package is actually dependent on the architecture of the build machine, instead of the environment in which it will be installed in the future.

This makes sense, given the implementation details of the preprocessing selectors feature, but users are inclined to think that this dependency is conditional on _install_ time. It's confusing! It would be an improvement to at least mention this in the docs, both under the noarch and the preprocessing selector sections, but it would be even better if conda-build issues warnings when you are building noarch packages with preprocessing selectors in the recipe.
