### ISSUE TITLE
Tests for packages with features fail

### ISSUE THREAD

**Issue by Zaharid** [conda/conda-build#1026]
I have a packgage called nnpdf_use_double, which tracks a feature of the same name. The meta.yaml is copied from the documentation:

```
package:
  # This name doesn't have to be the same as the feature, but can avoid confusion if it is
  name: nnpdf_use_double
  # This need not relate to the version of any of the packages with the
  # feature. It is just a version for this metapackage.
  version: 1.0

build:
  track_features:
      - nnpdf_use_double
```

When I try to build a package that depends on this feature, I cannot get past the tests:

```
package:
  # This name doesn't have to be the same as the feature, but can avoid confusion if it is
  name: xxx
  # This need not relate to the version of any of the packages with the
  # feature. It is just a version for this metapackage.
  version: 1.0

build:
  features:
      - nnpdf_use_double

test:
    requires:
        - python
    imports:
        - collections
```

Conda build fails with the error:

```
$ conda build xxx 

Removing old build environment
BUILD START: xxx-1.0-nnpdf_use_double_0
Package: xxx-1.0-nnpdf_use_double_0
no source
number of files: 0
Fixing permissions
Fixing permissions
BUILD END: xxx-1.0-nnpdf_use_double_0
TEST START: xxx-1.0-nnpdf_use_double_0
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: ............
Solving package specifications: ....
Error: The following specifications were found to be in conflict:
  - xxx 1.0 nnpdf_use_double_0
Use "conda info <package>" to see the dependencies for each package.
```
