### ISSUE TITLE
include_recipe key not recognized

### ISSUE THREAD

**Issue by elehcim** [conda/conda-build#1080]
Hello,
the `build` section of my meta.yaml file is:

```
build:
  number: 0
  binary_relocation: False
  include_recipe: False
  script_env:
    - ENV_VAR
```

I don't want to include the recipe in my package as documented [here](http://conda.pydata.org/docs/building/meta-yaml.html#include-build-recipe).

`conda-build .` fails with `Error: in section 'build': unknown key 'include_recipe'`.

I cannot understand why... Do you have any hints, or it is a bug?
Thank you

-----
It seems I have the latest conda-build
```
conda update conda-build
Fetching package metadata .......
# All requested packages already installed.
# packages in environment at /home/user/Software/anaconda3:
#
conda-build               1.21.3                   py35_0
```
