### ISSUE TITLE
The --output parameter output is not correct when a build hasn't been previously performed

### ISSUE THREAD

**Issue by joelhullcio** [conda/conda-build#1084]
Note the sequence below.
Delete the conda-bld directory, perform conda build --output . and the result does not include the GIT_DESCRIBE_TAG env var value in the version number as the recipe directs.  Only after running a build does the --output include the value correctly.

The user shouldn't have to perform a build to get the correct output value.

```
~/Projects/jeh/misc/conda.recipe/
git tag
1.1
~/Projects/jeh/misc/conda.recipe/
rm -rf /opt/anaconda/conda-bld/
~/Projects/jeh/misc/conda.recipe/
conda build --output .
/opt/anaconda/conda-bld/osx-64/jehmisc-0.0-0.tar.bz2
~/Projects/jeh/misc/conda.recipe/
conda build .
  .
  .
  .
~/Projects/jeh/misc/conda.recipe/
conda build --output .
/opt/anaconda/conda-bld/osx-64/jehmisc-1.1-0.tar.bz2
```

meta.yaml contents

```
package:
  name: jehmisc
  version: {{ environ.get('GIT_DESCRIBE_TAG', '0.0') }}

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  string: {{ environ.get('GIT_DESCRIBE_NUMBER', '0') }}

source:
  git_url: ../

requirements:
  build:
    - python

  run:
    - python
```
