### ISSUE TITLE
Conda Build Templates

### ISSUE THREAD

**Issue by srossross** [conda/conda-build#1095]
Perhaps it would be good to revamp the conda build template files. And make them a first class citizen:

Some ideas:
1. Load templates from `meta.yaml.template` this should result in a auto generated `meta.yaml`
   - This would result in better understanding of failed builds becuse of unclear template variables
2. Currently there are two passes of the  build:  1 - to fetch the build sources 2. to render the meta.yaml from the template. Perhaps we can make this more clear in the yaml file maybe using the `---` yaml syntax
   
   ``` yaml
   # File: meta.yaml.template
   # Required information
   # This can not be templated
   source: ...
   --- 
   # Template vars
   build: 
    number: {{ var }}
   ```
3. Allow for user contributed build extensions (conda packages) that can define template variables etc. eg:
   
   ```
   # File: meta.yaml.template
   source: ...
   build_ext_modules:
     - conda-build-etx-auto-build-numbers
   ---
   build:
      number: {{ my_great_build_number_generator() }}
   ```
   
   in this example `conda build .` would install/require the conda package `conda-build-etx-auto-build-numbers` to be installed into the root environment before the build starts.

cc @kalefranz @mcg1969
