### ISSUE TITLE
conda-build caches source tree too aggressively

### ISSUE THREAD

**Issue by pitrou** [conda/conda-build#1133]
Let's say I have the following recipe for easily testing changes locally:
```
package:
  name: mypkg
  version: {{ GIT_DESCRIBE_TAG }}

build:
  number: {{ GIT_DESCRIBE_NUMBER }}

source:
  path: ../

test:
  commands:
    - do_something
```

Unfortunately, if I built this recipe once and GIT_DESCRIBE_NUMBER doesn't change, whatever later changes I make in the source tree, conda-build will not pick them up and re-use the old source tree. I then have to manually set a bogus build number each time I change something in the source tree.

This also seems to be a regression, as I didn't encounter this before.
