### ISSUE TITLE
AttributeError: 'dict' object has no attribute 'partition'

### ISSUE THREAD

**Issue by Godley** [conda/conda-build#1170]
I'm trying to create a conda recipe for python-poppler-qt4 but they have a missing requirement which is sip so I can't do it using a skeleton, even though it's on pip. Having rolled my own meta file, I get the following stack trace:
<img width="602" alt="screen shot 2016-08-03 at 21 48 21" src="https://cloud.githubusercontent.com/assets/4128117/17381502/23cb4138-59c4-11e6-9af8-6343f474695e.png">

Here is the yaml file:
```
package:
    name: python-poppler-qt4
    version: 2.4.9

build:
    number: 0
    number: 2
    number: 3

requirements:
    build:
        - python
        - pip
        - pip:
            - sip
            - python-poppler-qt4


about:
    home: https://github.com/wbsoft/python-poppler-qt4
    license: LGPL
```

Here's the output of conda info:
<img width="602" alt="screen shot 2016-08-03 at 21 53 57" src="https://cloud.githubusercontent.com/assets/4128117/17381649/dd5b5304-59c4-11e6-8db6-8441b0b6cafe.png">

Any pointers?
