### ISSUE TITLE
pin ABI version of dll dependency at build time

### ISSUE THREAD

**Issue by minrk** [conda/conda-build#1176]
I want this for pyzmq, but I think it’s pretty general (I know @SylvainCorlay has encountered it).

When a package links a DLL, it will only work with the ABI version of that dependency that it loaded at build time. Many packages (e.g. pyzmq) are quite flexible in what versions of those DLLs they _can_ build against, and conda recipes tend to reflect this flexibility. However, that makes it possible to do things like install pyzmq-15.3 and zeromq-4.0, which won’t work because pyzmq-15.3 was built against zeromq-4.1 which has a different ABI than zeromq-4.0, and will fail to load.

The pattern that makes the most sense to me is to leave the build dependency open, but then pin the _runtime_ dependency based on the version loaded at build time. I think conda doesn’t actually record ABI versions, only package versions, but I’m guessing that’s an okay approximation in most cases.

Right now, [what I’m trying](https://github.com/conda-forge/pyzmq-feedstock/pull/11) is pinning the upstream dependency explicitly in meta.yml, which ought to work, but is more restrictive than should really be necessary at the recipe level.

Here’s what I’m imagining in `meta.yml`:

``` yaml

requirements:
  build:
    - liba
    - libb
    - libc
  runtime:
    - liba build.x*
    - libb build.xy*
    - libc ==build.xyz
```

Where `liba build.x` would resolve as the major version of liba at build time, `libb build.xy` as major.minor of libb, `build.xyz` as full version of libc, etc.

Perhaps simpler to implement would be a separate dependency _category_, along the lines of:

``` yaml
dependencies:
  runtime_build_version:
    major:
      - liba
    minor:
      - libb
```

but that’s not as nice or flexible as allowing substitutions into the existing version resolution spec.

In general, I think it would be appropriate for conda-build to record the _exact_ versions of all packages loaded in the build env (including channels) in the package metadata, if it’s not already doing so.
