### ISSUE TITLE
conda build --output should not check out sources

### ISSUE THREAD

**Issue by whitequark** [conda/conda-build#1211]
It used not to, but at some point that changed, and now trying to figure where the built package is wastes a lot of time.

**Comment by msarahan** [comment]
conda build should only be downloading source if it is necessary to render the recipe.  Do you use git variables in your jinja2 templates?  If so, you have to download the source before your recipe's build string can be determined.

**Comment by whitequark** [comment]
No. This is the complete `meta.yaml` file, for the reference:
```
package:
  name: rustc
  version: "1.12.0"

source:
  git_url: https://github.com/m-labs/rust
  git_rev: artiq

build:
  number: 1

requirements:
  build:
    - system [linux]
    - cmake
    - llvm-or1k
    - curl
  run:
    - system [linux]
    - llvm-or1k

about:
  home: http://rust-lang.org/
  license: MIT/Apache
  summary: A safe, concurrent, practical language
```
