### ISSUE TITLE
Creating split/derived packages

### ISSUE THREAD

**Issue by jhunkeler** [conda/conda-build#1223]
[x-post from Anaconda mailing list]

Will conda-build ever support the ability to generate derived packages 
from a single recipe? I understand it's a bit more complex than this: 

## pseudo-recipe

```yaml
name: stuff 
version: 1.0.0 
derivative: 
     - a: 
         - '$PREFIX/bin/a_*' 
         - '$PREFIX/lib/liba*.so' 
     - b: 
         - '$PREFIX/bin/b_*' 
         - '$PREFIX/lib/libb*.so' 
```

## pseudo-script

```bash
./configure --prefix=$PREFIX 
make install 
```

## pseudo-build

```bash
$ conda build stuff/ 
BUILD START: stuff-1.0.0 
BUILD DERIVED: stuff-a-1.0.0 
BUILD DERIVED: stuff-b-1.0.0 
BUILD END: stuff-1.0.0 
```

## produces

```
stuff-1.0.0.tar.bz2 
stuff-a-1.0.0.tar.bz2 
stuff-b-1.0.0.tar.bz2 
```

## internal composition

```
stuff-1.0.0.tar.bz2: 
     bin/c_thing1 
     bin/c_thing2 
     lib/libcthings.so 

stuff-a-1.0.0.tar.bz2: 
     bin/a_thing1 
     bin/a_thing2 
     lib/libathings.so 

stuff-b-1.0.0.tar.bz2 
     bin/b_thing1 
     bin/b_thing2 
     lib/libbthings.so 
```

## conda composition

```python
{ name: 'stuff', version: '1.0.0', depends: [''] } 
{ name: 'stuff-a', version: '1.0.0', depends: ['stuff'] } 
{ name: 'stuff-b', version: '1.0.0', depends: ['stuff'] } 
```

Regards, 
Joe 

@msarahan's response attached for consolidation's sake:

> Hi Joe,
> 
> We don't have solid plans, but yes, "split packages" or derived packages are definitely something that I want to add.
> 
> Presently it is slated for the major release after the pending 2.0 release.
> 
> Conda-build's road map is at https://docs.google.com/document/d/1Xc_DGM6PEOAR0IPtlBn-yph2vZqTzYoVeh0ObBEjLkw/edit?usp=sharing - and anyone should be able to comment there.
> 
> If you want to see this sooner, please write up your initial thoughts (like you've done here) in a conda-build issue.  We'll link any PRs to that issue, to keep discussion consolidated.
