### ISSUE TITLE
Split packages proposal

### ISSUE THREAD

**Issue by msarahan** [conda/conda-build#1338]
@mingwandroid and I have been discussing split packages as an urgent prerequisite to enabling easier construction of build toolchains (perhaps with crosstools-ng, http://crosstool-ng.org/)

In coming up with ideas for implementation, we're looking at precedent set by Linux distributions.
- Arch: Defines list of packages to be built in pkgname field (bash array).  Bash functions have a specific form that connects them with package names.  Example: https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/gcc#n7
- Red Hat: "subpackages" - http://www.rpm.org/max-rpm/s1-rpm-subpack-spec-file-changes.html - explicit lists of files.
- Debian: Makefile based.  Additional targets specified in makefile and in helper files. https://wiki.debian.org/PkgSplit and http://php-java-bridge.cvs.sourceforge.net/viewvc/php-java-bridge/php-java-bridge/debian/rules?view=markup and http://php-java-bridge.cvs.sourceforge.net/viewvc/php-java-bridge/php-java-bridge/debian/

What we have as initial design ideas for conda-build are:
- Change the name field to allow lists.  Each entry is a separate package.  These entries would be used to select logic for installation in the shell scripts.

```
package:
  name:
    - somename_somefeature1
    - somename_somefeature2
```
- Alternatively, Keep the name field the same, but add an "outputs" field that lists other outputs.  If not specified, defaults to normal conda package output.

```
package:
  name: somename
  outputs:
    - somefeature1
    - somefeature2
```
- Prefer automatic collection of files, as is done now, over explicit lists of files.  After each install+packaging step, the files would be removed from the build prefix.
- Prefer functions defined in central shell/batch scripts (as opposed to several scripts), but have conda-build call the correct function/subroutine based on output name.
- Alternatively, have outputs list as dictionary instead, with values being scripts to run for packaging.

CC @pelson @ocefpaf @janschulz - we wanted to involve you, given your involvement with some of these systems.  Do you have opinions or battle scars to share?  Naming is all negotiable here at this point - if something like the "outputs" field seems like a good idea with a bad name.

**Comment by janschulz** [comment]
My "ideas" are in https://github.com/conda/conda/issues/793#issuecomment-174446435 I would prefere a file based package split:

[Rest ist form the linked comment:]


I would find it better if there is an additional way to add binary packages, which can take specific files and the rest is taken by the main package. Like:

```
package:
  name: mypackage
  version: 1.0.0

  requirements:
    build:
     # build requirements are for all packages...
      - python
      - .... all the rest, including the qt dependencies...

    run:
      - python
      - numpy

binary-package:
  name: mypackage-pyqt
  run-requirements:
       - pyqt
       - matplotlib {PACKAGE_VERSION} # replaced by the complete version of this package
  files:
        include: 
          - pyqt/*.*
        exclude:
          - pyqt/README.md

binary-package:
  name: mypackage-docs
  run-requirements:
       - matplotlib {PACKAGE_VERSION} # replaced by the complete version of this package
  files:
        include: 
          - docs/*.*
        exclude:
          - docs/README.md

binary-package:
  name: mypackage-tests
  run-requirements:
       - nose
       - mock
       - matplotlib {PACKAGE_VERSION} # replaced by the complete version of this package
  files:
        include: 
          - src/matplotlib/tests
```

This would build 4 packages: mypackage-tests, mypackage-docs, mypackage-pyqt and mypackage. Each package can be installed as a normal package... In this case, the three additional packages depend on the exact version of main package, so that updates to e.g mypackage-pyqt will also update the main package and keep them in sync.

See also the debian dir for the matplotlib debian package, which works similar, only the above info is split across multiple files: https://anonscm.debian.org/cgit/python-modules/packages/matplotlib.git/tree/debian

- `control` defines the packages and their dependencies
- `*.install` tells the build process, which files belong to which package

**Comment by msarahan** [comment]
Thanks @janschulz 

I have thought about your idea, and come up with this syntax that I hope captures most or all of what you want, along with some additions:

```
        outputs:
            - name: filename
              script: script file or list of commands to install files into the build prefix
              script_interpreter: program to use to run script (optional.  Limited autodetection
                                                                when not provided.)
              type: (optional, to support wheel/rpm/deb output someday, defaults to 'conda' for
                        conda package)
              noarch: (optional string identifier of noarch variety)
              requirements: (optional list of runtime requirements for installing the output file)
              test:
                  requirements: (same as conda-build recipe)

                  script: script file or list of commands to execute for testing
                  script_interpreter: program to use to run script (optional. autodetection when
                                                                    not provided)

            # It should be possible to use Jinja2 here to fill in things like the parent package
            #    name and build string, where desired:
            - name: {{ PKG_NAME }}-src_{{ CONDA_BUILD_STRING }}
            # Alternatively, build string could be computed just from runtime dependencies
```

- I want all outputs or binary-packages under a single key for easier iteration over them.
- I think each package should be independently testable (to make sure that you've included everything you need to, for example)
- This syntax allows people to either just copy files, or to install files and let conda take care of it.  The core idea is just that however you move things into the build prefix to get detected is up to you.
- I think that for simplicity, we probably should have these outputs be in addition to the main output, which retains its default behavior, and which is built and packaged prior to any additional outputs, with the thinking that subsequent outputs may use the primary output.
- The script and script_interpreter stuff is meant to facilitate running bash on windows, for example.
- The type is something of a placeholder to help in future specification of building wheels, for example.
- noarch spec is because some packages (like source packages or test data) will be noarch, while others might be specialized.  noarch string stuff is in #1285 and #1334 

CC @jjhelmus - for wheels.

**Comment by msarahan** [comment]
In discussion with @mingwandroid, he would like to be able to take something like thrift, which has several language backends supported, and break out the backends within one recipe.  I think this will not work well, because each backend may then be split further (for example, Python 2.7/3.4/3.5).  I think that a constraint here is a one-to-one mapping between output entries in the recipe and outputs.  Additionally, although the script entry may be used to build arbitrarily and deploy, I would discourage it, as it skirts most of conda-build's logic for setup and such, and ultimately may not work well.

**Comment by janschulz** [comment]
Do I understand that right that if I want to split a package, e.g. libpng into header and library, I would have to create two install scripts and would need to compile+install it twice plus different "deletes" in PRefix to get the right filesets? If so: how would that handle longrunning builds of big libs which would now need to be done twice?

I still think using something like 

```
build:
     [whatever was done before

outputs:
            - name: filename
              filelist: [globs*, files] # instead of scripts
              type: [... rest of your proposal...]
            - name: xxxx
              filelist: [...]
              include-leftover-files: True # optional, only once, gets all the files which are not in other packages
```
[This is inspired by the debian system of splitting a package]
