### ISSUE TITLE
conda build 2.0.0 - change in how test files found/copied over braking test step

### ISSUE THREAD

**Issue by davidslac** [conda/conda-build#1369]
With conda-build 2.0.0, the test part of my recipe is failing. What I had was, for building openmpi
```
test:
  files:
    - test/helloworld.c
    - test/helloworld.cxx
  commands:
    - mpicc  helloworld.c   -o helloworld_c
    - mpicxx helloworld.cxx -o helloworld_cxx
```
but now I get an error message when it gets to the test, that it can't find helloword.c

That is, before, I specified a file in dirA/file, and I got "file" in my test directory, but it is not there anymore, is it in "test/file?" Also in the build test, the package openmpi has its own test directory  - it that cause problems, but this is the test step so it shouldn't

On the conda documentation page http://conda.pydata.org/docs/building/meta-yaml.html#test-section I see that I should do 
```
test:
  source_files:
    - test-data.txt
    - some/directory
    - some/directory/pattern*.sh
```
what is the difference between a source_file and a file? And in any case it is not working, I keep getting error messages like
```
('Did not find any source_files for test with pattern %s', u'helloworld.c')
```
in that case, I had removed the test subdirectory of my recipe, and was trying to get things that were in the same directory as the meta.yaml, etc
