### ISSUE TITLE
Jinja errors in package name evaluation are masked

### ISSUE THREAD

**Issue by ma-ba** [conda/conda-build#1378]
Jinja errors inside package name expression are overridden / masked by `Error: package/name missing in ...`. See:
```yaml
package:
  name: {{ some_erroneous_expression }}
```
```bash
+(root) $ conda build --no-anaconda-upload . 1>/dev/null 
Error: package/name missing in: '/home/maba/dev/conda/conda-build/bugs/jinja-package-name-error-masked/meta.yaml'
```
Notice that errors for other fields are not masked:
```yaml
package:
  name: some_package
  version: {{ some_erroneous_expression }}                                                                               
```
```bash
+(root) $conda build --no-anaconda-upload . 1>/dev/null 
Undefined Jinja2 variables remain (['some_erroneous_expression']).  Please enable source downloading and try again.
```
