### ISSUE TITLE
Cannot set package name from load_setup_py_data()['name']

### ISSUE THREAD

**Issue by ma-ba** [conda/conda-build#1379]
`conda-build` fails if package name is set from `setup.py` data using Jinja. See:
```python
# setup.py
from setuptools import setup
setup(name='package_name')
```
```yaml
# meta.yaml
{% set data = load_setup_py_data() %}
package:
  name: {{ data['name'] }}
source:
  path: ./
```
```bash
+(root) $ conda build --no-anaconda-upload . 1>/dev/null
Error: package/name missing in: '/home/maba/dev/conda/conda-build/bugs/jinja-setup-py-name/meta.yaml'
```
Concerning the inaccurate error message see #1378.

However, loading using `from_recipe_dir=True` works:
```yaml
# meta.yaml
{% set data = load_setup_py_data(from_recipe_dir=True) %}
package:
  name: {{ data['name'] }}
source:
  path: ./
```
```bash
+(root) $ conda build --no-anaconda-upload . 1>/dev/null
```

**Comment by ma-ba** [comment]
BTW: This also breaks `conda_build/templates/setuptools.yaml` which uses:
```jinja
{% set data = load_setup_py_data()%}
{% block body -%}
{% block package -%}
package:
  name: {{data.get('name').lower().replace(' ', '_')}}
...
```
In consequence `example_packages/setuptools/conda.yaml` is broken since it consists of:
```jinja
{% extends "setuptools.yaml" %}
```

**Comment by ma-ba** [comment]
This issue will be resolved once #1379 is resolved by #1395.

**Comment by lijunzh** [comment]
This problem re-occurred for me.

I have `meta.yaml` as following:

```
{% set data = load_setup_py_data() %}
package:
    name: {{ data['name'] }}
    version: {{ data['version'] }}

source:
    path: .
```

It throws error:

```
Error: package/name missing in: '/Users/lijun/git/vision/meta.yaml'
```

but when I type in the package name explicitly as 
```
{% set data = load_setup_py_data() %}
package:
    name:  vision
    version: {{ data['version'] }}

source:
    path: .
```

It works.


My `conda build` version is as follows:
```
$ conda build --version
conda-build 3.12.0
```
