### ISSUE TITLE
`test source_files` does not create intermediate directories

### ISSUE THREAD

**Issue by jhprinz** [conda/conda-build#1510]
I have the following part in my `meta.yml`

```yml
test:
  source_files:
    - ipynbtest/examples/ipynbtest_tutorial.ipynb
```

This fails with an error like: (I replaced my homefolder with `~` there are actually absolute paths)
```
IOError: [Errno 2] No such file or directory: u'~/anaconda/conda-bld/conda-recipe_1478272007306/test_tmp/ipynbtest/examples/ipynbtest_tutorial.ipynb'
```

After some digging it turns out that the problem is that in `test_tmp` there is no `examples` directory and hence the 

```
  File "~/anaconda/lib/python2.7/site-packages/conda_build/create_test.py", line 69, in create_files
    copy_into(f, f.replace(config.work_dir, config.test_dir), config.timeout)
```

can find the source but not open the destination

```
  File "~/anaconda/lib/python2.7/shutil.py", line 83, in copyfile with open(dst, 'wb') as fdst:
```

When change the part in `meta.yaml` to 

```yml
test:
  source_files:
    - ipynbtest/examples/*.ipynb
```

it also _fails_ whereas 

```yml
test:
  source_files:
    - ipynbtest/examples
```

it works. 

My conclusion is that this needs to be either well documented or better the intermediate folders needs to be created. This should be an easy fix if so desired.
