### ISSUE TITLE
Allow setting environment variable *values* to pass to build scripts (via `script_env`)

### ISSUE THREAD

**Issue by tadeu** [conda/conda-build#1553]
Currently, it is only possible to allow environment variables to "pass through" to the build scripts, by putting the environment variable names in the `build/script_env` list in `meta.yaml`.

This proposal is to allow setting the values too, something like one of these options:

1.
```yaml
build:
  script_env:
    - MYVAR
    - ANOTHER_VAR
    - CONFIG_VAR=some value
    - ANOTHER_CONFIG_VAR=some other value
```

2.
```yaml
build:
  script_env:
    - MYVAR
    - ANOTHER_VAR
    - CONFIG_VAR: some value
    - ANOTHER_CONFIG_VAR: some other value
```

3.
```yaml
build:
  script_env:
    - MYVAR
    - ANOTHER_VAR
  script_env_with_values:  # <-- could be a better name
    CONFIG_VAR: some value
    ANOTHER_CONFIG_VAR: some other value
```

Advantage of 1 is that it is still a list of strings, disadvantage is that we have to parse the string to see if it has an `=`, and this may be a problem because on unix environment variables are allowed to have `=` in their names (through escaping).

Advantage of 2 is that is seems the most pretty, and yaml does the parsing for us. Disadvantage is that it is weird, because it is a list of strings or dicts. What if the user pass a dict with more than one element?

Advantage of 3 is that is seems very well-formed and type safe. Disadvantage is that it seems verbose.

I'm willing to work on a PR, any though on which format should be chosen?

This is very useful for when we have some jinja2 configuration variables in the `meta.yaml` (e.g., some extra version information that do not go in the $PKG_VERSION variable), and we want to pass it to the build scripts, e.g.:

```yaml
{%- set version="6.3" -%}
{%- set version_year_and_patch="2016.123" -%}

# ...

build:
  script_env:
    - MYVAR
    - ANOTHER_VAR
    - VERSION_YEAR_AND_PATCH: {{ version_year_and_patch }}  # e.g., to be used to find some directories
```

**Comment by msarahan** [comment]
May I propose a 4th format:

```
build:
  script_env:
    - name: MYVAR
    - name: ANOTHER_VAR
    - name: CONFIG_VAR
       value: some value
    - name: ANOTHER_CONFIG_VAR
       value: some other value
```

In other words, every entry is a dictionary that must have a name entry.  It can optionally have a value entry.  This has the downside of not being backwards compatible, but avoids the frankenstein of 2 and the keyword proliferation of 3.

The general concern with setting variable values in meta.yaml is the potential conflict with any existing setting for environment variables.  What is your proposed scheme for clobbering or merging these?  As long as it is well-defined or specifiable in the meta.yaml file somehow, I don't think it matters exactly what the behavior is.

**Comment by tadeu** [comment]
I didn't want to break the API (and backwards compatibility) for something this simple, but if you think it is best, then ok :).

> The general concern with setting variable values in meta.yaml is the potential conflict with any existing setting for environment variables.

At first I didn't think about merging existing values (such as adding things to PATH), just overwriting the values (if they are already defined). Merging could be done by the user in different ways using `jinja`.

**Comment by msarahan** [comment]
@tadeu sorry, I somehow missed your response here.  I'm fine with your option 2 for now.  I think the type detection isn't too hairy, and maintaining backwards compatibility is really key.  I welcome the PR whenever you have time.  Please include tests of the functionality, as well as tests of anticipated schemes for merging values.

**Comment by jakirkham** [comment]
Deja vu.

xref: https://github.com/conda/conda-build/pull/767

**Comment by ltalirz** [comment]
I just stumbled upon this issue via google, and [it seems to me](https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#use-environment-variables) that defining values via option 1

```yaml 
build:
  script_env:
    - MYVAR
    - ANOTHER_VAR
    - CONFIG_VAR=some value
    - ANOTHER_CONFIG_VAR=some other value
```

is now supported. I guess this issue can be closed?
