### ISSUE TITLE
Buildstring "pyXY" ommited when python version is fixed in Recipe

### ISSUE THREAD

**Issue by sscherfke** [conda/conda-build#1558]
I'm not sure whether this is a bug or a feature, but if you fix the the Python version in your recipe like this:
```yaml
requirements:
  build:
    - python >=3.5
    # - python 3*  # Results in the same behavior
  run:
    - python >=3.5
    # - python 3*  # Results in the same behavior
```
then the packages built with `conda build` will have no build string, only a version and build number (like `a.b.c-d`.

If you remove the version specifiers and only use `- python` as requirement, you will get (as exepcted) a build string: `a.b.c-pyXY_d`.

The problem with the former one is, that the package looks Python-agnostic when in fact, the files will get installed into `lib/pythonX.Y/site-packages` and will thus only be available for the interpreter version that was used for building the package.
