### ISSUE TITLE
Cannot parse meta.yaml

### ISSUE THREAD

**Issue by ilfrich** [conda/conda-build#1618]
I just upgraded from conda-build 2.0.12 to 2.1.0 and since that a `conda build <directory>` fails with the following error:

```
...
number of files: 2
Fixing permissions
Fixing permissions
updating index in: /Users/ilfrich/miniconda2/conda-bld/osx-64
updating: myclient-1.0.0-py27_3.tar.bz2
----------------------------------------------------------------------
Unable to parse meta.yaml file

Error Message:
--> while parsing a block node
--> did not find expected node content
-->   in "<unicode string>", line 1, column 1
```

This happens to any package I try to build, which previously was no problem (with 2.0.12).

My environment:

```
               platform : osx-64
          conda version : 4.2.13
       conda is private : False
      conda-env version : 4.2.13
    conda-build version : 2.1.0
         python version : 2.7.12.final.0
```

Nothing special to the meta.yaml, simple project, setup.py, 1 package, 1 script, 1 `run` dependency

**Comment by msarahan** [comment]
Please post any example recipe that you can.

**Comment by ilfrich** [comment]
Ok, after a bit of debugging I narrowed it down to the existence of a `.git` folder in the module directory. I could replicate this behaviour with every module I tested with:

```bash
# clone a module repository
git clone <some module repo>
cd repo
# this will fail with 'Unable to parse meta.yaml file'
conda build .
# get rid of the .git folder
rm -rf .git
# now the build passes without problems
conda build .
```

The .git folder shouldn't prevent from building. Also the error message is misleading. I spend an hour or more playing around with the meta.yaml, because the error said so.

One of my meta.yaml:

```yaml
package:
    name: mypackagename
    version: "1.0.0"

source:
    path: .

build:
    number: 3

requirements:
    build:
        - python
    run:
        - python
        - requests

about:
    home: "git@github.com:top/secret.git"
    license: "MIT"
```
