### ISSUE TITLE
empty lists in meta.yaml

### ISSUE THREAD

**Issue by ddale** [conda/conda-build#166]
Conda raises errors when it encounters an empty list in meta.yaml. But empty lists may be unavoidable. For example, selectors can yield an empty list on a particular platform:

``` yaml
build:
  binary_has_prefix_files:
    - lib/foo.so # [linux]
```

which would yield an error on osx:

`Error: build/binary_has_prefix_files should be a list of paths`
