### ISSUE TITLE
noarch_python packages are not placed in noarch folder 

### ISSUE THREAD

**Issue by jjhelmus** [conda/conda-build#1679]
Packages build with the `build/noarch_python` option set to `True` seem to be placed in a platform specific folder (i.e. linux-64) rather than the noarch folder.  

For example:

```
$ rm -f ~/anaconda/conda-bld/noarch/* ~/anaconda/conda-bld/linux-64/*
$ conda build .
BUILD START: imagesize-0.7.1-py_0
updating index in: /home/jhelmus/anaconda/conda-bld/linux-64
removing: imagesize-0.7.1-py_0.tar.bz2
updating index in: /home/jhelmus/anaconda/conda-bld/noarch

The following NEW packages will be INSTALLED:

    openssl:    1.0.2j-0      defaults
    python:     3.6.0-0       defaults
    readline:   6.2-2         defaults
    setuptools: 27.2.0-py36_0 defaults
    sqlite:     3.13.0-0      defaults
    tk:         8.5.18-0      defaults
    xz:         5.2.2-1       defaults
    zlib:       1.2.8-3       defaults

Source cache directory is: /home/jhelmus/anaconda/conda-bld/src_cache
Found source in cache: imagesize-0.7.1.tar.gz
...
running install_scripts
writing list of installed files to 'record.txt'
compiling .pyc files...
number of files: 8
Fixing permissions
Fixing permissions
/home/jhelmus/anaconda/conda-bld/linux-64/imagesize-0.7.1-py_0.tar.bz2
updating index in: /home/jhelmus/anaconda/conda-bld
updating index in: /home/jhelmus/anaconda/conda-bld/noarch
updating index in: /home/jhelmus/anaconda/conda-bld/linux-64
updating: imagesize-0.7.1-py_0.tar.bz2
updating index in: /home/jhelmus/anaconda/conda-bld
Nothing to test for: imagesize-0.7.1-py_0
...
$ ls ~/anaconda/conda-bld/noarch/
repodata.json  repodata.json.bz2
$ ls ~/anaconda/conda-bld/linux-64/
imagesize-0.7.1-py_0.tar.bz2  repodata.json  repodata.json.bz2

```

recipe in question is:

``` yaml
package:
  name: imagesize
  version: 0.7.1

source:
  fn: imagesize-0.7.1.tar.gz
  url: https://pypi.io/packages/source/i/imagesize/imagesize-0.7.1.tar.gz
  sha256: 0ab2c62b87987e3252f89d30b7cedbec12a01af9274af9ffa48108f2c13c6062

build:
  number: 0
  noarch_python: True
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
```

conda info is as follows:

```
$ conda info
Current conda install:

               platform : linux-64
          conda version : 4.3.5
       conda is private : False
      conda-env version : 4.3.5
    conda-build version : 2.1.1
         python version : 3.5.2.final.0
       requests version : 2.12.4
       root environment : /home/jhelmus/anaconda  (writable)
    default environment : /home/jhelmus/anaconda
       envs directories : /home/jhelmus/anaconda/envs
          package cache : /home/jhelmus/anaconda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /home/jhelmus/.condarc
           offline mode : False
             user-agent : conda/4.3.5 requests/2.12.4 CPython/3.5.2 Linux/4.4.0-59-generic debian/stretch/sid glibc/2.23
                UID:GID : 5001:1004
```
