### ISSUE TITLE
conda-build >= 2.1.6 deletes environment variables

### ISSUE THREAD

**Issue by sscherfke** [conda/conda-build#1851]
Conda-build >= 2.1.6 seems to unset environment variables causing builds to fail.

To reproduce, simply create a recipe that has something like this in its test section:
```yaml
test:
  commands:
    - python -c "import os; print('ENV VAR:', os.getenv('TEST_BEFORE_DEPLOY'))"
```
and run
```bash
export TEST_BEFORE_DEPLOY=lolno
conda build recipe/
```
With conda-build 2.1.5 the expected value of the env var is printed, with conda-build 2.1.6 and 2.1.7 `None` is printed.
