### ISSUE TITLE
conda-build 2.1.7-py35_0 test command exit codes are ignored on windows

### ISSUE THREAD

**Issue by Korijn** [conda/conda-build#1860]
exactly as the title describes;

```yaml
test:
  commands:
  - py.test -n2 --pyargs mylib --durations=3
```

if that test run fails, it returns exit code 1, and yet, the build passes
