### ISSUE TITLE
Build python not respected for jinja

### ISSUE THREAD

**Issue by njalerikson** [conda/conda-build#1885]
I have a meta.yaml that uses jinja2 to get the version number. The super exciting twist is that my root conda is Python 2.7 however the recipe needs to be built for Python 3.6.

So when I say `conda build --python=3.6 ...` the build terminates almost immediately due to syntax errors (classic 2.7 vs 3+ errors).

What is happening is that conda build tries to use the root python for the jinja2 parsing, not Python 3.6 that is defined as a requirement on the command line but also as a requirement in the meta.yaml.

```
{% set data = load_setup_py_data() %}

package:
  name: hypcore
  version: {{ data.get('version') }}

...

requirements:
  build:
    - python >=3.6
  run:
    - python >=3.6
```

The build works without any issues if I remove the jinja clauses.

In some ways this is related to #1439.
