### ISSUE TITLE
conda skeleton pypi fails setuptools patch

### ISSUE THREAD

**Issue by jakirkham** [conda/conda-build#1917]
Seems that `conda skeleton pypi` is expecting `setuptools` to already exist when it does its magic. Though I have `add_pip_as_python_dependency` disabled in my `.condarc`. Basically this issue seems to exist in `conda-build` 2.1.5+. In 2.1.4 it doesn't occur. Traceback and environment details below.

Traceback:

<details>

```bash
$ conda skeleton pypi pillow
pillow not found, trying Pillow
Warning, the following versions were found for Pillow
1.7.8
4.0.0
4.1.0
Using 4.1.0
Use --version to specify a different version.
Using url https://pypi.python.org/packages/80/38/5cb561c68155834c596018c47caa44da88ed34b09579b921c0e493fb06c7/Pillow-4.1.0.tar.gz (10.7 MB) for Pillow.
Downloading Pillow
Unpacking Pillow...
done
working in /var/folders/jj/pp1xwt1n4zdgy9zxbxc22t8w66tr7q/T/tmpQvmW7Tconda_skeleton_Pillow-4.1.0.tar.gz

The following NEW packages will be INSTALLED:

    ca-certificates: 2017.1.23-0 conda-forge
    ncurses:         5.9-10      conda-forge
    openssl:         1.0.2k-0    conda-forge
    python:          2.7.13-0    conda-forge
    pyyaml:          3.12-py27_1 conda-forge
    readline:        6.2-0       conda-forge
    sqlite:          3.13.0-1    conda-forge
    tk:              8.5.19-1    conda-forge
    yaml:            0.1.6-0     conda-forge
    zlib:            1.2.11-0    conda-forge

Applying patch: '/var/folders/jj/pp1xwt1n4zdgy9zxbxc22t8w66tr7q/T/tmpQvmW7Tconda_skeleton_Pillow-4.1.0.tar.gz/pypi-distutils.patch'
patching file core.py
Hunk #1 succeeded at 169 with fuzz 2 (offset 2 lines).
Traceback (most recent call last):
  File "setup.py", line 21, in <module>
    from setuptools import Extension, setup, find_packages
ImportError: No module named setuptools
$PYTHONPATH = /var/folders/jj/pp1xwt1n4zdgy9zxbxc22t8w66tr7q/T/tmpQvmW7Tconda_skeleton_Pillow-4.1.0.tar.gz/Pillow-4.1.0
Error: command failed: /Users/kirkhamj/build_artefacts/skeleton_1491943726158/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/bin/python setup.py install
```

</details>

<br>
Environment info:
<br>
<br>

<details>

```yaml
name: root
channels: !!python/tuple
- !!python/unicode
  'conda-forge'
- !!python/unicode
  'defaults'
dependencies:
- conda-forge::anaconda-client=1.5.1=py27_0
- conda-forge::anaconda-verify=1.2.0=py27_0
- conda-forge::appnope=0.1.0=py27_0
- conda-forge::backports.shutil_get_terminal_size=1.0.0=py27_1
- conda-forge::beautifulsoup4=4.5.3=py27_0
- conda-forge::ca-certificates=2017.1.23=0
- conda-forge::certifi=2017.1.23=py27_0
- conda-forge::cffi=1.7.0=py27_0
- conda-forge::chardet=2.3.0=py27_0
- conda-forge::clyent=1.2.1=py27_0
- conda-forge::conda=4.2.13=py27_0
- conda-forge::conda-build=2.1.9=py27_0
- conda-forge::conda-build-all=1.0.3=py27_0
- conda-forge::conda-env=2.6.0=0
- conda-forge::conda-execute=0.8.0=py27_1
- conda-forge::conda-verify=2.0.0=py27_0
- conda-forge::constructor=1.3.4=py27_0
- conda-forge::contextlib2=0.5.4=py27_0
- conda-forge::coverage=3.7.1=py27_1
- conda-forge::curl=7.52.1=0
- conda-forge::decorator=4.0.11=py27_0
- conda-forge::enum34=1.1.6=py27_1
- conda-forge::expat=2.1.0=2
- conda-forge::filelock=2.0.6=py27_0
- conda-forge::funcsigs=1.0.2=py27_0
- conda-forge::futures=3.0.5=py27_0
- conda-forge::gitdb=0.6.4=py27_1
- conda-forge::gitpython=2.1.1=py27_0
- conda-forge::idna=2.1=py27_0
- conda-forge::ipaddress=1.0.16=py27_0
- conda-forge::ipython=5.3.0=py27_0
- conda-forge::ipython_genutils=0.2.0=py27_0
- conda-forge::jinja2=2.9.5=py27_0
- conda-forge::libconda=4.0.0=py27_0
- conda-forge::libffi=3.2.1=3
- conda-forge::markupsafe=0.23=py27_1
- conda-forge::mock=2.0.0=py27_0
- conda-forge::ncurses=5.9=10
- conda-forge::nose=1.3.7=py27_2
- conda-forge::openssl=1.0.2k=0
- conda-forge::pathlib2=2.2.1=py27_0
- conda-forge::pbr=2.0.0=py27_0
- conda-forge::pexpect=4.2.1=py27_0
- conda-forge::pickleshare=0.7.3=py27_0
- conda-forge::pip=9.0.1=py27_0
- conda-forge::pkginfo=1.2.1=py27_0
- conda-forge::prompt_toolkit=1.0.14=py27_0
- conda-forge::psutil=5.2.1=py27_0
- conda-forge::ptyprocess=0.5.1=py27_0
- conda-forge::pyasn1=0.2.3=py27_0
- conda-forge::pycosat=0.6.1=py27_0
- conda-forge::pycparser=2.17=py27_0
- conda-forge::pycrypto=2.6.1=py27_0
- conda-forge::pygithub=1.29=py27_0
- conda-forge::pygments=2.2.0=py27_0
- conda-forge::pyopenssl=16.2.0=py27_0
- conda-forge::python=2.7.13=0
- conda-forge::python-dateutil=2.6.0=py27_0
- conda-forge::pytz=2017.2=py27_0
- conda-forge::pyyaml=3.12=py27_1
- conda-forge::readline=6.2=0
- conda-forge::requests=2.13.0=py27_0
- conda-forge::ruamel.ordereddict=0.4.6=py27_0
- conda-forge::ruamel.yaml=0.14.5=py27_0
- conda-forge::ruamel_yaml=0.11.14=py27_0
- conda-forge::scandir=1.5=py27_1
- conda-forge::setuptools=33.1.1=py27_0
- conda-forge::simplegeneric=0.8.1=py27_0
- conda-forge::six=1.10.0=py27_1
- conda-forge::smmap=2.0.1=py27_0
- conda-forge::sqlite=3.13.0=1
- conda-forge::tk=8.5.19=1
- conda-forge::traitlets=4.3.2=py27_0
- conda-forge::typing=3.6.1=py27_0
- conda-forge::wcwidth=0.1.7=py27_0
- conda-forge::wheel=0.29.0=py27_0
- conda-forge::yaml=0.1.6=0
- conda-forge::zlib=1.2.11=0
- cryptography=1.7.1=py27_0
- python.app=1.2=py27_4
- pip:
  - backports.shutil-get-terminal-size==1.0.0
  - conda-smithy (/Users/kirkhamj/Developer/Conda/conda-forge/conda-smithy)==2.0.2.dev4+fast.finish.cis
  - ipython-genutils==0.2.0
  - prompt-toolkit==1.0.14
  - ruamel-yaml==0.11.14
  - smmap2==2.0.1
prefix: /zopt/conda2
```

</details>
