### ISSUE TITLE
conda-build must not put abbreviated hashes in GIT_DESCRIBE_HASH

### ISSUE THREAD

**Issue by whitequark** [conda/conda-build#1940]
The default mode of operation of `git describe` results in abbreviated hashes whose length depends on, at least:
  * git version
  * the set of objects in the repository
and perhaps other factors.

This can lead to non-deterministic build metadata if GIT_DESCRIBE_HASH is used to derive version numbers or dependencies.

**Comment by msarahan** [comment]
Can you tell me more about how you hit this error?

If anyone is assuming exact length of git hashes, I believe they're in for a bad time.

**Comment by whitequark** [comment]
We have several buildbot buildslaves, which cache git repositories. We also derive build metadata from GIT_DESCRIBE_* variables:
```
build:
  noarch_python: true
  number: {{ environ.get("GIT_DESCRIBE_NUMBER", 0) }}
  string: py_{{ environ.get("GIT_DESCRIBE_NUMBER", 0) }}+git{{ environ.get("GIT_DESCRIBE_HASH", "")[1:9] }}

requirements:
  build:
    - artiq-dev {{ "{tag} py_{number}+git{hash}".format(tag=environ.get("GIT_DESCRIBE_TAG"), number=environ.get("GIT_DESCRIBE_NUMBER"), hash=environ.get("GIT_DESCRIBE_HASH")[1:]) if "GIT_DESCRIBE_TAG" in environ else "" }}
  run:
    - artiq {{ "{tag} py_{number}+git{hash}".format(tag=environ.get("GIT_DESCRIBE_TAG"), number=environ.get("GIT_DESCRIBE_NUMBER"), hash=environ.get("GIT_DESCRIBE_HASH")[1:]) if "GIT_DESCRIBE_TAG" in environ else "" }}
```
Well, one buildslave happened to have a few more tags in its copy of the same repository, and so `git-describe` returned a longer hash.

Of course, a workaround would be to limit the hashes to 7-8 characters (and this is what we did so far), but seeing as git-describe returns longer hashes precisely because they become ambiguous, this is not a good long-term solution. Moreover, I would prefer to have a much longer hash in the build number, to future-proof old packages and ensure hash to commit mapping always remains unambiguous, even when the history is much longer.
