### ISSUE TITLE
Test circular relationships between outputs

### ISSUE THREAD

**Issue by msarahan** [conda/conda-build#2021]
Outputs can have "delayed" circular relationships, like:

```
outputs:
    - name: a
      run_exports:
          - {{ pin_subpackage('b', exact=True) }}
    - name: b
       requirements:
           - {{ pin_subpackage('a', exact=True) }}
```

We need to test that some downstream package using 'a' as a build dependency ends up pinning 'b' as a runtime dependency with an exact pin.
