### ISSUE TITLE
During testing phase, platform.machine() returns None on Windows (regression)

### ISSUE THREAD

**Issue by mstimberg** [conda/conda-build#2064]
I am maintaining a conda package for [py-cpuinfo](https://github.com/workhorsy/py-cpuinfo), but with recent conda-build versions (from the 2.1.x branch) it fails during the test phase when it tries to check via `platform.machine()` whether it runs on a supported platform. The reason is that `platform.machine()` does not return `AMD64` as expected, but instead `None` (it works during the build phase).
I bisected the problem to commit 430ce9928, although I can't say I see how the commit would lead to this outcome. Here's a pretty minimal `meta.yaml` file that reproduces the issue for me, it fails with an `AssertionError` with conda-build versions after the above mentioned commit (or from release 2.1.6 on):
```yaml
package:
  name: dummy
  version: 1.0

requirements:
  run:
    - python

test:
  commands:
    - python -c "import platform; assert platform.machine()"
```
The problem seems to be Windows-specific (I only tested 64bit), it works fine for me on Linux and OS X.

**Comment by jjhelmus** [comment]
It [looks like on Windows](https://github.com/python/cpython/blob/v3.6.1/Lib/platform.py#L933-L944) the information for `platform.machine()` is being detected from PROCESSOR_* environment variables.  Conda build limits the environment variables which are passed to the build environment and these do not seem to be passed through.  It is possible to ["white-list" variables](https://conda.io/docs/building/meta-yaml.html#use-environment-variables) to be passed through to the build script using **script_env**.  For example adding the following to the example recipe allows the build to pass:

``` yaml
build:
  script_env:
    - PROCESSOR_ARCHITEW6432
    - PROCESSOR_ARCHITECTURE
    - PROCESSOR_IDENTIFIER
```

Longer term it might make sense to add these to the list of variables automatically inherited.
