### ISSUE TITLE
Combine skeleton and hg/git in one command

### ISSUE THREAD

**Issue by pigmej** [conda/conda-build#209]
generate valid package when:
- valid python package NOT pypi avaliable
- there are dependencies, entry_points etc

Currently `skeleton` is able to download package from pypi, would be cool if same logic could be applied to `hg_url` in `meta.yaml`

(examples in HG, but I think it should work with GIT too)

So I suppose the best would be to create 
`conda skeleton pyrepo --hg_url /tmp/hg_package --hg_tag`
The command would then work as follows:
- behave like `conda build package` with minimal template like:

```
package:
  name: package
  version: "{{ environ['HG_LATEST_TAG'] }}_{{ environ.get('HG_LATEST_TAG_DISTANCE', 0)}}"

source:
  hg_url: /tmp/hg_package
  hg_tag: {hg_tag}

build:
  number: {{ environ.get('HG_NUM_ID', 0) }}
  string: {{ environ.get('HG_BUILD_STR', '') }}
```
- except it stops after repo is prepared and basic meta.yaml is created
- then it will run similar logic as now is used for `conda convert pypi` but instead of downloading and unpacking it will use previously cloned / updated repo.

What do you @asmeurer think about that ?

Combination of this two, would allow easily create new conda packages directly from repo without extra work if they are valid python packages.
