### ISSUE TITLE
Conda convert ignores preprocessing selectors

### ISSUE THREAD

**Issue by plieningerweb** [conda/conda-build#2093]
How it should be?
The dependency should be included in the new package. Even better, the parsed meta.yaml with conditional depenencies (see https://conda.io/docs/building/meta-yaml.html#preprocessing-selectors) should be used for the converted package.

Example:
meta.yaml
```
requirements:
    build:
        - python
    run:
        - python
        - pywin32 # [win]
```
Built on linux and then converted to win64 using `conda convert --platform win-64 -o /opt/miniconda3/conda-bld/ /opt/miniconda3/conda-bld/linux-64/package_xy-0.1.31-py34_0.tar.bz2`

The converted package will not have the dependency of pywin32.

What I would expect:
The converted package should contain the run requirement for pywin32. 

Or if not, what is the the expected way to build pure python packages with different dependencies for several platforms?

I see #2085 only as a very ugly and manual hack, which destroys the idea of the build recipe.

**Comment by janosg** [comment]
Is there any progress on this? I have the opposite problem, i.e want a package to be excluded by `conda convert`. Thus the solution from #2085 will not work. 

Example:

```
requirements:
    build:
        - python
    run:
        - python
        - petsc4py # [not win] 
```
Building on linux and converting to win64 produces an uninstallable package because the dependency is not removed during conversion.
