### ISSUE TITLE
--output missing PKG_BUILDNUM in 2.1.x

### ISSUE THREAD

**Issue by daler** [conda/conda-build#2115]
Using the following recipe with a custom build string:

```yaml
package:
  name: ex
  version: "0.1"

source:
  fn: a.tar.gz
  url: https://a.tar.gz

build:
  number: 0
  string: "py{{CONDA_PY}}_gsl{{CONDA_GSL}}_{{PKG_BUILDNUM}}"

requirements:
  build:
    - gcc
    - python
    - gsl {{CONDA_GSL}}*

  run:
    - python
    - numpy >=1.10
    - libgcc
    - gsl {{CONDA_GSL}}*
```

2.0.12 has the following expected behavior:

```bash
conda build --version
# conda-build 2.0.12

CONDA_GSL=1.16 conda build --output recipedir
# /miniconda3/conda-bld/linux-64/ex-0.1-py35_gsl1.16_0.tar.bz2
```

but starting with 2.1.0 and including up to 2.1.15, the reported output file is missing the PKG_BUILDNUM:

```bash
conda build --version
# conda-build 2.1.15

CONDA_GSL=1.16 conda build --output recipedir
# /miniconda3/conda-bld/linux-64/ex-0.1-py35_gsl1.16_.tar.bz2
```

By messing around with this I've found that if I comment out the `source:` section, 2.1.x and 2.0.x behave the same. 2.1.x loses the build number once a source section is added.
