### ISSUE TITLE
Build recipe error: bad character '=' in package name dependancy

### ISSUE THREAD

**Issue by PeterKucirek** [conda/conda-build#2117]
I'm specifying a build recipe for my project using `meta.yaml` file but I keep encountering an error with the `requirements` section. The resulting error message when I run `conda-build`:

```
Error: bad character '=' in package name dependency 'pandas=0.20.2'
```

My `meta.yaml` file's requirements section looks like this:

```yaml
requirements:
  build:
    - python
    - setuptools
  run:
    - 'python >=3.5'
    - 'pandas=0.20.2'
    - 'py4j=0.10.4'
    - 'numba=0.33.0'
    - 'numexpr=2.5.2'
    - 'jupyter=1.0.0'
```

I'm using the same package specification syntax I would use to run `conda install`, and,  indeed, the syntax recommended by the documents. I have tried several variants on the pandas specification, including `pandas==0.20.2`, `pandas =0.20.2`, `pandas = 0.20.2`, `pandas == 0.20.2`; and, one time, `pandas<>0.20.2` just to see what would happen. 

The reason I'm playing with the spaces is that, for some reason `python>=3.5` does **not** work, but `python >=3.5` (note the space) **does** work. 

I've tried searching for this problem, but the best I can find is a link to a specific package's issue:
https://github.com/quantopian/zipline/issues/1013. It looks like it has something to do with Windows and/or Python 3.5+

Any help would be greatly appreciated.

Here's the results of `conda info`:

```
Current conda install:

               platform : win-64
          conda version : 4.3.22
       conda is private : False
      conda-env version : 4.3.22
    conda-build version : 2.1.15
         python version : 3.6.1.final.0
       requests version : 2.14.2
       root environment : C:\ProgramData\Miniconda3  (writable)
    default environment : C:\ProgramData\Miniconda3
       envs directories : C:\ProgramData\Miniconda3\envs
                          C:\Users\pjk\AppData\Local\conda\conda\envs
                          C:\Users\pjk\.conda\envs
          package cache : C:\ProgramData\Miniconda3\pkgs
                          C:\Users\pjk\AppData\Local\conda\conda\pkgs
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\pjk\.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.22 requests/2.14.2 CPython/3.6.1 Windows/7 W
indows/6.1.7601
          administrator : True
```

**Comment by msarahan** [comment]
Unfortunately, the syntax in meta.yaml does not match CLI syntax.  It follows the rules here: https://conda.io/docs/spec.html#package-match-specifications

except that names, versions, and build strings must be space-separated.

Imposing version specs on python doesn't usually work very well.  Instead, it is better to skip the recipe on python versions that don't match your constraint.  Also, I have loosened your versions a little bit.  Have such exact pins generally leads to unsatisfiable environments and hair pulling.

```
build:
  skip: True  # [py<35]

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - pandas 0.20.*
    - py4j 0.10.*
    - numba 0.33.*
    - numexpr 2.5.*
    - jupyter  1.0.*
```
