### ISSUE TITLE
3.0.5 fails with numpy x.x in 'host' section

### ISSUE THREAD

**Issue by nehaljwani** [conda/conda-build#2195]
Minimal example to reproduce:
```yaml
package:
  name: foobar

requirements:
  host:
    - numpy x.x
```

This works fine when 'host' is replaced with 'build'

The problem seems to be in https://github.com/conda/conda-build/blob/3.0.5/conda_build/render.py#L66-L67 where the replacement doesn't take place when the value of variable env is 'host' . I am not sure, but perhaps it should be:
```py
if env in ['build', 'host']:
```
