### ISSUE TITLE
3.0.5 indirect numpy dependency causes conflict

### ISSUE THREAD

**Issue by sklam** [conda/conda-build#2199]
Minimal recipe to trigger the error:

```yaml
# Usage:
#   conda build -c defaults -c conda-forge .
package:
  name: checkthis

requirements:
  build:
    - arrow-cpp 0.5.*   # from conda-forge
```

This causes:

```
conda.exceptions.UnsatisfiableError: The following specifications were found to be in conflict:
  - numpy 1.11.*
  - numpy 1.13.1 py36_0
```

Numpy version must be specified (e.g. `--numpy=1.13`) for it to work. 

In conda-build 2.1.17, the recipe works with just `conda build -c defaults -c conda-forge .`
