### ISSUE TITLE
Building a package with build and test requirement, the test requirement is used

### ISSUE THREAD

**Issue by gabm** [conda/conda-build#2217]
We have seperate build and test stages, so we build once with `--no-test` and another time with `-t`.

A package that has an asymetric build and test requirement will favor the test requirement in the build stage even when `--no-test` is specified...

Example:

lets suppose cmake is available in version 3.5, so the build requirement is satisfied, but not the test requirement. We are building with `--no-test`.  So in any case I'd expect CB to build,

```
package:
  name: "teskpkg"
  version: "1.0.0"
  
requiremnts:
  build:
    - cmake >= 3.5
     
test:
  requires:
    - cmake >= 3.7
```

When cmake 3.5 is available and we build with `conda build . --no-test` we get an error that the requriement cmake >= 3.7 cannot be not satisfied.

I noticed that in contrast to CB2 the test requirements are evaluated even before build. That might be the reason for htis. I dont specially like this because it breaks isolation between build and test stage, which imho should be isolated to allow for multi-stage building
