### ISSUE TITLE
Variant requirements should not be build requirements

### ISSUE THREAD

**Issue by sisp** [conda/conda-build#2229]
According to the [documentation](https://conda.io/docs/building/meta-yaml.html#subpackage-requirements):

> Subpackages support runtime and test requirements. Build requirements are not supported, because subpackages are created after the build phase is complete.

Now, consider the following ``meta.yaml``:

```yaml
package:
  name: pkg
  version: 1.0

build:
  number: 0

requirements:
  run:
    - sub1

outputs:
  - name: sub1
    requirements:
      - {{ pin_subpackage('sub2', exact=True) }}
  - name: sub2
```

The way I understand the documentation, ``sub2`` should be a **run** requirement of ``sub1`` but **no build** requirement. When I build ``pkg`` with ``conda-build=3.0.8``, ``/info/recipe/meta.yaml`` in ``sub1-1.0-hdb6aa64_0.tar.bz2`` looks as follows:

```yaml
# This file created by conda-build 3.0.8
# ------------------------------------------------

package:
    name: sub1
    version: '1.0'
build:
    noarch: false
    number: '0'
    string: hdb6aa64_0
requirements:
    build:
        - sub2 1.0 hbf21a9e_0
    run:
        - sub2 1.0 hbf21a9e_0
extra:
    final: true
    parent_recipe:
        name: pkg
        path: /recipes/pkg
        version: '1.0'
```

As you can see, ``sub2`` is both a build and a run requirement of ``sub1``.

Please correct me if I'm wrong, but shouldn't ``sub2`` only be a **run** requirement of ``sub1``?

Any help is very much appreciated!
