### ISSUE TITLE
The PROCESSOR_ARCHITECTURE environment variable is None on Windows

### ISSUE THREAD

**Issue by bryanwweber** [conda/conda-build#2257]
This is related to #2064, I think. Since version 2.1.16, the value for the `PROCESSOR_ARCHITECTURE` environment variable is `None` during at least the build phase. The following minimal `meta.yaml` demonstrates this:

```
package:
  name: dummy
  version: 1.0

requirements:
  run:
    - python

build:
  script:
    - python -c "import os; print(os.getenv('PROCESSOR_ARCHITECTURE'))"

  script_env:
    - PROCESSOR_ARCHITECTURE
```

where `AMD64` is printed (on my machine) for conda-build 2.1.15, and `None` is printed for 2.1.16. The result is the same whether the `script_env` key is included or not.

`git bisect` localizes the problem to this commit: https://github.com/conda/conda-build/commit/c87e157f45a3ac7b9bf05c1feb2d137b83672ef6

**Comment by msarahan** [comment]
Dang, that's unfortunate.  The purpose of that commit was exactly the opposite: to not require script_env at all, rather than to nuke this value completely.  Thanks for the help in isolating this.  I'll see what I can do for 3.0.10.

**Comment by msarahan** [comment]
I have tweaked your recipe slightly and made it a test.  I made python a build dep, not a run dep, and I changed your print statement into an assert so that the build would fail.

```
package:
  name: dummy
  version: 1.0

requirements:
  build:
    - python

build:
  script:
    - python -c "import os; assert os.getenv('PROCESSOR_ARCHITECTURE') == 'AMD64', 'PROCESSOR_ARCHITECTURE is {}'.format(os.getenv('PROCESSOR_ARCHITECTURE'))"
```

Indeed, I see this failure, but I'm a bit mystified.  The recorded bld.bat in the work folder has the correct variable setting:

```
@echo on
set "TMP=C:\Users\builder\AppData\Local\Temp"
set "COMPUTERNAME=DESKTOP-CB8H04D"
set "USERDOMAIN=DESKTOP-CB8H04D"
set "SystemDrive=C:"
set "LIBRARY_BIN=c:\users\builder\appdata\local\temp\pytest-of-msarahan\pytest-232\test_cpu_vars_win0\test_cpu_vars_win_1501901313100\_b_env\Library\bin"
set "PSModulePath=C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\"
set "R_VER=3.3.2"
set "SystemRoot=C:\WINDOWS"
set "ProgramData=C:\ProgramData"
set "CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files"
set "PROCESSOR_ARCHITECTURE=AMD64"
```

but the assert fails anyway.  This is some tricky detail of the environment that the python executable gets as a subprocess (of a subprocess).  I'll see if I can find a way to fix it.
