### ISSUE TITLE
3.0.10 raises "Unsatisfiable dependencies for platform osx-64"

### ISSUE THREAD

**Issue by guyer** [conda/conda-build#2317]
I am attempting to build trilinos (the bane of my existence), which requires the numpy C API, but my build fails at test with:

```
TEST START: /Users/guyer/anaconda/conda-bld/osx-64/trilinos-12.10.1-py27hadd81b6_2.tar.bz2
Renaming work directory,  /Users/guyer/anaconda/conda-bld/trilinos_1503630186988/work  to  /Users/guyer/anaconda/conda-bld/trilinos_1503630186988/work_moved_trilinos-12.10.1-py27hadd81b6_2
Traceback (most recent call last):
  File "/Users/guyer/anaconda/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/Users/guyer/anaconda/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 387, in main
    execute(sys.argv[1:])
  File "/Users/guyer/anaconda/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 378, in execute
    noverify=args.no_verify)
  File "/Users/guyer/anaconda/lib/python2.7/site-packages/conda_build/api.py", line 184, in build
    need_source_download=need_source_download, config=config, variants=variants)
  File "/Users/guyer/anaconda/lib/python2.7/site-packages/conda_build/build.py", line 1739, in build_tree
    test(pkg, config=metadata.config)
  File "/Users/guyer/anaconda/lib/python2.7/site-packages/conda_build/build.py", line 1518, in test
    channel_urls=tuple(metadata.config.channel_urls))
  File "/Users/guyer/anaconda/lib/python2.7/site-packages/conda_build/environ.py", line 688, in get_install_actions
    raise DependencyNeedsBuildingError(exc, subdir=subdir)
conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform osx-64: ['trilinos', 'numpy']
```

This seems similar to #2191 and #2197, but both of those issues are nominally fixed and I am using `conda-build` variants for numpy. 

This recipe successfully built with `conda-build 2.1.1` (before I foolishly heeded the warning to update).

I invoke
```
conda build trilinos --channel guyer --channel conda-forge
```
and my recipes are at https://github.com/guyer/conda-recipes/tree/trilinos_upgrade/trilinos

```
Current conda install:

               platform : osx-64
          conda version : 4.3.25
       conda is private : False
      conda-env version : 4.3.25
    conda-build version : 3.0.10
         python version : 2.7.13.final.0
       requests version : 2.14.2
       root environment : /Users/guyer/anaconda  (writable)
    default environment : /Users/guyer/anaconda
       envs directories : /Users/guyer/anaconda/envs
                          /Users/guyer/.conda/envs
          package cache : /Users/guyer/anaconda/pkgs
                          /Users/guyer/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /Users/guyer/.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.25 requests/2.14.2 CPython/2.7.13 Darwin/16.6.0 OSX/10.12.5    
                UID:GID : 17723:17723
```

**Comment by msarahan** [comment]
Sorry conda's hints aren't more helpful.  It looks to me like mpich is missing:

```
[root@19638a023b77 conda-recipes]# conda render trilinos
Returning non-final recipe for trilinos-12.10.1-py36_2; one or more dependencies was unsatisfiable:
Build: mpich
Host: None
package:
    name: trilinos
    version: 12.10.1
source:
    fn: trilinos-12.10.1-Source.tar.bz2
    md5: 1e14df93afaddb12cf840da56c5132ce
    url: https://trilinos.org/oldsite/download/files/trilinos-12.10.1-Source.tar.bz2
build:
    number: '2'
requirements:
    build:
        - python 3.6.*
        - numpy 1.10
        - nomkl
        - swig ==3.0.10
        - cmake
        - mpich
        - openblas
        - boost
    run:
        - openblas
        - numpy 1.10
        - python
        - mpich
        - nomkl
test:
    imports:
        - PyTrilinos
        - PyTrilinos._Teuchos
        - PyTrilinos.ML
extra:
    copy_test_source_files: true
    final: true
```

If you include conda-forge as a channel, it should work:

```
[root@19638a023b77 conda-recipes]# conda render trilinos -c conda-forge
package:
    name: trilinos
    version: 12.10.1
source:
    fn: trilinos-12.10.1-Source.tar.bz2
    md5: 1e14df93afaddb12cf840da56c5132ce
    url: https://trilinos.org/oldsite/download/files/trilinos-12.10.1-Source.tar.bz2
build:
    number: '2'
requirements:
    build:
        - bzip2 1.0.6 1
        - openblas 0.2.19 2
        - openssl 1.0.2l 0
        - libssh2 1.8.0 1
        - curl 7.54.1 0
        - sqlite 3.13.0 1
        - libgfortran 3.0.0 1
        - readline 6.2 0
        - krb5 1.14.2 0
        - pcre 8.39 0
        - ncurses 5.9 10
        - cmake 3.9.1 0
        - boost-cpp 1.64.0 1
        - libgcc 7.1.0 h9c9919c_0
        - python 3.6.2 0
        - icu 58.1 1
        - numpy 1.10.4 py36_blas_openblas_205
        - mpich 3.2 4
        - expat 2.2.1 0
        - tk 8.5.19 2
        - libgcc_linux-64 7.1.0 h12e1119_0
        - libgfortran_linux-64 7.1.0 ha5e90dd_0
        - libuv 1.11.0 0
        - libstdcxx_linux-64 7.1.0 h4f7dd76_0
        - nomkl 1.0 0
        - rhash 1.3.4 0
        - ca-certificates 2017.7.27.1 0
        - boost 1.64.0 py36_4
        - swig 3.0.10 2
        - blas 1.1 openblas
        - xz 5.2.3 0
        - zlib 1.2.11 0
    run:
        - mpich
        - python >=3.6,<3.7.0a0
        - openblas
        - numpy 1.10
        - nomkl
test:
    imports:
        - PyTrilinos
        - PyTrilinos._Teuchos
        - PyTrilinos.ML
extra:
    copy_test_source_files: true
    final: true
```

**Comment by guyer** [comment]
Thanks for the reply and the hint about `conda render`. Unfortunately, I already pass `--channel conda-forge`.

The package builds, but it fails to test. `mpich` is required for both.

FWIW, this is what I get. 
```

package:
    name: trilinos
    version: 12.10.1
source:
    fn: trilinos-12.10.1-Source.tar.bz2
    md5: 1e14df93afaddb12cf840da56c5132ce
    url: https://trilinos.org/oldsite/download/files/trilinos-12.10.1-Source.tar.bz2
build:
    number: '2'
requirements:
    build:
        - zlib 1.2.11 0
        - krb5 1.14.2 0
        - pip 9.0.1 py27_0
        - tk 8.5.19 2
        - mpich 3.2 4
        - swig 3.0.10 2
        - python 2.7.13 1
        - openblas 0.2.20 1
        - nomkl 1.0 0
        - bzip2 1.0.6 1
        - libgfortran 3.0.0 0
        - rhash 1.3.4 0
        - cmake 3.9.1 0
        - wheel 0.29.0 py27_0
        - xz 5.2.3 0
        - openssl 1.0.2l 0
        - pcre 8.39 0
        - ncurses 5.9 10
        - libssh2 1.8.0 1
        - boost 1.64.0 py27_4
        - icu 58.1 1
        - curl 7.54.1 0
        - readline 6.2 0
        - libuv 1.11.0 0
        - setuptools 36.2.2 py27_0
        - sqlite 3.13.0 1
        - certifi 2017.7.27.1 py27_0
        - ca-certificates 2017.7.27.1 0
        - boost-cpp 1.64.0 1
        - expat 2.2.1 0
        - numpy 1.10.4 py27_nomkl_2
    run:
        - mpich
        - numpy 1.10
        - python >=2.7,<2.8.0a0
        - nomkl
        - openblas
test:
    imports:
        - PyTrilinos
        - PyTrilinos._Teuchos
        - PyTrilinos.ML
extra:
    copy_test_source_files: true
    final: true
```

I don't know if it matters that I'm building with python 2.7 (PyTrilinos isn't ready for py3k just yet).

**Comment by msarahan** [comment]
Yes, sorry.  This appears to be a bug.  Here's a couple of workarounds:

The right way, which you should do anyway:

```
requirements:
  build:
    - python
    - numpy {{ numpy }}
    - nomkl
    - swig ==3.0.10
    - cmake
    - mpich
    - openblas
    - boost
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - nomkl
    - mpich
    - openblas
```

This takes advantage of the fact that numpy is forward-compatible (a recent discovery in our community).  So you'd build with 1.10, but you could install with any version of numpy, >1.10,<2.0a0

You could disable the upper bound completely with ```- {{ pin_compatible('numpy', max_pin=None) }}```

The crappy hack:

```
requirements:
  build:
    - python
    - numpy {{ numpy }}
    - nomkl
    - swig ==3.0.10
    - cmake
    - mpich
    - openblas
    - boost
  run:
    - python
    - numpy {{ numpy }}.*
    - nomkl
    - mpich
    - openblas
```

The .* is what is tripping up conda.  We add that in the build deps, but apparently not in the run deps...  I don't think this is a new bug, but I think that people knew to add the .* before, while the use of variants makes things more complicated, and people forgot.  I will add the automatic addition in the run deps.
