### ISSUE TITLE
Numpy dependency broken with conda-build 3.0

### ISSUE THREAD

**Issue by abergeron** [conda/conda-build#2338]
I have a test package with the meta.yaml:
```
package:
  name: temp
  version: 0.0.1

build:
  number: 0

requirements:
  build:
    - python {{ python }}
    - numpy {{ numpy }}
  run:
    - python {{ python }}
    - numpy {{ numpy }}
```

In the same folder I place a conda_build_config.yaml:
```
python:
  - 2.7
  - 3.5
  - 3.6
numpy:
  - 1.11
  - 1.12
  - 1.13
```

When I build the package matrix with conda-build I get a bunch of packages but when I try to install I get this error:
```
$ conda install --use-local temp
Fetching package metadata ...........
Solving package specifications: 

PackageNotFoundError: Packages missing in current channels:
            
  - temp -> numpy 1.11

We have searched for the packages in the following channels:
            
  - file:///Users/anakha/miniconda/conda-bld/osx-64
  - file:///Users/anakha/miniconda/conda-bld/noarch
  - https://repo.continuum.io/pkgs/free/osx-64
  - https://repo.continuum.io/pkgs/free/noarch
  - https://repo.continuum.io/pkgs/r/osx-64
  - https://repo.continuum.io/pkgs/r/noarch
  - https://repo.continuum.io/pkgs/pro/osx-64
  - https://repo.continuum.io/pkgs/pro/noarch
```
If I specify the full numpy version in conda_build_config.yaml, then it wants me to downgrade my numpy to 1.11.3.

The environment I want to install into has python 3.5 and numpy 1.13 installed.

I may have misread the docs somewhere, but I've gone through it a couple of times and nothing obvious jumps out at me.

The previous way of doing this with `numpy x.x` does work ok for this test package, but produces lots of deprecation warnings.
