### ISSUE TITLE
.git directory is deleted

### ISSUE THREAD

**Issue by jakirkham** [conda/conda-build#2360]
Appears that `.git` directories added to the `$PREFIX` during the build are stripped out entirely by `conda-build`. However not all `.` prefixed files are stripped. This is undesirable behavior if one wants to have a `git` repo in their package. A recipe that demonstrates this behavior is included in the details below. Ran this on macOS, but presumably it shows up everywhere.

<details>

```yaml
# filename: test-recipe/meta.yaml

package:
  name: test-recipe
  version: 1

build:
  script: git clone https://github.com/jakirkham/hello_tests "${PREFIX}/hello_tests"

requirements:
  build:
    - git

test:
  requires:
    - git

  commands:
    - cd "${PREFIX}/hello_tests"
    - git status
```

</details>
