### ISSUE TITLE
conda-build 3 unable to build R packages against old R

### ISSUE THREAD

**Issue by dopplershift** [conda/conda-build#2371]
For the following example recipe from `condo-recipes/r-packages/r-bitops/`

meta.yml:
```yaml
{% set version = '1.0-6' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-bitops
  version: {{ version|replace("-", "_") }}

source:
  fn: bitops_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/bitops_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/bitops/bitops_{{ version }}.tar.gz

  sha256: 9b731397b7166dd54941fb0d2eac6df60c7a483b2e790f7eb15b4d7b79c9d69c

build:
  number: 2

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - posix                # [win]
    - {{native}}toolchain  # [win]
    - gcc                  # [not win]

  run:
    - r-base
    - {{native}}gcc-libs   # [win]
    - libgcc               # [not win]

test:
  commands:
    - $R -e "library('bitops')"  # [not win]
    - "\"%R%\" -e \"library('bitops')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=bitops
  license: GPL (>= 2)
  summary: Functions for bitwise operations on integer vectors.
  license_family: GPL3
```

build.sh
```sh
#!/bin/bash

mv DESCRIPTION DESCRIPTION.old
grep -v '^Priority: ' DESCRIPTION.old > DESCRIPTION

$R CMD INSTALL --build .
```

running conda-build 3.0.15 fails during the testing phase when trying to build using R 3.2.2 as:
```sh
conda-build --R 3.2.2 .
```

Suspiciously, the following output is seen during the test phase:
```
R version 3.4.1 (2017-06-30) -- "Single Candle"
Copyright (C) 2017 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)
```

The error occurs on macOS and within a CentOS 6 docker container. Replacing the conda-build 3 install with conda-build 2 (running with the same command line) successfully builds the package.

**Comment by jjhelmus** [comment]
conda build 3.x does not appear to automatically pin the r-base version.  I don't know if this is intentional or a bug.  

A [pinning expression](https://conda.io/docs/user-guide/tasks/build-packages/variants.html#pinning-expressions) can be used to  pin the r-base version to the exact build time version.  The new requirements section would be:

``` yaml
requirements:
  build:
    - r-base
    - posix                # [win]
    - {{native}}toolchain  # [win]
    - gcc                  # [not win]

  run:
    - {{ pin_compatible('r-base', exact=True) }}
    - {{native}}gcc-libs   # [win]
    - libgcc               # [not win]
```

A more detailed discussion of the theory and use of build variants can be found in the [documentation](https://conda.io/docs/user-guide/tasks/build-packages/variants.html).
