### ISSUE TITLE
Environment variables indiscriminately passed through to TEST phase

### ISSUE THREAD

**Issue by chrisRedwine** [conda/conda-build#2372]
Since version 3.0 for Linux, environment variables are indiscriminately passed through to the TEST phase, regardless of the absence of `script_env`. This also appears to be the case on Windows since before 3.0.

```yaml
package:
  name: foo
  version: 1.0

build:
  script:
    - test ! "$FOO"  # [unix]
    - IF NOT "%FOO%" == "" exit 1  # [win]

test:
  commands:
    - test ! "$FOO"  # [unix]
    - IF NOT "%FOO%" == "" exit 1  # [win]
```

Running just `conda build .` (i.e., FOO not set) results in both build & test succeeding, whereas running `export FOO=abc && conda build .` results in the build succeeding and the _test failing_.
