### ISSUE TITLE
Add an option to export build time dependencies as run_constrained keys and pin strictly

### ISSUE THREAD

**Issue by 183amir** [conda/conda-build#2404]
Following the discussion here: https://github.com/conda/conda-build/pull/2001#issuecomment-332327309, I am proposing to add the following feature to conda build.
Currently, there is an option in conda build recipes which allows you to pin **all** the packages that were used during build time as runtime dependencies. See original pull request here: https://github.com/conda/conda-build/pull/741

For example a recipe like:
```
package:
  name: bob-devel

build:
  pin_depends: strict

requirements:
  run:
    - curl 7.52.1
```
will have the following `index.json`
```json
{
  "depends": [
    "curl 7.52.1 0",
    "openssl 1.0.2l 0",
    "zlib 1.2.8 3",
  ],
  "name": "bob-devel",
}
```
where `openssl` and `zlib` are dependencies of `curl`. Note that everything is pinned strictly and normally dependencies of `zlib` and `openssl` get pinned strictly too but I did not put it in the example above.

I propose a very similar functionality to be added for `run_constrained` keys as well.
For example for the following recipe:
```
package:
  name: bob-devel

build:
  pin_constrains: strict

run_constrained:
  - curl 7.52.1
```
we get this:
```json
{
  "constrains": [
    "curl 7.52.1 0",
    "openssl 1.0.2l 0",
    "zlib 1.2.8 3",
  ],
  "name": "bob-devel",
}
```

**Comment by 183amir** [comment]
I was thinking maybe instead of this, we can have a jinja function to help me do this. Something like:
```yaml
package:
  name: bob-devel
  version: 2018.02.21

requirements:
  host:
    - curl 7.55.1
  run_constrained:
  {% for package in packages('host', all=True) %}
    - {{ pin_compatible(package, exact=True) }}
  {% endfor %}
```
Would render to:
```yaml
package:
    name: bob-devel
    version: 2018.02.21
requirements:
    host:
        - ca-certificates 2017.08.26 h1d4fec5_0
        - libgcc-ng 7.2.0 h7cc24e2_2
        - openssl 1.0.2n hb7f436b_0
        - curl 7.55.1 h78862de_4
        - libssh2 1.8.0 h9cfc8f7_4
        - zlib 1.2.11 ha838bed_2
    run_constrained:
        - ca-certificates 2017.08.26 h1d4fec5_0
        - libgcc-ng 7.2.0 h7cc24e2_2
        - openssl 1.0.2n hb7f436b_0
        - curl 7.55.1 h78862de_4
        - libssh2 1.8.0 h9cfc8f7_4
        - zlib 1.2.11 ha838bed_2
```
