### ISSUE TITLE
local custom package not copying into SITE PACKAGES folder

### ISSUE THREAD

**Issue by seahawks8** [conda/conda-build#2415]
successfully built a custom package into a tar.bz2 file.
I am able to install via 
`conda install --use-local mycustompackage`

however when I check the sitepackages folder, nothing is there for mycustompackage.
perhaps I am missing something, here is my meta.YAML

```
package:
  name: reliability
  version: "0.1.1"

source:
  path: ../reliability

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - matplotlib
    - numpy
    - pandas
    - pip
    - pyodbc
    - pyqt
    - pywin32
    - qt
    - scipy
    - tqdm
    - xlwings
    - statistics # [py27 and py33]
    - openturns

test:
  imports:
    - openturns
    - PyQt5
    - tqdm
    - pyodbc
    - numpy
    - pandas
    - matplotlib

about:
  license: BSD
  license_file: LICENSE
```
