### ISSUE TITLE
outputs section does not allow multiple packages with the same package name

### ISSUE THREAD

**Issue by tomashek** [conda/conda-build#2438]
Feature request? Bug?

My question relates to our efforts to implement "shadow" packages using link scripts. I was hoping to simply add an additional "output" to the list of outputs that has as its setup a script that generates the post-link and pre-unlink scripts. The package name is the same as another output, and this seems to break when using conda-build 3.0.25.  conda-build 2.1.15 allowed this, but since it did not support the "string" field in "outputs", the last package of a particular name overwrote the previous output with the same name.

The conda-build error is:
```
INFO:conda_build.metadata:Attempting to finalize metadata for mkl
Traceback (most recent call last):
  File "/localdisk/work/miniconda3/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/localdisk/work/miniconda3/lib/python3.5/site-packages/conda_build/cli/main_build.py", line 388, in main
    execute(sys.argv[1:])
  File "/localdisk/work/miniconda3/lib/python3.5/site-packages/conda_build/cli/main_build.py", line 379, in execute
    noverify=args.no_verify)
  File "/localdisk/work/miniconda3/lib/python3.5/site-packages/conda_build/api.py", line 185, in build
    need_source_download=need_source_download, config=config, variants=variants)
  File "/localdisk/work/miniconda3/lib/python3.5/site-packages/conda_build/build.py", line 1772, in build_tree
    notest=notest,
  File "/localdisk/work/miniconda3/lib/python3.5/site-packages/conda_build/build.py", line 882, in build
    output_metas = expand_outputs([(m, need_source_download, need_reparse_in_env)])
  File "/localdisk/work/miniconda3/lib/python3.5/site-packages/conda_build/render.py", line 548, in expand_outputs
    for (output_dict, m) in _m.get_output_metadata_set(permit_unsatisfiable_variants=False):
  File "/localdisk/work/miniconda3/lib/python3.5/site-packages/conda_build/metadata.py", line 1747, in get_output_metadata_set
    permit_unsatisfiable_variants=permit_unsatisfiable_variants)
  File "/localdisk/work/miniconda3/lib/python3.5/site-packages/conda_build/metadata.py", line 636, in finalize_outputs_pass
    recipe_outputs)
  File "/localdisk/work/miniconda3/lib/python3.5/site-packages/conda_build/metadata.py", line 671, in get_updated_output_dict_from_reparsed_metadata
    assert len(output_ds) == 1
AssertionError
```

I would like to be able to designate multiple outputs using the same name, but variants of "string" or "features".

**Comment by msarahan** [comment]
I think that's a good feature request. Can you share your example recipe of exactly what you're trying to do, and how you'd like the syntax to look?

**Comment by tomashek** [comment]
Here is a sample meta.yaml:
```
{% set version = "2018.0.1" %}
{% set buildnumber = 0 %}

package:
  name: mkl
  version: {{version}}

build:
  number: {{buildnumber}}
  binary_relocation: false
  detect_binary_files_with_prefix: false

outputs:
  - name: mkl
    script: mkl-setup.sh
    requirements:
      - openmp 2018*
  - name: mkl-include
    script: mkl-include-setup.sh
  - name: mkl-static
    script: mkl-static-setup.sh
    requirements:
      - mkl-include {{version}}
  - name: mkl-devel
    requirements:
      - mkl {{version}}
      - mkl-include {{version}}
  - name: mkl
    string: intel_local__{{buildnumber}}
    script: mkl-shadow-setup.sh
    requirements:
      - openmp 2018*
  - name: mkl-include
    string: intel_local__{{buildnumber}}
    script: mkl-include-shadow-setup.sh
  - name: mkl-static
    string: intel_local__{{buildnumber}}
    script: mkl-static-shadow-setup.sh
    requirements:
      - mkl-include {{version}}

about:
  home: http://software.intel.com/en-us/articles/intel-mkl/
  license: proprietary - Intel
  license_file: license.txt
  license_family: Proprietary
  summary: Math library for Intel and compatible processors
```

**Comment by tomashek** [comment]
There are two versions of each named package: one that runs "setup" and the other that adds "local" to the string and runs "shadow-setup". The "setup" scripts copy the files, while the "shadow-setup" scripts create the two link scripts.

**Comment by tomashek** [comment]
By the way, if the "allow parameters in output section scripts" feature is added, all those setups scripts can be a single script with different parameters. As it is, those scripts are all small wrappers to a common script that takes the parameters.

**Comment by msarahan** [comment]
What's already there is that you can set parameters in conda_build_config.yaml, and they get passed through to build.sh/bld.bat as environment variables.  The tricky part is then to include those variables somehow in meta.yaml, so that they get encoded into the hash, so that packages don't clobber each other.

For example, here you could have something like:

conda_build_config.yaml:

```
shadow:
  - false
  - true
static:
  - false
  - true
```

meta.yaml:

```
outputs:
  - name: mkl{{ static }}
    script: mkl-setup.sh
    string: intel_local__{{buildnumber}}  # [shadow.lower() == 'true']
    requirements:
      - openmp 2018*      # [static.lower() == 'false']
      - mkl-include {{version}}  # [static.lower() == 'true']
  - name: mkl-include
    script: mkl-include-setup.sh
  - name: mkl-devel
    requirements:
      - mkl {{version}}
      - mkl-include {{version}}
```

build.sh:

```
if [ $shadow = "true" ]; then
   # shadow stuff
else
   # non-shadow stuff
fi

etc...
```

**Comment by tomashek** [comment]
Okay, I can try this. It would still take running the build twice, I think, but at least there would be a single recipe.

I think everything is there to avoid them clobbering (since I can add "local" or some such to the string).

But maybe I am misunderstanding what problem you were commenting on?

I need the package name to be the same for both packages. That is the challenge.

**Comment by msarahan** [comment]
I'm confused.  How would this require running the build twice?  Conda-build will loop over settings in conda_build_config.yaml.  The changes I recommended will produce identical packages to what you showed in your example.

Part of the problem here is that I think you really need the new key-value pair package specification stuff that's in conda 4.4.  With that, you could have 3 or 4 different mkl packages:

* mkl (shared, non-shadow)
* mkl (shared, shadow)
* mkl (static, non-shadow)
* mkl (static, shadow)

These are all named just mkl, but installing them is a matter of specifying the appropriate key-value stuff.  I'm sorry, I don't have examples right now.  I've been asking @kalefranz for examples for a while now.  Conda-build will probably need more work to properly support them - at the very least, any key-value pairs will probably need to become part of what makes up the hash.  Docs on what currently goes into the hash are at https://conda.io/docs/user-guide/tasks/build-packages/variants.html#differentiating-packages-built-with-different-variants

Until that's working, you need to do something like setting the string (as you are doing now) to differentiate packages when the package names are similar.  You can have many packages with the same name, but they need to loop over some parameter or parameters in meta.yaml, in order to have different output names.

```
outputs:
  - name: mkl
    script: mkl-setup.sh
    string: intel_local_{{shadow}}_{{static}}
    requirements:
      - openmp 2018*      # [static.lower() == 'false']
      - mkl-include {{version}}  # [static.lower() == 'true']
```

for example, will give 4 packages:

* mkl-(version)-intel_local_false_false
* mkl-(version)-intel_local_false_true
* mkl-(version)-intel_local_true_false
* mkl-(version)-intel_local_true_true

**Comment by msarahan** [comment]
I guess in other words, you can only have one ``name: mkl``, but you can tweak what loop variables go into any output packages.

**Comment by msarahan** [comment]
Furthermore, I believe it is necessary to maintain name uniqueness, because without it, the pin_subpackage jinja2 function would be ambiguous and very broken.  That function can handle variants of packages, but not duplicate package names.

**Comment by kalefranz** [comment]
> I've been asking @kalefranz for examples for a while now. 

Let me try to fix that :)

Here's an important blurb of information from the 4.4. changelog

> In implementing these key-value features, conda has added two new keywords to repodata. The feature concept was previously supported with `track_features` and `features` keys that roughly corresponded respectively to the new, more descriptive, provides_features and requires_features. The old keys are left for backward compatibility, and if the new keys are not provided in repodata, conda will actively do the translation. In contrast to the old keys being a space-delimited string of feature names, the new keys are both maps of key-value pairs.

So, from the [docs about old features](https://conda.io/docs/user-guide/tasks/build-packages/features.html#features) in meta.yaml, the entries are something like

```
build:
  features:
    - debug
```

and

```
build:
  track_features:
    - debug
```

We do need to update conda-build for key-value features.  I don't think that's been done yet. 

Rather than `features` and `track_features`, conda-build should now support `requires_features` and `provides_features` keywords under the `build` key, and the values for those two fields should themselves be key-value pairs in the form of a dict.  Both `requires_features` and `provides_features` should be recorded in `info/index.json`.

 In the above blurb, when I talk about conda doing active translation, the translation conda is doing would be equivalent to

```
build:
  requires_features:
    debug: true
```

and

```
build:
  provides_features:
    debug: true
```

A better example... It might make sense for us to make `python` a feature.  That should allow us to do things like

```
build:
  requires_features:
    gpu: cuda8
```

In the near term, we can create an empty (i.e. meta) package that contains

```
build:
  provides_features:
    gpu: cuda8
```

and the user could specify that package in their install command, and manually place that package into the environment.  In a future version of conda, I think the idea is for conda to be smart enough to recognize the the operating environment has cuda8 support, and then automatically inject that information into the index for the solver to consider.

This automatic recognition and injection part is what my working definition for "shadow package" is.  That is, I thought shadow packages would never be real packages, but more like "virtual" packages that conda just added to the index to influence the decisions made by the solver.

Perhaps that's not what other people envision shadow packages to be though, and my definition is too limited.  Perhaps we have a need for shadow packages, which could be extant, and also "virtual" packages, which are dynamically generated and internal to conda.

---

Did I come close to answering the questions?  I admit that was some rambling there.  What questions still remain?

**Comment by kalefranz** [comment]
I also want to give an example that I had been kicking around for a while.  I'm not sure everyone will agree with it or not, so I want to discuss the use case.

I'd really like for conda to be able to intelligently support pypy.  I know pypy is named differently than python, and it wouldn't strictly be necessary, but I think it's cleaner to install *only* one of cpython or pypy into an environment.  That is, an environment is only allowed to have a single python interpreter of any sort.  (We can of course debate the merits of that too, but go with the example for now.)

This problem reduces down to two package names that are mutually exclusive.  Currently, it's just the single package name match that provides the exclusion.  I envisioned using key-value features for this situation.  The feature name would be `python`.  And cpython interpreter packages would then have added to their metadata

```
build:
  provides_features:
    python: 3.6  # or could be cpython3.6
```

while a pypy package would have

```
build:
  provides_features:
    python: pypy2.7
```

Interested in thoughts here.  Perhaps I'm blowing up this issue now and we should start a new discussion thread.

**Comment by msarahan** [comment]
That's a good start.  Let me ask a few things I'm still unclear on.

- How does the user specify cuda8 at install time?  The analog here is that there are 3 different MKL varieties to choose from: the mkl we've always known, a static mkl which should only be used at build time, and a "shadow" mkl that is a placeholder, directing conda packages to a system installation of mkl.  This would perhaps require 2 different key-value pairs: one for blas (with a value of mkl), and another for the actual mkl implementation.

How does this look at install time?  How does a user say "I want blas=mkl and mkl_impl=shadow"?

I think your examples show how things look at build time adequately - at least until I implement your two new fields and kick the tires enough to come up with more questions.  Your pypy idea is fine, but it does belong in another issue.  I'm OK with your implementation idea, but also wary until I see something working.

**Comment by msarahan** [comment]
I have submitted a PR to implement provides_features and requires_features at https://github.com/conda/conda-build/pull/2440

Maybe we should test it with this MKL use case?

**Comment by kalefranz** [comment]
The example given currently in the conda changelog for 4.4, and I think it should still be accurate

    conda install scipy --feature blas=openblas
    conda install scipy[features='blas=openblas']
    conda install scipy "*[features='blas=openblas']"

The three should be equivalent.  Technically the way the solver is implemented, we should really be doing `conda install scipy "*[provides_features='blas=openblas']"`, but I think that's too heavy from a UX perspective, and also I think we can infer what the user means and coerce the matchspecs to be compatible with what the solver is expecting.

Should note: key-value features *do* have tests, but they are also completely new.  I know there are plenty of use cases and edge cases and situations that we're going to bump into.  If I knew what all they were right now, I'd of course write tests for them right now and have them covered.  I'm not sure what they are, but I know they exist.  In `defaults` right now, we really only use a single feature, which is `nomkl`.  We just need to exercise it all a lot more to see what shakes out.  So on this topic, I am asking for a little bit of both assistance in identifying the issues and patience in getting them smoothed over :)

**Comment by msarahan** [comment]
Thanks.  Do you have an example of more than one feature?  What is the delimiter?

```
conda install scipy --feature blas=mkl --feature mkl_impl=shadow
conda install scipy[features='blas=mkl,mkl_impl=shadow']
```

**Comment by kalefranz** [comment]
Oh, sorry.

> How does a user say "I want blas=mkl and mkl_impl=shadow"?

I was just answering!  Haha

You have it exactly how I would have typed it.  The delimiter is generally `,`, but can also be `, ` (comma + space).  As in python, `'` and `"` are interchangeable.

Within the square brackets, you don't always need to use quotes for values, except for when you do.  It'll make sense if you think about it.

I think the rule is that if the value of a key-value pair within the square brackets contains an equal, space, or comma, then you need to use quotes for the value.

I've got pretty extensive unit tests here.  It's pretty forgiving and hopefully just does the right thing for whatever comes naturally for users.

**Comment by brey** [comment]
Hi all. I have stumbled upon this issue trying to solve a similar but hopefully simpler problem.

I have a `conda_build_config.yaml` file like this

```
mpi:
  - mpich  # [not win]
  - openmpi  # [not win]

wwm:
  - false
  - true

```
and a recipe `meta.yaml` file like this:

```
outputs:
  - name: foo{{ '-wwm' if wwm == 'true' else '' }}
    script: build.sh
    {% set mpi_prefix = "mpi_" + mpi %}
    string: {{ mpi_prefix }}_h{{ PKG_HASH }}_{{ build }}

    requirements:

```
The build script and all the requirements are the the same and the `wwm` variable changes something in `build.sh` and I want the package name to be different according to `wwm`.

However, when I build not all configurations are done.  It creates only two mpi variants with `wwm` set to true both times. 

I also understand that this could be done somehow using `features` but I haven't figure out how. 

Any suggestions?
