### ISSUE TITLE
GLIB_2.14 memcpy is still used building recipe from conda-build via cross compilation.

### ISSUE THREAD

**Issue by rainwoodman** [conda/conda-build#2493]
When building a simple package with the new cross compilation toolchain and via conda-build, the advanced GLIBC symbols are still referenced.

The generated conda_build.sh seems to be missing the proper value of 
`export _PYTHON_SYSCONFIGDATA_NAME=_sysconfigdata_x86_64_conda_cos6_linux_gnu`.

It is not set in the activate.d scripts. For some reason the same script in my root conda environment sets this variable properly. As a result host gcc is used for linking at times, causing this problem:

- when I trigger conda_build.sh from my root environment the package builds without using GLIBC_2.14 symbols.;
- when I trigger conda_build.sh without my conda environment, the build produces binary using GLIBC_2.14;
- when I use conda-build; the build produces binary using GLIBC_2.14, likely because conda-build purges the variable before launching conda_build.sh

I've attached my recipe file and the script to check for GLIBC versions >= 2.13.

```
package:
  name: bigfile
  version: 0.1.38
source:
  fn: bigfile-0.1.38.tar.gz
  url: https://pypi.io/packages/source/b/bigfile/bigfile-0.1.38.tar.gz
  md5: eeab6afb43096db8515a6ffc9ee818e7

build:
  number: 3

requirements:
  build:
  - python {{ python }}
  - numpy {{ numpy }}
  - cython
  - mpi4py
  - '{{ compiler("c") }}'

  run:
  - python {{ python }}.*
  - numpy {{ numpy }}.*
  - mpi4py

test:
  # Python imports
  imports:
  - bigfile
  - bigfile.tests

about:
  home: http://github.com/rainwoodman/bigfile
  license: BSD-2-Clause
  summary: python binding of BigFile, a peta scale IO format
  license_family: BSD

extra:
  recipe-maintainers:
  - rainwoodman
```

and build.sh
```
#!/bin/bash
if [[ $OSTYPE == darwin* ]]; then
     export CFLAGS="$CFLAGS -headerpad_max_install_names"
     export CXXFLAGS=$CFLAGS
else
#     export CFLAGS="-include $PWD/glibc-compat.h"
echo
fi

#cp $RECIPE_DIR/../../glibc-compat.h .
cp $RECIPE_DIR/../../check-glibc.sh .

$PYTHON setup.py build

$PYTHON setup.py install

if [[ $OSTYPE != darwin* ]]; then
    bash check-glibc.sh $SP_DIR/$PKG_NAME || exit 1
fi

```

and check_glibc.sh
```
#! /bin/bash

set -e
if ! [ -d $1 ]; then
    echo Folder $1 does not exist -- did you give a wrong destination or forget --single-version-externally-managed
    exit 1
fi

fns=`find $1 -name '*.so'`
for fn in $fns; do
    echo "--- GLIBC symbols in $fn --"
    objdump -T $fn | grep GLIBC | awk '
        BEGIN { bad = 0 }
        {print $0}
        /GLIBC_2\.1[3-9]/ {
            bad = 1
        }
        /GLIBC_2\.[2-9][0-9]/ {
            bad = 1
        }
        END {
            if (bad) print("Bad symbols detected");
            exit bad;
        }
    '
done

```
