### ISSUE TITLE
Packages using openmp cannot find omp.h on OSX.

### ISSUE THREAD

**Issue by rainwoodman** [conda/conda-build#2496]
We see this error message:

https://travis-ci.org/bccp/conda-channel-bccp/jobs/301791318#L872

The recipe is 
```
package:
  name: classylss
  version: 0.2.6
source:
  fn: classylss-0.2.6.tar.gz
  url: https://pypi.io/packages/source/c/classylss/classylss-0.2.6.tar.gz
  md5: 7fab8900b6df6ce4124722648a44bcf5

build:
  number: 5

requirements:
  build:
  - python {{ python }}
  - numpy {{ numpy }}
  - setuptools
  - six   # only needed to download class, if needed
  - '{{ compiler("c") }}'
  - '{{ compiler("fortran") }}'
  - cython

  run:
  - python {{ python }}.*
  - numpy {{ numpy }}.*
  - cython

test:
  # Python imports
  imports:
  - classylss
  - classylss.binding

about:
  home: http://github.com/nickhand/classylss
  license: GPL3
  summary: python binding of CLASS for large-scale structure calculations
  license_family: GPL3

extra:
  recipe-maintainers:
  - rainwoodman
```

build.sh:

```
#!/bin/bash

pwd

if [[ $OSTYPE == darwin* ]]; then
     export CFLAGS="-headerpad_max_install_names"
     export CXXFLAGS=$CFLAGS
else
     export CFLAGS="$CFLAGS -g -fPIC"
fi

# this uses CFLAGS for CCFLAG
cp $RECIPE_DIR/class.cfg depends/class.cfg

$PYTHON setup.py install --single-version-externally-managed --record rec.txt

if [[ $OSTYPE != darwin* ]]; then
    cp $RECIPE_DIR/../../check-glibc.sh .
    bash check-glibc.sh $SP_DIR/$PKG_NAME || exit 1
fi
```
