### ISSUE TITLE
building rpy2

### ISSUE THREAD

**Issue by sebastian-luna-valero** [conda/conda-build#253]
Hi all,

I am building rpy2 with conda with the following recipe:
- build.sh:

```
$PYTHON setup.py install
```
- meta.yaml:

```
package:
  name: rpy2
  version: 2.4.4

source:
  fn: rpy2-2.4.4.tar.gz
  url: https://pypi.python.org/packages/source/r/rpy2/rpy2-2.4.4.tar.gz
  md5: 58fd357ba922839b65fd67766319b806

build:
  number: 0
  detect_binary_files_with_prefix: true

requirements:
  build:
    - gcc
    - readline
    - system
    - setuptools
    - python
    - r

  run:
    - gcc
    - readline
    - system
    - python
    - r

test:
  # Python imports
  imports:
    - readline
    - rpy2
    - rpy2.interactive
    - rpy2.interactive.tests
    - rpy2.rinterface
    - rpy2.rinterface.tests
    - rpy2.rlike
    - rpy2.rlike.tests
    - rpy2.robjects
    - rpy2.robjects.lib
    - rpy2.robjects.lib.tests
    - rpy2.robjects.tests

about:
  home: http://rpy.sourceforge.net
  license: GNU Affero General Public License v3 or GNU Library or Lesser General Public License (LGPL)

```

When I install the rpy2 package with conda in the target system and run other software with dependencies to readline, I get this error:

```
libreadline.so.6: undefined symbol: PC
```

I have found that `_rinterface.so` is pointing to the system's readline library instead of conda's:

```
ldd ./envs/test/lib/python2.7/site-packages/rpy2/rinterface/_rinterface.so | grep readline
    libreadline.so.6 => /lib64/libreadline.so.6 (0x00007f62b5447000)

```

I want to use conda's readline library, how can I enforce that?

Many thanks in advance for your help!
