### ISSUE TITLE
Potential conflict of the info directory

### ISSUE THREAD

**Issue by qobilidop** [conda/conda-build#2533]
This issue comes from a [discussion on the conda mailing list](https://groups.google.com/a/continuum.io/forum/#!topic/conda/edRGxwVCTRw/discussion). In summary, the issue is that, during building, a package might use the `info` directory, which is a special folder where conda stores metadata. In that case, the build would fail with `Exception: info/files`.

Following is an example to trigger this issue:

With `meta.yaml`:
```
{% set version = "2.1.5" %}

package:
  name: fftw
  version: {{ version }}

source:
  fn: fftw-{{ version }}.tar.gz
  url: http://www.fftw.org/fftw-{{ version }}.tar.gz

requirements:
  build:
    - gcc

  run:
    - libgcc
```

and `build.sh`:
```
#!/usr/bin/env bash

./configure -prefix=$PREFIX
make
make install
```

do `conda build .`. And it would fail.

@ngoldbaum proposes to rename the info directory to something like `__conda_info`. @msarahan concerns the transition issues for old conda versions.
