### ISSUE TITLE
recipe render error in conda-build 3.1

### ISSUE THREAD

**Issue by tomashek** [conda/conda-build#2553]
In a recipe with multiple outputs, if one of the outputs does not list a "requirements" section, the recipe is rendered with the next package in the "output" list as a dependency. If the recipe includes "requirements: []" then the problem does not exist.

Conda-build 3.0.31 does not have this problem.

Print the rendered recipe:
```
retval = api.render(<path_to_recipe>)
for pkg in retval:
    api.output_yaml(pkg[0])
```

recipe:
```
{% set version = "2018.0.1" %}
{% set buildnumber = 3 %}
{% set ipproot = 'localpath' %} 

package:
  name: ipp
  version: {{version}}

build:
  number: {{buildnumber}}
  string: intel_{{buildnumber}}
  binary_relocation: false
  detect_binary_files_with_prefix: false

outputs:
  - name: ipp
    script: meta.yaml
    script_interpreter: python {{ RECIPE_DIR }}/setup.py --fileset ipp --ipproot {{ ipproot }} --noop
  - name: ipp-include
    script: meta.yaml
    script_interpreter: python {{ RECIPE_DIR }}/setup.py --fileset ipp-include --ipproot {{ ipproot }} --noop
  - name: ipp-static
    script: meta.yaml
    script_interpreter: python {{ RECIPE_DIR }}/setup.py --fileset ipp-static --ipproot {{ ipproot }} --noop
    requirements:
      - ipp-include =={{version}}
  - name: ipp-devel
    requirements:
      - ipp =={{version}}
      - ipp-include =={{version}}

about:
  home: http://software.intel.com/en-us/articles/intel-ipp/
  license: proprietary - Intel
  license_file: license.txt
  license_family: Proprietary
  summary: Intel(R) Integrated Performance Primitives
```

ipp package is rendered with ipp-include as a requirement.
