### ISSUE TITLE
built osx packages depends on libgfortran, not libgfortran-ng

### ISSUE THREAD

**Issue by rainwoodman** [conda/conda-build#2558]
The current cross-compilation chain on osx produces binary packages that depend on libgfortran 3.0.1, which is only available on the anaconda channel, not the default channel, if the package uses ``{{compiler('fortran')}}``.

Is it supposed not to depend on libgfortran-ng on OSX? On linux it does depend on libgfortran-ng.

One example is https://github.com/bccp/conda-channel-bccp/issues/24 . 

The recipe is 

```
package:
  name: classylss
  version: 0.2.8
source:
  fn: classylss-0.2.8.tar.gz
  url: https://pypi.io/packages/source/c/classylss/classylss-0.2.8.tar.gz
  md5: d66a3d23b6a74734c6613fa6680ab394

build:
  number: 5

requirements:
  build:
  - '{{ compiler("c") }}'
  - '{{ compiler("fortran") }}'
  host:
  - python
  - numpy
  - setuptools
  - six   # only needed to download class, if needed
  - cython

  run:
  - python
  - '{{ pin_compatible("numpy") }}'
  - cython

test:
  # Python imports
  imports:
  - classylss
  - classylss.binding

about:
  home: http://github.com/nickhand/classylss
  license: GPL3
  summary: python binding of CLASS for large-scale structure calculations
  license_family: GPL3

extra:
  recipe-maintainers:
  - rainwoodman

```
