### ISSUE TITLE
conda skeleton cran uses wrong version of R

### ISSUE THREAD

**Issue by marykthompson** [conda/conda-build#2562]
I am trying to package some R packages from CRAN to use in a conda environment because I am using a combination of Python and R packages for a bioinformatics pipeline. Because of other dependencies, I need to keep R at version 3.3. However, when I try to use conda skeleton to build cran packages, it sets the R version for me at 3.4.

I made a brand new environment with the version of Python and R I want:

$ conda create -n bioinfo python=3.6.3 r=3.3.2

There is no R installed in the root environment. Then I follow the instructions for conda skeleton from within my environment:

(bioinfo)$ conda skeleton cran rootSolve

(bioinfo)$ conda build r-rootsolve

For some reason, this keeps coming up with an R3.4 dependency during the build process, even though according to CRAN, the rootSolve package only needs R>=2.01! Where is this coming from??

The following NEW packages will be INSTALLED: r-base: 3.4.2-haf99962_0

Though building the package does not actually change the version of R running in my environment, the package does not load in R3.3, unsurprisingly. The same thing is happening with two different packages I am trying to build from CRAN. I'm doing this on a linux-64 machine.

I apologize if this is something stupid, but I have read the relevant docs and been working on this for several hours to no avail.

**Comment by msarahan** [comment]
Your environment has no effect at all.  You can control the R version used in build by either specifying the --R flag to conda-build, or by setting a value for r_base in a conda_build_config.yaml file.

for example,

``conda build r-rootsolve --R 3.3.2``

The docs for conda_build_config.yaml are at https://conda.io/docs/user-guide/tasks/build-packages/variants.html

**Comment by marykthompson** [comment]
Thank you for your reply! I have been looking at this page, but unfortunately on my system, none of the following work for setting the R version for conda-build (I am using conda-build 3.1):

the following still build the package for R3.4:
$ conda build r-rootsolve --R 3.3.2
$ conda build r-rootsolve --R=3.3.2
$ export CONDA_R="3.3.2"
$ conda build r-rootsolve

#adding the desired build version in the meta.yaml file:
build:
    - r-base 3.3.2
    
#adding the desired build version in a file named conda_build_config.yaml in the r-rootsolve/ directory:

R
  -3.3.2
  
#also tried:
r
  -3.3.2

If you have any further suggestions, please let me know. One interesting thing is that when the build starts in all these cases, it lists r-base 3.3.2 among the packages to be installed, but after all the compilation messages, it then lists r-base 3.4.2, file of build output attached.
[conda_Rversion_failed_example.txt](https://github.com/conda/conda-build/files/1551737/conda_Rversion_failed_example.txt)

**Comment by msarahan** [comment]
Yes, it seems there is a bug in the automatic constraining of R.

```
conda render r-rootsolve --R=3.3.2
```

shows

```
package:
    name: r-rootsolve
    version: '1.7'
source:
    fn: rootSolve_1.7.tar.gz
    sha256: 08b3bb63f04fc0b065cb615b6ca1ef95eb6df7a813eb9eb625bc15c6de332c22
    url:
        - https://cran.r-project.org/src/contrib/rootSolve_1.7.tar.gz
        - https://cran.r-project.org/src/contrib/Archive/rootSolve/rootSolve_1.7.tar.gz
build:
    number: '0'
    rpaths:
        - lib/R/lib/
        - lib/
requirements:
    build:
        - ca-certificates 2017.08.26 ha1e5d58_0
        - compiler-rt 4.0.1 h5487866_0
        - gettext 0.19.8.1 hb0f4f8b_2
        - gsl 2.2.1 h002c638_3
        - icu 54.1 0
        - jpeg 9b he5867d9_2
        - libcxxabi 4.0.1 hebd6815_0
        - libgfortran 3.0.1 h93005f0_2
        - libiconv 1.14 0
        - make 4.2.1 h0cf4ea2_0
        - ncurses 5.9 10
        - pixman 0.34.0 hca0a616_3
        - readline 7.0 h5003dca_4
        - tk 8.6.7 h35a86e2_3
        - xz 5.2.3 h0278029_2
        - zlib 1.2.11 hf3cbc9b_2
        - gfortran_osx-64 4.8.5 hd9f5454_1
        - libcxx 4.0.1 h579ed51_0
        - libgcc 4.8.5 hdbeacc1_10
        - libpng 1.6.32 hd1e8b91_4
        - libxml2 2.9.4 0
        - openssl 1.0.2n hdbc3d79_0
        - pcre 8.39 1
        - cctools 895 h7512d6f_0
        - freetype 2.5.5 2
        - libffi 3.2.1 h475c297_4
        - libssh2 1.8.0 h9feafcd_3
        - libtiff 4.0.9 h0dac147_0
        - llvm-lto-tapi 4.0.1 h6701bc3_0
        - curl 7.55.1 h2e228d0_4
        - fontconfig 2.12.1 3
        - glib 2.50.2 1
        - ld64 274.2 h7c2db76_0
        - cairo 1.14.8 0
        - llvm 4.0.1 hc748206_0
        - clang 4.0.1 h662ec87_0
        - harfbuzz 0.9.39 2
        - clang_osx-64 4.0.1 h9d74b7d_5
        - pango 1.40.3 1
        - r-base 3.3.2 1
    host:
        - libgfortran >=3.0.1
    run:
        - r-base
        - libgfortran >=3.0.1
```

and that un-pinned r-base in run is what you're getting hung up on.   This commit was supposed to address that: https://github.com/conda/conda-build/commit/403817e507eea99090a019b4d019c6084d028c0f

but it appears that it needs more work.

You can also fix this in your recipe with this change to the run dependencies in meta.yaml:

```
  run:
    - {{ pin_compatible('r-base', max_pin='x.x') }}
    - {{native}}gcc-libs         # [win]
```
