### ISSUE TITLE
CB not honoring variants in split packages?

### ISSUE THREAD

**Issue by nehaljwani** [conda/conda-build#2599]
Given that I have a recipe:
```
package:
  name: test_pkg
  version: 5.4.0

outputs:
  - name: test_pkg_without_variant
  - name: test_pkg_with_variant
    requirements:
      build:
        - python
```
And the following `conda_build_config.yaml`:
```
python:
  - 2.7
  - 3.5
  - 3.6
```
With conda-build 3.0.31, it built:
```
test_pkg_with_variant-5.4.0-h8bdc588_0.tar.bz2
test_pkg_with_variant-5.4.0-hae0a370_0.tar.bz2
test_pkg_with_variant-5.4.0-h6bb98e6_0.tar.bz2
test_pkg_without_variant-5.4.0-h36134e3_0.tar.bz2
```

But with conda-build >3.0.31, it ignores the variants and just builds:
```
test_pkg_with_variant-5.4.0-0.tar.bz2
test_pkg_without_variant-5.4.0-0.tar.bz2
```

**Comment by nehaljwani** [comment]
If I explicitly add python as a runtime dep, then CB >3.0.31 builds the variants:
```
package:
  name: test_pkg
  version: 5.4.0

outputs:
  - name: test_pkg_without_variant
  - name: test_pkg_with_variant
    requirements:
      build:
        - python
      run:
        - python
```
The tarballs generated are:
```
test_pkg_with_variant-5.4.0-py27_0.tar.bz2
test_pkg_with_variant-5.4.0-py35_0.tar.bz2
test_pkg_with_variant-5.4.0-py36_0.tar.bz2
test_pkg_without_variant-5.4.0-0.tar.bz2
```
