### ISSUE TITLE
build/host dependency automatically added to run dependency

### ISSUE THREAD

**Issue by rainwoodman** [conda/conda-build#2602]
This behaviour is not documented in https://conda.io/docs/user-guide/tasks/build-packages/define-metadata.html#requirements-section

This is not always intended. For example if my application links to the static version of libz and bzip2, then there is no need to include the two packages at runtime. 

meta.yaml
```
package:
  name: python-mpi-bcast
  version: 0.1.1

source:
  fn: python-mpi-bcast-0.1.1.tar.gz # [unix]
  url: https://github.com/rainwoodman/python-mpi-bcast/archive/0.1.1.tar.gz

build:
  number: 1
  detect_binary_files_with_prefix: true
  features:
     - '{{ mpi }}'

requirements:
  build:
    - '{{ compiler("c") }}'
    - '{{ mpi }}'
    - bzip2
    - zlib 

  run:
    - '{{ mpi }}'

about:
  home: https://github.com/rainwoodman/python-mpi-bcast
  license: BSD
  summary: Launching Python Applications with MPI Broadcast
  description: |
        Tools for fast launching of python application on clusters with MPI.
        A new Python distribution is deployed to computing nodes at job launch.
```

produces index.json
```
{
  "arch": "x86_64",
  "build": "cori.prgenv.gnu.mpihdd81f19_1",
  "build_number": 1,
  "depends": [
    "bzip2 >=1.0.6,<2.0a0",
    "cori.prgenv.gnu.mpi",
    "zlib >=1.2.11,<1.3.0a0"
  ],
  "features": "cori.prgenv.gnu.mpi",
  "license": "BSD",
  "name": "python-mpi-bcast",
  "platform": "linux",
  "subdir": "linux-64",
  "timestamp": 1514242237957,
  "version": "0.1.1"
}

```

Even though bzip2 and zlib are not declared in run (nor in the variant file) it still shows up in index.json.
