### ISSUE TITLE
strong run_exports not crossing boundaries?

### ISSUE THREAD

**Issue by nehaljwani** [conda/conda-build#2607]
CB 3.2.0 and C 4.4.4

```
(base) bm-osx109-01:test builder$ cat build.sh 
stat $PREFIX/lib/libc++.dylib

(base) bm-osx109-01:test builder$ cat meta.yaml 
package:
  name: test
  version: 1.0.0

requirements:
  host:
   - make
  build:
   - {{ compiler('cxx') }}
```

A run of `conda build` fails with:
```
stat: /Users/builder/nwani/m3/conda-bld/test_1514579903346/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/libc++.dylib: stat: No such file or directory
```

But clangxx has:
```
strong: [libcxx  >=4.0.1]
```

The build above passes up to CB 3.1.3, after that, it breaks.
