### ISSUE TITLE
Fails to render requirements when using Jinja "extends"

### ISSUE THREAD

**Issue by ccharlesgb** [conda/conda-build#2684]
### Actual Behavior

I am experimenting with using a base template for my conda packages and believe I have found an issue with how conda renders the Jinja2 templates when using the {% extends "" %} syntax. I have 2 basic test packages which I have been using to isolate the issue. The first has the meta.yaml file:

**meta.yaml**
```yaml
package:
  name: cc_pack
  version: "0.1"

source:
  path: ../

requirements:
    build:
        - python
    run:
        - python

build:
  script: python setup.py install
  entry_points:
    - cc_test = cc_pack.do_stuff:main

test:
  imports:
    - cc_pack
```

Which renders using conda render to:
```
M:\Python>conda render cc-pack
package:
    name: cc_pack
    version: '0.1'
source:
    path: M:\Python\cc-pack
build:
    entry_points:
        - cc_test = cc_pack.do_stuff:main
    script: python setup.py install
requirements:
    build:
        - wheel 0.30.0 py27ha643586_1
        - setuptools 38.4.0 py27_0
        - pip 9.0.1 py27hdaa76b4_4
        - certifi 2018.1.18 py27_0
        - vs2008_runtime 9.00.30729.1 hfaea7d5_1
        - wincertstore 0.2 py27hf04cefb_0
        - vc 9 h7299396_1
        - python 2.7.14 h8c3f1cb_23
    run:
        - python >=2.7,<2.8.0a0
test:
    imports:
        - cc_pack
extra:
    copy_test_source_files: true
    final: true

```
This render builds as expected and works fine. However if I use the following Jinja base template:

**base_meta.yaml**
```yaml
package:
  name: {% block package_name %}{% endblock %}
  version: 0.1

source:
  path: ../

{% block requirements %}

{% endblock %}

build:
  script: python setup.py install
  entry_points:
    - cc_test = cc_pack.do_stuff:main

test:
  imports:
    - cc_pack

```

With the corresponding meta.yaml:

```yaml
{% extends "base_meta.yml" %}

{% block package_name %}cc-pack{% endblock %}

{% block requirements %}

requirements:
  build:
    - python
  run:
    - python
    
{% endblock %}
```
The render output is:
```yaml
M:\Python>conda render cc-pack
package:
    name: cc-pack
    version: '0.1'
source:
    path: M:\Python\cc-pack
build:
    entry_points:
        - cc_test = cc_pack.do_stuff:main
    script: python setup.py install
test:
    imports:
        - cc_pack
extra:
    copy_test_source_files: true
    final: true
```
The requirements section is missing! This then causes the build to fail and the import test failed to import the module. I can't find anything in the documentation that says this behavior is not supported.

I would expect the requirement section to render fine however it appears that this is ignored by the render stage.

##### `Output of conda info`

```
M:\Python>conda info

     active environment : None
       user config file : C:\Users\ccharles\.condarc
 populated config files : C:\Users\ccharles\.condarc
          conda version : 4.4.10
    conda-build version : 3.4.2
         python version : 2.7.13.final.0
       base environment : C:\dev\bin\Anaconda  (writable)
           channel URLs : https://conda.anaconda.org/r/win-64
                          https://conda.anaconda.org/r/noarch
                          https://repo.continuum.io/pkgs/main/win-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
                          http://conda/external/win-64
                          http://conda/external/noarch
                          http://conda/ci/win-64
                          http://conda/ci/noarch
                          file://fsrsvr06pr/departments/Pricing%20%26%20Forecast
ing/Department/Python/conda/ge/win-64
                          file://fsrsvr06pr/departments/Pricing%20%26%20Forecast
ing/Department/Python/conda/ge/noarch
          package cache : C:\dev\bin\Anaconda\pkgs
                          C:\Users\ccharles\AppData\Local\conda\conda\pkgs
       envs directories : C:\dev\bin\Anaconda\envs
                          C:\Users\ccharles\AppData\Local\conda\conda\envs
                          C:\Users\ccharles\.conda\envs
               platform : win-64
             user-agent : conda/4.4.10 requests/2.14.2 CPython/2.7.13 Windows/7
Windows/6.1.7601
          administrator : False
             netrc file : None
           offline mode : False
```

The test repo for reproducing this can be found: https://github.com/ccharlesgb/cc-pack
