### ISSUE TITLE
Issues using load_setup_py_data in multi-project repositories

### ISSUE THREAD

**Issue by mariusvniekerk** [conda/conda-build#2697]
I have a git repository that has roughly the following structure.  
All python packages are versioned using versioneer, with prefix matching so that
module_a and module_b have seperate versions.

```
./.git
./module_a/setup.py
./module_a/setup.cfg
./module_a/conda.recipe/meta.yaml
./module_a/module_a/...
./module_b/setup.py
./module_b/conda.recipe/meta.yaml
./module_b/module_b/...
```

### setup.cfg
```
[versioneer]
VCS = git
style = pep440
versionfile_source = module_a/_version.py
versionfile_build = module_a/_version.py
tag_prefix = MOD_A_
```

The following used to work in conda-build 2, but fails in conda-build 3.

### meta.yaml
```yaml
package:
  name: module_a
  version: "{{ load_setup_py_data(
      setup_file='setup.py',
      config=namespace(build_python='', work_dir=environ['SRC_DIR'] + '/module_a')
    ).version }}"
source:
  path: ../..

build:
  script:
    - cd module_a
    - python -m pip install --no-deps --ignore-installed .
```

## Error

```
> cd module_a
> conda build conda-recipe
SystemExit: Undefined Jinja2 variables remain (['version']).  Please enable source downloading and try again.
```

What is the best way to proceed in conda-build-3.
