### ISSUE TITLE
Behavior of pin_compatible() is different for different runs?

### ISSUE THREAD

**Issue by nehaljwani** [conda/conda-build#2707]
I have a simple recipe:
```
[root@f0795f5d6960 build_scripts]# cat meta.yaml 
package:
  name: pkg
  version: 1.0.0

requirements:
  host:
    - python
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}
```

I have a simple build matrix:
```
[root@f0795f5d6960 build_scripts]# cat conda_build_config.yaml 
numpy:
  - 1.9   # [unix]
python:
  - 2.7
  - 3.5
  - 3.6
```
In a fresh container of docker.io/conda/c3i-linux-64, build this recipe.

One building this package, one the first run, I get:
```
pkg-1.0.0-py27h24bf2e0_0.tar.bz2 -> "numpy >=1.9.3,<2.0a0"
pkg-1.0.0-py35h24bf2e0_0.tar.bz2 -> "numpy >=1.14.1,<2.0a0"
pkg-1.0.0-py36h24bf2e0_0.tar.bz2 -> "numpy >=1.9.3,<2.0a0"
```
Now, I run it again. This time I get:
```
pkg-1.0.0-py27h24bf2e0_0.tar.bz2 -> "numpy >=1.14.1,<2.0a0"
pkg-1.0.0-py35h24bf2e0_0.tar.bz2 -> "numpy >=1.14.1,<2.0a0"
pkg-1.0.0-py36h24bf2e0_0.tar.bz2 -> "numpy >=1.14.1,<2.0a0"
```
Now, I run it again. This time I get:
```
pkg-1.0.0-py27h24bf2e0_0.tar.bz2 -> "numpy >=1.9.3,<2.0a0"
pkg-1.0.0-py35h24bf2e0_0.tar.bz2 -> "numpy >=1.9.3,<2.0a0"
pkg-1.0.0-py36h24bf2e0_0.tar.bz2 -> "numpy >=1.9.3,<2.0a0"
```
Now, I run it again. This time I get same as above.

Now, I run it again. This time I get the same as the second run.

What's happening?
