### ISSUE TITLE
Conda-build dependency error

### ISSUE THREAD

**Issue by AaronV77** [conda/conda-build#2804]
Hello again, I'm trying to build a package for conda from scratch rather then using a PyPi package this time. The dependency list is a little different this time around and is causing a dependency issue:

    Traceback (most recent call last):
    File "setup.py", line 6, in <module>
        pbr=True,
    File "/Users/aaronV/anaconda3/conda-bld/quest_1522847612043/place_holder/lib/python3.6/site-packages/setuptools/__init__.py", line 128, in setup
        _install_setup_requires(attrs)
    File "/Users/aaronV/anaconda3/conda-bld/quest_1522847612043/place_holder/lib/python3.6/site-packages/setuptools/__init__.py", line 123, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
    File "/Users/aaronV/anaconda3/conda-bld/quest_1522847612043/place_holder/lib/python3.6/site-packages/setuptools/dist.py", line 513, in fetch_build_eggs
        replace_conflicting=True,
    File "/Users/aaronV/anaconda3/conda-bld/quest_1522847612043/place_holder/lib/python3.6/site-packages/pkg_resources/__init__.py", line 774, in resolve
        replace_conflicting=replace_conflicting
    File "/Users/aaronV/anaconda3/conda-bld/quest_1522847612043/place_holder/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1057, in best_match
        return self.obtain(req, installer)
    File "/Users/aaronV/anaconda3/conda-bld/quest_1522847612043/place_holder/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1069, in obtain
        return installer(requirement)
    File "/Users/aaronV/anaconda3/conda-bld/quest_1522847612043/place_holder/lib/python3.6/site-packages/setuptools/dist.py", line 580, in fetch_build_egg
        return cmd.easy_install(req)
    File "/Users/aaronV/anaconda3/conda-bld/quest_1522847612043/place_holder/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 661, in easy_install
        not self.always_copy, self.local_index
    File "/Users/aaronV/anaconda3/conda-bld/quest_1522847612043/place_holder/lib/python3.6/site-packages/setuptools/package_index.py", line 656, in fetch_distribution
        self.find_packages(requirement)
    File "/Users/aaronV/anaconda3/conda-bld/quest_1522847612043/place_holder/lib/python3.6/site-packages/setuptools/package_index.py", line 489, in find_packages
        self.scan_url(self.index_url + requirement.unsafe_name + '/')
    File "/Users/aaronV/anaconda3/conda-bld/quest_1522847612043/place_holder/lib/python3.6/site-packages/setuptools/package_index.py", line 829, in scan_url
        self.process_url(url, True)
    File "/Users/aaronV/anaconda3/conda-bld/quest_1522847612043/place_holder/lib/python3.6/site-packages/setuptools/package_index.py", line 324, in process_url
        "Be sure to add all dependencies in the meta.yaml  url=%s" % url)
    RuntimeError: Setuptools downloading is disabled in conda build. Be sure to add all dependencies in the meta.yaml  url=https://pypi.python.org/simple/pytest-runner/
    Traceback (most recent call last):
    File "/Users/aaronV/anaconda3/bin/conda-build", line 6, in <module>
        sys.exit(conda_build.cli.main_build.main())
    File "/Users/aaronV/anaconda3/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 420, in main
        execute(sys.argv[1:])
    File "/Users/aaronV/anaconda3/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 411, in execute
        verify=args.verify)
    File "/Users/aaronV/anaconda3/lib/python3.6/site-packages/conda_build/api.py", line 199, in build
        notest=notest, need_source_download=need_source_download, variants=variants)
    File "/Users/aaronV/anaconda3/lib/python3.6/site-packages/conda_build/build.py", line 2105, in build_tree
        notest=notest,
    File "/Users/aaronV/anaconda3/lib/python3.6/site-packages/conda_build/build.py", line 1377, in build
        utils.check_call_env(cmd, env=env, cwd=src_dir, stats=build_stats)
    File "/Users/aaronV/anaconda3/lib/python3.6/site-packages/conda_build/utils.py", line 301, in check_call_env
        return _func_defaulting_env_to_os_environ('call', *popenargs, **kwargs)
    File "/Users/aaronV/anaconda3/lib/python3.6/site-packages/conda_build/utils.py", line 280, in _func_defaulting_env_to_os_environ
        raise subprocess.CalledProcessError(proc.returncode, _args)
    subprocess.CalledProcessError: Command '['/bin/bash', '-e', '/Users/aaronV/anaconda3/conda-bld/quest_1522847612043/work/conda_build.sh']' returned non-zero exit status 1.

Here is my setup.py:

```
from setuptools import setup

setup(
    setup_requires=['pbr', 'pytest-runner'],
    pbr=True,
)
```

Here is my meta.yml file:

```
{% set version = "2.4.1" %}

package:
  name: quest
  version: {{ version }}

source:
  git_url: https://github.com/erdc/quest.git
  git_rev: {{ version }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python
    - setuptools
    - pbr

  run:
    - python
    - fiona
    - rasterio
    - gdal
    - numpy
    - geojson
    - jinja2
    - ulmo
    - pyyaml
    - matplotlib
    - click
    - werkzeug
    - peewee
    - stevedore
    - geopandas
    - distributed
    - psutil
    - pint
    - pony
    - tornado
    - sortedcollections
    - pytest-cov
    - param
    - sphinx
    - sphinx_rtd_theme
    - hs_restclient
    - girder-client

test:
  imports:
    - quest
```

Now I've tired moving things around and double checking the dependency list, and still get this error with anything I try. I read some where in: https://conda.io/docs/user-guide/tasks/build-packages/define-metadata.html that the jinja2 package has to be some where specific but couldn't make out where it has to be, but could that be the cause of this headache? Thanks for any advice~!
