### ISSUE TITLE
Incorrect package name export

### ISSUE THREAD

**Issue by Theophile88** [conda/conda-build#2827]
### Actual Behavior

The package which is `kaldi==r7271.1a4dbf6=h6bb2d05_2` is exported as `kaldi==r7271.1a4dbf6=2`.

With the following `meta.yaml` in `conda/kaldi`:
```
{% set name = "kaldi" %}
{% set version = "r7271.1a4dbf6" %}
{% set git_rev = "1a4dbf6be118e4967cf4efd510811ef72cdfee3d" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/kaldi-asr/kaldi.git
  git_rev: {{ git_rev }}

build:
  number: 0
  skip: True  # [not linux]
  requires_features:
    blas: mkl
  run_exports:
    - {{ pin_subpackage(name, exact=True) }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

test:
  commands:
    - conda inspect linkages -p $PREFIX {{ name }}  # [not win]
    - conda inspect objects -p $PREFIX {{ name }}  # [osx]

about:
  home: http://kaldi-asr.org/
  license: Apache-2.0
  license_file: COPYING
  summary: 'Kaldi is a toolkit for speech recognition written in C++.'
  description: |
    Kaldi is intended for use by speech recognition researchers. It is a framework rather than a library.
  doc_url: http://kaldi-asr.org/doc
  dev_url: http://kaldi-asr.org/forums.html
```
`conda build --output conda/kaldi` gives:

```
/scratch/....../softs/anaconda2/conda-bld/linux-64/kaldi-r7271.1a4dbf6-hf484d3e_0.tar.bz2
```

but `conda render conda/kaldi` generates an incorrect `run_exports`  (see below `kaldi r7271.1a4dbf6 0`)

```
package:
    name: kaldi
    version: r7271.1a4dbf6
source:
    git_rev: 1a4dbf6be118e4967cf4efd510811ef72cdfee3d
    git_url: https://github.com/kaldi-asr/kaldi.git
build:
    number: '0'
    requires_features:
        blas: mkl
    run_exports:
        - kaldi r7271.1a4dbf6 0
requirements:
    build:
        - binutils_impl_linux-64 2.28.1 had2808c_3
        - libstdcxx-ng 7.2.0 hdf63c60_3
        - binutils_linux-64 7.2.0 26
        - gcc_impl_linux-64 7.2.0 habb00fd_3
        - gcc_linux-64 7.2.0 26
        - gxx_impl_linux-64 7.2.0 hdf63c60_3
        - gxx_linux-64 7.2.0 26
    run:
        - libstdcxx-ng >=7.2.0
        - libgcc-ng >=7.2.0
test:
    commands:
        - conda inspect linkages -p $PREFIX kaldi
about:
    description: 'Kaldi is intended for use by speech recognition researchers. It
        is a framework rather than a library.

        '
    dev_url: http://kaldi-asr.org/forums.html
    doc_url: http://kaldi-asr.org/doc
    home: http://kaldi-asr.org/
    license: Apache-2.0
    license_file: COPYING
    summary: Kaldi is a toolkit for speech recognition written in C++.
extra:
    copy_test_source_files: true
    final: true
```

The bug seems to be in `pin_subpackage()`.

### Expected Behavior

The package should be exported as `kaldi r7271.1a4dbf6 hf484d3e 0`.

##### `Output of conda info`
```
     active environment : dev
    active env location : .../dev
            shell level : 1
       user config file : .../home/.condarc
 populated config files : .../home/.condarc
                          .../softs/anaconda2/envs/dev/.condarc
          conda version : 4.5.1
    conda-build version : 3.8.1
         python version : 2.7.14.final.0
       base environment : /scratch/...../softs/anaconda2  (writable)
           channel URLs : https://www.idiap.ch/software/bob/conda/label/beta/linux-64
                          https://www.idiap.ch/software/bob/conda/label/beta/noarch
                          https://www.idiap.ch/software/bob/conda/linux-64
                          https://www.idiap.ch/software/bob/conda/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /scratch/......./softs/anaconda2/pkgs
                          /idiap/home/....../.conda/pkgs
       envs directories : /scratch/......./softs/anaconda2/envs
                          /idiap/home/......./.conda/envs
               platform : linux-64
             user-agent : conda/4.5.1 requests/2.18.4 CPython/2.7.14 Linux/4.9.0-5-amd64 debian/9 glibc/2.24
                UID:GID : 1667:500
             netrc file : None
           offline mode : False

```
