### ISSUE TITLE
conda-build 3 allows spec without space between name and version spec

### ISSUE THREAD

**Issue by jakirkham** [conda/conda-build#2828]
The following recipe below is not valid under `conda-build` 2, but appears to be valid (IOW it builds) under `conda-build` 3. Based on discussion in issue ( https://github.com/conda/conda-docs/issues/448 ), it sounds like not requiring the space is not intentional. So the question becomes what should `conda-build`'s behavior be going forward? Should it start erroring again? Should it warn? Something else?

```yaml
{% set version = "1.10.1" %}

package:
  name: holoviews
  version: {{ version }}

source:
  fn: holoviews-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/h/holoviews/holoviews-{{ version }}.tar.gz
  sha256: 3fa11d143ba9a60802686af23942848067181771c7558a369b3e1476ad54ba9f

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .


requirements:
  build:
    - python
    - pip
    - param >=1.6.0,<2.0
  run:
    - python
    - param >=1.6.0,<2.0
    - numpy
    - matplotlib
    - bokeh>=0.12.14,<=0.12.16
    - jupyter
    - notebook
    - ipython>=5.4.0

test:
  imports:
    - holoviews

about:
  home: www.holoviews.org
  summary: Stop plotting your data - annotate your data and let it visualize itself.
  license: BSD 3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - jlstevens
    - philippjfr
    - basnijholt
```

ref: https://github.com/conda-forge/holoviews-feedstock/pull/33
