### ISSUE TITLE
run_exports issue in conda-build=3.9

### ISSUE THREAD

**Issue by isuruf** [conda/conda-build#2851]
### Actual Behavior

```yaml
package:
  name: asd
  version: 1.2

build:
  number: 0

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - sqlite
    - zlib
    - jpeg
  run:
    - sqlite
    - zlib
    - jpeg
```

Gives the following info.json
```json
{
  "arch": "x86_64",
  "build": "h3390bc4_0",
  "build_number": 0,
  "depends": [
    "jpeg >=9b,<10a",
    "libgcc-ng",
    "libstdcxx-ng",
    "sqlite >=3.22.0,<4.0a0",
    "zlib >=1.2.11,<1.3.0a0"
  ],
  "name": "asd",
  "platform": "linux",
  "subdir": "linux-64",
  "timestamp": 1524956394962,
  "version": "1.2"
}
```

### Expected Behavior

Expected and conda-build=3.8 behaviour. Notice `libgcc-ng >=4.9`

```json
{
  "arch": "x86_64",
  "build": "h3390bc4_0",
  "build_number": 0,
  "depends": [
    "jpeg >=9b,<10a",
    "libgcc-ng >=4.9",
    "libstdcxx-ng >=4.9",
    "sqlite >=3.22.0,<4.0a0",
    "zlib >=1.2.11,<1.3.0a0"
  ],
  "name": "asd",
  "platform": "linux",
  "subdir": "linux-64",
  "timestamp": 1524956481256,
  "version": "1.2"
}
```

### Steps to Reproduce

Use `conda-build=3`. Add `conda-forge` channel. Build with latest `conda_build_config.yaml` from `conda-forge-pinning`.

##### `Output of conda info`

```
     active environment : None
       user config file : /home/isuru/.condarc
 populated config files : /home/isuru/.condarc
          conda version : 4.5.1
    conda-build version : 3.8.1
         python version : 3.6.4.final.0
       base environment : /home/isuru/miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /home/isuru/miniconda3/pkgs
                          /home/isuru/.conda/pkgs
       envs directories : /home/isuru/miniconda3/envs
                          /home/isuru/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.1 requests/2.18.4 CPython/3.6.4 Linux/4.13.0-38-generic ubuntu/16.04 glibc/2.23
                UID:GID : 1000:1000
             netrc file : /home/isuru/.netrc
           offline mode : False
```

**Comment by msarahan** [comment]
Could not reproduce.  In a docker container:

```
conda render . -c conda-forge -m /opt/conda/conda_build_config.yaml

package:
    name: asd
    version: '1.2'
build:
    number: '0'
requirements:
    build:
        - toolchain_cxx_linux-64 2.1.2 0
        - cmake 3.11.1 0
        - openssl 1.0.2o 0
        - bzip2 1.0.6 1
        - ca-certificates 2018.4.16 0
        - expat 2.2.5 0
        - ncurses 5.9 10
        - zlib 1.2.11 0
        - toolchain_c_linux-64 2.1.2 0
        - libssh2 1.8.0 2
        - libuv 1.20.2 0
        - rhash 1.3.4 0
        - krb5 1.14.6 0
        - toolchain 2.1.2 0
        - curl 7.59.0 1
        - xz 5.2.3 0
    host:
        - jpeg 9b 2
        - libgcc-ng 7.2.0 hdf63c60_3
        - libstdcxx-ng 7.2.0 hdf63c60_3
        - ncurses 5.9 10
        - zlib 1.2.11 0
        - readline 7.0 0
        - sqlite 3.22.0 0
    run:
        - libgcc-ng >=4.9
        - jpeg >=9b,<10a
        - libstdcxx-ng >=4.9
        - sqlite >=3.22.0,<4.0a0
        - zlib >=1.2.11,<1.3.0a0
extra:
    copy_test_source_files: true
    final: true
```

```
conda build . -c conda-forge -m /opt/conda/conda_build_config.yaml
```

```
{
  "arch": "x86_64",
  "build": "h3390bc4_0",
  "build_number": 0,
  "depends": [
    "jpeg >=9b,<10a",
    "libgcc-ng >=4.9",
    "libstdcxx-ng >=4.9",
    "sqlite >=3.22.0,<4.0a0",
    "zlib >=1.2.11,<1.3.0a0"
  ],
  "name": "asd",
  "platform": "linux",
  "subdir": "linux-64",
  "timestamp": 1525097117407,
  "version": "1.2"
}
```

I have made small edits to conda-build, which was having some strange issues with python sometimes coming in as a tuple, which made other parts barf.

```
diff --git a/conda_build/environ.py b/conda_build/environ.py
index c46f0056..8eefcf5a 100644
--- a/conda_build/environ.py
+++ b/conda_build/environ.py
@@ -45,8 +45,10 @@ def get_lua_ver(config):


 def get_py_ver(config):
-    return '.'.join(config.variant.get('python',
-                                       get_default_variant(config)['python']).split('.')[:2])
+    py = config.variant.get('python', get_default_variant(config)['python'])
+    if not hasattr(py, 'split'):
+        py = py[0]
+    return '.'.join(py.split('.')[:2])


 def get_r_ver(config):
diff --git a/conda_build/metadata.py b/conda_build/metadata.py
index 9f7e1024..4ec4da35 100644
--- a/conda_build/metadata.py
+++ b/conda_build/metadata.py
@@ -85,6 +85,9 @@ def ns_cfg(config):

     defaults = variants.get_default_variant(config)
     py = config.variant.get('python', defaults['python'])
+    # there are times when python comes in as a tuple
+    if not hasattr(py, 'split'):
+        py = py[0]
     py = int("".join(py.split('.')[:2]))
     d.update(dict(py=py,
                     py3k=bool(30 <= py < 40),
```
