### ISSUE TITLE
Allow multiline `script` in `outputs`

### ISSUE THREAD

**Issue by jakirkham** [conda/conda-build#2857]
For the `outputs` section, would be nice to have the option of using multiline of list scripts. This is good for compactness and to handle commonplace situations that involve `cd`ing into some directory first before running the relevant step (e.g. `make install`).

**Comment by msarahan** [comment]
This is allowed, but you have to do

```
- name: output
  build:
    script:
      - cd
      - echo weee
```

The ``script`` field directly under the output, not under the build section, only takes a filename argument.  Sorry for the confusing labels.
