### ISSUE TITLE
Using msvc_compiler still results in a matrix with compiler syntax

### ISSUE THREAD

**Issue by jakirkham** [conda/conda-build#2866]
When upgrading to `conda-smithy` 3 and `conda-build` 3, created this change to the [`ninja` feedstock]( https://github.com/conda-forge/ninja-feedstock/ ) and re-rendered. Was thinking that setting `msvc_compiler` and having `{{ compiler("cxx") }}` would result in effectively skipping the compiler matrix matrix. However it still generated VS 2008 and VS 2015 variants. Using the diff below (switching to `skip`) fixed the issue.

<details>
<summary>Recipe</summary>

```yaml
{% set version = "1.8.2" %}

package:
  name: ninja
  version: {{ version }}

source:
  fn: v{{ version }}.tar.gz
  url: https://github.com/ninja-build/ninja/archive/v{{ version }}.tar.gz
  sha256: 86b8700c3d0880c2b44c2ff67ce42774aaf8c28cbf57725cb881569288c1c6f4

build:
  number: 1
  msvc_compiler: 14.0  # [win]

requirements:
  build:
    - {{ compiler("cxx") }}
    - python

test:
  commands:
    - ninja --version

about:
  home: https://ninja-build.org/
  license: Apache 2.0
  license_family: Apache
  license_file: COPYING
  summary: A small build system with a focus on speed

extra:
  recipe-maintainers:
    - frol
    - Korijn
    - xoviat
```

</details>

<details>
<summary>Diff</summary>

```diff
diff --git a/recipe/meta.yaml b/recipe/meta.yaml
index c551396..658cbce 100644
--- a/recipe/meta.yaml
+++ b/recipe/meta.yaml
@@ -11,7 +11,7 @@ source:
 
 build:
   number: 1
-  msvc_compiler: 14.0  # [win]
+  skip: true  # [win and vc!=14]
 
 requirements:
   build:
```

</details>

**Comment by msarahan** [comment]
sorry, I need to add a deprecation notice to msvc_compiler.  It may be broken even outside of the context of variants, and I definitely don't have time to fix it.

You may want to add:

```
build:
  ignore_run_exports:
    - vc
requirements:
  run:
    - vs2015_runtime
```

This will allow you to use your ninja package in py2.7 envs.
