### ISSUE TITLE
empty host section is discarded, host and build envs merged

### ISSUE THREAD

**Issue by mbargull** [conda/conda-build#2887]
### Actual Behavior

`host` and `build` environments are merged if `requirements/host` is present but empty, i.e., an empty `list` or `None`.

### Expected Behavior

`build` and `host` should not be merged for all cases were `host` is present, [as described in the docs](https://conda.io/docs/user-guide/tasks/build-packages/define-metadata.html#host):
> The only time that build and host are merged is when the host section is absent, and no `{{ compiler() }}` jinja2 functions are used in meta.yaml.

### Steps to Reproduce

```
(base) $ conda --version
conda 4.5.4
(base) $ conda-build --version
conda-build 3.10.2
(base) $ cat meta.yaml
package:
  name: pkg
requirements:
  build:
    - bzip2
  host:
(base) $ conda render .
package:
    name: pkg
requirements:
    build:
        - libgcc-ng 7.2.0 hdf63c60_3
        - bzip2 1.0.6 h9a117a8_4
    run:
        - bzip2 >=1.0.6,<2.0a0
extra:
    copy_test_source_files: true
    final: true

(base) $ echo '    - unzip' >> meta.yaml 
(base) $ cat meta.yaml 
package:
  name: pkg
requirements:
  build:
    - bzip2
  host:
    - unzip
(base) $ conda render .
package:
    name: pkg
requirements:
    build:
        - libgcc-ng 7.2.0 hdf63c60_3
        - bzip2 1.0.6 h9a117a8_4
    host:
        - libgcc-ng 7.2.0 hdf63c60_3
        - unzip 6.0 h611a1e1_0
extra:
    copy_test_source_files: true
    final: true

```
Expected behavior: No `run: ['bzip2 >=1.0.6,<2.0a0']` in both cases.

##### `Output of conda info`

```
     active environment : base
    active env location : /opt/conda
            shell level : 1
       user config file : /root/.condarc
 populated config files : 
          conda version : 4.5.4
    conda-build version : 3.10.2
         python version : 3.6.5.final.0
       base environment : /opt/conda  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /opt/conda/pkgs
                          /root/.conda/pkgs
       envs directories : /opt/conda/envs
                          /root/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.4 requests/2.18.4 CPython/3.6.5 Linux/4.14.39-1-MANJARO debian/9 glibc/2.24
                UID:GID : 0:0
             netrc file : None
           offline mode : False
```

**Comment by msarahan** [comment]
I think #2882 should fix this.  Can you try it?

**Comment by mbargull** [comment]
Same result with latest `master`:
```
(base) $ conda-build --version                                                                                                                                                                                                                                                   
conda-build 3.10.2+8.g44821450
(base) $ cat meta.yaml                                                                                                                                                                                                                                                           
package:
  name: pkg
requirements:
  build:
    - bzip2
  host:
(base) $ conda-render .                                                                                                                                                                                                                                                          
package:
    name: pkg
requirements:
    build:
        - libgcc-ng 7.2.0 hdf63c60_3
        - bzip2 1.0.6 h9a117a8_4
    run:
        - bzip2 >=1.0.6,<2.0a0
extra:
    copy_test_source_files: true
    final: true

(base) $ echo '    - unzip' >> meta.yaml                                                                                                                                                                                                                                         
(base) $ cat meta.yaml                                                                                                                                                                                                                                                           
package:
  name: pkg
requirements:
  build:
    - bzip2
  host:
    - unzip
(base) $ conda render .                                                                                                                                                                                                                                                          
package:
    name: pkg
requirements:
    build:
        - libgcc-ng 7.2.0 hdf63c60_3
        - bzip2 1.0.6 h9a117a8_4
    host:
        - libgcc-ng 7.2.0 hdf63c60_3
        - unzip 6.0 h611a1e1_0
extra:
    copy_test_source_files: true
    final: true

```
