### ISSUE TITLE
Incorrect path, cannot create directory

### ISSUE THREAD

**Issue by mliu49** [conda/conda-build#2901]
I'm experiencing an error on 3.10.4 which was not present on 3.10.2. I have not tested 3.10.3, so I can't comment on whether that version works.

On 3.10.4, the following occurs a the`install_egg_info` step:
```
changing mode of /home/travis/miniconda/conda-bld/rmg_1526922894154/_build_env/bin/thermoEstimator.py to 755
changing mode of /home/travis/miniconda/conda-bld/rmg_1526922894154/_build_env/bin/databaseTest.py to 755
running install_egg_info
Writing /home/travis/miniconda/conda-bld/rmg_1526922894154/_build_env/lib/python2.7/site-packages/RMG_Py-2.1.9-py2.7.egg-info
cp: cannot create directory ‘/home/travis/miniconda/conda-bld/rmg_1526922894154/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python2.7/site-packages’: No such file or directory
source tree in: /home/travis/miniconda/conda-bld/rmg_1526922894154/work
Traceback (most recent call last):
  File "/home/travis/miniconda/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/home/travis/miniconda/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 420, in main
    execute(sys.argv[1:])
  File "/home/travis/miniconda/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 411, in execute
    verify=args.verify)
  File "/home/travis/miniconda/lib/python2.7/site-packages/conda_build/api.py", line 200, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "/home/travis/miniconda/lib/python2.7/site-packages/conda_build/build.py", line 2168, in build_tree
    notest=notest,
  File "/home/travis/miniconda/lib/python2.7/site-packages/conda_build/build.py", line 1408, in build
    utils.check_call_env(cmd, env=env, cwd=src_dir, stats=build_stats)
  File "/home/travis/miniconda/lib/python2.7/site-packages/conda_build/utils.py", line 300, in check_call_env
    return _func_defaulting_env_to_os_environ('call', *popenargs, **kwargs)
  File "/home/travis/miniconda/lib/python2.7/site-packages/conda_build/utils.py", line 280, in _func_defaulting_env_to_os_environ
    raise subprocess.CalledProcessError(proc.returncode, _args)
subprocess.CalledProcessError: Command '['/bin/bash', '-e', '/home/travis/miniconda/conda-bld/rmg_1526922894154/work/conda_build.sh']' returned non-zero exit status 1
```

On 3.10.2, the following occurs instead (and then continues with the rest of the build).
```
changing mode of /home/travis/miniconda/conda-bld/rmg_1526926882611/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/bin/thermoEstimator.py to 755
changing mode of /home/travis/miniconda/conda-bld/rmg_1526926882611/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/bin/databaseTest.py to 755
running install_egg_info
Writing /home/travis/miniconda/conda-bld/rmg_1526926882611/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python2.7/site-packages/RMG_Py-2.1.9-py2.7.egg-info
source tree in: /home/travis/miniconda/conda-bld/rmg_1526926882611/work
Resource usage statistics from building rmg:
   Process count: 6
   CPU time: Sys=0:00:08.5, User=0:08:59.8
   Memory: 827.8M
   Disk usage: 219.1K
   Time elapsed: 0:10:01.6
Packaging rmg
INFO:conda_build.build:Packaging rmg
Packaging rmg-2.1.9-py27_2
INFO:conda_build.build:Packaging rmg-2.1.9-py27_2
compiling .pyc files...
```

It seems related to the switch from `_h_env_...` to `_build_env` and some path not getting changed. I don't have a good way to reproduce this, besides building RMG-Py, but can provide additional info if needed. It seems to me like this shouldn't be related to the specific build setup for RMG-Py though, so perhaps building other packages could also cause this error.

Travis build links:
- Broken (3.10.4): https://travis-ci.org/mliu49/RMG-build/builds/381772481
- Working (3.10.2): https://travis-ci.org/mliu49/RMG-build/builds/381790265

Output of conda info:

```
$ conda info -a
     active environment : None
       user config file : /home/travis/.condarc
 populated config files : 
          conda version : 4.5.4
    conda-build version : not installed
         python version : 2.7.14.final.0
       base environment : /home/travis/miniconda  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /home/travis/miniconda/pkgs
                          /home/travis/.conda/pkgs
       envs directories : /home/travis/miniconda/envs
                          /home/travis/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.4 requests/2.18.4 CPython/2.7.14 Linux/4.14.12-041412-generic ubuntu/14.04 glibc/2.19
                UID:GID : 2000:2000
             netrc file : None
           offline mode : False
```
The travis build script installs conda-build after checking conda info, so its version is not listed here.

**Comment by msarahan** [comment]
What does your recipe look like?  3.10.4 tried to straighten out some annoying implicit behavior around when the build and host section get split.  You're probably breaking because of it.  #2896 

There might be a fix here, but it'll probably be easier for you to update your recipe to use build/host properly.  If you post your recipe here, I can give you tips.

**Comment by mliu49** [comment]
Oh, I didn't know about the host section. Any tips would be greatly appreciated!

meta.yaml
```
# For conda build
package:
  name: rmg
  version: {{ environ.get('GIT_DESCRIBE_TAG', '') }}

source:
  path: .

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}

requirements:
  build:
    - boost ==1.56.0
    - cython >=0.25.2
    - gcc_linux-64 # [linux]
    - clang_osx-64 # [osx]
    - jinja2
    - lpsolve55
    - numpy
    - openbabel
    - pydas >=1.0.2
    - pydqed >=1.0.1
    - pyrdl
    - python
    - pyzmq
    - quantities
    - rdkit >=2015.09.2
    - scipy
    - scoop
    - setuptools

  run:
    - argparse # [py26]
    - cairo # [unix]
    - cairocffi # [unix]
    - cantera >=2.3.0a3
    - coolprop
    - coverage
    - cython >=0.25.2
    - ffmpeg
    - gprof2dot
    - graphviz
    - guppy
    - jinja2
    - lpsolve55
    - markupsafe
    - matplotlib >=1.5
    - mock
    - mopac
    - nose
    - numpy
    - openbabel
    - psutil
    - pydas >=1.0.2
    - pydot ==1.2.2
    - pydqed >=1.0.1
    - pymongo
    - pyparsing
    - pyrdl
    - python
    - pyzmq
    - quantities
    - rdkit >=2015.09.2
    - rmgdatabase >=2.1.9
    - scipy
    - scoop
    - symmetry
    - xlwt

test:
  source_files:
    - 'examples/rmg/minimal'
  imports:
    - rmgpy
  commands:
    - rmg.py examples/rmg/minimal/input.py

about:
  home: http://github.com/ReactionMechanismGenerator/RMG-Py
  license: MIT
  summary: "A program for automatically generating kinetic models of chemical reaction mechanisms."
```

build.sh
```
make install
cp -R ${SRC_DIR}/external ${SP_DIR}
```

**Comment by msarahan** [comment]
You're using the compiler packages manually, but you should be using the jinja2 functions.  These have strong run_exports, and that's the reason for the breakage to you.  I highly advise you to read the blog post at https://www.anaconda.com/blog/developer-blog/utilizing-the-new-compilers-in-anaconda-distribution-5/ and the docs linked therein.  This section may also be helpful to you: https://conda.io/docs/user-guide/tasks/build-packages/define-metadata.html#host

Your requirements should look like:

```
requirements:
  build:
    - {{ compiler('c') }}
  host:
    - boost ==1.56.0
    - cython >=0.25.2
    - jinja2
    - lpsolve55
    - numpy
    - openbabel
    - pydas >=1.0.2
    - pydqed >=1.0.1
    - pyrdl
    - python
    - pyzmq
    - quantities
    - rdkit >=2015.09.2
    - scipy
    - scoop
    - setuptools

  run:
    - argparse # [py26]
    - cairo # [unix]
    - cairocffi # [unix]
    - cantera >=2.3.0a3
    - coolprop
    - coverage
    - cython >=0.25.2
    - ffmpeg
    - gprof2dot
    - graphviz
    - guppy
    - jinja2
    - lpsolve55
    - markupsafe
    - matplotlib >=1.5
    - mock
    - mopac
    - nose
    - {{ pin_compatible('numpy') }}
    - openbabel
    - psutil
    - pydas >=1.0.2
    - pydot ==1.2.2
    - pydqed >=1.0.1
    - pymongo
    - pyparsing
    - pyrdl
    - python
    - pyzmq
    - quantities
    - rdkit >=2015.09.2
    - rmgdatabase >=2.1.9
    - scipy
    - scoop
    - symmetry
    - xlwt
```

I added in pin_compatible('numpy') just on a wild guess that you compile against numpy's C interface.  If you know that you don't, you can revert that back to plain numpy.
