### ISSUE TITLE
3.10.5 regression: test: files

### ISSUE THREAD

**Issue by isuruf** [conda/conda-build#2923]
### Actual Behavior
```
OSError: Failed to copy /tmp/tmp40p9rd3n/info/recipe/hello_world.f90 to /home/conda/feedstock_root/build_artifacts/flang_1527329374284/test_tmp/hello_world.f90.  Error was: Command 'cp -a /tmp/tmp40p9rd3n/info/recipe/hello_world.f90 /home/conda/feedstock_root/build_artifacts/flang_1527329374284/test_tmp/hello_world.f90' returned non-zero exit status 1.
```

### Expected Behavior

No Error. Switching to 3.10.3 fixes the error

### Steps to Reproduce

See https://circleci.com/gh/conda-forge/flang-feedstock/38

##### `Output of conda info`

```

```

**Comment by msarahan** [comment]
I added a test for this in https://github.com/conda/conda-build/pull/2932/commits/7bc4d2a3660d53387241062a8a405c56bd7b50c6

It seems to be working fine.  Please submit an MRE if you are still having issues.

**Comment by isuruf** [comment]
I will submit an MRE. I think the reason why 7bc4d2a works is because it is for a global test and the issue above is for an output. I'll confirm tonight

**Comment by msarahan** [comment]
ah, yes, that is a very important difference.

**Comment by isuruf** [comment]
Add a file called called `file` alongside the following meta.yaml and it fails.
```
package:
  name: test
  version: 1.0

outputs:
  - name: test

  - name: test2
    test:
      files:
        - file
      commands:
        - test -e file
```
