### ISSUE TITLE
pin_subpackage doesn't know about epochs.

### ISSUE THREAD

**Issue by isuruf** [conda/conda-build#2926]
### Actual Behavior

Following package has 

```yaml
run_exports: - {{ pin_subpackage('cddlib', max_pin='x') }}
```

conda render of a package that depends on it has
```yaml
host:
        - cddlib 1!0.94i h16a7912_0
    run:
        - cddlib >=0.94i,<1.0a0
```

### Expected Behavior

```yaml
host:
        - cddlib 1!0.94i h16a7912_0
    run:
        - cddlib >=1!0.94i,<1!1.0a0
```

##### `Output of conda info`

```
 active environment : None
       user config file : /home/isuru/.condarc
 populated config files : /home/isuru/.condarc
          conda version : 4.5.1
    conda-build version : 3.10.5
         python version : 3.6.4.final.0
       base environment : /home/isuru/miniconda3  (writable)
          package cache : /home/isuru/miniconda3/pkgs
                          /home/isuru/.conda/pkgs
       envs directories : /home/isuru/miniconda3/envs
                          /home/isuru/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.1 requests/2.18.4 CPython/3.6.4 Linux/4.13.0-43-generic ubuntu/16.04 glibc/2.23
                UID:GID : 1000:1000
             netrc file : /home/isuru/.netrc
           offline mode : False

```
