### ISSUE TITLE
Add env var to help writing portable meta.yaml output section

### ISSUE THREAD

**Issue by sdebionne** [conda/conda-build#2928]
Since Windows and Linux (and possibly macOS) have different package folder layouts, it would be great to have some predefined environment variables to help write the output section file list in a portable way, something like:

```
outputs:
  - name: my-subpackage
    files:
      - {{ REL_SHLIB_DIR }}/mylib{{ SHLIB_EXT }}*
      - {{ REL_SP_DIR }}/mymod{{ PYMOD_EXT }}
      - {{ REL_SP_DIR }}/mymod.py
```

where 

`REL_SP_DIR`:
 - `lib/python{{ PY_VER }}/site-packages` on Linux
 - `lib\site-packages` on Windows

`REL_SHLIB_DIR`:
 - `lib` on Linux
 - `Library\bin` on Windows

`PYMOD_EXT`:
 - `.so` on Linux
 - `.pyd` on Windows
