### ISSUE TITLE
Output of conda render has changed

### ISSUE THREAD

**Issue by 183amir** [conda/conda-build#2931]
### Actual Behavior
conda render now outputs a `Hash contents` section before outputting a valid YAML file.

### Expected Behavior
conda render should output a valid YAML file like before. At least while in conda build version 3 to keep backwards compatibility.

### Steps to Reproduce
Using conda build 3.10.5 and the following recipe:
```yaml
package:
  name: temp
  version: 1.0
```
conda render outputs:
```yaml
--------------
Hash contents:
--------------
{}
----------
meta.yaml:
----------
package:
    name: temp
    version: '1.0'
extra:
    copy_test_source_files: true
    final: true
```
which is not a valid yaml file anymore. The output used to be:
```yaml
package:
    name: temp
    version: '1.0'
extra:
    copy_test_source_files: true
    final: true
```
which I was parsing using another script.

##### `Output of conda info`

```
conda info

     active environment : base
    active env location : /home/amir/miniconda
            shell level : 1
       user config file : /home/amir/.condarc
 populated config files : /home/amir/miniconda/.condarc
                          /home/amir/.condarc
          conda version : 4.5.4
    conda-build version : 3.10.5
         python version : 3.6.5.final.0
       base environment : /home/amir/miniconda  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /home/amir/miniconda/pkgs
                          /home/amir/.conda/pkgs
       envs directories : /home/amir/miniconda/envs
                          /home/amir/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.4 requests/2.18.4 CPython/3.6.5 Linux/4.16.11-1-ARCH arch/rolling glibc/2.27
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```

I think about two solutions for this:
1. Hash contents only is shown using a command line option like `--hash-contents`.
2. Hash contents would show up in the extra section of the rendered yaml file.
