### ISSUE TITLE
No valid recipes found for input

### ISSUE THREAD

**Issue by levinandrew** [conda/conda-build#2933]
### Context

I have created a C++ library called `analytics` that performs some math calculations. I want to play with this C++ logic in python, so I created wrappers for the C++ library using pybind11. These wrappers work; I create a shared object lib file (`libpyanaltics`) and have tested it. I now want to create an anaconda package that imports this C++ library and allows me to play with it in a jupyter notebook. 

I have created a directory called `pyanalytics`. Below is the setup of this directory: 

```
.:
lib  Makefile  meta.yaml  pyanalytics  setup.py  src  tests

./lib:
libpyanalytics.so  libpyanalytics.so.debug

./pyanalytics:
__init__.py

./src:
Makefile  pyanalytics.cpp 

./tests:
test_pricer.py
```
`lib`, `pyanalyics` (same name as parent directory), `src`, and `tests` are directories with their contents shown above. `src` contains the C++ pybind wrappers. `__init__.py` contained inside `pyanalytics` has one single line: `import libpyanalytics`.

Here is the contents of my meta.yaml file:
```
package:
    name: pyanalytics
    version: "0.1"

source:
    path: .

build:
    script: python setup.py install -f
    script_env:

requirements:
    build:
        - python
        - setuptools

    run:
        - python
        - numpy

test:
    requires:
        - pytest
        - scipy
        - numpy

    source_files:
        - tests/*.py

    imports:
        - pyanalytics

    commands:
        - pytest tests
```
 And here is the contents of `setup.py`:
```
import os
import setuptools

setuptools.setup(
    name='pyanalytics',
    packages=setuptools.find_packages(where='lib'),
    version=0.1,
    description='python port of analytics',
)
```

### Actual Behavior
I try to build the package using the following command: `conda-build pyanalytics`, and I receive a message saying the following: 

```
Traceback (most recent call last):
  File "/home/anaconda2/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/home/anaconda2/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 413, in main
    execute(sys.argv[1:])
  File "/home/anaconda2/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 404, in execute
    verify=args.verify)
  File "/home/anaconda2/lib/python2.7/site-packages/conda_build/api.py", line 191, in build
    raise ValueError('No valid recipes found for input: {}'.format(recipe_paths_or_metadata))
ValueError: No valid recipes found for input: ['pyanalytics']
```

### Expected Behavior

I expect for the package to build and run my tests allowing me to add it to my local anaconda environment. 

### Steps to Reproduce

I believe the information I provided above in the context section should be sufficient to help with this issue, but please let me know if I need to be more specific.

##### `Output of conda info`

```
     active environment : None
       user config file : /home/.condarc
 populated config files :
          conda version : 4.4.10
    conda-build version : 3.4.1
         python version : 2.7.14.final.0
       base environment : /home/anaconda2  (writable)
           channel URLs : https://repo.continuum.io/pkgs/main/linux-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
          package cache : /home/anaconda2/pkgs
                          /home/.conda/pkgs
       envs directories : /home/anaconda2/envs
                          /home/.conda/envs
               platform : linux-64
             user-agent : conda/4.4.10 requests/2.18.4 CPython/2.7.14 Linux/3.10.0-123.el7.x86_64 centos/7 glibc/2.17
                UID:GID : 1829:1829
             netrc file : None
           offline mode : False
```

Thank you for taking the time to help me through this issue.
