### ISSUE TITLE
libc is not included in runtime environment

### ISSUE THREAD

**Issue by ifmar** [conda/conda-build#2935]
I build a package using condas gcc compiler with this recipe:
```
package:
  name: example
  version: 1.0
source:
  path: ../
build:
  detect_binary_files_with_prefix: true

requirements:
   build:
     - {{ compiler('cxx') }}
     - {{ compiler('c') }}
```

### Actual Behavior
Installing the package:
```
The following NEW packages will be INSTALLED:

    example:      1.0-hf484d3e_0   local
    libgcc-ng:    7.2.0-hdf63c60_3      
    libstdcxx-ng: 7.2.0-hdf63c60_3  
```
Now the programm is linked against libstdcxx of my conda environemnt and the libc of my system.
I found the same behavior when installing some packages from the anaconda repo.

### Expected Behavior

I expected that the `libc` would be required for runtime as well so that they both are linked from there.
Did I miss something or is the above intended?
##### `Output of conda info`
```
   active environment : testEnv
    active env location : /home/markus/HiWi/miniconda3/envs/testEnv
            shell level : 1
       user config file : /home/markus/.condarc
 populated config files : /home/markus/HiWi/miniconda3/.condarc
          conda version : 4.5.4
    conda-build version : 3.10.5
         python version : 3.5.5.final.0
       base environment : /home/markus/HiWi/miniconda3  (writable)
          package cache : /home/markus/HiWi/miniconda3/pkgs
                          /home/markus/.conda/pkgs
       envs directories : /home/markus/HiWi/miniconda3/envs
                          /home/markus/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.4 requests/2.18.4 CPython/3.5.5 Linux/4.13.0-43-generic ubuntu/16.04 glibc/2.23
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False

```
