### ISSUE TITLE
run_exports is not honored when host section is absent

### ISSUE THREAD

**Issue by nehaljwani** [conda/conda-build#2946]
```
package:
  name: bob_the_builder
  version: 1.0.0

requirements:
  build:
    - zlib
```
```
[root@8d13aca83e43 ~]# conda search --info bob_the_builder -c local
Loading channels: done
bob_the_builder 1.0.0 0
-----------------------
file name   : bob_the_builder-1.0.0-0.tar.bz2
name        : bob_the_builder
version     : 1.0.0
build string: 0
build number: 0
size        : 111 KB
constrains  : ()
subdir      : linux-64
url         : file:///opt/conda/conda-bld/linux-64/bob_the_builder-1.0.0-0.tar.bz2
md5         : ce8ebb62bfe3a4ac48885dad4d3d3d23
dependencies: 
```

Till 3.10.4 it used to honor. Starting 3.10.5, this problem occurs. Maybe somewhere an empty host section is crawling around?
