### ISSUE TITLE
Serially iterating over a matrix uses same work directory!!

### ISSUE THREAD

**Issue by nehaljwani** [conda/conda-build#2947]
Recipe:
```
[root@8d13aca83e43 ~]# cat meta.yaml 
package:
  name: bob_and_wendy
  version: 1.2.3

requirements:
  host:
    - python
  run:
    - python

[root@8d13aca83e43 ~]# cat build.sh 
echo "Build directory being used is: $PWD" >> "$RECIPE_DIR/blddir.txt"
```
Matrix:
```
[root@8d13aca83e43 ~]# cat conda_build_config.yaml 
python:
  - 2.7
  - 3.5
  - 3.6
```
Result:
```
[root@8d13aca83e43 ~]# conda build .  -m conda_build_config.yaml
...
... bob_the_builder_can_we_fix_it ...
... bob_the_builder_can_we_fix_it ...
... bob_the_builder_can_we_fix_it ...
...
[root@8d13aca83e43 ~]# cat blddir.txt 
Build directory being used is: /opt/conda/conda-bld/bob_and_wendy_1528051044598/work
Build directory being used is: /opt/conda/conda-bld/bob_and_wendy_1528051044598/work
Build directory being used is: /opt/conda/conda-bld/bob_and_wendy_1528051044598/work
```
This hurts build isolation :(
