### ISSUE TITLE
Conda build scripts using system cmake vs. cmake installed in build env

### ISSUE THREAD

**Issue by benbovy** [conda/conda-build#2951]
### Actual Behavior

I need a recent version of cmake to build a library, so I add in the build requirements in `meta.yaml` (cmake is available in conda-forge). Conda build picks the right cmake version (i.e., the one installed in the build environment) if I use the default name for the build script (i.e., `build.sh`). However, when I use another name (because my recipe builds multiple packages), cmake version is the system installed version (or cmake is not found if it's not installed).

### Expected Behavior

Always use cmake installed in the build environment.

### Steps to Reproduce

Config 1:

```yaml
# ...
 
outputs:
  - name: fastscapelib
    script: build.sh
    requirements:
      build:
        - {{ compiler('cxx') }}
        - cmake

# ...
```

Config 2 (unexpected behavior):

```yaml
# ...
 
outputs:
  - name: fastscapelib
    script: build_mylibrary.sh
    requirements:
      build:
        - {{ compiler('cxx') }}
        - cmake

# ...
```

`build.sh` or `build_mylibrary.sh` looks like this:

```bash
which cmake
cmake -DBUILD_TESTS=OFF -DCMAKE_INSTALL_PREFIX=$PREFIX $SRC_DIR -DCMAKE_INSTALL_LIBDIR=lib
make install
```

Output of `which cmake` with config 1:

`/Users/bbovy/miniconda3/conda-bld/fastscapelib_1528288923401/_build_env/bin/cmake`

Output of `which cmake` with config 2:

`/usr/local/bin/cmake`

##### `Output of conda info`
```
     active environment : None
       user config file : /Users/bbovy/.condarc
 populated config files : /Users/bbovy/.condarc
          conda version : 4.5.4
    conda-build version : 3.5.1
         python version : 3.5.4.final.0
       base environment : /Users/bbovy/miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/osx-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/osx-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /Users/bbovy/miniconda3/pkgs
                          /Users/bbovy/.conda/pkgs
       envs directories : /Users/bbovy/miniconda3/envs
                          /Users/bbovy/.conda/envs
               platform : osx-64
             user-agent : conda/4.5.4 requests/2.18.4 CPython/3.5.4 Darwin/16.7.0 OSX/10.12.6
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```
