### ISSUE TITLE
selectors are not applied before checking for used variables.

### ISSUE THREAD

**Issue by isuruf** [conda/conda-build#2958]
### Actual Behavior

For example, when you have
```
requirements:
   build:
     - {{ compiler('c') }}    # [not win]
     - m2w64-toolchain   # [win]
```

on windows, conda-build thinks the compiler is used and leads to 2 builds, one for vs2008, one for vs2015.

### Expected Behavior

Only one build should happen

### Steps to Reproduce

An example recipe is at https://github.com/conda-forge/r-tensora-feedstock/pull/1
##### `Output of conda info`

```

```

**Comment by msarahan** [comment]
Yep, known issue.  Used variable stuff is all based on raw text.  You might be able to separate it into phases, where the first phase would detect usage in selectors, and a second phase would be for everything else (with the text having selectors applied).

Please consider submitting a PR if you need this urgently.  I can't get to this for a while.

**Comment by jakirkham** [comment]
A workaround for this would be...

```yaml
build:
  ...
  force_ignore_keys:    # [win]
    - c_compiler        # [win]
    - m2w64_c_compiler  # [unix]

requirements:
  build:
    - {{ compiler("c") }}        # [unix]
    - {{ compiler("m2w64_c") }}  # [win]
```

The `build/force_ignore_keys` drops those keys from consideration so has the intended effect of the selectors on the `compiler` portion below.

Unfortunately [dropping the selectors]( https://github.com/conda-forge/make-feedstock/commit/3d52e8bb37f8857eb0789de38e8eebac8039c649 ) could generate an unknown `compiler` (e.g. `m2w64_c` on Unix), which cause the [build to crash]( https://travis-ci.org/conda-forge/make-feedstock/builds/404241827 ). So the selectors remain needed below even if they don't solve the full problem. Rendering does not catch this either.
