### ISSUE TITLE
Rasterio build failing, trying to use osgeo gdal instead of default

### ISSUE THREAD

**Issue by rsignell-usgs** [conda/conda-build#300]
I'm trying to build rasterio, and I'm trying to use the osgeo binstar gdal package as a requirement (because the default was failing with a libgdal.so error).  

The only way I could figure out how to get conda build to use the osgeo version of gdal was to specify the meta.yaml build requirements as:

```
requirements:
  build:
    - python
    - numpy >=1.8
    - cligj
    - geos >=3.4
    - gdal 1.11.1 np19py27_11
    - enum34
    - affine >=1.0
    - setuptools
    - cython >=0.20

  run:
    - python
    - numpy >=1.8
    - cligj
    - geos >=3.4
    - gdal 1.11.1 np19py27_11
    - enum34
    - affine >=1.0
```

but I'm getting an error from curl when it tried to download:

```
AssertionError: gdal-1.11.1-np19py27_11.tar.bz2 MatchSpec(u'curl')
```

My conda info looks like this:

```
[testbed@testbed2 conda-recipes]$ conda info
Current conda install:

             platform : linux-64
        conda version : 3.7.4
  conda-build version : 1.9.1
       python version : 2.7.9.final.0
     requests version : 2.5.1
     root environment : /home/testbed/anaconda  (writable)
  default environment : /home/testbed/anaconda
     envs directories : /home/testbed/anaconda/envs
        package cache : /home/testbed/anaconda/pkgs
         channel URLs : https://conda.binstar.org/rsignell/linux-64/
                        http://repo.continuum.io/pkgs/free/linux-64/
                        https://conda.binstar.org/osgeo/linux-64/
          config file : /home/testbed/.condarc
    is foreign system : False
```
