### ISSUE TITLE
Expose "work_moved" folder location as an environment variable?

### ISSUE THREAD

**Issue by aldanor** [conda/conda-build#3001]
When running the tests that are not included with the package (and there may be multiple reasons for it to be so), it's a major PITA to try and run them, you have to figure that the test runner is located in `.../test_tmp` and from there you have to find `.../work_moved_*` and hope that the tests were moved there.

Wondering, could `conda-build` expose environment variables like the current source location that it copies and then moves around? E.g., something like `PKG_SRC_DIR`, so you could do things like

```yaml
test:
  requires:
  - pytest
  commands:
  - cd $PKG_SRC_DIR && py.test
```
