### ISSUE TITLE
Compiler packages are not found in local packages

### ISSUE THREAD

**Issue by sdebionne** [conda/conda-build#3004]
### Actual Behavior

A compiler package is not found in the local `conda-bld` folder. If the package is published in a channel, it works fine.
Compiler packages are most of the time tuned and compiled locally.

### Steps to Reproduce

On Windows, get vs2017.zip from #2541

Build the compiler package:

```
conda build vs21017
```

Build a test package with the compiler:

##### `meta.yaml`
```
package:
  name: my-test-pkg
  version: 0.1

requirements:
  build:
    - {{ compiler('cxx') }}
```

##### `conda_build_config.yaml`
```
cxx_compiler:
  - vs2017                     # [win]
```

##### `Output of conda info`
```
conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform win-64: {'vc=14.1'}
```
