### ISSUE TITLE
Error with channel::package build requirement in meta.yaml

### ISSUE THREAD

**Issue by tebeka** [conda/conda-build#3071]
### Actual Behavior
Here's `meta.yaml`

```yaml
package:
    name: nustream
    version: "0.1.0"

build:
    number: 1

source:
    path: ..

requirements:
    build:
        - msgpack-python
        - pandas
        - setuptools
    run:
        - python

test:
    requires:
        - pytest

about:
    home: https://github.com/tebeka/nustream
    license: Apache
```

When running `conda build meta.yaml` I get the error
```
conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform linux-64: {'conda-forge::msgpack-python'}
```
### Expected Behavior

Normal build, this `channel::package` notation works in `conda env create -n name -f environment.yml`

### Steps to Reproduce

```
git clone git@github.com:tebeka/nustream.git
cd nustream/conda.recipe
conda build meta.yaml
```

##### `Output of conda info`
```
     active environment : None
            shell level : 0
       user config file : /home/miki/.condarc
 populated config files : /home/miki/.condarc
          conda version : 4.5.9
    conda-build version : 3.12.1
         python version : 3.7.0.final.0
       base environment : /opt/miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /opt/miniconda3/pkgs
                          /home/miki/.conda/pkgs
       envs directories : /opt/miniconda3/envs
                          /home/miki/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.9 requests/2.19.1 CPython/3.7.0 Linux/4.15.0-30-generic ubuntu/18.04 glibc/2.27
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```
