### ISSUE TITLE
Build dies with Unhashable type error

### ISSUE THREAD

**Issue by dmitry-kabanov** [conda/conda-build#3076]
### Actual Behavior

I build a package with the following:

```
{% set name = "madagascar" %}
{% set version = "2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}-1.tar.bz2
  url: https://downloads.sourceforge.net/project/rsf/{{ name }}/{{ name }}-{{ version }}/{{ name }}-{{ version }}-1.tar.bz2
  md5: aeb4a8bad0fcfeed92a2b838fcef831b

build:
  number: 3

requirements:
  build:
    - {{ compiler('c') }}
    - python 2.7
    - scons
    - numpy
    - swig
  host:
    run:
      - python 2.7
      - scons
      - numpy
      - swig

test:
  imports:
    - rsf.api
  commands:
    - test -f $PREFIX/bin/sfwiggle                 # [unix]
    - if not exist %PREFIX%\\bin\\sfwiggle exit 1  # [win]

about:
  home: http://www.ahay.org/wiki/Main_Page
  license: GPL
  license_file: COPYING.txt
  summary: 'A package for reproducible geophysical data processing'

extra:
  recipe-maintainers:
    - dmitry-kabanov
```

and it crashes with `TypeError: unhashable type`.

### Expected Behavior

Conda build should work successfully.

### Steps to Reproduce

1. Create directory `madagascar`
2. Create file `madagascar/meta.yaml` with the content provided above
3. Execute command `conda build madagascar`

##### `Output of conda info`

```
$ conda info

     active environment : None
       user config file : /home/kabanod/.condarc
 populated config files : 
          conda version : 4.5.9
    conda-build version : 3.12.0
         python version : 2.7.15.final.0
       base environment : /home/kabanod/apps/python/2.7-Miniconda2-4.5  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /home/kabanod/apps/python/2.7-Miniconda2-4.5/pkgs
                          /home/kabanod/.conda/pkgs
       envs directories : /home/kabanod/apps/python/2.7-Miniconda2-4.5/envs
                          /home/kabanod/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.9 requests/2.18.4 CPython/2.7.15 Linux/4.4.0-131-generic ubuntu/16.04 glibc/2.23
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```
