### ISSUE TITLE
Disabling pip's cache directory results in .egg-info directories 

### ISSUE THREAD

**Issue by jjhelmus** [conda/conda-build#3094]
#3053 disabled pip's cache directory by default in the build environment.  

An unfortunate side effect of disabling pip's cache directory is that an `.egg-info` directory is produced rather than a `.dist-info` directory.  This is a result a pip not generating wheels during the install process.

For example, take the following recipe:

``` yaml
package:
  name: imagesize
  version: 1.0.0

source:
  url: https://pypi.io/packages/source/i/imagesize/imagesize-1.0.0.tar.gz
  sha256: 5b326e4678b6925158ccc66a9fa3122b6106d7c876ee32d7de6ce59385b96315

build:
  #script: python -m pip install .
  script: unset PIP_NO_CACHE_DIR; python -m pip install .

requirements:
  host:
    - python
    - pip
  run:
    - python
```

As written, pip's cache directory is disabled in conda-build >= 3.12.1.  The resulting package will contain an `.egg-info` directory:

```
lib/python3.6/site-packages/imagesize-1.0.0-py3.6.egg-info/dependency_links.txt
lib/python3.6/site-packages/imagesize-1.0.0-py3.6.egg-info/top_level.txt
lib/python3.6/site-packages/imagesize-1.0.0-py3.6.egg-info/installed-files.txt
lib/python3.6/site-packages/imagesize-1.0.0-py3.6.egg-info/SOURCES.txt
```

Using the commented script, re-enables the cache directory, resulting in a wheel being generated as an intermediate.  The conda package then contains a `.dist-info` directory.

``` 
lib/python3.6/site-packages/imagesize-1.0.0.dist-info/INSTALLER
lib/python3.6/site-packages/imagesize-1.0.0.dist-info/top_level.txt
lib/python3.6/site-packages/imagesize-1.0.0.dist-info/WHEEL
lib/python3.6/site-packages/imagesize-1.0.0.dist-info/RECORD
lib/python3.6/site-packages/imagesize-1.0.0.dist-info/LICENSE.txt
lib/python3.6/site-packages/imagesize-1.0.0.dist-info/METADATA
```

I believe that `dist-info` directories should be preferred and these are currently not the default. 

It is possible that the python version entry in the `egg-info` directories (**py3.6**.egg-info) could be problematic for `noarch: python` packages although I have no evidence of this.
