### ISSUE TITLE
"pip" dependency appears twice with conda skeleton

### ISSUE THREAD

**Issue by Bezier89** [conda/conda-build#3137]
### Actual Behavior

Run conda skeleton on any pypi package. "pip" will appear twice in the requirements sections, as below:

```
requirements:
  host:
    - mpmath >=0.19
    - pip
    - pip
    - python
  run:
    - mpmath >=0.19
    - python
```

### Expected Behavior

"pip" does not appear twice

### Steps to Reproduce

Run a command such as this (any pypi package should work, this is just an example):

`conda skeleton pypi sympy`

##### `Output of conda info`

```
     active environment : None
          conda version : 4.5.11
    conda-build version : 3.14.4
         python version : 3.6.6.final.0
               platform : win-64
             user-agent : conda/4.5.11 requests/2.19.1 CPython/3.6.6 Windows/10 Windows/10.0.15063
          administrator : False
             netrc file : None
           offline mode : False
```
