### ISSUE TITLE
/lib64/libdl.so.2 ... not found in sysroot, is this binary repackaging?

### ISSUE THREAD

**Issue by dbast** [conda/conda-build#3164]
### Actual Behavior

While building shellcheck on Linux, see https://github.com/conda-forge/staged-recipes/pull/6682 , the following warnings are reported:

`WARNING (shellcheck,bin/shellcheck): /lib64/libutil.so.1 not found in sysroot, is this binary repackaging? .. do you need to use install_name_tool/patchelf?
WARNING (shellcheck,bin/shellcheck): /lib64/libpthread.so.0 not found in sysroot, is this binary repackaging? .. do you need to use install_name_tool/patchelf?
WARNING (shellcheck,bin/shellcheck): /lib64/libc.so.6 not found in sysroot, is this binary repackaging? .. do you need to use install_name_tool/patchelf?
WARNING (shellcheck,bin/shellcheck): /lib64/libm.so.6 not found in sysroot, is this binary repackaging? .. do you need to use install_name_tool/patchelf?
WARNING (shellcheck,bin/shellcheck): /lib64/libdl.so.2 not found in sysroot, is this binary repackaging? .. do you need to use install_name_tool/patchelf?
WARNING (shellcheck,bin/shellcheck): /lib64/librt.so.1 not found in sysroot, is this binary repackaging? .. do you need to use install_name_tool/patchelf?`

### Expected Behavior

According to @jakirkham at least some libs, e.g. ` /lib64/libdl.so.2` are system provided and should not be reported.

### Steps to Reproduce

Have a look at the CIRCLE CI output in https://github.com/conda-forge/staged-recipes/pull/6682

##### `Output of conda info`

```
active environment : base
    active env location : /opt/conda
            shell level : 1
       user config file : /home/conda/.condarc
 populated config files : /home/conda/.condarc
          conda version : 4.5.11
    conda-build version : 3.15.1
         python version : 3.6.6.final.0
       base environment : /opt/conda  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /opt/conda/pkgs
                          /home/conda/.conda/pkgs
       envs directories : /opt/conda/envs
                          /home/conda/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.11 requests/2.19.1 CPython/3.6.6 Linux/4.4.0-96-generic centos/6.10 glibc/2.12
                UID:GID : 1001:1001
             netrc file : None
           offline mode : False
```

**Comment by mingwandroid** [comment]
You've built a binary but do not seem to have specified any compilers to be used?

**Comment by mingwandroid** [comment]
conda-build how introspects binary files to make sure it knows about all of them. These system ones (part of glibc) come from compiler packages, but since you aren't using any you need to specify the ones you don't want to be warned about (these warnings will hopefully default to errors some day to prevent the proliferation of broken packages).

To avoid seeing warnings when binary repackaging add this to meta.yaml:

```
build:
  missing_dso_whitelist:
    - /lib64/libutil.so.1 
    - /lib64/libpthread.so.0
    - /lib64/libc.so.6
    - /lib64/libdl.so.2
    - /lib64/librt.so.1
```

**Comment by dbast** [comment]
Thanks. The compiler in that case is Stack (which brings the GHC Haskell compiler). I'll add those lines to the meta.yaml. Is there also a way to add that to the stack compiler package instead?

**Comment by mingwandroid** [comment]
No.

**Comment by dbast** [comment]
Ok, thanks. closing this.

**Comment by jakirkham** [comment]
So is the suggestion that we should have a Haskell compiler as well? If so, would you be able to advise us a bit on how to build this, Ray?

**Comment by mingwandroid** [comment]
Oh boy, building haskell is far outside my field of knowledge. For haskell (and likely rust) I'd binary repackage for now.

I've been using official rust toolchains in combination with our libs and compilers successfully on macOS and Linux FWIW.

While building these would be good (and rust may be easy now-a-days), I still wonder if it's worth the effort.

**Comment by jakirkham** [comment]
For the Haskell compiler? I think we may already be doing that. These are generally resource intensive and (most) free CI resources won't cut it here. Though that's another discussion.

Should we be using `cdt`s with these binary repacks as well?

The other question I'm trying to figure out is how we can instruct `conda-build` and then `conda` what constitutes the compiler runtime in this case. AFAICT this include the libraries listed above and `gmp`.

How have you been handling these issues with Rust packages?

**Comment by mingwandroid** [comment]
You can add compilers to make conda-build shut up about missing glibc libs (since it'll then find them in the sysroot).

I don't know what you mean about `gmp`, it's not a compiler runtime to me.

I've not been packaging any rust binaries yet, I don't even have a toolchain package though I'm thinking about it; I would binary repackage the official rust toolchain then I'd have a conda-rust toolchain that adds some config files and sets some vars upon activation.

The one thing holding me back is knowing what to do about nightly vs stable wrt rust compilers, do we need both? A lot of the more modern rust stuff seems to require nightly compilers AFAICT.

**Comment by tashrifbillah** [comment]
@mingwandroid , the white listing suggestion didn't work for me. The following is a snippet of my `meta.yaml`:

```
package:
    name: someName
    version: 2.3.0
source:
    fn: v2.3.0.tar.gz
    url: someUrl.com
build:
    binary_relocation: true
    string: 'py3'

    missing_dso_whitelist:
         - /lib64/libutil.so.1 
         - /lib64/libpthread.so.0
         - /lib64/libc.so.6
         - /lib64/libdl.so.2
         - /lib64/librt.so.1
    
requirements:
    build:
        - bzip2 1.0.6 1
        - ca-certificates 2018.4.16 0
        - cmake
        - curl 7.60.0 0
        - expat 2.2.5 0
        - krb5 1.14.6 0
        - libssh2
        - libuv 1.20.3 0
        - ncurses 5.9 10
        - openssl 1.0.2o 0
        - rhash 1.3.4 0
        - xz 5.2.3 0
        - zlib 1.2.11 0
        
extra:
    copy_test_source_files: true
    final: true

```

I also tried  putting the white list under `requirements > build` section, didn't work either.
