### ISSUE TITLE
Build a pure Python package without setup.py?

### ISSUE THREAD

**Issue by teake** [conda/conda-build#3166]
I want to build a pure-Python Conda package, but I don't necessarily want to make it pip-installable. Is it then possible (or recommended) to forego `setup.py` altogether? Having only a `meta.yaml` and no `MANIFEST.in`, `setup.py`, etc keeps things nice and tidy IMHO.

If I do the following in `meta.yaml`:
```yaml
build:
  noarch: python
  script:
    - mkdir -p $PREFIX/site-packages
    - cp -r <package_src_dir> $PREFIX/site-packages/<package_name>
```
then it seems to work. There's no `.egg-info` directory, but I'm guessing conda doesn't use that anyway.

Are there any obvious errors or pitfalls I should know about when I go this route? Might there even be a built-in directive that does this already?
