### ISSUE TITLE
Test commands not running on Windows

### ISSUE THREAD

**Issue by nehaljwani** [conda/conda-build#3243]
This is a side effect of https://github.com/conda/conda-build/pull/3236

A very small reproducer is:
```
(base) C:\Users\Wani\Downloads\scratch>type meta.yaml
package:
   name: yes_sir
   version: 0.0.1

test:
   commands:
     - echo "Hello"
```

For the time being, downgrade conda-build to 3.16.1
