### ISSUE TITLE
Commented selectors cause only first variant to be built

### ISSUE THREAD

**Issue by gabm** [conda/conda-build#3273]
### Actual Behavior

Building the following recipe with `conda-build . --variants="{my_variant: ['on', 'off']}"` 

```
package:
  name: "testpkg"
  version: 1


build:
  features:
    - my_feature #[ my_variant == "on" ]
```

produces only one output package. Sometimes for my_variant = on, sometimes for off.

### Expected Behavior

It should build two packages, one with and one without feature.

Now when you remove the comment (the hash sign), then it works as expected:

```
    - my_feature [ my_variant == "on" ]
```

### Steps to Reproduce

- build the above pkg with `conda-build . --variants="{my_variant: ['on', 'off']}"`

##### `Output of conda info`

```

```
