### ISSUE TITLE
existing packages are removed from build prefix for multiple outputs

### ISSUE THREAD

**Issue by bergtholdt** [conda/conda-build#3310]
### Actual Behavior

I have a simple recipe with multiple outputs and different build env packages.

```yaml
package:
  name: test_lib_and_wrap
  version: 1.0

build:
  number: 0

outputs:
  - name: libtest
    build:
      run_exports:
        - {{ pin_subpackage('libtest', exact=True) }}
    requirements:
      build:
        - {{ compiler('c') }}
        - cmake
      host:

  - name: pytest
    requirements:
      build:
        - {{ compiler('c') }}
        - cmake
        - swig
      host:
        - python {{ python }}
        - {{ pin_subpackage('libtest', exact=True) }}
      run:
        - {{ pin_compatible('python') }}
        - {{ pin_subpackage('libtest', exact=True) }}
```

After building libtest the build_prefix (and host_prefix) are removed and are prepared for the second output pytest. However all packages from compiler('c'), cmake and their dependencies are missing in the build_prefix, just the new package swig + dependencies (pcre) are installed, thus failing to build pytest with cmake.

### Expected Behavior

Full build environment available for each output.

### Steps to Reproduce

Just run conda build on the recipe and interrupt after each output and inspect the build_env.

I digged into this a little deeper and found that in the inner loop in build.py over the outputs, all m.config.build_prefix are the same as the m.config.host_prefix. This hints that the recipe is actually not parsed correctly or it should be documented. The correct behavior can be achieved by introducing build and host sections in the parent's requirements section of the recipe (even if they are empty) like this:

```yaml
package:
  name: test_lib_and_wrap
  version: 1.0

build:
  number: 0

requirements:
  build:
  host:
  
outputs:
  - name: libtest
    build:
      run_exports:
        - {{ pin_subpackage('libtest', exact=True) }}
    requirements:
      build:
        - {{ compiler('c') }}
        - cmake
      host:

  - name: pytest
    requirements:
      build:
        - {{ compiler('c') }}
        - cmake
        - swig
      host:
        - python {{ python }}
        - {{ pin_subpackage('libtest', exact=True) }}
      run:
        - {{ pin_compatible('python') }}
        - {{ pin_subpackage('libtest', exact=True) }}
````

This should at least be documented as it cost me another half a day to find the issue and track it down. However I find it more intuitive if the first recipe actually worked as expected.

**Comment by msarahan** [comment]
This looks like a bug.  Explicit dependencies should never be missing like this.  Thanks for reporting.

**Comment by msarahan** [comment]
yep, confirmed it.  I added a bit of a test by calling $CC --version in build/script for each output.  We'll add a test case for this.

**Comment by msarahan** [comment]
In the past, this kind of thing has been because Conda has kept a cached record of what exists in a prefix, even if that stuff has been removed out from under conda.  We do try to tell conda to remove these locations from its cache, but that may have broken here somehow.

**Comment by msarahan** [comment]
Proof that rendering is fine - just not env creation:

```
conda render test_compiler_in_outputs
--------------
Hash contents:
--------------
{'c_compiler': 'clang'}
----------
meta.yaml:
----------
package:
    name: libtest
    version: '1.0'
build:
    number: 0
    run_exports:
        - libtest 1.0 0
    script:
        - $CC --version
requirements:
    build:
        - bzip2 1.0.6 h1de35cc_5
        - ca-certificates 2018.03.07 0
        - compiler-rt 4.0.1 hcfea43d_1
        - libcxxabi 4.0.1 hcfea43d_1
        - xz 5.2.4 h1de35cc_4
        - zlib 1.2.11 h1de35cc_3
        - libcxx 4.0.1 hcfea43d_1
        - openssl 1.1.1a h1de35cc_0
        - cctools 895 1
        - expat 2.2.6 h0a44026_0
        - libssh2 1.8.0 ha12b0ac_4
        - llvm-lto-tapi 4.0.1 1
        - ncurses 6.1 h0a44026_1
        - rhash 1.3.6 ha12b0ac_0
        - ld64 274.2 1
        - libcurl 7.62.0 h051b688_0
        - cmake 3.12.2 haff7e42_0
        - llvm 4.0.1 1
        - clang 4.0.1 1
        - clang_osx-64 4.0.1 h1ce6c1d_11
extra:
    copy_test_source_files: true
    final: true
    parent_recipe:
        name: test_lib_and_wrap
        path: /Users/msarahan/code/test_compiler_in_outputs
        version: '1.0'

--------------
Hash contents:
--------------
{'c_compiler': 'clang'}
----------
meta.yaml:
----------
package:
    name: pylibtest
    version: '1.0'
build:
    number: 0
    script:
        - $CC --version
requirements:
    build:
        - llvm 4.0.1 1
        - clang 4.0.1 1
        - ca-certificates 2018.03.07 0
        - rhash 1.3.6 ha12b0ac_0
        - xz 5.2.4 h1de35cc_4
        - expat 2.2.6 h0a44026_0
        - compiler-rt 4.0.1 hcfea43d_1
        - libcurl 7.62.0 h051b688_0
        - llvm-lto-tapi 4.0.1 1
        - zlib 1.2.11 h1de35cc_3
        - cctools 895 1
        - libssh2 1.8.0 ha12b0ac_4
        - clang_osx-64 4.0.1 h1ce6c1d_11
        - pcre 8.42 h378b8a2_0
        - ld64 274.2 1
        - openssl 1.1.1a h1de35cc_0
        - bzip2 1.0.6 h1de35cc_5
        - cmake 3.12.2 haff7e42_0
        - swig 3.0.12 h1cb45b9_3
        - libcxxabi 4.0.1 hcfea43d_1
        - libcxx 4.0.1 hcfea43d_1
        - ncurses 6.1 h0a44026_1
    host:
        - ca-certificates 2018.03.07 0
        - libcxxabi 4.0.1 hcfea43d_1
        - xz 5.2.4 h1de35cc_4
        - zlib 1.2.11 h1de35cc_3
        - libcxx 4.0.1 hcfea43d_1
        - openssl 1.1.1a h1de35cc_0
        - tk 8.6.8 ha441bb4_0
        - libffi 3.2.1 h475c297_4
        - ncurses 6.1 h0a44026_1
        - libedit 3.1.20170329 hb402a30_2
        - readline 7.0 h1de35cc_5
        - sqlite 3.25.3 ha441bb4_0
        - python 3.6.7 haf84260_0
        - certifi 2018.11.29 py36_0
        - setuptools 40.6.2 py36_0
        - wheel 0.32.3 py36_0
        - pip 18.1 py36_0
        - libtest 1.0 h1de35cc_0
    run:
        - python >=3.6,<3.7.0a0
        - libtest 1.0 h1de35cc_0
extra:
    copy_test_source_files: true
    final: true
    parent_recipe:
        name: test_lib_and_wrap
        path: /Users/msarahan/code/test_compiler_in_outputs
        version: '1.0'
```
