### ISSUE TITLE
Possible to render only jinja? (no exact versions, no indirect dependencies)

### ISSUE THREAD

**Issue by stuarteberg** [conda/conda-build#3321]
The `conda render` command can be useful for conda-build power-users, for various purposes.

As I understand it, the render command does the following:

1. Render jinja templates and selectors
2. If necessary:
2.a. Download the source to obtain values for certain variables (e.g. `GIT_DESCRIBE_NUMBER`)
2.b. Re-render remaining jinja templates
3. Solve for build/host requirements and their dependencies, and add them to the `requirements` section.

Just curious: Is there any way to tell `conda render` to stop after step 2?  For my particular use-case, I don't want indirect dependencies or exact versions included in the output.  I just want the output after jinja rendering.

If you want a concrete example, compare the [this recipe for h5py][1] with the rendered output below.

[1]: https://github.com/conda-forge/h5py-feedstock/blob/master/recipe/meta.yaml

<details>

<summary>Rendered h5py recipe</summary>

```yaml
package:
    name: h5py
    version: 2.8.0
source:
    patches:
        - backport_1099.patch
    sha256: eae41382be28b7264824450ce343dd625f972bedaaa3b0cced284986aabcbaee
    url: https://github.com/h5py/h5py/archive/2.8.0.tar.gz
build:
    number: '1005'
requirements:
    build:
        - cctools 895 1
        - ld64 274.2 1
        - compiler-rt 4.0.1 hcfea43d_1
        - libcxxabi 4.0.1 hcfea43d_1
        - llvm-lto-tapi 4.0.1 1
        - clang 4.0.1 1
        - clang_osx-64 4.0.1 h1ce6c1d_11
        - llvm 4.0.1 1
        - libcxx 4.0.1 hcfea43d_1
    host:
        - ca-certificates 2018.11.29 ha4d7672_0
        - libffi 3.2.1 hfc679d8_5
        - libgfortran 3.0.0 1
        - ncurses 6.1 hfc679d8_2
        - xz 5.2.4 h470a237_1
        - zlib 1.2.11 h470a237_3
        - hdf5 1.10.4 nompi_h5598ddc_1003
        - openblas 0.3.3 ha44fe06_1
        - openssl 1.0.2p h470a237_1
        - readline 7.0 haf1bffa_1
        - tk 8.6.9 ha92aebf_0
        - blas 1.1 openblas
        - sqlite 3.26.0 hb1c47c0_0
        - python 3.6.7 h5001a0f_1
        - certifi 2018.11.29 py36_1000
        - cython 0.29.1 py36hfc679d8_0
        - numpy 1.11.3 py36_blas_openblashb06ca3d_205
        - pkgconfig 1.3.1 py36_1001
        - six 1.12.0 py36_1000
        - setuptools 40.6.3 py36_0
        - wheel 0.32.3 py36_0
        - pip 18.1 py36_1000
    run:
        - hdf5
        - six
        - python >=3.6,<3.7.0a0
        - numpy >=1.11.3,<2.0a0
test:
    imports:
        - h5py
about:
    home: http://www.h5py.org/
    license: BSD-3-Clause
    license_file: licenses/license.txt
    summary: Read and write HDF5 files from Python
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - pitrou
        - tacaswell
        - ocefpaf
```

</details>

<details>

<summary>Output of conda info</summary>

```
$ conda info

     active environment : base
    active env location : /miniforge
            shell level : 1
       user config file : /Users/bergs/.condarc
 populated config files : /miniforge/.condarc
          conda version : 4.5.11
    conda-build version : 3.12.1
         python version : 3.6.6.final.0
       base environment : /miniforge  (writable)
           channel URLs : https://conda.anaconda.org/flyem-forge/osx-64
                          https://conda.anaconda.org/flyem-forge/noarch
                          https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/osx-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/osx-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /miniforge/pkgs
                          /Users/bergs/.conda/pkgs
       envs directories : /miniforge/envs
                          /Users/bergs/.conda/envs
               platform : osx-64
             user-agent : conda/4.5.11 requests/2.14.2 CPython/3.6.6 Darwin/16.7.0 OSX/10.12.6
                UID:GID : 1633079952:1899195968
             netrc file : None
           offline mode : False

```

</details>
