### ISSUE TITLE
build.sh should get deleted for recipes with embedded build scripts

### ISSUE THREAD

**Issue by dan-blanchard** [conda/conda-build#333]
If you have a recipe that uses something like:

```yaml
build:
  script:
    - cd $RECIPE_DIR
    - $PYTHON setup.py install
```

you'll end up with a build.sh file in the directory where your recipe file is after you run `conda build`.  It'd be really nice if these temporary build scripts got deleted automatically.
