### ISSUE TITLE
Test environment excludes variant inputs

### ISSUE THREAD

**Issue by minrk** [conda/conda-build#3377]
### Actual Behavior

CONDA_BUILD_SYSROOT set in conda_build_config.yaml affects build env but not test env

### Expected Behavior

CONDA_BUILD_SYSROOT (and all other user-specified build env) affects both build and test env the same

### Steps to Reproduce

Build a recipe with CONDA_BUILD_SYSROOT set in conda_build_config.yaml and use $CONDA_BUILD_SYSROOT in both the build and test process.

conda_build_config.yaml:

```yaml
CONDA_BUILD_SYSROOT: "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk"
```

meta.yaml:

```yaml
package:
  name: test-pkg
  version: 0.0.0

build:
  script:
    - 'env | sort > "${PREFIX}/build-env"'

requirements:
  build:
    - {{ compiler('c') }}

test:
  requires:
    - {{ compiler('c') }}
  commands:
    - 'env | sort > ./test-env'
    - 'diff ${PREFIX}/build-env ./test-env'
```

A workaround for now is to tell conda-build that this is a "used variable," so it gets added to the variant:

```yaml
build:
  script:
    - echo {{CONDA_BUILD_SYSROOT}}
    ...
```

conda-build can't know, however, in general what variables are consumed.

It would seem that the `config.variant` used to create the build environment should be identical to the `config.variant` used to create the test environment. However, the `config.variant` for the test env is reconstructed only from the .tar.bz2 package, which doesn't contain the same information as the original, only the 'used variables' that go into the hash input.

##### `Output of conda info`

```
     active environment : None
            shell level : 0
       user config file : /Users/benjaminrk/.condarc
 populated config files : /Users/benjaminrk/.condarc
          conda version : 4.6.2
    conda-build version : 3.17.8+5.g5ce3ea9c.dirty
         python version : 3.7.2.final.0
       base environment : /Users/benjaminrk/conda  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/osx-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/benjaminrk/conda/pkgs
                          /Users/benjaminrk/.conda/pkgs
       envs directories : /Users/benjaminrk/conda/envs
                          /Users/benjaminrk/.conda/envs
               platform : osx-64
             user-agent : conda/4.6.2 requests/2.21.0 CPython/3.7.2 Darwin/18.2.0 OSX/10.14.2
                UID:GID : 501:20
             netrc file : /Users/benjaminrk/.netrc
           offline mode : False
```
