### ISSUE TITLE
Conda build ignores variants

### ISSUE THREAD

**Issue by stefdoerr** [conda/conda-build#3378]
### Actual Behavior

conda build builds a package for python 3.5 and ignores my configuration matrix in `conda_build_config.yaml`. I read through the variants documentation and played around a decent bit but I can't get it to build the specified variants. This is the output of `conda build`
https://gist.github.com/stefdoerr/8b786b7bd4702bac1fb99fcfc6a844a6
Maybe I am understanding something wrong from the docs.

### Expected Behavior

conda build should create four packages
* python=3.6 / numpy=1.11
* python=3.6 / numpy=1.15.2
* python=3.7 / numpy=1.11
* python=3.7 / numpy=1.15.2

### Steps to Reproduce
`conda_build_config.yaml`
```
python:
  - 3.7
  - 3.6

numpy:
  - 1.15.2
  - 1.11
```

`meta.yaml`
```
package:
  name: test
  version: {{ environ.get('BUILD_VERSION', 0 ) }}

source:
   path: ../..

build:
  number: {{ environ.get('BUILD_NUMBER', 0 ) }}

requirements:
  host:
    - python {{ python }}
    - numpy {{ numpy }}

  run:
    - python {{ python }}
    - numpy {{ numpy }}
```

##### `Output of conda info`

```
     active environment : test_htmdmol
    active env location : /shared/sdoerr/Software/miniconda3/envs/test_htmdmol
            shell level : 1
       user config file : /home/sdoerr/.condarc
 populated config files : /home/sdoerr/.condarc
          conda version : 4.6.2
    conda-build version : not installed
         python version : 3.6.6.final.0
       base environment : /shared/sdoerr/Software/miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /shared/sdoerr/Software/miniconda3/pkgs
                          /home/sdoerr/.conda/pkgs
       envs directories : /shared/sdoerr/Software/miniconda3/envs
                          /home/sdoerr/.conda/envs
               platform : linux-64
             user-agent : conda/4.6.2 requests/2.20.1 CPython/3.6.6 Linux/3.10.0-862.14.4.el7.x86_64 centos/7.5.1804 glibc/2.17
                UID:GID : 3041:3000
             netrc file : None
           offline mode : False

```

**Comment by tadeu** [comment]
`numpy` is correctly varying in both builds, but the `python` it's using seems to be `3.5.6`, weird

**Comment by msarahan** [comment]
try removing the {{ python }} stuff from meta.yaml.  The python stuff is extremely special cased and fragile.  It's best to leave no constraint at all on those lines, just python.

```
package:
  name: test
  version: {{ environ.get('BUILD_VERSION', 0 ) }}

source:
   path: ../..

build:
  number: {{ environ.get('BUILD_NUMBER', 0 ) }}

requirements:
  host:
    - python
    - numpy {{ numpy }}

  run:
    - python
    - numpy {{ numpy }}
```

And for numpy, it's better to set the lower bound, and assume forward compatibility:

```
package:
  name: test
  version: {{ environ.get('BUILD_VERSION', 0 ) }}

source:
   path: ../..

build:
  number: {{ environ.get('BUILD_NUMBER', 0 ) }}

requirements:
  host:
    - python
    - numpy

  run:
    - python
    - {{ pin_compatible('numpy') }}
```

no jinja2 var for numpy is necessary because the name will match up with conda_build_config.yaml.

```
python:
  - 3.7
  - 3.6

numpy:
  - 1.11
```

because only the lower bound matters.
