### ISSUE TITLE
Feature request: explicit transitive run_exports

### ISSUE THREAD

**Issue by minrk** [conda/conda-build#3380]
In thinking about compiler wrappers (e.g. mpicc), I find myself wanting to declare in my package that run_exports should be inherited from the wrapped compiler.

E.g. what folks do right now to build with mpich is to include both mpich (with its compiler wrappers) and the relevant compilers themselves:

```yaml
requirements:
  build:
    - {{ compiler('c') }}
  host:
    - mpich
```

and in `build.sh` there is `export CC=mpicc` etc.

But if I wrote an mpich compiler wrapper that functions as a conda compiler package, they would have just:

```yaml
# conda_build_config.yaml
c_compiler:
  - mpich-mpicc

# meta.yaml
requirements:
  build:
    - {{ compiler('c') }}
```

The result of using the compiler wrapper should be the same run_exports as before. To accomplish (approximately) this, I currently have to find and copy/paste the run_exports of each compiler package for each platform into my wrapper package. This is almost correct, but allows the run_exports to fall out of sync as the wrapped compiler is updated.

### Proposal: run_exports_include

*... or run_exports.include, etc.*

It would be handy to be able to have in my package:

```yaml
build:
  run_exports_include:
    - {{ compiler('c') }}
```

which is interpreted by conda-build to mean that `run_exports` for my compiler-wrapper package would include the run_exports from `gxx_linux-64` (or what have you). In order to stay correct, this should be evaluated at the build time of the downstream package, not the build time of my wrapper (e.g. if an update to the compiler package bumped the minimum runtime lib version since my wrapper was last built). This build-time-evaluation of run_exports cannot be accomplished with the copy/paste of run_exports that is the only option at the moment.

**Comment by jjhelmus** [comment]
I really like this idea.  One though is that rather than adding a new section to build could this be accomplished with a new jinja function that extracted the run_export from a package? 

For example:

``` yaml
build:
  run_export:
     - {{ extract_run_export(compiler('c')) }}
```
