### ISSUE TITLE
Rendering apr recipe fails on Windows (works on other platforms)

### ISSUE THREAD

**Issue by jakirkham** [conda/conda-build#3411]
### Actual Behavior

Tried to build [this `apr` recipe]( https://github.com/conda-forge/staged-recipes/blob/35a794435f407c6fff9c5e558d31b71cd8b8e607/recipes/apr/meta.yaml ) in PR ( https://github.com/conda-forge/staged-recipes/pull/7386 ). On macOS and Linux, it builds fine. On Windows, the meta appears to run into some kind of parsing issue on Windows. The result is the traceback shown below.

```python
Traceback (most recent call last):
  File ".ci_support\build_all.py", line 130, in <module>
    build_all(args.recipes_dir, args.arch)
  File ".ci_support\build_all.py", line 68, in build_all
    build_folders(recipes_dir, new_comp_folders, arch, channel_urls)
  File ".ci_support\build_all.py", line 104, in build_folders
    config=config, finalize=False)
  File "C:\projects\staged-recipes\.ci_support\compute_build_graph.py", line 403, in construct_graph
    recipes_dir, config=config, finalize=finalize)
  File "C:\projects\staged-recipes\.ci_support\compute_build_graph.py", line 219, in add_recipe_to_graph
    rendered = _get_or_render_metadata(recipe_dir, worker, config=config, finalize=finalize)
  File "C:\Miniconda36-x64\lib\site-packages\conda\exports.py", line 182, in __call__
    return self.func(*args, **kw)
  File "C:\projects\staged-recipes\.ci_support\compute_build_graph.py", line 212, in _get_or_render_metadata
    bypass_env_check=True, config=config, finalize=finalize)
  File "C:\Miniconda36-x64\lib\site-packages\conda_build\api.py", line 51, in render
    bypass_env_check=bypass_env_check):
  File "C:\Miniconda36-x64\lib\site-packages\conda_build\metadata.py", line 1994, in get_output_metadata_set
    for k in out_metadata.get_used_vars()}))] = out, out_metadata
  File "C:\Miniconda36-x64\lib\site-packages\conda_build\metadata.py", line 2122, in get_used_vars
    force_global=force_global)
  File "C:\Miniconda36-x64\lib\site-packages\conda_build\metadata.py", line 2175, in _get_used_vars_meta_yaml
    force_top_level=force_top_level, force_global=force_global, apply_selectors=False)
  File "C:\Miniconda36-x64\lib\site-packages\conda_build\metadata.py", line 2162, in _get_used_vars_meta_yaml_helper
    apply_selectors=apply_selectors))
  File "C:\Miniconda36-x64\lib\site-packages\conda_build\metadata.py", line 1693, in extract_single_output_text
    output = output_matches[output_index] if output_matches else ''
IndexError: list index out of range
```

ref: https://ci.appveyor.com/project/conda-forge/staged-recipes/builds/22603852#L185

### Expected Behavior

Would like it to build on Windows as well or at least get past the meta parsing stage.

### Steps to Reproduce

Run this on Windows.

```batch
python .ci_support\build_all.py recipes
```

Alternatively run the following on any platform.

```python
import os
from os.path import join as pjoin, exists as pexists

import conda_build.conda_interface as cbci
import conda_build.api as cbapi


platform = "win"
arch = "64"
channel_urls = ["local", "conda-forge", "defaults"]

variant_config_files = []
exclusive_config_file = pjoin(cbci.root_dir, "conda_build_config.yaml")
recipe_path = pjoin("recipes", "apr")

os_variant_config_file = pjoin(
    ".ci_support", "{platform}{arch}.yaml".format(platform=platform, arch=arch)
)
if pexists(os_variant_config_file):
    variant_config_files.append(os_variant_config_file)


config = cbapi.Config(variant_config_files=variant_config_files,
                      arch=arch,
                      exclusive_config_file=exclusive_config_file,
                      channel_urls=channel_urls)

cbapi.render(recipe_path=recipe_path,
             platform=platform,
             arch=arch,
             verbose=False,
             permit_undefined_jinja=True,
             bypass_env_check=True,
             config=config,
             finalize=False)
```

Edit: Changed script to handle a missing OS specific variant file (for Linux).

##### `Output of conda info`

```
     active environment : base
    active env location : C:\Miniconda36-x64
            shell level : 1
       user config file : C:\Users\appveyor\.condarc
 populated config files : C:\Users\appveyor\.condarc
          conda version : 4.6.7
    conda-build version : 3.17.8
         python version : 3.6.5.final.0
       base environment : C:\Miniconda36-x64  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Miniconda36-x64\pkgs
                          C:\Users\appveyor\.conda\pkgs
                          C:\Users\appveyor\AppData\Local\conda\conda\pkgs
       envs directories : C:\Miniconda36-x64\envs
                          C:\Users\appveyor\.conda\envs
                          C:\Users\appveyor\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.6.7 requests/2.18.4 CPython/3.6.5 Windows/2012ServerR2 Windows/6.3.9600
          administrator : True
             netrc file : None
           offline mode : False
```

**Comment by jakirkham** [comment]
Note that simply changing the script's `platform` to `"osx"` or `"linux"` does not encounter the problem.

**Comment by jakirkham** [comment]
Alright have refined this further.

<details>
<summary>Recipe:</summary>

```yaml
# multiout/meta.yaml

package:
  name: out
  version: 1.0.0

build:
  number: 0

requirements:
  run:
    - out1
    - out2
    - out3

outputs:
  - name: out1
    version: 1.0.0
    build:
      run_exports:
        - {{ pin_subpackage('out1', max_pin='x') }}
      script: echo "Installing out1..."
    requirements:
      build:
        - {{ compiler('c') }}
      host:
    test:
      commands:
        - echo "Testing out1..."

  - name: out3
    version: 1.0.0
    build:
      run_exports:
        - {{ pin_subpackage('out3', max_pin='x') }}
      script: echo "Installing out3..."
    requirements:
      build:
        - {{ compiler('c') }}
      host:
        - out1
        - out2
    test:
      commands:
        - echo "Testing out3..."

  - name: out2
    version: 1.0.0
    build:
      run_exports:
        - {{ pin_subpackage('out2', max_pin='x') }}
      script: echo "Installing out2..."
    requirements:
      build:
        - {{ compiler('c') }}
      host:
        - out1
    test:
      commands:
        - echo "Testing out2..."

about:
  home: https://conda.io/
  license: MIT
  summary: Test repo
```

```yaml
# multiout/conda_build_config.yaml
target_platform:
- win-64
```

</details>

<br>

<details>
<summary>Script:</summary>

```python
import os
from os.path import join as pjoin

import conda_build.conda_interface as cbci
import conda_build.api as cbapi


platform = "win"
arch = "64"
channel_urls = ["local", "defaults"]

variant_config_files = []
exclusive_config_file = pjoin(cbci.root_dir, "conda_build_config.yaml")
recipe_path = pjoin("recipes", "multiout")

config = cbapi.Config(variant_config_files=variant_config_files,
                      arch=arch,
                      exclusive_config_file=exclusive_config_file,
                      channel_urls=channel_urls)

cbapi.render(recipe_path=recipe_path,
             platform=platform,
             arch=arch,
             verbose=False,
             permit_undefined_jinja=True,
             bypass_env_check=True,
             config=config,
             finalize=False)
```

</details>
