### ISSUE TITLE
Testing based on recipes is deprecated as of conda-build 3.16.0

### ISSUE THREAD

**Issue by kylekeppler** [conda/conda-build#3417]
`Testing based on recipes is deprecated as of conda-build 3.16.0.  Please adjust your code to pass your desired conda package to test instead.`

Can someone clarify what this means? The first sentence makes me think I should not use the `test` key in `meta.yaml` at all. The second means I should only use the `test/imports` key??? The docs do not indicate any deprecation.

I only get this when running `conda-build -t`. No warning with `conda-build`, however the `file.ext` does not get copied into the `test_tmp`.

`conda 4.6.7`
`conda-build 3.17.8`

Relevant part of `meta.yaml`:
```
test:
  imports:
    - mypylib
  files:
    - tests/test_files/file.ext
  source_files:
    - tests/*.py
  requires:
    - pytest
  commands:
    - pytest tests
```

`file.ext` is pretty large and I don't want it in the release package. I think this is what is intended by the `test/files` and `test/source_files` `meta.yaml` keys. My library is a file reader, so one test attempts to open this large file.
