### ISSUE TITLE
Is missing_dso_whitelist broken in 3.17.x ?

### ISSUE THREAD

**Issue by nehaljwani** [conda/conda-build#3427]
The following recipe works with CB 3.16.x but fails with 3.17.x:

```
package:
  name: miss_me_q
  version: 0.0.1

build:
  missing_dso_whitelist:
    - /lib/libc.so.6
    - /lib/libselinux.so.1
    - /lib64/libcap.so.2
    - /lib/librt.so.1
    - /lib64/libacl.so.1
    - /lib/ld-linux.so.2
    - /lib/libpthread.so.0
    - /lib64/libattr.so.1
  script:
   - mkdir -p $PREFIX/bin
   - cp /bin/ls $PREFIX/bin/
```
