### ISSUE TITLE
overlinking error with conda-forge mpich package

### ISSUE THREAD

**Issue by pmspire** [conda/conda-build#3438]
### Actual Behavior

When building a simple recipe requiring the `mpich` package from `conda-forge`, I get an unexpected overlinking error. This could be an issue with the package; if so, I'll raise an issue with the maintainers. But I don't understand the error emitted by `conda-build`, so would like to rule out the possibility that it's a `conda-build` problem.

Here's the error in question from the `conda-build` output:
```
ERROR (foo,bin/p): runpaths ['$SELFDIR/../lib'] found in /lscratch/pmadden/miniconda/conda-bld/foo_1552159548912/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/bin/p
```
Strangely (maybe), I do get a tarball package file and can create a conda environment from it, and `conda-build` exits with 0 status. The combination of the 0 exit status and the `ERROR` in the output seems like an issue even if there's a problem with the `mpich` package.
### Expected Behavior

No overlinking error.

### Steps to Reproduce
```
% cat p.f90
program p
  use mpi
end program p

% cat meta.yaml 
package:
  name: foo
  version: 0.0.1

build:
    script: mpifort $FFLAGS -o $PREFIX/bin/p p.f90

requirements:
  build:
    - {{ compiler('fortran') }}
    - make
  host:
    - mpich
  run:
    - mpich

source:
  path: .

% conda build -c conda-forge --error-overlinking .
```
##### `Output of conda info`
```
     active environment : base
    active env location : /lscratch/pmadden/miniconda
            shell level : 1
       user config file : /home/spire/pmadden/.condarc
 populated config files : 
          conda version : 4.6.7
    conda-build version : 3.17.8
         python version : 3.7.2.final.0
       base environment : /lscratch/pmadden/miniconda  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /lscratch/pmadden/miniconda/pkgs
                          /home/spire/pmadden/.conda/pkgs
       envs directories : /lscratch/pmadden/miniconda/envs
                          /home/spire/pmadden/.conda/envs
               platform : linux-64
             user-agent : conda/4.6.7 requests/2.21.0 CPython/3.7.2 Linux/3.10.0-327.3.1.el7_lustre.x86_64 rhel/7.2 glibc/2.17
                UID:GID : 5090:5018
             netrc file : /home/spire/pmadden/.netrc
           offline mode : False
```
