### ISSUE TITLE
conda build adds new dependencies to package?

### ISSUE THREAD

**Issue by hhuuggoo** [conda/conda-build#3457]
### Actual Behavior

This is a question not a bug report.  After building a package, There are extra dependencies in the resulting package than the original recipe.  My question is just why this is necessary, and is there a way to prevent this from happening?  My original recipe is:

```
package:
  name: sutils
  version: {{ environ.get('VERSION', '0.1') }}
build:
  number: 1
requirements:
  build:
    - python=3.7
  run:
    - python=3
```
Inside the package

```
package:
    name: sutils
    version: '0.1'
build:
    number: '1'
    string: py37_1
requirements:
    build:
        - bzip2 1.0.6 h14c3975_1002
        - ca-certificates 2019.3.9 hecc5488_0
        - certifi 2019.3.9 py37_0
        - libffi 3.2.1 he1b5a44_1006
        - libgcc-ng 8.2.0 hdf63c60_1
        - libstdcxx-ng 8.2.0 hdf63c60_1
        - ncurses 6.1 hf484d3e_1002
        - openssl 1.1.1b h14c3975_1
        - pip 19.0.3 py37_0
        - python 3.7.2 h381d211_0
        - readline 7.0 hf8c457e_1001
        - setuptools 40.8.0 py37_0
        - sqlite 3.26.0 h67949de_1001
        - tk 8.6.9 h84994c4_1000
        - wheel 0.33.1 py37_0
        - xz 5.2.4 h14c3975_1001
        - zlib 1.2.11 h14c3975_1004
    run:
        - bzip2 >=1.0.6,<2.0a0
        - libffi >=3.2.1,<4.0a0
        - openssl >=1.1.1b,<1.1.2a
        - python=3
        - readline >=7.0,<8.0a0
        - sqlite >=3.26.0,<4.0a0
        - tk >=8.6.9,<8.7.0a0
        - xz >=5.2.4,<6.0a0
        - zlib >=1.2.11,<1.3.0a0
extra:
    copy_test_source_files: true
    final: true
```
This isn't desirable because then my packages are less compatible (for example, very tied to specific versions of openssl)

### Expected Behavior

The package dependencies should match that of the recipe.

### Steps to Reproduce

build any recipe that depends on python

##### `Output of conda info`

```
     active environment : pdc
    active env location : /home/ubuntu/miniconda3/envs/pdc
            shell level : 2
       user config file : /home/ubuntu/.condarc
 populated config files : /home/ubuntu/miniconda3/.condarc
          conda version : 4.6.2
    conda-build version : 3.17.6
         python version : 3.7.1.final.0
       base environment : /home/ubuntu/miniconda3  (writable)
           channel URLs : https://conda.saturncloud.io/pkgs/linux-64
                          https://conda.saturncloud.io/pkgs/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/ubuntu/miniconda3/pkgs
                          /home/ubuntu/.conda/pkgs
       envs directories : /home/ubuntu/miniconda3/envs
                          /home/ubuntu/.conda/envs
               platform : linux-64
             user-agent : conda/4.6.2 requests/2.19.1 CPython/3.7.1 Linux/4.15.0-1034-aws ubuntu/18.04.1 glibc/2.27
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```

**Comment by msarahan** [comment]
Those are coming from run_exports entries in the upstream packages.  Read more at https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#export-runtime-requirements

Constraining things is done to the best of our understanding of binary compatibility bounds.  The openssl constraint isn't bad.  It constrains to the appropriate release series, and presents a minimum bound matching the version used at build time.  It looks worse than it is because openssl's versioning is pretty weird.

Your packages aren't any more or less compatible because of this.  Leaving off constraints does not magically make things compatible, you'd just be more likely to have problems at runtime because of binary compatibility issues.

**Comment by hhuuggoo** [comment]
So I ran into this because I built package X a few months ago, and it was pinned to a specific version of openssl, and then I built package Y today, which has a dependency on package X , which after building resulted in dependencies to a different and incompatible openssl verison.  I do get the reasoning your mentioning, however since this is a pure python package, is there a way to express that I'm fine with any valid python 3.7/openssl combination?

(I'd like to avoid noarch packages, because they cause some issues with other tools I'm planning on using, like anaconda constructor)

Thanks!

**Comment by msarahan** [comment]
If openssl is not actually a dependency, don't list it.  Otherwise, if you are using ctypes or something like that, and really are not dependent on binary compatibility (you're still bound by API compatibility, of course), then you can ignore run exports:

```
build:
  ignore_run_exports:
    - openssl
```

This is documented at the bottom of the section that I linked you to before: https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#export-runtime-requirements

**Comment by hhuuggoo** [comment]
I'm not listing openssl, that's why I'm confused.  I'm only listing python=3.7.  Am I doing something wrong?  IS the only way to not express a specific openssl dependency to add ignore_run_exports if I'm depending on python?

**Comment by msarahan** [comment]
Oh, I see.  The problem is that you're listing python versions, and that python is special-cased and crappy.  noarch is the only way that we have to express that.

```
build:
  noarch: python
requirements:
  build:
    - python >=3.5
  run:
    - python >=3.5
```

You could otherwise build out the python 3 matrix that you want:

```
build:
  skip: true  # [py<35]

requirements:
  build:
    - python
  run:
    - python
```

There's no alternative between these 2.  It would be nice to fix this, but there's too many other priorities ahead of this.  It definitely won't be fixed in the near term without a community contribution.
