### ISSUE TITLE
`noarch` not propagated to `outputs`

### ISSUE THREAD

**Issue by epruesse** [conda/conda-build#3495]
### Actual Behavior

```yaml
package:
  name: x
  version: 0.1
build:
  noarch: generic
  number: 0

outputs:
  - name: x
  - name: x-feature
```

Builds
-  `noarch/x-0.1-0.tar.bz2` and
-  **`linux-64`**`/x-feature-0.1-0.tar.bz2`** (on linux host)

### Expected Behavior

Top level `noarch` setting should propagate to outputs.

Builds 
- `noarch/x-0.1-0.tar.bz2` and 
- **`noarch`**`/x-feature-0.1-0.tar.bz2`

### Steps to Reproduce

See https://github.com/bioconda/bioconda-recipes/blob/056fe1495123c92501bc89d411255c78b0737cdb/recipes/gatk4/meta.yaml

### Workaround

Repeat `build: noarch: generic` in `outputs: []`. Doesn't seem to be documented though, guessing it's side effect of each output having a `MetaData` instance?
