### ISSUE TITLE
Building package for incorrect python version

### ISSUE THREAD

**Issue by biancaG** [conda/conda-build#3522]
### Actual Behavior
Conda builds package for python 3.7 despite meta.yaml specifying python 3.6. See meta.yaml and logs here: https://gist.github.com/biancaG/7fbbd007cdd042eb2b65633209c964f3
The package file name says py37 and when I've tried to install the packages produced it tries to pull in python 3.7.

### Expected Behavior
Package should be built for the python version specified in meta.yaml, which is 3.6. 

### Steps to Reproduce
Assuming you have conda-build and git installed:
Check out `conda_packaging` branch of this repo: https://github.com/biancaG/awra_cms
```
cd packaging
python setup.py sdist
conda build -c conda-forge .
```
The package produced includes 'py37' in the name, which I'm pretty sure marks it as python 3.7. It can be installed with:
```
conda index <path to package from your conda build output>
conda install --use-local awracms
```

##### `Output of conda info`
```
     active environment : py3.6
    active env location : /home/biancag/miniconda3/envs/py3.6
            shell level : 2
       user config file : /home/biancag/.condarc
 populated config files : 
          conda version : 4.6.14
    conda-build version : 3.17.8
         python version : 3.7.1.final.0
       base environment : /home/biancag/miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/biancag/miniconda3/pkgs
                          /home/biancag/.conda/pkgs
       envs directories : /home/biancag/miniconda3/envs
                          /home/biancag/.conda/envs
               platform : linux-64
             user-agent : conda/4.6.14 requests/2.21.0 CPython/3.7.1 Linux/5.0.9-100.fc28.x86_64 fedora/28 glibc/2.27
                UID:GID : 4636:5001
             netrc file : None
           offline mode : False
```

**Comment by jjhelmus** [comment]
You need to specify the Python version in the `host` section.  The following recipe will build a Python 3.6 package:

``` yaml
{% set name = "awracms" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: ./dist/awrams-1.2.tar.gz
  sha256: a69876739042bb0f612c54a452b0799b8dabab6c66ec31e9ba40cfbbdc914440

requirements:
  host:
    - python 3.6
    - setuptools
    - nose
    - pydoe
  run:
    - python 3.6
    - numpy
    - scipy
    - matplotlib
    - pandas
    - h5py
    - cffi
    - libnetcdf
    - netcdf4
    - libgdal # [linux]
    - gdal # [linux]
    - anaconda::libgdal =2.3.2  # [windows]
    - anaconda::gdal =2.3.2  # [windows]
    - dask
    - seaborn
    - basemap
    - cartopy
    - paramiko
    - SALib
    - msgpack-python
    - mpi4py
    - pydoe

about:
  home: https://github.com/awracms/awra_cms
  license: AWRA license
  summary: 'Australian Water Resources Assessment (AWRA) Community Modelling System'

  description: |
    The AWRA modelling system (AWRAMS) has been developed by the Commonwealth Scientific
    and Industrial Research Organisation (CSIRO) and the Bureau towards fulfilling the Bureaus
    water reporting requirements specified in the Water Act (2007).

  doc_url: https://github.com/awracms/awra_cms
  dev_url: https://github.com/awracms/awra_cms

extra:
  recipe-maintainers:
    - bianca.gibson@bom.gov.au
```
