### ISSUE TITLE
conda-render / api.render() always setting PKG_HASH to "1234567"

### ISSUE THREAD

**Issue by aldanor** [conda/conda-build#3543]
I was testing `conda-render` on a simplistic package like

```yaml
package:
  name: hello
  version: 3.2.1
requirements:
  build:
    - python=3.6
    - pip
  run:
  - python=3.6
build:
  string: py{{py}}_h{{PKG_HASH}}_{{PKG_BUILDNUM}}
```

And it always outputs `py36_h1234567_0` (after a bit of a delay).

Looks like it's somehow related to `meta.final` flag - is one supposed to set it manually in extra/final? (if it's set though, the build environment doesn't get fully expanded; however the PKG_HASH is still 1234567).

What needs to be done for PKG_HASH to be properly populated?
