### ISSUE TITLE
conda build fails with `>=` of variable in `host` section

### ISSUE THREAD

**Issue by ksangeek** [conda/conda-build#3544]
### Actual Behavior

This is a sample recipe file `meta.yaml`

```
package:
  name: dummy-conda
  version: 1.1.1

source:
  path: .

requirements:
  host:
    - python >={{python}}
  run:
    - python >={{python}}
```

And this is the jinja variable `python` defined in a yaml file -
```
$ cat conda_local_config.yaml
python:
  - 3.6
```

When I do a build

```
$ conda build -m conda_local_config.yaml recipe/
```

It fails with 
```
Received dictionary as spec.  Note that pip requirements are not supported in conda-build meta.yaml.
```

### Expected Behavior

It should recognize the `python` variable and continue the build.
Though the problem is only with recognizing `python` variable along with `>=` in `host` section. The `run` section does not have an issue.

If I remove the `>=` from python variable in meta.yaml;
or use hard-coded value, the build works fine.

These are the 2 variants of meta.yaml file which work -
```
package:
  name: dummy-conda
  version: 1.1.1

source:
  path: .

requirements:
  host:
    - python {{python}}
  run:
    - python >={{python}}
```

and this too works fine -

```
package:
  name: dummy-conda
  version: 1.1.1

source:
  path: .

requirements:
  host:
    - python >=3.6
  run:
    - python >={{python}}
``` 

### Steps to Reproduce

1. Take the recipe file attached 
[dummy-conda.tar.gz](https://github.com/conda/conda-build/files/3295972/dummy-conda.tar.gz)
2. `conda build -m conda_local_config.yaml recipe/` fails!
```
$ conda build -m conda_local_config.yaml recipe/
No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11
WARNING:conda_build.metadata:No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11
Adding in variants from internal_defaults
INFO:conda_build.variants:Adding in variants from internal_defaults
Adding in variants from conda_local_config.yaml
INFO:conda_build.variants:Adding in variants from conda_local_config.yaml
Received dictionary as spec.  Note that pip requirements are not supported in conda-build meta.yaml.
```

##### `Output of conda info`

```
$ conda info

     active environment : None
       user config file : <my-home-path>/.condarc
 populated config files : <my-home-path>/.condarc
          conda version : 4.6.14
    conda-build version : 3.16.3
         python version : 3.6.8.final.0
       base environment : /opt/anaconda3  (writable)
           channel URLs : file://<path-to-my-private-repo>
                          https://repo.anaconda.com/pkgs/main/linux-ppc64le
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-ppc64le
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-ppc64le
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /opt/anaconda3/pkgs
                          <my-home-path>/.conda/pkgs
       envs directories : /opt/anaconda3/envs
                          <my-home-path>/.conda/envs
               platform : linux-ppc64le
             user-agent : conda/4.6.14 requests/2.21.0 CPython/3.6.8 Linux/4.14.0-115.2.2.el7a.ppc64le rhel/7.6 glibc/2.17
                UID:GID : 1084:1500
             netrc file : <my-home-path>/.netrc
           offline mode : False
```
