### ISSUE TITLE
run_exports not applied when channel does not provide channeldata.json

### ISSUE THREAD

**Issue by jjhelmus** [conda/conda-build#3583]
As of #3561, run exports are extracted from channeldata.json rather than the packages themselves.  This speeds up rendering time but will cause run exports to not be applied if the channel from which the package is supplied does not provide channeldata.json.  Most channels on Anaconda.org do not provide channeldata.json.

A simple example:

```
package:
  name: exporty
  version: 1.0.0

build:
  run_exports:
    strong:
      - exporty
```

```
package:
  name: example
  version: 1.0.0

requirements:
  build:
    - exporty
```

Building `exporty` and locally and rendering `example` gives a correct rendering with run_export applied:

```
$ conda render example/
--------------
Hash contents:
--------------
{}
----------
meta.yaml:
----------
package:
    name: example
    version: 1.0.0
requirements:
    build:
        - exporty 1.0.0 0
    run:
        - exporty
extra:
    copy_test_source_files: true
    final: true
```

Using the uploaded `exporty` package on Anaconda.org results in no run_exports applied:

```
$ conda render -c jjhelmus example/
--------------
Hash contents:
--------------
{}
----------
meta.yaml:
----------
package:
    name: example
    version: 1.0.0
requirements:
    build:
        - exporty 1.0.0 0
extra:
    copy_test_source_files: true
    final: true
```

**Comment by mariusvniekerk** [comment]
@jjhelmus is this why we are missing run_exports for our conda-forge aarch64 and ppc64le packages?

**Comment by jjhelmus** [comment]
> @jjhelmus is this why we are missing run_exports for our conda-forge aarch64 and ppc64le packages?

Yes, moving the effected conda-build aarch64 packages (3.18.6  3.18.5 3.18.4) to a broken label may be the easiest fix until this is changed in conda-build itself.

**Comment by minrk** [comment]
There's something wrong with run_exports on linux-64 as well. When I run `conda render` on a package that has `fftw` as a host dependency, it's getting run_exports coming from builds of packages not in the host environment. Seems like something's amiss in general in the run_exports computation.

meta.yaml:

<details>

```yaml
$ cat test/meta.yaml
package:
  name: testing
  version: 1.0

source:

build:
  number: 1

requirements:
  build: []
  host:
    - fftw
  run:
    - fftw

```
</details>

`conda render --verbose test`

<details>

```yaml
Adding in variants from internal_defaults
No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11
Attempting to finalize metadata for testing
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done
--------------
Hash contents:
--------------
{}
----------
meta.yaml:
----------
package:
    name: testing
    version: '1.0'
build:
    number: '1'
requirements:
    host:
        - libgcc-ng 9.1.0 hdf63c60_0
        - libgfortran-ng 7.3.0 hdf63c60_0
        - fftw 3.3.8 nompi_h7f3a6c3_1105
    run:
        - fftw * mpi_openmpi_*
extra:
    copy_test_source_files: true
    final: true
```

</details>


`conda info`

<details>

```
     active environment : base
    active env location : /opt/conda
            shell level : 1
       user config file : /home/conda/.condarc
 populated config files : /home/conda/.condarc
          conda version : 4.7.5
    conda-build version : 3.18.6
         python version : 3.7.3.final.0
       virtual packages :
       base environment : /opt/conda  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /opt/conda/pkgs
                          /home/conda/.conda/pkgs
       envs directories : /opt/conda/envs
                          /home/conda/.conda/envs
               platform : linux-64
             user-agent : conda/4.7.5 requests/2.22.0 CPython/3.7.3 Linux/4.9.125-linuxkit centos/6.10 glibc/2.12
                UID:GID : 9001:9001
             netrc file : None
           offline mode : False
```

</details>

FWIW, I confirmed that this does not happen with conda-build 3.18.3 and does with 3.18.4-6.
