### ISSUE TITLE
Detect correct extraction for CDT binary rpms 

### ISSUE THREAD

**Issue by hmaarrfk** [conda/conda-build#3595]
If a binary RPM only has one folder at the top level, say `./usr`, then conda build will remove that folder from the structure. But for RPMs, we thus loose the intended folder structure.

Is there a way to stop top level folder stripping? Otherwise, maybe we can detect the intended folder structure and autodetect a fix like:

```
source:
  - url: http://mirror.centos.org/centos/6.10/os/x86_64/Packages/libudev-devel-147-2.73.el6_8.2.x86_64.rpm
    sha256: 318322d5e63b27bf423e011e9b3d8863e5b1aa5ac57de131add0a85c8e6bbbfe
    # The rpm only contains one folder, usr, so without this, we lose the
    # intended folder structure of the RPM
    folder: binary/usr
```

xref: https://github.com/conda-forge/staged-recipes/pull/8739#discussion_r300883633

##### `Output of conda info`

```
 conda info

     active environment : base
    active env location : /home/mark/miniconda3
            shell level : 1
       user config file : /home/mark/.condarc
 populated config files : /home/mark/.condarc
          conda version : 4.7.5
    conda-build version : 3.17.8
         python version : 3.7.3.final.0
       virtual packages : 
       base environment : /home/mark/miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/mark/miniconda3/pkgs
                          /home/mark/.conda/pkgs
       envs directories : /home/mark/miniconda3/envs
                          /home/mark/.conda/envs
               platform : linux-64
             user-agent : conda/4.7.5 requests/2.22.0 CPython/3.7.3 Linux/5.0.0-20-generic ubuntu/19.04 glibc/2.29
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```
