### ISSUE TITLE
track_features should reject dashes in feature name

### ISSUE THREAD

**Issue by ezyang** [conda/conda-build#3651]
features rejects dashes, but `track_features` does not

**Comment by marcelotrevisani** [comment]
Could you please give us more complete information and example to reproduce it?

**Comment by ezyang** [comment]
When I conda build this meta.yaml:

```
package:
  name: feature1
  version: 1.0

build:
  track_features:
      - foo-bar
  noarch: generic
```

Conda accepts it. It should not: foo-bar is an illegal feature name, and if you try to use it in a feature field, it will be rejected.
