### ISSUE TITLE
Noarch subpackages

### ISSUE THREAD

**Issue by fcollonval** [conda/conda-build#3702]
### Actual Behavior

I would like to package a [`jupyterlab-git`](https://github.com/conda-forge) using `outputs` feature similarly to `matplotlib` to produce 2 packages:
- One with the server extension
- The second requiring the server extension, adding the jupyter labextension and requiring `nodejs` as run dependency (so the user will be able to repack jupyterlab as in the current recipe)

I got a first version in a PR that is almost what I'm looking for. But unfortunately the `noarch` option is use only for the server package and not for the extension one. Is there a way to get the noarch options to be propagated to all subpackages?

The recipe is :
```yaml
{% set name = "jupyterlab-git" %}
{% set version = "0.8.1" %}
{% set sha256 = "972611bf24120d9acd0261d7ea4cd6b5540fd5dd47c951b84cb60020e5d7d6d8" %}

package:
  name: {{ name|lower }}-server
  version: {{ version }}

source:
  url: https://github.com/jupyterlab/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  noarch: python

requirements:
  build:
    - nodejs
  host:
    - jupyterlab >=1.0.0
    - pip
    - python >=3.5
  run:
    - jupyterlab >=1.0.0
    - python >=3.5
    - nbdime >=1.1.0

test:
  imports:
    - jupyterlab_git

outputs:
  - name: {{ name|lower }}-server

  - name: {{ name|lower }}
    requirements:
      host:
        - jupyterlab >=1.0.0
        - python >=3.5
      run:
        - python >=3.5
        - nodejs
        - {{ pin_subpackage('jupyterlab-git-server', exact=True) }}
    test:
      imports:
        - jupyterlab_git
      commands:
        - jupyter labextension list
        - jupyter lab build
  
  
about:
  home: https://github.com/jupyterlab/jupyterlab-git
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A Git extension for JupyterLab
  description: A JupyterLab extension for version control using git
  dev_url: https://github.com/jupyterlab/jupyterlab-git

extra:
  recipe-maintainers:
    - dbast
    - blink1073

```

`conda render` is the following:

```
--------------
Hash contents:
--------------
{}
----------
meta.yaml:
----------
package:
    name: jupyterlab-git-server
    version: 0.8.1
source:
    sha256: 972611bf24120d9acd0261d7ea4cd6b5540fd5dd47c951b84cb60020e5d7d6d8
    url: https://github.com/jupyterlab/jupyterlab-git/archive/v0.8.1.tar.gz
build:
    noarch: python
    number: '1'
requirements:
    build:
        - openssl 1.1.1c h516909a_0
        - ca-certificates 2019.6.16 hecc5488_0
        - icu 64.2 he1b5a44_1
        - _libgcc_mutex 0.1 main
        - libgcc-ng 9.1.0 hdf63c60_0
        - zlib 1.2.11 h516909a_1005
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - nodejs 12.8.1 h10a4023_0
        - libuv 1.30.1 h516909a_0
    host:
... [skipped]
    run:
        - jupyterlab >=1.0.0
        - python >=3.5
        - nbdime >=1.1.0
test:
    imports:
        - jupyterlab_git
outputs:
    -   name: jupyterlab-git-server
    -   name: jupyterlab-git
        requirements:
            host:
                - jupyterlab >=1.0.0
                - python >=3.5
            run:
                - python >=3.5
                - nodejs
                - jupyterlab-git-server 0.8.1 py_1
        test:
            commands:
                - jupyter labextension list
                - jupyter lab build
            imports:
                - jupyterlab_git
about:
    description: A JupyterLab extension for version control using git
    dev_url: https://github.com/jupyterlab/jupyterlab-git
    home: https://github.com/jupyterlab/jupyterlab-git
    license: BSD 3-Clause
    license_family: BSD
    license_file: LICENSE
    summary: A Git extension for JupyterLab
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - dbast
        - blink1073

--------------
Hash contents:
--------------
{}
----------
meta.yaml:
----------
package:
    name: jupyterlab-git
    version: 0.8.1
source:
    sha256: 972611bf24120d9acd0261d7ea4cd6b5540fd5dd47c951b84cb60020e5d7d6d8
    url: https://github.com/jupyterlab/jupyterlab-git/archive/v0.8.1.tar.gz
build:
    noarch: false
    number: '1'
requirements:
    host:
[skipped]
    run:
        - python >=3.7,<3.8.0a0
        - nodejs
        - jupyterlab-git-server 0.8.1 py_1
test:
    commands:
        - jupyter labextension list
        - jupyter lab build
    imports:
        - jupyterlab_git
about:
    description: A JupyterLab extension for version control using git
    dev_url: https://github.com/jupyterlab/jupyterlab-git
    home: https://github.com/jupyterlab/jupyterlab-git
    license: BSD 3-Clause
    license_family: BSD
    license_file: LICENSE
    summary: A Git extension for JupyterLab
extra:
    copy_test_source_files: true
    final: true
    parent_recipe:
        name: jupyterlab-git-server
        path: /home/fcollonval/nodewks/jupyterlab-git-feedstock/recipe
        version: 0.8.1
    recipe-maintainers:
        - dbast
        - blink1073
```

### Expected Behavior

propagate noarch to the subpackages.

### Steps to Reproduce

Run conda render on the provided recipe.

##### `Output of conda info`

```
     active environment : base
    active env location : /home/fcollonval/miniconda3
            shell level : 1
       user config file : /home/fcollonval/.condarc
 populated config files : /home/fcollonval/.condarc
          conda version : 4.7.11
    conda-build version : 3.18.9
         python version : 3.7.3.final.0
       virtual packages : 
       base environment : /home/fcollonval/miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/fcollonval/miniconda3/pkgs
                          /home/fcollonval/.conda/pkgs
       envs directories : /home/fcollonval/miniconda3/envs
                          /home/fcollonval/.conda/envs
               platform : linux-64
             user-agent : conda/4.7.11 requests/2.22.0 CPython/3.7.3 Linux/4.19.0-5-amd64 debian/10 glibc/2.28
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```

**Comment by mingwandroid** [comment]
Hi @fcollonval, 

Yes! This should be possible (and in fact it should propagate already, so I'm keeping this open). As a workaround each output can override basically any (fact check request to @msarahan) metadata from the top-level package (and presumably things that didn't propagate for whatever reason), so this *should* work:

```
build:
  number: 1
```
..
```
outputs:
  - name: {{ name|lower }}-server
    noarch: python

  - name: {{ name|lower }}
    noarch: python
```

Cheers.
