### ISSUE TITLE
Improve legibility of larger tables

### ISSUE THREAD

**Issue by scw** [conda/conda-build#3713]
Sections such as [Environment variables](http://conda.pydata.org/docs/building/environment-vars.html) use long tables to list their entries. The current look has a consistency that's nice, but the tables are cut off, and require scrolling within the tables which is tricky:

![screen shot 2016-09-23 at 10 28 43 pm](https://cloud.githubusercontent.com/assets/1314/18805509/0301b35a-81de-11e6-8d8b-8e1dbb01e56b.png)

Making these changes to the CSS improved the table legibility:

``` css
.wy-table-responsive table td, .wy-table-responsive table th {
    white-space: normal;
}

.wy-table td, .rst-content table.docutils td, .rst-content table.field-list td {
    vertical-align: top;
}
```

![screen shot 2016-09-23 at 10 38 35 pm](https://cloud.githubusercontent.com/assets/1314/18805532/8121fea2-81de-11e6-959d-a89496bcfe47.png)

I see that there's an upstream [sphinx_rtd_theme](https://github.com/snide/sphinx_rtd_theme) that may be the ultimate place to fix this, but thought I'd report here as it relates to the way tables are used within the Conda docs.
