### ISSUE TITLE
Fixing dependencies of multiple outputs

### ISSUE THREAD

**Issue by jpoeppel** [conda/conda-build#3732]
Hi everyone, this may just be me not understanding conda-build/the documentation enough, but I have a problem with shared dependencies of multiple outputs.

The concrete case is that we have a library that uses google's protobuf protocol, i.e. we require libprotobuf in order to compile the Proto files for the different languages (CPP and Python in this case). 
I wanted to split the library into 2 outputs, one for cpp and one for python, with a general meta package containing both of them.
Now, since the protobuf files are very sensitive to the libprotobuf version used when compiling the files, I would like to share these dependencies across both outputs.

I understand that I can pin run-time requirements to build requirements using "pin_compatible" but it looks like this only works within a single output.

I can of course, hardcode a specific protobuf version (e.g. 3.9.0) and pass that to all outputs, but I would have preferred if it picks the newest (or otherwise only mildly restricted) version of protobuf each time I trigger a build and just update the runtime requirements so that the generated files work in the environments the packages are installed into.

### Actual Behavior

Runtime requirements for a shared dependency are not fixed to the same version across different outputs.

### Expected Behavior

Some way in the recipe to specify that whatever version is used during build (of the first package) is used as build/host and run requirement for all other outputs.

##### `Output of conda info`

```
conda info

     active environment : None
            shell level : 0
       user config file : /Users/jpoeppel/.condarc
 populated config files : /Users/jpoeppel/.condarc
          conda version : 4.7.12
    conda-build version : 3.18.9
         python version : 3.7.3.final.0
       virtual packages : 
       base environment : /Users/jpoeppel/miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/jpoeppel/miniconda3/pkgs
                          /Users/jpoeppel/.conda/pkgs
       envs directories : /Users/jpoeppel/miniconda3/envs
                          /Users/jpoeppel/.conda/envs
               platform : osx-64
             user-agent : conda/4.7.12 requests/2.22.0 CPython/3.7.3 Darwin/18.7.0 OSX/10.14.6
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```

**Comment by mingwandroid** [comment]
Can you share a recipe?

**Comment by jpoeppel** [comment]
Sure, this is the one where I already used the fixed version variable.

The "install_cpp/py.sh" scripts are doing either a cmake or python installation. Currently both of them are also building the proto files separately, which I could also do in a shared build step at the top level, but since this would require a change to the setup.py, I currently refrained from doing so.

```
{% set protobufversion = "3.8.0" %}

package:
  name: ipaaca
  version: "0.1.1"

source:
  - path: ../ipaacalib/cpp/
    folder: ipaaca-cpp
  - path: ../ipaacalib/python/
    folder: ipaaca-py
  - path: ../ipaacalib/proto/
    folder: proto

build:
  number: 4
  

requirements:
  build:
    - {{ compiler('cxx') }} 7.3 # [linux]
    - cmake >=3.10
  run:
    - ipaaca-cpp
    - ipaaca-py

outputs:
  - name: ipaaca-cpp
    script: install_cpp.sh
    requirements:
      host:
        - libprotobuf {{ protobufversion }}
        - mosquitto
        - libboost

      run:
        - mosquitto
        - {{ pin_compatible('libprotobuf', max_pin='x.x') }}
        - libboost

  - name: ipaaca-py
    noarch: python
    script: install_python.sh
    requirements:
      host:
        - python
        - pip
        - setuptools
        - protobuf {{ protobufversion }}

      run:
        - python
        - mosquitto
        - paho-mqtt
        - {{ pin_compatible('protobuf', max_pin='x.x') }}
    
```
