### ISSUE TITLE
Incorrect hash contents when using multiple outputs with jinja2 or YAML anchors

### ISSUE THREAD

**Issue by chrisburr** [conda/conda-build#3749]
### Actual Behavior

Dependencies are ignored for packages in `outputs` which have been declared using jinja2 templating or YAML anchors.

### Expected Behavior

Hash should be the same regardless of how the package is included as a dependency.

### Steps to Reproduce

Use render the `meta.yaml` file below. This behaviour is not related to having multiple outputs and can be seen with a single element in `outputs` (they're combined here for convenience).

```yaml
{% macro build_dependencies() %}
        - {{ compiler('fortran') }}
{% endmacro -%}

package:
  name: example
  version: "1.0.0"

build:
  number: 0

outputs:
  - name: example-output-1
    requirements:
      build: {{- build_dependencies() }}

  - name: example-output-2
    requirements: &some_label
      build:
        - {{ compiler('fortran') }}

  - name: example-output-3
    requirements:
      <<: *some_label
```

Using `conda render .` gives:

```yaml
--------------
Hash contents:
--------------
{}
----------
meta.yaml:
----------
package:
    name: example-output-1
    version: 1.0.0
build:
    noarch: false
    number: '0'
requirements:
    build:
        - libcxxabi 9.0.0 0
        - libiconv 1.15 h01d97ff_1005
        - llvm-openmp 9.0.0 h40edb58_0
        - zlib 1.2.11 h01d97ff_1006
        - libcxx 9.0.0 0
        - libgfortran 4.0.0 2
        - cctools 921 h5ba7a2e_3
        - gmp 6.1.2 h0a44026_1000
        - libllvm9 9.0.0 h770b8ee_2
        - tapi 1000.10.8 h770b8ee_2
        - clang 9.0.0 h28b9765_0
        - isl 0.19 0
        - ld64 409.12 h3c32e8a_3
        - mpfr 4.0.2 h44b798e_0
        - mpc 1.1.0 h3aece09_1006
        - gfortran_impl_osx-64 7.3.0 hf4212f2_2
        - gfortran_osx-64 7.3.0 h22b1bf0_4
    run:
        - libgfortran >=4.0.0,<5.0.0.a0
extra:
    copy_test_source_files: true
    final: true
    parent_recipe:
        name: example
        path: /Users/christopherburr/Development/conda-forge/root-feedstock/test
        version: 1.0.0

--------------
Hash contents:
--------------
{'fortran_compiler': 'gfortran'}
----------
meta.yaml:
----------
package:
    name: example-output-2
    version: 1.0.0
build:
    noarch: false
    number: '0'
requirements:
    build:
        - libcxxabi 9.0.0 0
        - gmp 6.1.2 h0a44026_1000
        - tapi 1000.10.8 h770b8ee_2
        - cctools 921 h5ba7a2e_3
        - clang 9.0.0 h28b9765_0
        - mpfr 4.0.2 h44b798e_0
        - ld64 409.12 h3c32e8a_3
        - gfortran_osx-64 7.3.0 h22b1bf0_4
        - libllvm9 9.0.0 h770b8ee_2
        - libcxx 9.0.0 0
        - isl 0.19 0
        - libiconv 1.15 h01d97ff_1005
        - libgfortran 4.0.0 2
        - mpc 1.1.0 h3aece09_1006
        - llvm-openmp 9.0.0 h40edb58_0
        - gfortran_impl_osx-64 7.3.0 hf4212f2_2
        - zlib 1.2.11 h01d97ff_1006
    host:
        - llvm-openmp 9.0.0 h40edb58_0
        - libgfortran 4.0.0 2
    run:
        - libgfortran >=4.0.0,<5.0.0.a0
extra:
    copy_test_source_files: true
    final: true
    parent_recipe:
        name: example
        path: /Users/christopherburr/Development/conda-forge/root-feedstock/test
        version: 1.0.0

--------------
Hash contents:
--------------
{}
----------
meta.yaml:
----------
package:
    name: example-output-3
    version: 1.0.0
build:
    noarch: false
    number: '0'
requirements:
    build:
        - libcxxabi 9.0.0 0
        - libiconv 1.15 h01d97ff_1005
        - llvm-openmp 9.0.0 h40edb58_0
        - zlib 1.2.11 h01d97ff_1006
        - libcxx 9.0.0 0
        - libgfortran 4.0.0 2
        - cctools 921 h5ba7a2e_3
        - gmp 6.1.2 h0a44026_1000
        - libllvm9 9.0.0 h770b8ee_2
        - tapi 1000.10.8 h770b8ee_2
        - clang 9.0.0 h28b9765_0
        - isl 0.19 0
        - ld64 409.12 h3c32e8a_3
        - mpfr 4.0.2 h44b798e_0
        - mpc 1.1.0 h3aece09_1006
        - gfortran_impl_osx-64 7.3.0 hf4212f2_2
        - gfortran_osx-64 7.3.0 h22b1bf0_4
    run:
        - libgfortran >=4.0.0,<5.0.0.a0
extra:
    copy_test_source_files: true
    final: true
    parent_recipe:
        name: example
        path: /Users/christopherburr/Development/conda-forge/root-feedstock/test
        version: 1.0.0
```

##### `Output of conda info`

```

     active environment : analysis-productions
    active env location : /Users/christopherburr/miniconda3/envs/analysis-productions
            shell level : 4
       user config file : /Users/christopherburr/.condarc
 populated config files : /Users/christopherburr/.condarc
          conda version : 4.7.12
    conda-build version : 3.18.9
         python version : 3.7.3.final.0
       virtual packages :
       base environment : /Users/christopherburr/miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/christopherburr/miniconda3/pkgs
                          /Users/christopherburr/.conda/pkgs
       envs directories : /Users/christopherburr/miniconda3/envs
                          /Users/christopherburr/.conda/envs
               platform : osx-64
             user-agent : conda/4.7.12 requests/2.22.0 CPython/3.7.3 Darwin/18.7.0 OSX/10.14.6
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```
