### ISSUE TITLE
source: path with folder option on windows does not preserve case

### ISSUE THREAD

**Issue by pkitslaar** [conda/conda-build#3755]
I had an issue where I was copying a Python package which had a camel case name (e.g fooBar) using the following meta.yaml set

```
source:
  - path: ../fooBar/
    folder: fooBar
  - path: ../setup.py
```

Later in the setup.py it tries to find the package 'fooBar' which fails.

When inspecting the copied files by conda-build I see that the fooBar package is copied to the
folder 'foobar' (all lower case)

Looking at the code I see this line in the utils.py which I think is causing this issue

https://github.com/conda/conda-build/blob/2be41a76309c0552f359e1b271738ff0e73163fb/conda_build/utils.py#L649
