### ISSUE TITLE
Handling GIT_* environment variables with multiple outputs

### ISSUE THREAD

**Issue by jakirkham** [conda/conda-build#3760]
Not sure whether this is a bug or a feature request. Currently a recipe that uses `outputs` (with one or more packages produced), can use `GIT_*` variables. However these appear to be unassigned. As a result if one tries to generate version information using them, one ends up with an empty version string.

### Actual Behavior

An example of this behavior is in PR ( https://github.com/conda-forge/metawrap-feedstock/pull/11 ). Though one can also just use the `meta.yaml` below to produce this as well.

```yaml
# filename: recipe/meta.yaml

{% set name = "metawrap" %}

package:
  name: {{ name }}-split

outputs:
  - name: {{ name|lower }}
    version: "{{ environ.get('GIT_DESCRIBE_TAG', '')[1:] }}{{ '+' + environ.get('GIT_DESCRIBE_NUMBER', '0') + '.' + environ.get('GIT_DESCRIBE_HASH', '0') if environ.get('GIT_DESCRIBE_NUMBER', '0') != '0' else '' }}"
    source:
      git_url: https://github.com/jakirkham/metawrap
      git_rev: HEAD
    build:
      noarch: python
      number: 1
      script: python -m pip install --no-deps --ignore-installed .
    requirements:
      host:
        - pip
        - python
        - setuptools
      run:
        - python
      test:
        source_files:
          - tests
        imports:
          - metawrap
        commands:
          - python -m unittest discover -s .
        about:
          home: http://github.com/jakirkham/metawrap
          license: BSD 3-Clause
          license_family: BSD
          license_file: LICENSE.txt
          summary: A collection of wrappers for functions and classes.
          doc_url: https://metawrap.readthedocs.io/
          dev_url: http://github.com/jakirkham/metawrap

extra:
  recipe-maintainers:
    - jakirkham
```

### Expected Behavior

Honestly it is hard to say. One might hope that these `GIT_*` variables are set with a specific source in mind, but how to instruct that case is a little unclear. This may rely on new features. Alternatively the `GIT_*` variables could be disambiguated somehow based on which source they relate to. Again it is unclear exactly how this should be done. Perhaps there are other options here?

### Steps to Reproduce

Run `conda build recipe` using the recipe provided above.

##### `Output of conda info`

```
     active environment : base
    active env location : /opt/conda
            shell level : 1
       user config file : /home/conda/.condarc
 populated config files : /home/conda/.condarc
          conda version : 4.7.12
    conda-build version : 3.18.9
         python version : 3.7.3.final.0
       virtual packages : 
       base environment : /opt/conda  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /opt/conda/pkgs
                          /home/conda/.conda/pkgs
       envs directories : /opt/conda/envs
                          /home/conda/.conda/envs
               platform : linux-64
             user-agent : conda/4.7.12 requests/2.22.0 CPython/3.7.3 Linux/4.15.0-1059-azure centos/6.10 glibc/2.12
                UID:GID : 1001:1001
             netrc file : None
           offline mode : False
```
