### ISSUE TITLE
Using load_setup_py_data() makes build to crash on Windows

### ISSUE THREAD

**Issue by gabrielcnr** [conda/conda-build#3768]
### Actual Behavior

On Windows, when using `load_setup_py_data()` in your recipe, if your base conda installation has `python=2.7` and your build/host environment has `python=3.7`, when it executes the `load_setup_py_data()` it crashes with a Runtime Error of the MSVC Runtime Library (see screenshot below).

I did some investigation and debugging and the error/crash happens when conda build invokes the `python.exe` interpreter in the host environment to execute the copied `_load_setup_py_data.py` script, at the moment it tries to `import setuptools` there.

![image](https://user-images.githubusercontent.com/209902/66569218-fdddba80-eb62-11e9-92e6-670f1cd9d20e.png)

##### Simple project structure
```
|   setup.py         
|                    
+---conda.recipe     
|       meta.yaml    
|                    
\---crashdemo
        foo.py       
        __init__.py  
```

##### setup.py
```python
from setuptools import setup

setup(
	name='crashdemo',
	version='1.2.3',
	packages=['crashdemo'],
	zip_safe=False,
)
```

##### conda recipe (meta.yaml)

```yaml
{% set data = load_setup_py_data() %}

package:
  name: crashdemo
  version: "1.2.3"

source:
  path: ../

build:
  script:
    - python setup.py install
  preserve_egg_dir: true

requirements:
  build:
    - python      >=3.7,<3.8
    - setuptools

  run:
    - python      >=3.7,<3.8

test:
  imports:
    - problem

```

##### `Output of conda info`

```
     active environment : None
            shell level : 0
       user config file : C:\Users\greis\.condarc
 populated config files : C:\Users\greis\.condarc
          conda version : 4.7.12
    conda-build version : 3.18.9
         python version : 2.7.16.final.0
       virtual packages : __cuda=6.5
       base environment : c:\dev\bin\conda  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : c:\dev\bin\conda\pkgs
                          C:\Users\greis\.conda\pkgs
                          C:\Users\greis\AppData\Local\conda\conda\pkgs
       envs directories : c:\dev\bin\conda\envs
                          C:\Users\greis\.conda\envs
                          C:\Users\greis\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.7.12 requests/2.22.0 CPython/2.7.16 Windows/10 Windows/10.0.17134
          administrator : False
             netrc file : None
           offline mode : False
```
