### ISSUE TITLE
Build/host dependency of header-only C++ packages

### ISSUE THREAD

**Issue by sdebionne** [conda/conda-build#3796]
When a C++ header-only package `foo` depends on another header only-package `bar`, is there a way to ensure that the downstream project get both installed as `host` requirements?

```
foobar <--depends-- foo <--depends-- bar
```

with

```
package:
  name: foobar

requirements:
  host:
    - foo
```

```
package:
  name: foo

requirements:
  host:
    - bar
```

With the current implementation, only foo gets installed.

Is there any way to export the build/host requirements of a package to the downstream projects transitively, maybe something like `build_export`?

**Comment by marcelotrevisani** [comment]
If you add the ``run`` ``requirements`` on the ``bar`` project
everything which is there will be at the ``host`` section as well.

**Comment by marcelotrevisani** [comment]
You can also do
https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#export-runtime-requirements

**Comment by marcelotrevisani** [comment]
Did it solve your problem?

**Comment by sdebionne** [comment]
Well I thought of using runtime requirements briefly but then the headers would be installed with the dowstream project `foobar`, no?

What I think might be needed is the twin of `run_exports`:

```yaml
# meta.yaml of foo 
build:
  host_exports:
    - bar
```

so anyone using `foo` as a host dependency would automatically get `bar` installed in the host environment.

My workaround is to list both `foo` and `bar` as host dependencies:

```yaml
# meta.yaml of foobar 
build:
  host:
    - foo
    - bar # this should not be needed
```
