### ISSUE TITLE
Using checksum of uncompressed tarball.

### ISSUE THREAD

**Issue by isuruf** [conda/conda-build#3799]
### Actual Behavior

```meta.yaml
{% set version = '3.0.3' %}

package:
  name: mpi4py
  version: {{ version }}

source:
  url: https://bitbucket.org/mpi4py/mpi4py/downloads/mpi4py-{{ version }}.tar.gz
  sha256: 012d716c8b9ed1e513fcc4b18e5af16a8791f51e6d1716baccf988ad355c5a1f

build:
  number: 0

test: {}
```

Consider the above recipe. This fails with a checksum failure and conda-build says that the checksum should be `a9f8f549781a2757988eb536fd5f088d8b1f94c2a79ed9724c12f9a6f7d188d1`, but this is the checksum of the uncompressed tarball.

```bash
$ wget https://bitbucket.org/mpi4py/mpi4py/downloads/mpi4py-3.0.3.tar.gz 2> /dev/null
$ sha256sum mpi4py-3.0.3.tar.gz
012d716c8b9ed1e513fcc4b18e5af16a8791f51e6d1716baccf988ad355c5a1f  mpi4py-3.0.3.tar.gz
$ gzip -d mpi4py-3.0.3.tar.gz 
$ sha256sum mpi4py-3.0.3.tar
a9f8f549781a2757988eb536fd5f088d8b1f94c2a79ed9724c12f9a6f7d188d1  mpi4py-3.0.3.tar
```

If I use the URL from pypi, this works.

```YAML
{% set version = '3.0.3' %}
{% set name = "mpi4py" %}

package:
  name: mpi4py
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 012d716c8b9ed1e513fcc4b18e5af16a8791f51e6d1716baccf988ad355c5a1f

build:
  number: 0

test: {}
```

This looks like https://github.com/conda/conda/issues/3798

##### `Output of conda info`

```
     active environment : base
    active env location : /home/isuru/miniconda3
            shell level : 1
       user config file : /home/isuru/.condarc
 populated config files : /home/isuru/miniconda3/.condarc
                          /home/isuru/.condarc
          conda version : 4.7.11
    conda-build version : 3.18.9
         python version : 3.6.7.final.0
       virtual packages : 
       base environment : /home/isuru/miniconda3  (read only)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/isuru/miniconda3/pkgs
                          /home/isuru/.conda/pkgs
       envs directories : /home/isuru/.conda/envs
                          /home/isuru/miniconda3/envs
               platform : linux-64
             user-agent : conda/4.7.11 requests/2.22.0 CPython/3.6.7 Linux/4.15.0-66-generic ubuntu/18.04.3 glibc/2.27
                UID:GID : 1000:1000
             netrc file : /home/isuru/.netrc
           offline mode : False
```
