### ISSUE TITLE
Couldn't extract raw recipe text for <package> output

### ISSUE THREAD

**Issue by seanyen** [conda/conda-build#3860]
I am using `conda-build 3.18.11` and when I was working on a recipe with multiple outputs. `conda build` fails to continue with this error:

`Couldn't extract raw recipe text for <package> output`

And here is a minimum `meta.yml` to repro this issue.

```yaml
package:
  name: ros
  version: 0.0.1

source:
  - url: https://github.com/ros-gbp/catkin-release/archive/release/melodic/catkin/0.7.20-1.tar.gz
    folder: ros-melodic-catkin

build:
  number: 0

outputs:
- name: ros-melodic-catkin
  requirements:
    build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - cmake
    host:
    - rospkg
    - mock
    - empy
    - catkin_pkg
    - cmake
    - gmock
    - gtest
    - nose
    run:
    - mock
    - empy
    - catkin_pkg
    - cmake
    - gmock
    - gtest
    - nose
  script: bld_.bat

about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
  - seanyen
```

Output of `conda info`
```no-highlight
     active environment : base
    active env location : C:\Users\seanyen\AppData\Local\Continuum\miniconda3\envs\smithy
            shell level : 2
       user config file : C:\Users\seanyen\.condarc
 populated config files : C:\Users\seanyen\.condarc
          conda version : 4.8.2
    conda-build version : 3.18.11
         python version : 3.6.7.final.0
       virtual packages :
       base environment : C:\Users\seanyen\AppData\Local\Continuum\miniconda3\envs\smithy  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\seanyen\AppData\Local\Continuum\miniconda3\envs\smithy\pkgs
                          C:\Users\seanyen\.conda\pkgs
                          C:\Users\seanyen\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\seanyen\AppData\Local\Continuum\miniconda3\envs\smithy\envs
                          C:\Users\seanyen\.conda\envs
                          C:\Users\seanyen\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.8.2 requests/2.22.0 CPython/3.6.7 Windows/10 Windows/10.0.18362
          administrator : False
             netrc file : None
           offline mode : False
```

**Comment by seanyen** [comment]
I created a PR to address the problem I hit.

**Comment by seanyen** [comment]
It turned out the root cause is the indentation.

In my example, I didn't have any spaces in the beginning of the line `- name : xyz` for `outputs` section. And unfortunately, `conda-build` is sensitive to that and expects some spaces there.

Here is where it selects subpackages from the `outputs` section:
https://github.com/conda/conda-build/blob/881d73a8990c040f6496506ef4f06d4f4170e249/conda_build/metadata.py#L60

And here is an example how it is sensitive to the indentation:
https://regex101.com/r/yfP2B3/2

**Comment by DavidJVitale** [comment]
My team manages a CICD server that runs `conda build` every day to build our package -- we never had much issues, but this error started recently popping up intermittently for us. **The fix that I found was to add 3 dashes to the top of the file** (a [YAML directive](https://yaml.org/spec/1.1/#YAML%20directive/) ). 

So OP's `meta.yaml` would become something like this:


```yaml
---
package:
  name: ros
  version: 0.0.1

source:
  - url: https://github.com/ros-gbp/catkin-release/archive/release/melodic/catkin/0.7.20-1.tar.gz
    folder: ros-melodic-catkin

build:
...
```

From the bit of digging I did into `conda-build`'s source code, this is the line that was causing the failure: https://github.com/conda/conda-build/blob/363010b80c14c6d6e636592c2bd05fa6eff5e679/conda_build/metadata.py#L1314

https://github.com/conda/conda-build/blob/363010b80c14c6d6e636592c2bd05fa6eff5e679/conda_build/metadata.py#L1705

It has something to do with parsing the file, since the `raw_recipe_text` variable was being set to `""` in my case, which was causing the Exception to be thrown. Adding the three dashes caused that variable to be truthy because of a regex match.
