### ISSUE TITLE
Feature request: Expose test artifacts

### ISSUE THREAD

**Issue by teake** [conda/conda-build#3913]
I would like to request a feature that enables exposing artifacts produced during the test phase. The artifacts have to be readily accessible after the build and test of the package has been completed.

This could either be done by

* exposing the value of `--output-folder` as a variable in `meta.yaml` or as a environment variable during the build / test, or
* explicitly defining test artifacts in `meta.yaml` like so:
  
  ```yml
  test:
    artifacts:
      paths:
        - coverage-reports/*coverage-*.xml
        - xunit-reports/xunit-result-*.xml
  ```

  (Note: this is intentionally modeled like the [GitLab CI config file syntax](https://docs.gitlab.com/ee/ci/yaml/#artifacts).) The `paths` keyword is perhaps a bit YAGNI but it allows to easily add additional configuration under `artifacts`.

The reason I'm asking is that I'm currently trying to expose Python coverage and test reports generated during CI inside the test phase, so that I can import them into SonarQube.

Related discussions:

* https://gitter.im/conda/conda-build?at=5e482f550ec5ff431e94d924
* https://gitter.im/conda/conda-build?at=5e7a173723bb4937981c056d

**Comment by teake** [comment]
Btw, I currently have a workaround by doing

```yml
test:
  commands:
    - [...]
    - [ ! -z ${GITLAB_CI+x} ]; then
        coverage xml -i -o "${CI_PROJECT_DIR}/coverage.xml";
      fi
```
But that couples the testing phase tightly to the GitLab CI environment.

**Comment by mingwandroid** [comment]
It would be a cool feature, however it would require some tricky engineering because, as things stand, the final package is created before testing. It is also possible to re-run the tests on a package. What would you propose to do here if the artifacts already exist? Would you just overwrite or would you rotate them?

**Comment by teake** [comment]
My current use case is report generation during CI. So to be honest I do not care if old reports get overwritten -- I just want the latest and the greatest. That's also how coverage.py works, it silently overwrites previous reports. Don't know about other tools though. So my vote would be to keep it simple and not rotate them.

And I'm afraid I cannot really comment on the engineering bit without diving into the code. I do have a question about it though: shouldn't it be possible to deduce the path of the build conda package at test time? If that turns out to be hard, I would also be happy if the test artifacts could be placed relative to the current working directory in which `conda build` was called.

**Comment by mingwandroid** [comment]
The reason we engineered it so we can run the test phase separately from the build (and without having any build env or artifacts from the build around) is so that testing can be done at a later date in a different mix of packages. The official installers can be instructed to run their tests by passing '-t' at install time, for example.

So there is no such path in general to be deduced.

conda-build allows you to explicitly specify which files need to be bundled up for the test phase, but I don't *think* you can specify ones from the build env. This might be a nice feature but there would need to be some path relocation support implemented for it to be useful for people testing outside of building, otherwise we could consider to have another test section, in-build-tests (or end-of-build-tests), which are run well, at the end of the build. If we did this then your idea would complement it well!

**Comment by msarahan** [comment]
I think this might not be as hard as you're thinking, @mingwandroid. It could be as simple as:

```
test:
  copy_output_files:
    - relpath_glob/in/test/env
  copy_output_folder: some_abs_path  # optional; default to cwd where conda-build command was called. Can contain ~ so that it is more portable.
```

such that at the end of testing, before conda-build cleans up, it would try to copy or move files from the test env into some other location. path relocation might be nice to have, but probably not strictly necessary.

**Comment by teake** [comment]
Yes that would work for my use case. I think having an additional `--copy-output-folder` cli switch to override the meta.yaml key or the cwd default would be good. You'll often know where you want those files to go when you invoke `conda build`.

**Comment by mingwandroid** [comment]
We'd have to repackage the package after tests if any artifacts are created and stored though?

**Comment by teake** [comment]
Not as far as I'm concerned. In my case these test artifacts are transient and are immediately picked up by the CI runner and can be thrown away after that. They do not need to be stored in the conda package.

**Comment by teake** [comment]
FWIW, I have devised another workaround: determining the test directory from the test log and moving coverage report from there to the local dir. In my `.gitlab-ci.yml` I now have

```yml
my_conda_test_job:
  script:
    - conda build <previously_build_tarball> --test --keep-old-work | tee test.log
    - CONDA_TEST_SRC_DIR=$(grep -oP '^export SRC_DIR=\K.*$' test.log)
    - mv "$CONDA_TEST_SRC_DIR/coverage.xml" .
  artifacts:
    paths:
      - coverage.xml
```

It would be great if `$CONDA_TEST_SRC_DIR` (i.e. the directory from which the tests are run) could be set from an option switch of `conda build`.
