### ISSUE TITLE
Bundling pypi dependencies in conda build

### ISSUE THREAD

**Issue by edublancas** [conda/conda-build#3918]
Hi, I'm trying to make a recipe for an internal package. This package has dependencies only available in pypi.

I've been reading that one way to approach this problem is just to build recipes for all dependencies not available in conda, but I found a simpler approach in the [documentation](https://docs.conda.io/projects/conda-build/en/latest/user-guide/wheel-files.html).

Such example says that if the build command has `pip install`, all dependencies will become part of the package, for my use case, that's ok, I only want the recipe for internal distribution. However, my recipe is failing to install such dependencies.

My meta.yaml looks like this:

```yaml
package:
  name: some_package
  version: "some_version"

source:
  # the only difference between the example in the docs
  # and mine is that I'm building from source instead of a wheel
  path: ../src

build:
    # according to the docs, this should install all dependencies
    # declared in setup.py
    script: pip install .
   # Note: also tried using a build.sh file instead of this

requirements:
  host:
    - python
    - pip
  run:
    - python
    # ... other dependencies

test:
    import:
        # this passes
        - some_package
        # this does not, even though is declared in setup.py
        # under install_requires, only available in pypi
        - some_dependency

```

Looks like conda-build is implicitly ignoring my setup.py dependencies. Is this new behavior?

I also tried switching the build script to be `python setup.py install`

But I get an error "Setuptools downloading is disabled in conda build".

So it seems that `python setup.py install` is doing what I want (downloading dependencies) but conda-build is not allowing it, is there a way to override this?

I'm running conda-build 3.18.11 and conda 4.8.3

Thanks.
