### ISSUE TITLE
Testing the first subpackage is ignored

### ISSUE THREAD

**Issue by fcollonval** [conda/conda-build#3933]
### Actual Behavior

For recipe with multiple outputs, the first subpackage `test` section is ignored.
`conda-build` is reporting 

```
Nothing to test for: /file/to/package
```

### Expected Behavior

The subsection `test` of the first subpackage is honored.

### Steps to Reproduce

See https://github.com/conda-forge/matplotlib-feedstock/pull/238

More specifically:

[Nothing to test for: /home/conda/feedstock_root/build_artifacts/linux-64/matplotlib-base-3.2.1-py37h6ea8729_200.tar.bz2](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=136005&view=logs&j=4f922444-fdfe-5dcf-b824-02f86439ef14&t=937c195f-508d-5135-dc9f-d4b5730df0f7&l=3209)

Although the recipe states:
```yaml
    test:
      requires:
        - pytest
      imports:
        - matplotlib
        - matplotlib.pyplot
        - matplotlib._image
        - matplotlib._path
        - matplotlib._png
        - matplotlib._tri
        - matplotlib.backends._backend_agg
        - matplotlib.ft2font
        - matplotlib.ttconv
        - matplotlib.backends._tkagg  # [not win]
        - mpl_toolkits
        - pylab
```

##### `Output of conda info`

```
     active environment : base
    active env location : /opt/conda
            shell level : 1
       user config file : /home/conda/.condarc
 populated config files : /opt/conda/.condarc
                          /home/conda/.condarc
          conda version : 4.8.3
    conda-build version : 3.19.1
         python version : 3.7.6.final.0
       virtual packages : __glibc=2.12
       base environment : /opt/conda  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /opt/conda/pkgs
                          /home/conda/.conda/pkgs
       envs directories : /opt/conda/envs
                          /home/conda/.conda/envs
               platform : linux-64
             user-agent : conda/4.8.3 requests/2.23.0 CPython/3.7.6 Linux/4.15.0-1071-azure centos/6.10 glibc/2.12
                UID:GID : 1001:1001
             netrc file : None
           offline mode : False
```

Other example:  https://github.com/conda-forge/staged-recipes/pull/11280

A parade seems to build the first package outside the output and then use `run_exports` in the first outputs sub-packages as in https://github.com/conda-forge/lalinference-feedstock/blob/master/recipe/meta.yaml. But this does not seem coherent with the usage of `outputs` advertised in the documentation:

> This is an alternative to the existing behavior, not an addition to it.
