### ISSUE TITLE
Specifying {{ blas_impl }} in test-reqs only causes builds for each blas-variant

### ISSUE THREAD

**Issue by h-vetinari** [conda/conda-build#3947]
I'm hitting this in https://github.com/conda-forge/staged-recipes/pull/11337, where the package should in principle be compatible with all blas variants. However, I wanted to make sure that it's *tested* against all blas variants, and so I had a recipe along the lines of (simplified for illustration):

```
requirements:
  build:
    - {{ compiler('cxx') }}
    - [...]
  host:
    - python
    - [...]
    - libblas
    - liblapack
  run:
    - [...]
    - libblas
    - liblapack

test:
  requires:
    # make sure we test with all blas implementations
    - blas * *{{ blas_impl }}
    - [...]
  commands:
    - [run test suite]
```

This however causes a build for each blas-variant (staged-recipes builds `[py36, py37] x blas_impl`):
```
Solving environment: ...working... done
BUILD START: ['faiss-cpu-1.6.3-h4fbf4f8_0.tar.bz2', 'faiss-cpu-1.6.3-h9246793_0.tar.bz2', 'faiss-cpu-1.6.3-h0851671_0.tar.bz2', 'faiss-cpu-1.6.3-h810b19b_0.tar.bz2', 'faiss-cpu-1.6.3-h382abfb_0.tar.bz2', 'faiss-cpu-1.6.3-he41370b_0.tar.bz2']
```
and consequent warnings that there's overlap between the packages
```
Exact overlap between lib/python3.6/site-packages/faiss-1.6.3.dist-info/INSTALLER in packages faiss-cpu and faiss-cpu
WARNING conda_build.build:build(2162): Exact overlap between lib/python3.6/site-packages/faiss-1.6.3.dist-info/INSTALLER in packages faiss-cpu and faiss-cpu
[...]
```

If everything worked flawlessly, the added testing against the different blas-variants shouldn't be necessary, but as it turns out, there was at least one [bug](https://github.com/conda-forge/scipy-feedstock/issues/128) in `scipy` (resp. its packaging) uncovered by this.

All things considered, I'm thinking that crucial packages like numpy/scipy should probably err on the side of caution and test against all blas-variants, but this seems to be not possible currently without duplicating builds, hence this issue.
