### ISSUE TITLE
conda skeleton pypi click - fails dependencies - but doesnt list depends missing

### ISSUE THREAD

**Issue by marcusobrien** [conda/conda-build#3960]
### Actual Behavior
Trying to build "click" sample from conda build tutorials

(CIRQ_Quantum) C:\Users\marcu>conda skeleton pypi click

Two exceptions are thrown - the first fails on get_install_actions, its saying 
conda.exceptions.ResolvePackageNotFound:
  - python=None

Full traceback :

Traceback (most recent call last):
  File "H:\anaconda3\lib\site-packages\conda_build\environ.py", line 757, in get_install_actions
    actions = install_actions(prefix, index, specs, force=True)
  File "H:\anaconda3\lib\site-packages\conda\common\io.py", line 88, in decorated
    return f(*args, **kwds)
  File "H:\anaconda3\lib\site-packages\conda\plan.py", line 474, in install_actions
    txn = solver.solve_for_transaction(prune=prune, ignore_pinned=not pinned)
  File "H:\anaconda3\lib\site-packages\conda\core\solve.py", line 117, in solve_for_transaction
    should_retry_solve)
  File "H:\anaconda3\lib\site-packages\conda\core\solve.py", line 158, in solve_for_diff
    force_remove, should_retry_solve)
  File "H:\anaconda3\lib\site-packages\conda\core\solve.py", line 275, in solve_final_state
    ssc = self._add_specs(ssc)
  File "H:\anaconda3\lib\site-packages\conda\core\solve.py", line 555, in _add_specs
    explicit_pool = ssc.r._get_package_pool(self.specs_to_add)
  File "H:\anaconda3\lib\site-packages\conda\resolve.py", line 553, in _get_package_pool
    pool = self.get_reduced_index(specs)
  File "H:\anaconda3\lib\site-packages\conda\common\io.py", line 88, in decorated
    return f(*args, **kwds)
  File "H:\anaconda3\lib\site-packages\conda\resolve.py", line 574, in get_reduced_index
    explicit_specs, features = self.verify_specs(explicit_specs)
  File "H:\anaconda3\lib\site-packages\conda\resolve.py", line 288, in verify_specs
    raise ResolvePackageNotFound(bad_deps)
conda.exceptions.ResolvePackageNotFound:
  - python=None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "H:\anaconda3\Scripts\conda-skeleton-script.py", line 10, in <module>
    sys.exit(main())
  File "H:\anaconda3\lib\site-packages\conda_build\cli\main_skeleton.py", line 65, in main
    return execute(sys.argv[1:])
  File "H:\anaconda3\lib\site-packages\conda_build\cli\main_skeleton.py", line 61, in execute
    version=args.version, config=config)
  File "H:\anaconda3\lib\site-packages\conda_build\api.py", line 290, in skeletonize
    recursive=recursive, config=config, **kwargs)
  File "H:\anaconda3\lib\site-packages\conda_build\skeletons\pypi.py", line 319, in skeletonize
    setup_options=setup_options)
  File "H:\anaconda3\lib\site-packages\conda_build\skeletons\pypi.py", line 726, in get_package_metadata
    config=config)
  File "H:\anaconda3\lib\site-packages\conda_build\skeletons\pypi.py", line 1127, in get_pkginfo
    setup_options=setup_options)
  File "H:\anaconda3\lib\site-packages\conda_build\skeletons\pypi.py", line 1164, in run_setuppy
    subdir=config.host_subdir, clear_cache=False, config=config)
  File "H:\anaconda3\lib\site-packages\conda_build\environ.py", line 850, in create_env
    channel_urls=tuple(config.channel_urls))
  File "H:\anaconda3\lib\site-packages\conda_build\environ.py", line 759, in get_install_actions
    raise DependencyNeedsBuildingError(exc, subdir=subdir)
conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform win-64: {'python=None'}

### Steps to Reproduce

conda skeleton pypi click

##### `Output of conda info`

```
    active environment : CIRQ_Quantum
    active env location : H:\anaconda3\envs\CIRQ_Quantum
            shell level : 1
       user config file : C:\Users\marcu\.condarc
 populated config files : C:\Users\marcu\.condarc
          conda version : 4.8.2
    conda-build version : 3.18.11
         python version : 3.7.6.final.0
       virtual packages : __cuda=11.0
       base environment : H:\anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
                          https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : H:\anaconda3\pkgs
                          C:\Users\marcu\.conda\pkgs
                          C:\Users\marcu\AppData\Local\conda\conda\pkgs
       envs directories : H:\anaconda3\envs
                          C:\Users\marcu\.conda\envs
                          C:\Users\marcu\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.8.2 requests/2.22.0 CPython/3.7.6 Windows/10 Windows/10.0.18362
          administrator : False
             netrc file : None
           offline mode : False
```

**Comment by marcelotrevisani** [comment]
Yeah, ``conda-build skeleton`` needs a major refactoring.
For packages on ``pypi`` you might try to use [grayskull](https://github.com/marcelotrevisani/grayskull/) if you want to
in the future, the plan is to integrate it to skeleton

Using grayskull it will give you the following recipe
``grayskull pypi click``
```yaml
{% set name = "click" %}
{% set version = "7.1.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d2b5255c7c6349bc1bd1e59e08cd12acbbd63ce649f2588755783aa94dfb6b1a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python !=3.0,!=3.1,!=3.2,!=3.3,!=3.4
  run:
    - python !=3.0,!=3.1,!=3.2,!=3.3,!=3.4

test:
  imports:
    - click
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/click/
  summary: Composable command line interface toolkit
  license: BSD-3-Clause
  license_file: LICENSE.rst

```
