### ISSUE TITLE
Multiple outputs, initial solve partially wrong

### ISSUE THREAD

**Issue by wolfv** [conda/conda-build#3964]
I have recipes with many interdependent outputs and I _believe_ (but I am not 100% sure) that the initial render of the recipe doesn't take into account the other (dependent) outputs which leads to a state where the final creation of the environments doesn't have a valid solution. 

I think for example in this scenario it might fail:

```
- name: x
  depends:
    - a 0.1
- name: y
  depends:
    - b
    - x
```

Now if two versions of `b` exist that also depend on `a`, I believe the initial render might find a wrong solution for `y`

```
repodata

b 1.0
- depends: a 1.0
b 0.1
- depends: a 0.1
```

Now after the initial render, I believe the recipe of conda-build looks like:

```
- name: x
  depends:
    - a==0.1==HASH
- name: y
  depends:
    - b==1.0==HASH
    - x // doesn't pin
```

Now `y -> b 1.0 -> a 1.0` _and_ `x -> b 0.1 -> a -> 0.1` which conflicts.
However, I don't really have a good reproducer for this but someone with intricate knowledge of conda-build might be able to confirm this issue?

In my opinion, outputs should probably be treated as seperate recipes, and there should not be an initial render step for the entire `meta.yaml`.
