### ISSUE TITLE
Building recipe with source from git repo hangs

### ISSUE THREAD

**Issue by farleylai** [conda/conda-build#3977]
Trying to build from a Git repo but the build hangs indefinitely.
On the other hand, it works fine if the source is from PYPI.
Any ideas?

### Actual Behavior

`conda-build` makes no progress with the following message when building a recipe for [mmcv](https://github.com/open-mmlab/mmcv) from a Git source. However, if the source is PYPI, the build finishes as expected.

```sh
$> conda-build recipe

No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11
WARNING:conda_build.metadata:No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11
Cloning into '/home/ml/farleylai/miniconda3/envs/build37/conda-bld/mmcv_1593052184645/work'...
done.
checkout: 'HEAD'
Your branch is up-to-date with 'origin/_conda_cache_origin_head'.
==> git log -n1 <==

commit 69048ff056d1c34ef78fe6f55c63f663a62bb0c7
Author: Harry <hejm37@mail2.sysu.edu.cn>
Date:   Sat Jun 20 00:49:44 2020 +0800

    Specifying distributed training port in os.environ when training with slurm (#362)
    
    * feat: support for os.environ port for slurm training
    
    * fix: port data type
    
    * feat: add flawed unittest
    
    * feat: add flawed unittest
    
    * docs: add comments
    
    * fix: unittest
    
    * fix: unittest

==> git describe --tags --dirty <==

v0.6.1-2-g69048ff

==> git status <==

On branch _conda_cache_origin_head
Your branch is up-to-date with 'origin/_conda_cache_origin_head'.
nothing to commit, working directory clean

Adding in variants from internal_defaults
INFO:conda_build.variants:Adding in variants from internal_defaults
```

### Expected Behavior

To simply build the package successfully through the end.

### Steps to Reproduce

1. Just copy and save the following content in `recipe/meta.yaml`
2. `export RECIPE=mmcv conda-build recipe`

```yml
package:
  name: {{ RECIPE }}
  version: {{ environ.get('GIT_DESCRIBE_TAG', '').replace('v', '') }}

source:
  git_rev: {{ GIT_DESCRIBE_TAG }}
  git_url: https://github.com/open-mmlab/mmcv.git

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  {% if environ.get('GIT_DESCRIBE_NUMBER', '0') == '0' %}string: py{{ environ.get('PY_VER').replace('.', '') }}_0
  {% else %}string: py{{ environ.get('PY_VER').replace('.', '') }}_{{ environ.get('GIT_BUILD_STR', 'GIT_STUB') }}{% endif %}
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - cython
    - opencv
    - pip
    - pytest-runner
    - python=3.7
  run:
    - addict
    - numpy
    - opencv
    - python=3.7
    - pytorch
    - pyyaml
    - torchvision
    - yapf
test:
  requires:
    - pytest
  imports:
    - mmcv
    - mmcv.arraymisc
    - mmcv.cnn
    - mmcv.cnn.bricks
    - mmcv.fileio
    - mmcv.fileio.handlers
    - mmcv.image
    - mmcv.parallel
    - mmcv.runner
    - mmcv.runner.hooks
    - mmcv.runner.hooks.logger
    - mmcv.runner.optimizer
    - mmcv.utils
    - mmcv.video
    - mmcv.video.optflow_warp
    - mmcv.visualization

about:
  home: https://github.com/open-mmlab/mmcv
  license: Apache License
  license_family: APACHE
  summary: Composable command line interface toolkit
```

In comparison, the same recipe using the PYPI source is included as follows:

```sh
{% set version = "0.6.1" %}

package:
  name: {{ RECIPE }}
  version: {{ version }}

source:
  url: "https://pypi.io/packages/source/{{ RECIPE[0] }}/{{ RECIPE }}/{{ RECIPE }}-{{ version }}.tar.gz"
  sha256: 8f22e2be557ab267a042720c631e2bf9d6aaf3c266917c45f2dcb407db16ed1a

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - cython
    - opencv
    - pip
    - pytest-runner
    - python=3.7
  run:
    - addict
    - numpy
    - opencv
    - python=3.7
    - pytorch
    - pyyaml
    - torchvision
    - yapf
test:
  requires:
    - pytest
  imports:
    - mmcv
    - mmcv.arraymisc
    - mmcv.cnn
    - mmcv.cnn.bricks
    - mmcv.fileio
    - mmcv.fileio.handlers
    - mmcv.image
    - mmcv.parallel
    - mmcv.runner
    - mmcv.runner.hooks
    - mmcv.runner.hooks.logger
    - mmcv.runner.optimizer
    - mmcv.utils
    - mmcv.video
    - mmcv.video.optflow_warp
    - mmcv.visualization

about:
  home: https://github.com/open-mmlab/mmcv
  license: Apache License
  license_family: APACHE
  summary: Composable command line interface toolkit
```

### `Output of conda info`

```
     active environment : build37
    active env location : /home/ml/farleylai/miniconda3/envs/build37
            shell level : 2
       user config file : /home/ml/farleylai/.condarc
 populated config files : /home/ml/farleylai/.condarc
          conda version : 4.8.3
    conda-build version : 3.18.9
         python version : 3.7.3.final.0
       virtual packages : __cuda=10.1
                                      __glibc=2.23
       base environment : /home/ml/farleylai/miniconda3  (writable)
           channel URLs : 
                          https://conda.anaconda.org/pytorch/linux-64
                          https://conda.anaconda.org/pytorch/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /home/ml/farleylai/miniconda3/pkgs
                          /home/ml/farleylai/.conda/pkgs
       envs directories : /home/ml/farleylai/miniconda3/envs
                          /home/ml/farleylai/.conda/envs
               platform : linux-64
             user-agent : conda/4.8.3 requests/2.23.0 CPython/3.7.3 Linux/4.15.0-106-generic ubuntu/16.04.6 glibc/2.23
                UID:GID : 8531:3000
             netrc file : None
           offline mode : False
```
