### ISSUE TITLE
Activating Test Environment does not work under Windows

### ISSUE THREAD

**Issue by KevDi** [conda/conda-build#4037]
### Actual Behavior

I want to build my python library as a conda package using the `conda build .` command.

This is my `meta.yaml` File:

```yaml
{% set data = load_setup_py_data() %}

package:
  name: communicator
  version: {{ data['version'] }}

source:
  path: ..

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - python 3.8
    - pip
    - rdflib
  run:
    - python
    - rdflib
    - isodate

test:
  imports:
    - communicator

about:
  home: https://example.com
  summary: {{ data['description'] }}
  license: {{ data['license'] }}
  license_file: LICENSE
```

And this is my `setup.py` file:

```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from setuptools import setup

with open("README.rst") as readme_file:
    readme = readme_file.read()

with open("HISTORY.rst") as history_file:
    history = history_file.read()

requirements = ["rdflib"]

test_requirements = ["rdflib",]

setup(
    name="communicator",
    version="0.1.0",
    description="Package to query the Triple Store for Workflow Configuration Details.",
    long_description=readme + "\n\n" + history,
    author="name",
    author_email="mail",
    packages=["communicator",],
    package_dir={"communicator": "communicator"},
    include_package_data=True,
    install_requires=requirements,
    license="MIT license",
    zip_safe=False,
    keywords="communicator",
    classifiers=[
        "Development Status :: 2 - Pre-Alpha",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Natural Language :: English",
        "Programming Language :: Python :: 3.8",
    ],
    test_suite="tests",
    tests_require=test_requirements,
)
```

If i run the `conda build .` i got the following error:

```
set PREFIX=C:\Users\username\conda-bld\communicator_1599210681542\_test_env
set SRC_DIR=C:\Users\username\conda-bld\communicator_1599210681542\test_tmp

%SRC_DIR%>call "%SRC_DIR%\conda_test_env_vars.bat"

%SRC_DIR%>set "CONDA_SHLVL="   &&
Der Befehl "C:\Program" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.

%SRC_DIR%>conda activate "%PREFIX%"
(%PREFIX%) %SRC_DIR%>IF 0 NEQ 0 exit 1
```
In english the error is like the command "C:\Program" is spelled wrong or could not be found.
In my opinion it seems like there are some quotes are missing around the Path because `C:\Program File\` contains an whitespace and for that the command has to be quoted

##### `Output of conda info`

```
active environment : communicator
    active env location : C:\Users\user\.conda\envs\communicator
            shell level : 2
       user config file : C:\Users\user\.condarc
 populated config files : C:\Program Files\Anaconda3\.condarc
                          C:\Users\user\.condarc
          conda version : 4.7.12
    conda-build version : 3.18.8
         python version : 3.7.4.final.0
       virtual packages : __cuda=10.1
       base environment : C:\Program Files\Anaconda3  (read only)

          package cache : C:\ProgramData\conda-pkgs
       envs directories : C:\Users\user\.conda\envs
                          C:\Program Files\Anaconda3\envs
                          C:\Users\user\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.7.12 requests/2.22.0 CPython/3.7.4 Windows/10 Windows/10.0.17763
          administrator : False
             netrc file : None
           offline mode : False
```
