### ISSUE TITLE
presence of channel_alias in .condarc reorders channel priority during build

### ISSUE THREAD

**Issue by FaustinCarter** [conda/conda-build#4096]
### Actual Behavior

I am building a package that collects deps from several internal (non-public) package repositories. These channels are specified in the user condarc file with full URLs. Channel priority is also set to strict in the user condarc file. No other condarc files are populated.

The build works fine in this scenario. No problems.

However, if I then _add_ a `channel_alias` to my user condarc file, the build fails. After much debugging, it has become clear that adding the alias results in the channel priority order getting changed during the portion of the build process where the list of packages to be installed in the build env (spec) is generated. Then, when it tries to generate that new environment, it fails, because that list is incompatible with the strict priority setting. In other words, conda-build is generating a package list that is impossible for conda create to satisfy.

Relaxing the user condarc priority setting to flexible allows the build to continue, but my build environment has a different set of packages than it should.

Example condarc file for successful build:

```yaml
channel_priority: strict
channels:
  - https://repo.mysite.com/path/to/repos/channel1
  - https://repo.mysite.com/path/to/repos/channel2
  - https://repo.mysite.com/path/to/repos/channel3
  - https://repo.mysite.com/path/to/repos/channel4
```

Example of a condarc file that fails

```yaml
channel_priority: strict
channels:
  - https://repo.mysite.com/path/to/repos/channel1
  - https://repo.mysite.com/path/to/repos/channel2
  - https://repo.mysite.com/path/to/repos/channel3
  - https://repo.mysite.com/path/to/repos/channel4
channel_alias: https://repo.mysite.com/path/to/repos/
```

Modification that builds, but with packages from wrong channels (i.e. a package gets installed from channel2 that should come from channel1)

```yaml
channel_priority: flexible
channels:
  - https://repo.mysite.com/path/to/repos/channel1
  - https://repo.mysite.com/path/to/repos/channel2
  - https://repo.mysite.com/path/to/repos/channel3
  - https://repo.mysite.com/path/to/repos/channel4
channel_alias: https://repo.mysite.com/path/to/repos/
```

A condarc file that results in a successful build. Note that the `channel_alias` here is _not_ part of any of the existing channel URLs

```yaml
channel_priority: strict
channels:
  - https://repo.mysite.com/path/to/repos/channel1
  - https://repo.mysite.com/path/to/repos/channel2
  - https://repo.mysite.com/path/to/repos/channel3
  - https://repo.mysite.com/path/to/repos/channel4
channel_alias: https://some.othersite.com/repos/
```

For what it's worth, this also fails, which is very frustrating, because having the channel alias makes managing our infrastructure a bit simpler.

```yaml
channel_priority: strict
channels:
  - channel1
  - channel2
  - channel3
  - channel4
channel_alias: https://repo.mysite.com/path/to/repos/
```

It's worth mentioning that this bug _does not_ exist in the code that `conda create` uses to solve and create an env. It is local to conda-build. Why does conda-build reimplement this?

##### `Output of conda info`

```
     active environment : base
    active env location : C:\Users\username\CustomMiniconda
            shell level : 1
       user config file : C:\Users\username\.condarc
 populated config files : C:\Users\username\.condarc
          conda version : 4.8.5
    conda-build version : 3.20.3
         python version : 3.7.8.final.0
       virtual packages :
       base environment : C:\Users\username\CustomMiniconda  (writable)
           channel URLs : https://repo.mysite.com/path/to/channel1/win-64
                          https://repo.mysite.com/path/to/channel1/noarch
                          https://repo.mysite.com/path/to/channel2/win-64
                          https://repo.mysite.com/path/to/channel2/noarch
                          https://repo.mysite.com/path/to/channel3/win-64
                          https://repo.mysite.com/path/to/channel3/noarch
                          https://repo.mysite.com/path/to/channel4/win-64
                          https://repo.mysite.com/path/to/channel4/noarch
          package cache : C:\Users\username\CustomMiniconda
                          C:\Users\username\.conda\pkgs
                          C:\Users\username\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\username\CustomMiniconda
                          C:\Users\username\.conda\envs
                          C:\Users\username\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.8.5 requests/2.24.0 CPython/3.7.8 Windows/10 Windows/10.0.19041
          administrator : False
             netrc file : None
           offline mode : False
```
