### ISSUE TITLE
`conda render` has a problem with `GIT_*` variables on patched sources

### ISSUE THREAD

**Issue by ajelinski** [conda/conda-build#4118]
There is a bug in `conda-build` v3.20.4 and v3.20.5 which causes never-ending `conda render`. Funny thing is, there's no bug if you add `--verbose` (which unfortunately won't work for e.g. `conda render --output`).
`conda-build` v3.20.3 doesn't have such problems.

### Actual Behavior

Virtually never-ending rendering with output:
```
write() argument must be str, not bytes
write() argument must be str, not bytes
write() argument must be str, not bytes
write() argument must be str, not bytes
write() argument must be str, not bytes
write() argument must be str, not bytes
write() argument must be str, not bytes
write() argument must be str, not bytes
write() argument must be str, not bytes
```

### Expected Behavior

Rendered metadata should be sent to the `stdout`.

### Steps to Reproduce

1. Install `conda-build` v3.20.4 or v3.20.5
2. Create a directory with `meta.yaml`:
```
package:
  name: bsdiff4
  version: {{ GIT_DESCRIBE_TAG }}

source:
  git_url: https://github.com/ilanschnell/bsdiff4.git
  git_rev: 1.1.4
  patches:
    - test.patch
```
and `test.patch`:
```
diff --git a/README.rst b/README.rst
index ac92874..30c5ab4 100644
--- a/README.rst
+++ b/README.rst
@@ -2,6 +2,8 @@
 bsdiff4: binary diff and patch using the BSDIFF4-format
 =======================================================

+
+
 The code is mostly derived from cx_bsdiff (written by Anthony Tuininga,
 http://cx-bsdiff.sourceforge.net/).  The cx_bsdiff code in turn was derived
 from bsdiff, the standalone utility produced for BSD which can be found
```
3. Run `conda render .` in the created directory.

##### `Output of conda info`

Not applicable. Tested on a few versions of conda with different configurations on Linux and macOS.

**Comment by cgr71ii** [comment]
This problems still exists with conda build 3.21.4. When using GIT_* variables in `build: number:` or `build: string:`, some binaries are not correctly patched. BTW this bug is really annoying... It was really hard to find out that the problem was related to the use of environmental variables...

I will not open a new issue because I think that with the following example, which should work as expected (i.e. it fails), it will be clear that the problem might be the same.

Just in case: this problem was not happening in December of 2020 to me.

## Example
meta.yaml
```yaml
{% set name = "bitextor" %}
{% set version = "8" %}

package:
  name: "{{ name }}"
  version: "{{ version }}"

source:
  git_url: https://github.com/bitextor/bitextor/
  git_branch: snake_performance
  folder: "bitextor"

build:
  skip: True  # [not linux64]
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  string: {{ GIT_BUILD_STR }}
  preserve_egg_dir: True

requirements:
  build:
    - git
    - make=4.2.1
    - cmake=3.16.3
    - automake=1.16.1
    - pkg-config=0.29.1

    - gcc_linux-64=9.3.0
    - gxx_linux-64=9.3.0
    - go-cgo=1.13.5=h77d97cf_0
    - pip=20.2.4=py_0
    - python=3.8.5=h7579374_1
  run:
    - pip=20.2.4=py_0
    - python=3.8.5=h7579374_1

about:
  home: https://github.com/bitextor/bitextor/
  license: GPL3
  license_family: GPL3
  summary: Bitextor generates translation memories from multilingual websites
```

build.sh
```bash
echo -e "\e[4m\e[1mBuilding Bitextor...\e[0m"

# Go dependencies
echo -e " - \e[4mInstalling Go dependencies...\e[0m"
#mkdir "$SRC_DIR/gopath"
mkdir "$PWD/gopath"
go env
#export CGO_ENABLED="1"
#export GOPATH="$SRC_DIR/gopath"
export GOPATH="$PWD/gopath"
go get github.com/paracrawl/giawarc/...
go get github.com/paracrawl/giashard/...

# Copy src (not usual in builds, but we need src because we are using bash and python scripts)
cp -r "$SRC_DIR/gopath" "$PREFIX"

# Soft link (is necessary that is relative, not absolute)
cd "$PREFIX/bin"

### Other soft links
ln -s ../gopath/bin/giawarc ./giawarc || echo -e " - \e[31m\e[4mpost-build-act: could not create link 'giawarc'...\e[0m" # Warning: bitextor will look for giarwarc at ~/go/bin
ln -s ../gopath/bin/giashard ./giashard || echo -e " - \e[31m\e[4mpost-build-act: could not create link 'giashard'...\e[0m" # Warning: bitextor will look for giashard at ~/go/bin

# Restore initial working directory (trying to prevent errors)
cd "$SRC_DIR"

echo -e "\e[4m\e[1mBuild done!\e[0m"
```

Script to build
```bash
#!/bin/bash

usage()
{
  echo "make_conda_build [-h] [-e <CONDA_ENV_NAME>] [-r]"
  echo ""
  echo "OPTIONS:"
  echo "  -e <CONDA_ENV_NAME>     Name of the conda environment which will be used to build"
  echo "                          Bitextor. If not specified, the default value is"
  echo "                          \"bitextor-build\"."
  echo "  -r                      It removes the conda environment before start if exists."
  echo "  -h                      It displays this help message."
}

CONDA_ENV_NAME="bitextor-build"
REMOVE_ENV_IF_EXISTS=""

while getopts "e:rh" options
do
  case "${options}" in
    e) CONDA_ENV_NAME=$OPTARG;;
    r) REMOVE_ENV_IF_EXISTS="y";;
    h) usage
       exit 0;;
    \?) usage 1>&2
        exit 1;;
  esac
done

source $(conda info --base)/etc/profile.d/conda.sh

if [[ "$REMOVE_ENV_IF_EXISTS" == "y" ]]; then
  conda remove -y -n $CONDA_ENV_NAME --all
fi

if [[ "$(conda env list | grep ^$CONDA_ENV_NAME[\ +])" != "" ]]; then
  echo "Error: conda environment '$CONDA_ENV_NAME' already exists"
  echo
  usage 1>&2
  exit 1
fi

conda create -y -n $CONDA_ENV_NAME python=3.8.5
conda activate $CONDA_ENV_NAME

if [[ "$(conda config --show channels | grep conda-forge)" == "" ]]; then
  echo "Info: adding 'conda-forge' channel (remove it manually after the build is done if you want). This is common at fresh installations"
  conda config --add channels conda-forge
fi
if [[ "$(conda config --show channels | grep bioconda)" == "" ]]; then
  echo "Info: appending 'bioconda' channel (remove it manually after the build is done if you want)"
  conda config --append channels bioconda # snakemake
fi
if [[ "$(conda config --show channels | grep dmnapolitano)" == "" ]]; then
  echo "Info: appending 'dmnapolitano' channel (remove it manually after the build is done if you want)"
  conda config --append channels dmnapolitano # warcio
fi

conda config --show channels
conda install -y conda-build
conda install -y conda-verify

if [[ -f ./meta.yaml ]]; then
  conda-build --no-anaconda-upload .
else
  echo "File meta.yaml not found on current directory. Go to build directory and execute this script again."
fi
```

Commands to build and install:
```bash
conda deactivate && ./make_conda_build.sh -e go_test -r
rm -rf ~/miniconda3/envs/go_test_install && conda create -y -n go_test_install && conda activate go_test_install && conda install -y ~/miniconda3/envs/go_test/conda-bld/linux-64/bitextor-8-py38_0.tar.bz2 && conda update --all -y
```

Once the above commands have been run and the package has been installed, if you run `giashard` you will get a 'Segmentation Fault', what does not happen with `giawarc`. In the main project, this problem only affects to the binary `giashard`. When you get rid of `build: number:` and `build: string:`, everything is ok.
