### ISSUE TITLE
"Building conda packages from scratch" tutorial is confusing as written

### ISSUE THREAD

**Issue by rohanaras** [conda/conda-build#4164]
I wasn't sure if this is where I should put comments on the documentation—let me know if I should move it elsewhere.

Anyway the "[Editing the meta.yaml file]" section appears to contradict itself somewhat twice in the two following sentences:

> Save **the file** in the same `click` directory as `meta.yaml`. It should match [this meta.yaml file](https://docs.conda.io/projects/conda-build/en/latest/_downloads/d42b166defebcb482accb83c6edec8c9/meta.yaml).

If I understand correctly, the file in question (emphasis in quote mine) should be `meta.yaml`. In which case the following would make more sense:
> Save the newly created `meta.yaml` in the `click` directory from step 1.

The second sentence refers to a file that doesn't actually match what the tutorial instructs. The linked file contains
```yaml
{% set name = "click" %}
{% set version = "7.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5b94b49521f6456670fdb30cd82a4eca9412788a93fa6dd6df72c94d5a8ff2d7

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - click

about:
  home: https://palletsprojects.com/p/click/
  license: BSD
  license_family: BSD
  summary: Composable command line interface toolkit
```
vs the instructructed
```yaml
package:
  name: click
  version: 7.1.2

source:
  git_rev: 7.1.2
  git_url: https://github.com/pallets/click.git

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - click

about:
  home: https://github.com/pallets/click
```

Actually on a final note, step 2 of the same section provides a license to input into the sample `meta.yaml`, though the sample doesn't actually indicate that it should go under the `about` section.
