### ISSUE TITLE
Multi-output recipes might not run test suite in certain cases

### ISSUE THREAD

**Issue by h-vetinari** [conda/conda-build#4172]
The cvxpy-feedstock has been multi-output since @djsutherland's https://github.com/conda-forge/cvxpy-feedstock/pull/6 more than 2 years ago.

The recipe clearly specifies to run a test suite:
```
outputs:
  - name: cvxpy
    requirements:
      [...]
    test:
      imports:
        - [...]
      requires:
        - nose
      commands:
        - nosetests cvxpy
```

However, it seems this `commands` section was never run! Now that this was [discovered](https://github.com/conda-forge/cvxpy-feedstock/pull/46) today (and promptly [fixed](https://github.com/conda-forge/cvxpy-feedstock/pull/46/commits/e468f584beb551f9305946b2ac1189052da5607d) by @isuruf), it turns out that several packages have been shipping in a broken state for a long time, which is obviously... less than ideal.

The relation between the package-name and whether tests are run for sub-packages is also very confusing to me, but in any case, recipe maintainership (across many packages) is not reasonably possible without being able to trust that conda does something as fundamental as running the test section of the recipe _completely_.
