### ISSUE TITLE
The use of GIT_* environmental variables in meta.yaml makes patched binaries to fail

### ISSUE THREAD

**Issue by cgr71ii** [conda/conda-build#4195]
When using GIT_* variables in `build: number:` or `build: string:`, some binaries are not correctly patched. The issue #4118 might help to find the solution to this issue since it seems to be related due to the use of GIT_* environment variables.

Just in case: this problem was not happening in December of 2020 to me. The build was working correctly until it failed a few weeks ago without modifying anything.

BTW this bug is really annoying... It was really hard to find out that the problem was related to the use of environmental variables...

### Actual Behavior

Error "Segmentation Fault" with binary `giashard`, but not `giawarc` (it does not seem to be related to golang) and not any other binary of the project.

### Expected Behavior

The binary `giashard` should not throw any error, and `giashard --help` should show the help message.

### Steps to Reproduce

meta.yaml
```yaml
{% set name = "bitextor" %}
{% set version = "8" %}

package:
  name: "{{ name }}"
  version: "{{ version }}"

source:
  git_url: https://github.com/bitextor/bitextor/
  git_branch: snake_performance
  folder: "bitextor"

build:
  skip: True  # [not linux64]
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  string: {{ GIT_BUILD_STR }}
  preserve_egg_dir: True

requirements:
  build:
    - git
    - make=4.2.1
    - cmake=3.16.3
    - automake=1.16.1
    - pkg-config=0.29.1

    - gcc_linux-64=9.3.0
    - gxx_linux-64=9.3.0
    - go-cgo=1.13.5=h77d97cf_0
    - pip=20.2.4=py_0
    - python=3.8.5=h7579374_1
  run:
    - pip=20.2.4=py_0
    - python=3.8.5=h7579374_1

about:
  home: https://github.com/bitextor/bitextor/
  license: GPL3
  license_family: GPL3
  summary: Bitextor generates translation memories from multilingual websites
```

build.sh
```bash
echo -e "\e[4m\e[1mBuilding Bitextor...\e[0m"

# Go dependencies
echo -e " - \e[4mInstalling Go dependencies...\e[0m"
#mkdir "$SRC_DIR/gopath"
mkdir "$PWD/gopath"
go env
#export CGO_ENABLED="1"
#export GOPATH="$SRC_DIR/gopath"
export GOPATH="$PWD/gopath"
go get github.com/paracrawl/giawarc/...
go get github.com/paracrawl/giashard/...

# Copy src (not usual in builds, but we need src because we are using bash and python scripts)
cp -r "$SRC_DIR/gopath" "$PREFIX"

# Soft link (is necessary that is relative, not absolute)
cd "$PREFIX/bin"

### Other soft links
ln -s ../gopath/bin/giawarc ./giawarc || echo -e " - \e[31m\e[4mpost-build-act: could not create link 'giawarc'...\e[0m" # Warning: bitextor will look for giarwarc at ~/go/bin
ln -s ../gopath/bin/giashard ./giashard || echo -e " - \e[31m\e[4mpost-build-act: could not create link 'giashard'...\e[0m" # Warning: bitextor will look for giashard at ~/go/bin

# Restore initial working directory (trying to prevent errors)
cd "$SRC_DIR"

echo -e "\e[4m\e[1mBuild done!\e[0m"
```

Script to build (`make_conda_build.sh`)
```bash
#!/bin/bash

usage()
{
  echo "make_conda_build [-h] [-e <CONDA_ENV_NAME>] [-r]"
  echo ""
  echo "OPTIONS:"
  echo "  -e <CONDA_ENV_NAME>     Name of the conda environment which will be used to build"
  echo "                          Bitextor. If not specified, the default value is"
  echo "                          \"bitextor-build\"."
  echo "  -r                      It removes the conda environment before start if exists."
  echo "  -h                      It displays this help message."
}

CONDA_ENV_NAME="bitextor-build"
REMOVE_ENV_IF_EXISTS=""

while getopts "e:rh" options
do
  case "${options}" in
    e) CONDA_ENV_NAME=$OPTARG;;
    r) REMOVE_ENV_IF_EXISTS="y";;
    h) usage
       exit 0;;
    \?) usage 1>&2
        exit 1;;
  esac
done

source $(conda info --base)/etc/profile.d/conda.sh

if [[ "$REMOVE_ENV_IF_EXISTS" == "y" ]]; then
  conda remove -y -n $CONDA_ENV_NAME --all
fi

if [[ "$(conda env list | grep ^$CONDA_ENV_NAME[\ +])" != "" ]]; then
  echo "Error: conda environment '$CONDA_ENV_NAME' already exists"
  echo
  usage 1>&2
  exit 1
fi

conda create -y -n $CONDA_ENV_NAME python=3.8.5
conda activate $CONDA_ENV_NAME

if [[ "$(conda config --show channels | grep conda-forge)" == "" ]]; then
  echo "Info: adding 'conda-forge' channel (remove it manually after the build is done if you want). This is common at fresh installations"
  conda config --add channels conda-forge
fi
if [[ "$(conda config --show channels | grep bioconda)" == "" ]]; then
  echo "Info: appending 'bioconda' channel (remove it manually after the build is done if you want)"
  conda config --append channels bioconda # snakemake
fi
if [[ "$(conda config --show channels | grep dmnapolitano)" == "" ]]; then
  echo "Info: appending 'dmnapolitano' channel (remove it manually after the build is done if you want)"
  conda config --append channels dmnapolitano # warcio
fi

conda config --show channels
conda install -y conda-build
conda install -y conda-verify

if [[ -f ./meta.yaml ]]; then
  conda-build --no-anaconda-upload .
else
  echo "File meta.yaml not found on current directory. Go to build directory and execute this script again."
fi
```

Commands to build and install
```bash
conda deactivate && ./make_conda_build.sh -e go_test -r
rm -rf ~/miniconda3/envs/go_test_install && conda create -y -n go_test_install && conda activate go_test_install && conda install -y ~/miniconda3/envs/go_test/conda-bld/linux-64/bitextor-8-py38_0.tar.bz2 && conda update --all -y
```

Once the above commands have been run and the package has been installed, if you run giashard you will get a 'Segmentation Fault', what does not happen with giawarc. In the main project, this problem only affects to the binary giashard. When you get rid of build: number: and build: string:, everything is ok.
