### ISSUE TITLE
Negative matching 'files' for outputs

### ISSUE THREAD

**Issue by duncanmmacleod** [conda/conda-build#4196]
### Actual Behavior

There is currently no good way to exclude one or more files from being included in an output package that uses `files`.

### Expected Behavior

Support for some sort of negative match condition that is collected and applied _after_ the positive glob expressions are resolved. Anything analogous to the `%exclude` macro you can use in RPM spec files would be great.

Perhaps something as simple as a leading exclamation `!` would work:

```yaml
outputs:
  - name: mpyackage
    files:
      - bin/mypackage*
      - "!bin/mypackage-optional*"

  - name: mypackage-optional
    files:
      - bin/mypackage-optional
```

[AFAIK the exclamation is special in YAML, so it would have to be quoted always]

I'm happy to contribute to development, if other people think this is a good idea.
