### ISSUE TITLE
AttributeError when running conda skeleton

### ISSUE THREAD

**Issue by vvzen** [conda/conda-build#4227]
Hi all,

I'm getting an error when trying to run conda skeleton to build a local conda package for a repo that is on PyPI.
I'm gonna have a look myself since I've seen a few similar issues and maybe it's just due to how OpenTimelineIO is writing their requirements.
This is the traceback:

```
Traceback (most recent call last):
  File "/Users/vvzen/miniconda3/bin/conda-skeleton", line 11, in <module>
    sys.exit(main())
  File "/Users/vvzen/miniconda3/lib/python3.7/site-packages/conda_build/cli/main_skeleton.py", line 65, in main
    return execute(sys.argv[1:])
  File "/Users/vvzen/miniconda3/lib/python3.7/site-packages/conda_build/cli/main_skeleton.py", line 61, in execute
    version=args.version, config=config)
  File "/Users/vvzen/miniconda3/lib/python3.7/site-packages/conda_build/api.py", line 277, in skeletonize
    recursive=recursive, config=config, **kwargs)
  File "/Users/vvzen/miniconda3/lib/python3.7/site-packages/conda_build/skeletons/pypi.py", line 320, in skeletonize
    setup_options=setup_options)
  File "/Users/vvzen/miniconda3/lib/python3.7/site-packages/conda_build/skeletons/pypi.py", line 729, in get_package_metadata
    metadata.update(get_entry_points(pkginfo))
  File "/Users/vvzen/miniconda3/lib/python3.7/site-packages/conda_build/skeletons/pypi.py", line 1011, in get_entry_points
    "test_commands": make_entry_tests(entry_list)
  File "/Users/vvzen/miniconda3/lib/python3.7/site-packages/conda_build/skeletons/pypi.py", line 1265, in make_entry_tests
    entry = entry_point.partition('=')[0].strip()
AttributeError: 'list' object has no attribute 'partition'
```

### Expected Behavior

A conda package should get created

### Steps to Reproduce

`conda skeleton pypi opentimelineio`

##### Output of conda info

```
active environment : base
    active env location : /Users/vvzen/miniconda3
            shell level : 1
       user config file : /Users/vvzen/.condarc
 populated config files : /Users/vvzen/.condarc
          conda version : 4.10.1
    conda-build version : 3.21.4
         python version : 3.7.3.final.0
       virtual packages : __osx=10.14.6=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /Users/vvzen/miniconda3  (writable)
      conda av data dir : /Users/vvzen/miniconda3/etc/conda
  conda av metadata url : https://repo.anaconda.com/pkgs/main
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/vvzen/miniconda3/pkgs
                          /Users/vvzen/.conda/pkgs
       envs directories : /Users/vvzen/miniconda3/envs
                          /Users/vvzen/.conda/envs
               platform : osx-64
             user-agent : conda/4.10.1 requests/2.19.1 CPython/3.7.3 Darwin/18.7.0 OSX/10.14.6
                UID:GID : 501:20
             netrc file : /Users/vvzen/.netrc
           offline mode : False
```

**Comment by vvzen** [comment]
Turns out that `entry_list` is not just made of strings, but contains also another list:
```
['otioview = opentimelineview.console:main', 'otiocat = opentimelineio.console.otiocat:main', 'otioconvert = opentimelineio.console.otioconvert:main', 'otiostat = opentimelineio.console.otiostat:main', 'otiopluginfo = opentimelineio.console.otiopluginfo:main', ['otioautogen_serialized_schema_docs = opentimelineio.console.autogen_serialized_datamodel:main']]
 ```

**Comment by vvzen** [comment]
Went a bit deeper in this rabbit hole, this  is their pkginfo.yaml :

```
classifiers:
- 'Development Status :: 4 - Beta'
- 'Topic :: Multimedia :: Graphics'
- 'Topic :: Multimedia :: Video'
- 'Topic :: Multimedia :: Video :: Display'
- 'Topic :: Multimedia :: Video :: Non-Linear Editor'
- 'Topic :: Software Development :: Libraries :: Python Modules'
- 'License :: Other/Proprietary License'
- 'Programming Language :: Python :: 2'
- 'Programming Language :: Python :: 2.7'
- 'Programming Language :: Python :: 3'
- 'Programming Language :: Python :: 3.6'
- 'Programming Language :: Python :: 3.7'
- 'Operating System :: OS Independent'
- 'Natural Language :: English'
entry_points:
  console_scripts:
  - otioview = opentimelineview.console:main
  - otiocat = opentimelineio.console.otiocat:main
  - otioconvert = opentimelineio.console.otioconvert:main
  - otiostat = opentimelineio.console.otiostat:main
  - otiopluginfo = opentimelineio.console.otiopluginfo:main
  - - otioautogen_serialized_schema_docs = opentimelineio.console.autogen_serialized_datamodel:main
extras_require:
  dev:
  - flake8>=3.5
  - coverage>=4.5
  - tox>=3.0
  - urllib3>=1.24.3
  view:
  - PySide2~=5.11
home: http://opentimeline.io
install_requires:
- pyaaf2==1.4.0
license: Modified Apache 2.0 License
name: OpenTimelineIO
packages:
- opentimelineio
- opentimelineio.core
- opentimelineio.plugins
- opentimelineio.algorithms
- opentimelineio.adapters
- opentimelineio.schema
- opentimelineio.schemadef
- opentimelineio.console
- opentimelineview
- opentimelineio_contrib
- opentimelineio_contrib.adapters
- opentimelineio_contrib.adapters.aaf_adapter
setuptools: true
summary: Editorial interchange format and API
tests_require:
- mock;python_version<"3.3"
version: 0.13.0
```

That `- - ` line in the `entry_points` feels like a typo.
This is probably nothing on the conda side, feel free to close this issue!
