### ISSUE TITLE
[py3x] selector for x>6 are not implemented

### ISSUE THREAD

**Issue by chenghlee** [conda/conda-build#4297]
### Actual Behavior

Selectors like `[py37]` and `[py38]` do not function as most, if not all, users expect. Instead, unless overridden by an environment variable, they are silently treated as falsey, often producing surprising/confusing results (e.g., conda/conda#10975).

Granted, they are [not documented](https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#preprocessing-selectors) as actually existing, but since `py34`, `py35`, and `py36` do exist, it's not entirely unreasonable to assume that corresponding selectors exist for Python >=3.7.

### Expected Behavior

`py3x`-type selectors for Python 3.7 and above are implemented and set to `True` for the appropriate version. (See "Steps to Reproduce" below.)

### Steps to Reproduce

Test recipe `mypkg/recipe/meta.yaml`:
```
package:
    name: a_pkg
    version: 0.0.1

requirements:
  run:
    - dep_a =1.7  # [py==37]
    - dep_b =1.7  # [py37]
    - dep_c
```

`conda render --python=3.7 mypkg` currently yields (removing the irrelevant bits):
```
package:
  name: mypkg
  version: 1.0.0
requirements:
  run:
    - dep_b =1.7
    - dep_c
```
where I would expect:
```
package:
  name: mypkg
  version: 1.0.0
requirements:
  run:
    - dep_a =1.7
    - dep_b =1.7
    - dep_c
```

### Output of `conda info`

```
$ conda info

     active environment : base
    active env location : $CONDA_PREFIX
            shell level : 1
       user config file : $HOME/.condarc
 populated config files : $HOME/.condarc
          conda version : 4.10.3
    conda-build version : 3.21.5
         python version : 3.8.11.final.0
       virtual packages : __cuda=11.0=0
                          __linux=5.4.0=0
                          __glibc=2.27=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : $CONDA_PREFIX  (writable)
      conda av data dir : $CONDA_PREFIX/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : $CONDA_PREFIX/pkgs
                          $HOME/.conda/pkgs
       envs directories : $CONDA_PREFIX/envs
                          $HOME/.conda/envs
               platform : linux-64
             user-agent : conda/4.10.3 requests/2.26.0 CPython/3.8.11 Linux/5.4.0-87-generic ubuntu/18.04.6 glibc/2.27
                UID:GID : 1000:100
             netrc file : $HOME/.netrc
           offline mode : False
```
