### ISSUE TITLE
Bypass Checking on Conda Build?

### ISSUE THREAD

**Issue by achapkowski** [conda/conda-build#4339]
Condas is great, but it takes forever to do checking.  Is there a way to bypass this and live on the edge when using conda-build?

**Comment by kenodegard** [comment]
You can disable verification via `--no-verify`, is this what you are looking for?

**Comment by msarahan** [comment]
That's not verification. That's working to solve your recipe dependencies to actual packages instead of your abstract specifications. Can you post your recipe? It is likely that you have one or more conflicting dependencies, and that is what is making the solver struggle.

**Comment by achapkowski** [comment]
Here is the meta.yml
```
---
about:
  license: Apache 2.0
  summary: The Package Meta.yml
build:
  number: '0'
package:
  name: pygeopackage
  version: 2.0.0
requirements:
  build:
  - python >=3.7
  - cachetools
  - ujson >=3
  - setuptools
  - six
  - notebook
  - ipywidgets >7
  - widgetsnbextension >3
  - pandas >=1
  - numpy >=1.16.2
  - matplotlib
  - keyring <21.8.0
  - pytest
  - pyshp >=2
  - requests
  - requests-toolbelt
  - requests-kerberos
  - requests-oauthlib
  - requests_ntlm
  - requests-negotiate-sspi [win]
  - pywin32-security [win]
  - lerc
  - winkerberos      [win]
  - cryptography
  - lxml
  - certifi
  run:
  - python >=3.7
  - six
  - cachetools
  - notebook
  - ipywidgets >=7
  - widgetsnbextension >=3
  - pandas >=1
  - ujson >=3
  - numpy >=1.16.2
  - pyshp >=2
  - matplotlib
  - keyring >=19, <21.8.0
  - requests
  - requests-toolbelt
  - requests-kerberos
  - requests-oauthlib
  - requests_ntlm
  - requests-negotiate-sspi [win]
  - pywin32-security [win]
  - lerc
  - winkerberos      [win]
  - python-certifi-win32 [win]
  - cryptography
  - lxml
  - certifi
source:
  path: ../../src
```
