### ISSUE TITLE
Error: output metadata set is empty.  Please file an issue on the conda-build

### ISSUE THREAD

**Issue by ngam** [conda/conda-build#4362]
see https://github.com/conda-forge/staged-recipes/pull/17580

### Actual Behavior

```
$ CONFIG=linux64 ./.scripts/run_docker_build.sh
...
    assert out_metadata_map, ("Error: output metadata set is empty.  Please file an issue"
AssertionError: Error: output metadata set is empty.  Please file an issue on the conda-build tracker at https://github.com/conda/conda-build/issues

```

### Expected Behavior

Build-as-usual.

### Steps to Reproduce

see https://github.com/conda-forge/staged-recipes/pull/17580

##### ~`Output of conda info`~

```
$ CONFIG=linux64 ./.scripts/run_docker_build.sh
```

### Recipe

<details><summary>meta.yaml in full at the time of writing/issue</summary>
<p>

```yaml
{% set name = "mxnet" %}
{% set version = "v2.0.0.beta0.rc1" %}
{% set sha256 = "dfb741a07971b2607474b299ac880ba07e9fdaf217404c7d20bd5a4762324f26" %}
{% set build_number = "0" %}

package:
  name: {{ name }}-split
  version: {{ version }}

source:
  - url: https://github.com/apache/incubator-{{ name }}/archive/refs/tags/{{ version }}.tar.gz
    sha256: {{ sha256 }}
  # build as provided upstream:
  # see some discussion here:
  # https://github.com/apache/incubator-mxnet/issues/19610
  - url: https://github.com/dmlc/dmlc-core/archive/5df8305.tar.gz
    sha256: a8046f752f36005564d2924b4b6f73e1aea3cce7ff10f9e19d99ad6a22a045b2
    folder: 3rdparty/dmlc-core
  - url: https://github.com/dmlc/ps-lite/archive/34fd45c.tar.gz
    sha256: ec5d5baab8bbf0c3983ad5f18d7f963f15ae7cd4d154ec204b03c1dceccf209b
    folder: 3rdparty/ps-lite
  - url: https://github.com/dmlc/dlpack/archive/3efc489.tar.gz
    sha256: b59586ce69bcf3efdbf3cf4803fadfeaae4948044e2b8d89cf912194cf28f233
    folder: 3rdparty/dlpack
  - url: https://github.com/google/googletest/archive/eb9225c.tar.gz
    sha256: a4cb4b0c3ebb191b798594aca674ad47eee255dcb4c26885cf7f49777703484f
    folder: 3rdparty/googletest
  - url: https://github.com/apache/incubator-tvm/archive/efdac94.tar.gz
    sha256: 656c38d66baeab885b0212602148bb55ad3cf7d22f52ded8ece53f88e103a2f5
    folder: 3rdparty/tvm
  - url: https://github.com/onnx/onnx-tensorrt/archive/2eb74d9.tar.gz
    sha256: df99819727445c247fb5c21c2fd825ded3269376867457ae84fa6d6f1c0ae331
    folder: 3rdparty/onnx-tensorrt
  - url: https://github.com/NVlabs/cub/archive/0158fa1.tar.gz
    sha256: 43424c4c17a997d1d730c89ec14688671245de7941e02b388d7d3df6ea53777a
    folder: 3rdparty/nvidia_cub
  - url: https://github.com/nih-at/libzip/releases/download/v1.8.0/libzip-1.8.0.tar.gz
    sha256: 30ee55868c0a698d3c600492f2bea4eb62c53849bcf696d21af5eb65f3f3839e
    folder: 3rdparty/libzip
  - url: https://github.com/kpu/intgemm/archive/8f28282.tar.gz
    sha256: bc8bd8015613a13747eb769876385ec53e8c1ea7ae3f8414521dc53b8fcdfc65
    folder: 3rdparty/intgemm
  - url: https://github.com/oneapi-src/oneDNN/archive/f40443c.tar.gz
    sha256: da1dd1bb68ce3318db11e57971f975653e84adcb7d65cd879e558f2245e6de9a
    folder: 3rdparty/onednn

build:
  number: {{ build_number }}
  skip: True  # [not linux64]

outputs:

  - name: lib{{ name }}
    script: build_libmxnet.sh

    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ compiler('fortran') }}
        - make
        - cmake
        - ccache
        - llvm-openmp  # [osx]
        - libgomp  # [linux]

      host:
        # need to better expose these deps
        - openblas
        - mkl
        - opencv
        - onednn
      
      run:
        # ?

    test:
      imports:
      commands:
        - echo "testing later..." 

  - name: {{ name }}
    script: {{ PYTHON }} -m pip install ./python -vv

    requirements:
      build:
        - python
        - pip
        - setuptools
     
      host:
        - numpy >=1.17
        - requests >= 2.20.0,<3
        - graphviz <0.9.0
        - python_version <3.7
        - contextvars <3.7

      run:
        - numpy >=1.17
        - requests >= 2.20.0,<3
        - graphviz <0.9.0
        - python_version <3.7
        - contextvars <3.7

    test:
      imports:
      commands:
        - echo "testing later..." 

about:
  home: http://mxnet.io
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: MXNet is a deep learning framework designed for both efficiency and flexibility
  description: |
    Apache MXNet (incubating) is a deep learning framework designed for both
    efficiency and flexibility. It allows you to mix symbolic and imperative
    programming to maximize efficiency and productivity. At its core, MXNet
    contains a dynamic dependency scheduler that automatically parallelizes both
    symbolic and imperative operations on the fly. A graph optimization layer on
    top of that makes symbolic execution fast and memory efficient. MXNet is
    portable and lightweight, scaling effectively to multiple GPUs and multiple
    machines. MXNet is also more than a deep learning project. It is also a
    collection of blue prints and guidelines for building deep learning systems,
    and interesting insights of DL systems for hackers.
  doc_url: https://mxnet.incubator.apache.org/
  dev_url: https://github.com/apache/incubator-mxnet

extra:
  recipe-maintainers:
    - barry-jin  
    - ngam
  feedstock-name: mxnet
```

</p>
</details>

**Comment by jezdez** [comment]
This doesn't have enough context I'm afraid, could you please update the ticket with more information how to reproduce this?

**Comment by ngam** [comment]
> This doesn't have enough context I'm afraid, could you please update the ticket with more information how to reproduce this?

What kind of info would you like? Did you try to reproduce by making a meta.yaml file with the above recipe?

**Comment by ngam** [comment]
Would it help if I reproduce this in a staged-recipes again or would you like to be able to reproduce it in a different way?

**Comment by ngam** [comment]
This is all the context I could really provide: https://github.com/conda-forge/staged-recipes/pull/17929

**Comment by ngam** [comment]
I see, so I am out of my depth because of I abandoned what I was trying to achieve (splitting a recipe, etc.) and instead I went for one whole output in the recipe. 

Sorry if I am not clear or making your life harder; I am actually trying to help and following the prompt to file an issue :) 

I will trying to spell out the steps more thoroughly, but for now: https://github.com/conda-forge/staged-recipes/pull/17929 --- let me know if these details are enough or if you'd like me to try to say more. Also, please feel free to close this issue if you think it is some odd case (i.e. not useful to you, maintainers, here).

---

On staged-recipes:
1. fork the staged-recipes repo: (github.com/conda-forge/staged-recipes)
2. in a new folder (call it mxnet) copy meta.yaml
<details> 

```yaml
{% set name = "mxnet" %}
{% set version = "v2.0.0.beta0.rc1" %}
{% set sha256 = "dfb741a07971b2607474b299ac880ba07e9fdaf217404c7d20bd5a4762324f26" %}
{% set build_number = "0" %}

package:
  name: {{ name }}-split
  version: {{ version }}

source:
  - url: https://github.com/apache/incubator-{{ name }}/archive/refs/tags/{{ version }}.tar.gz
    sha256: {{ sha256 }}
  # build as provided upstream:
  # see some discussion here:
  # https://github.com/apache/incubator-mxnet/issues/19610
  - url: https://github.com/dmlc/dmlc-core/archive/5df8305.tar.gz
    sha256: a8046f752f36005564d2924b4b6f73e1aea3cce7ff10f9e19d99ad6a22a045b2
    folder: 3rdparty/dmlc-core
  - url: https://github.com/dmlc/ps-lite/archive/34fd45c.tar.gz
    sha256: ec5d5baab8bbf0c3983ad5f18d7f963f15ae7cd4d154ec204b03c1dceccf209b
    folder: 3rdparty/ps-lite
  - url: https://github.com/dmlc/dlpack/archive/3efc489.tar.gz
    sha256: b59586ce69bcf3efdbf3cf4803fadfeaae4948044e2b8d89cf912194cf28f233
    folder: 3rdparty/dlpack
  - url: https://github.com/google/googletest/archive/eb9225c.tar.gz
    sha256: a4cb4b0c3ebb191b798594aca674ad47eee255dcb4c26885cf7f49777703484f
    folder: 3rdparty/googletest
  - url: https://github.com/apache/incubator-tvm/archive/efdac94.tar.gz
    sha256: 656c38d66baeab885b0212602148bb55ad3cf7d22f52ded8ece53f88e103a2f5
    folder: 3rdparty/tvm
  - url: https://github.com/onnx/onnx-tensorrt/archive/2eb74d9.tar.gz
    sha256: df99819727445c247fb5c21c2fd825ded3269376867457ae84fa6d6f1c0ae331
    folder: 3rdparty/onnx-tensorrt
  - url: https://github.com/NVlabs/cub/archive/0158fa1.tar.gz
    sha256: 43424c4c17a997d1d730c89ec14688671245de7941e02b388d7d3df6ea53777a
    folder: 3rdparty/nvidia_cub
  - url: https://github.com/nih-at/libzip/releases/download/v1.8.0/libzip-1.8.0.tar.gz
    sha256: 30ee55868c0a698d3c600492f2bea4eb62c53849bcf696d21af5eb65f3f3839e
    folder: 3rdparty/libzip
  - url: https://github.com/kpu/intgemm/archive/8f28282.tar.gz
    sha256: bc8bd8015613a13747eb769876385ec53e8c1ea7ae3f8414521dc53b8fcdfc65
    folder: 3rdparty/intgemm
  - url: https://github.com/oneapi-src/oneDNN/archive/f40443c.tar.gz
    sha256: da1dd1bb68ce3318db11e57971f975653e84adcb7d65cd879e558f2245e6de9a
    folder: 3rdparty/onednn

build:
  number: {{ build_number }}
  skip: True  # [not linux64]

outputs:

  - name: lib{{ name }}
    script: build_libmxnet.sh

    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ compiler('fortran') }}
        - make
        - cmake
        - ccache
        - llvm-openmp  # [osx]
        - libgomp  # [linux]

      host:
        # need to better expose these deps
        - openblas
        - mkl
        - opencv
        - onednn
      
      run:
        # ?

    test:
      imports:
      commands:
        - echo "testing later..." 

  - name: {{ name }}
    script: {{ PYTHON }} -m pip install ./python -vv

    requirements:
      build:
        - python
        - pip
        - setuptools
     
      host:
        - numpy >=1.17
        - requests >= 2.20.0,<3
        - graphviz <0.9.0
        - python_version <3.7
        - contextvars <3.7

      run:
        - numpy >=1.17
        - requests >= 2.20.0,<3
        - graphviz <0.9.0
        - python_version <3.7
        - contextvars <3.7

    test:
      imports:
      commands:
        - echo "testing later..." 

about:
  home: http://mxnet.io
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: MXNet is a deep learning framework designed for both efficiency and flexibility
  description: |
    Apache MXNet (incubating) is a deep learning framework designed for both
    efficiency and flexibility. It allows you to mix symbolic and imperative
    programming to maximize efficiency and productivity. At its core, MXNet
    contains a dynamic dependency scheduler that automatically parallelizes both
    symbolic and imperative operations on the fly. A graph optimization layer on
    top of that makes symbolic execution fast and memory efficient. MXNet is
    portable and lightweight, scaling effectively to multiple GPUs and multiple
    machines. MXNet is also more than a deep learning project. It is also a
    collection of blue prints and guidelines for building deep learning systems,
    and interesting insights of DL systems for hackers.
  doc_url: https://mxnet.incubator.apache.org/
  dev_url: https://github.com/apache/incubator-mxnet

extra:
  recipe-maintainers:
    - ngam
  feedstock-name: mxnet
```

</details>

3. in the same folder, copy the .sh file
<details>

```bash
#!/bin/env bash

if [[ "$OSTYPE" == "darwin"* ]]; then
   export CXXFLAGS="${CXXFLAGS} -D_LIBCPP_DISABLE_AVAILABILITY"
   if [[ "$target_platform" == "osx-arm64" ]]; then
       cp config/distribution/darwin_cpu.cmake config.cmake
   else
       cp config/distribution/darwin_cpu_mkl.cmake config.cmake
       export MKL_INCLUDE_DIR=${CONDA_PREFIX}/include
   fi
elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
       # if want to add mkl to cuda builds:
       CMAKE_ARGS_BLAS=-DUSE_BLAS='mkl'
       export MKL_INCLUDE_DIR=${CONDA_PREFIX}/include
   if [[ "$cuda_compiler_version" == "None" ]]; then
       cp config/distribution/linux_cpu_mkl.cmake config.cmake
   elif [[ $cuda_compiler_version == 11.0 ]]; then
       cp config/distribution/linux_cu110.cmake config.cmake
       export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda/lib64/stubs
   elif [[ $cuda_compiler_version == 11.2 ]]; then
       cp config/distribution/linux_cu112.cmake config.cmake  
       export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda/lib64/stubs
       # setting LD_LIBRARY_PATH to potential fix future cuda builds. 
       # Details from CI runs (limited to 6 hours):
       # - run fails around 90% through cmake with around 5.5 hours
       # - complains about not finding `libnvidia-ml.so.1`
       # - we have `libnvidia-ml.so` in /usr/local/cuda/lib64/stubs
       # - we could maybe make symlink here too?
   fi
fi

rm -rf build; mkdir build && cd build

# consider adding: -DBUILD_SHARED_LIBS=ON \
# causing ps-lite to fail?
# need to maybe add ps-lite pkg to cf

cmake \
       -DCMAKE_PREFIX_PATH=$PREFIX \
       -DCMAKE_BUILD_TYPE=Release \
       -DCMAKE_INSTALL_LIBDIR="lib" \
       -DCMAKE_INSTALL_PREFIX=$PREFIX \
       -DCMAKE_INCLUDE_PATH=$PREFIX/include \
       -DUSE_CPP_PACKAGE=ON \
       -DUSE_OPENMP=ON \
       -DBLA_STATIC=OFF \
       ${CMAKE_ARGS_BLAS} \
       ${CMAKE_ARGS} \
..

make -j ${CPU_COUNT}
make install

# cd ../python

# if [[ "$OSTYPE" == "darwin"* ]]; then
#     export MXNET_LIBRARY_PATH=${PREFIX}/lib/libmxnet.dylib
# else
#     export MXNET_LIBRARY_PATH=${PREFIX}/lib/libmxnet.so
# fi

# export MXNET_INCLUDE_PATH=${PREFIX}/include/mxnet

# ${PYTHON} -m pip install . -vv

# #
# # if [[ "$OSTYPE" == "darwin"* ]]; then
# #     ln ${PREFIX}/lib/libmxnet.dylib $SP_DIR/mxnet/libmxnet.dylib
# #     find ${PREFIX} | grep libmxnet.dylib | grep -v $PREFIX/lib/libmxnet.dylib | xargs rm -f
# #
# # else
# #     ln ${PREFIX}/lib/libmxnet.so $SP_DIR/mxnet/libmxnet.so
# #     find ${PREFIX} | grep libmxnet.so | grep -v $PREFIX/lib/libmxnet.so | xargs rm -f
# #
# # fi
# #

# # Copy the [de]activate scripts to $PREFIX/etc/conda/[de]activate.d.
# # This will allow them to be run on environment activation.
# for CHANGE in "activate" "deactivate"
# do
#     mkdir -p "${PREFIX}/etc/conda/${CHANGE}.d"
#     cp "${RECIPE_DIR}/scripts/${CHANGE}.sh" "${PREFIX}/etc/conda/${CHANGE}.d/${PKG_NAME}_${CHANGE}.sh"
# done 
```

</details>

4. submit a PR to upstream
5. get error below

---

On a local machine:
1. fork the staged-recipes repo: (github.com/conda-forge/staged-recipes)
2. clone the repo locally
3. (optional) make a branch 
4. copy meta.yaml
<details> 

```yaml
{% set name = "mxnet" %}
{% set version = "v2.0.0.beta0.rc1" %}
{% set sha256 = "dfb741a07971b2607474b299ac880ba07e9fdaf217404c7d20bd5a4762324f26" %}
{% set build_number = "0" %}

package:
  name: {{ name }}-split
  version: {{ version }}

source:
  - url: https://github.com/apache/incubator-{{ name }}/archive/refs/tags/{{ version }}.tar.gz
    sha256: {{ sha256 }}
  # build as provided upstream:
  # see some discussion here:
  # https://github.com/apache/incubator-mxnet/issues/19610
  - url: https://github.com/dmlc/dmlc-core/archive/5df8305.tar.gz
    sha256: a8046f752f36005564d2924b4b6f73e1aea3cce7ff10f9e19d99ad6a22a045b2
    folder: 3rdparty/dmlc-core
  - url: https://github.com/dmlc/ps-lite/archive/34fd45c.tar.gz
    sha256: ec5d5baab8bbf0c3983ad5f18d7f963f15ae7cd4d154ec204b03c1dceccf209b
    folder: 3rdparty/ps-lite
  - url: https://github.com/dmlc/dlpack/archive/3efc489.tar.gz
    sha256: b59586ce69bcf3efdbf3cf4803fadfeaae4948044e2b8d89cf912194cf28f233
    folder: 3rdparty/dlpack
  - url: https://github.com/google/googletest/archive/eb9225c.tar.gz
    sha256: a4cb4b0c3ebb191b798594aca674ad47eee255dcb4c26885cf7f49777703484f
    folder: 3rdparty/googletest
  - url: https://github.com/apache/incubator-tvm/archive/efdac94.tar.gz
    sha256: 656c38d66baeab885b0212602148bb55ad3cf7d22f52ded8ece53f88e103a2f5
    folder: 3rdparty/tvm
  - url: https://github.com/onnx/onnx-tensorrt/archive/2eb74d9.tar.gz
    sha256: df99819727445c247fb5c21c2fd825ded3269376867457ae84fa6d6f1c0ae331
    folder: 3rdparty/onnx-tensorrt
  - url: https://github.com/NVlabs/cub/archive/0158fa1.tar.gz
    sha256: 43424c4c17a997d1d730c89ec14688671245de7941e02b388d7d3df6ea53777a
    folder: 3rdparty/nvidia_cub
  - url: https://github.com/nih-at/libzip/releases/download/v1.8.0/libzip-1.8.0.tar.gz
    sha256: 30ee55868c0a698d3c600492f2bea4eb62c53849bcf696d21af5eb65f3f3839e
    folder: 3rdparty/libzip
  - url: https://github.com/kpu/intgemm/archive/8f28282.tar.gz
    sha256: bc8bd8015613a13747eb769876385ec53e8c1ea7ae3f8414521dc53b8fcdfc65
    folder: 3rdparty/intgemm
  - url: https://github.com/oneapi-src/oneDNN/archive/f40443c.tar.gz
    sha256: da1dd1bb68ce3318db11e57971f975653e84adcb7d65cd879e558f2245e6de9a
    folder: 3rdparty/onednn

build:
  number: {{ build_number }}
  skip: True  # [not linux64]

outputs:

  - name: lib{{ name }}
    script: build_libmxnet.sh

    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ compiler('fortran') }}
        - make
        - cmake
        - ccache
        - llvm-openmp  # [osx]
        - libgomp  # [linux]

      host:
        # need to better expose these deps
        - openblas
        - mkl
        - opencv
        - onednn
      
      run:
        # ?

    test:
      imports:
      commands:
        - echo "testing later..." 

  - name: {{ name }}
    script: {{ PYTHON }} -m pip install ./python -vv

    requirements:
      build:
        - python
        - pip
        - setuptools
     
      host:
        - numpy >=1.17
        - requests >= 2.20.0,<3
        - graphviz <0.9.0
        - python_version <3.7
        - contextvars <3.7

      run:
        - numpy >=1.17
        - requests >= 2.20.0,<3
        - graphviz <0.9.0
        - python_version <3.7
        - contextvars <3.7

    test:
      imports:
      commands:
        - echo "testing later..." 

about:
  home: http://mxnet.io
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: MXNet is a deep learning framework designed for both efficiency and flexibility
  description: |
    Apache MXNet (incubating) is a deep learning framework designed for both
    efficiency and flexibility. It allows you to mix symbolic and imperative
    programming to maximize efficiency and productivity. At its core, MXNet
    contains a dynamic dependency scheduler that automatically parallelizes both
    symbolic and imperative operations on the fly. A graph optimization layer on
    top of that makes symbolic execution fast and memory efficient. MXNet is
    portable and lightweight, scaling effectively to multiple GPUs and multiple
    machines. MXNet is also more than a deep learning project. It is also a
    collection of blue prints and guidelines for building deep learning systems,
    and interesting insights of DL systems for hackers.
  doc_url: https://mxnet.incubator.apache.org/
  dev_url: https://github.com/apache/incubator-mxnet

extra:
  recipe-maintainers:
    - ngam
  feedstock-name: mxnet
```

</details>

5. copy the .sh file
<details>

```bash
#!/bin/env bash

if [[ "$OSTYPE" == "darwin"* ]]; then
   export CXXFLAGS="${CXXFLAGS} -D_LIBCPP_DISABLE_AVAILABILITY"
   if [[ "$target_platform" == "osx-arm64" ]]; then
       cp config/distribution/darwin_cpu.cmake config.cmake
   else
       cp config/distribution/darwin_cpu_mkl.cmake config.cmake
       export MKL_INCLUDE_DIR=${CONDA_PREFIX}/include
   fi
elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
       # if want to add mkl to cuda builds:
       CMAKE_ARGS_BLAS=-DUSE_BLAS='mkl'
       export MKL_INCLUDE_DIR=${CONDA_PREFIX}/include
   if [[ "$cuda_compiler_version" == "None" ]]; then
       cp config/distribution/linux_cpu_mkl.cmake config.cmake
   elif [[ $cuda_compiler_version == 11.0 ]]; then
       cp config/distribution/linux_cu110.cmake config.cmake
       export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda/lib64/stubs
   elif [[ $cuda_compiler_version == 11.2 ]]; then
       cp config/distribution/linux_cu112.cmake config.cmake  
       export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda/lib64/stubs
       # setting LD_LIBRARY_PATH to potential fix future cuda builds. 
       # Details from CI runs (limited to 6 hours):
       # - run fails around 90% through cmake with around 5.5 hours
       # - complains about not finding `libnvidia-ml.so.1`
       # - we have `libnvidia-ml.so` in /usr/local/cuda/lib64/stubs
       # - we could maybe make symlink here too?
   fi
fi

rm -rf build; mkdir build && cd build

# consider adding: -DBUILD_SHARED_LIBS=ON \
# causing ps-lite to fail?
# need to maybe add ps-lite pkg to cf

cmake \
       -DCMAKE_PREFIX_PATH=$PREFIX \
       -DCMAKE_BUILD_TYPE=Release \
       -DCMAKE_INSTALL_LIBDIR="lib" \
       -DCMAKE_INSTALL_PREFIX=$PREFIX \
       -DCMAKE_INCLUDE_PATH=$PREFIX/include \
       -DUSE_CPP_PACKAGE=ON \
       -DUSE_OPENMP=ON \
       -DBLA_STATIC=OFF \
       ${CMAKE_ARGS_BLAS} \
       ${CMAKE_ARGS} \
..

make -j ${CPU_COUNT}
make install

# cd ../python

# if [[ "$OSTYPE" == "darwin"* ]]; then
#     export MXNET_LIBRARY_PATH=${PREFIX}/lib/libmxnet.dylib
# else
#     export MXNET_LIBRARY_PATH=${PREFIX}/lib/libmxnet.so
# fi

# export MXNET_INCLUDE_PATH=${PREFIX}/include/mxnet

# ${PYTHON} -m pip install . -vv

# #
# # if [[ "$OSTYPE" == "darwin"* ]]; then
# #     ln ${PREFIX}/lib/libmxnet.dylib $SP_DIR/mxnet/libmxnet.dylib
# #     find ${PREFIX} | grep libmxnet.dylib | grep -v $PREFIX/lib/libmxnet.dylib | xargs rm -f
# #
# # else
# #     ln ${PREFIX}/lib/libmxnet.so $SP_DIR/mxnet/libmxnet.so
# #     find ${PREFIX} | grep libmxnet.so | grep -v $PREFIX/lib/libmxnet.so | xargs rm -f
# #
# # fi
# #

# # Copy the [de]activate scripts to $PREFIX/etc/conda/[de]activate.d.
# # This will allow them to be run on environment activation.
# for CHANGE in "activate" "deactivate"
# do
#     mkdir -p "${PREFIX}/etc/conda/${CHANGE}.d"
#     cp "${RECIPE_DIR}/scripts/${CHANGE}.sh" "${PREFIX}/etc/conda/${CHANGE}.d/${PKG_NAME}_${CHANGE}.sh"
# done 
```

</details>
6. try to build recipe: either with 
    a. python build-locally.py (need docker) or
    b. conda build recipes/mxnet (or whatever the folder is name; this needs conda-build)
7. get error below

--- 

The error: 

```
    assert out_metadata_map, ("Error: output metadata set is empty.  Please file an issue"
AssertionError: Error: output metadata set is empty.  Please file an issue on the conda-build tracker at https://github.com/conda/conda-build/issues

```

<details>

```
uilding mxnet with conda-forge/label/main
rendering /home/conda/staged-recipes-copy/recipes/mxnet for linux-64
Setting build arch. This is only useful when pretending to be on another arch, such as for rendering necessary dependencies on a non-native arch. I trust that you know what you're doing.
WARNING:conda_build.config:Setting build arch. This is only useful when pretending to be on another arch, such as for rendering necessary dependencies on a non-native arch. I trust that you know what you're doing.
WARNING conda_build.config:arch(317): Setting build arch. This is only useful when pretending to be on another arch, such as for rendering necessary dependencies on a non-native arch. I trust that you know what you're doing.
Setting build platform. This is only useful when pretending to be on another platform, such as for rendering necessary dependencies on a non-native platform. I trust that you know what you're doing.
WARNING:conda_build.config:Setting build platform. This is only useful when pretending to be on another platform, such as for rendering necessary dependencies on a non-native platform. I trust that you know what you're doing.
WARNING conda_build.config:platform(331): Setting build platform. This is only useful when pretending to be on another platform, such as for rendering necessary dependencies on a non-native platform. I trust that you know what you're doing.
Traceback (most recent call last):
  File "/home/conda/staged-recipes-copy/.ci_support/build_all.py", line 203, in <module>
    build_all(os.path.join(root_dir, "recipes"), args.arch)
  File "/home/conda/staged-recipes-copy/.ci_support/build_all.py", line 106, in build_all
    build_folders(recipes_dir, folders, arch, channel_urls)
  File "/home/conda/staged-recipes-copy/.ci_support/build_all.py", line 143, in build_folders
    G = construct_graph(recipes_dir, worker=worker, run='build',
  File "/home/conda/staged-recipes-copy/.ci_support/compute_build_graph.py", line 401, in construct_graph
    add_recipe_to_graph(recipe_dir, graph, run, worker, conda_resolve,
  File "/home/conda/staged-recipes-copy/.ci_support/compute_build_graph.py", line 219, in add_recipe_to_graph
    rendered = _get_or_render_metadata(recipe_dir, worker, config=config, finalize=finalize)
  File "/opt/conda/lib/python3.9/site-packages/conda/exports.py", line 189, in __call__
    return self.func(*args, **kw)
  File "/home/conda/staged-recipes-copy/.ci_support/compute_build_graph.py", line 210, in _get_or_render_metadata
    api.render(meta_file_or_recipe_dir, platform=platform, arch=arch,
  File "/opt/conda/lib/python3.9/site-packages/conda_build/api.py", line 49, in render
    for od, om in meta.get_output_metadata_set(
  File "/opt/conda/lib/python3.9/site-packages/conda_build/metadata.py", line 2086, in get_output_metadata_set
    assert out_metadata_map, ("Error: output metadata set is empty.  Please file an issue"
AssertionError: Error: output metadata set is empty.  Please file an issue on the conda-build tracker at https://github.com/conda/conda-build/issues
##[error]Bash exited with code '1'.
```

</details>
