### ISSUE TITLE
BUG: Regression for openssl recipe, regarding spurious circular dependence

### ISSUE THREAD

**Issue by h-vetinari** [conda/conda-build#4397]
Sometime between early January and early February**, the openssl-feedstock recipe stopped working on OSX.

It now raises:
```
  File "/Users/runner/miniforge3/lib/python3.9/site-packages/conda_build/metadata.py", line 1268, in ms_depends
    raise RuntimeError("%s cannot depend on itself" % self.name())
RuntimeError: openssl cannot depend on itself
```

These failures manifest in both https://github.com/conda-forge/openssl-feedstock/pull/83 and https://github.com/conda-forge/openssl-feedstock/pull/84.

I cannot tell where this is coming from, but assumed it might have something to do with the run-export. Therefore I tried
```diff
diff --git a/recipe/meta.yaml b/recipe/meta.yaml
index 83fbae5..04399d8 100644
--- a/recipe/meta.yaml
+++ b/recipe/meta.yaml
@@ -28,7 +28,7 @@ outputs:
       run_exports:
         # openssl's versioning used to be X.Y.Z(rev), but is MAJOR.MINOR.PATCH since 3.0.0;
         # see https://www.openssl.org/policies/releasestrat.html
-        - {{ pin_subpackage('openssl', max_pin='x') }}
+        - {{ pin_compatible('openssl', max_pin='x') }}
     requirements:
       build:
         - {{ compiler('c') }}
```
but this didn't change the error. Same for setting `feedstock-name: openssl` (and rerendering).

** between [this](https://github.com/conda-forge/openssl-feedstock/runs/4727823675) and [that](https://github.com/conda-forge/openssl-feedstock/runs/5047865649) CI run. The latter was _before_ https://github.com/conda-forge/conda-build-feedstock/pull/172 was merged, so I don't think it has something to do with the 3.21.8 release, but conda-build is still where the breakage manifests itself, hence the issue here.

<details>
<summary><code>openssl-feedstock/recipe/meta.yaml</code></summary>

Most recent version from https://github.com/conda-forge/openssl-feedstock/pull/84

```
{% set version = "3.0.2" %}

package:
  name: openssl_split
  version: {{ version }}

source:
  url: http://www.openssl.org/source/openssl-{{ version }}.tar.gz
  sha256: 98e91ccead4d4756ae3c9cde5e09191a8e586d9f4d50838e7ec09d6411dfdb63

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - nasm               # [win]
    - make               # [unix]
    - perl *
  # Empty host section to ensure that this is identified as cb3
  host:

outputs:
  - name: openssl
    build:
      no_link: lib/libcrypto.so.3.0  # [linux]
      no_link: lib/libcrypto.3.0.dylib  # [osx]
      run_exports:
        # openssl's versioning used to be X.Y.Z(rev), but is MAJOR.MINOR.PATCH since 3.0.0;
        # see https://www.openssl.org/policies/releasestrat.html
        - {{ pin_subpackage('openssl', max_pin='x') }}
    requirements:
      build:
        - {{ compiler('c') }}
        - make
        - perl *
      # Empty host section to ensure that this is identified as cb3
      host:
      run:
        - ca-certificates
    script: install_openssl.sh  # [unix]
    script: install_openssl.bat  # [win]
    test:
      commands:
        - copy NUL checksum.txt        # [win]
        - touch checksum.txt           # [unix]
        - openssl sha256 checksum.txt

  - name: libopenssl-static
    requirements:
      build:
        - {{ compiler('c') }}
    script: install_libopenssl-static.sh  # [unix]
    script: install_libopenssl-static.bat  # [win]
    test:
      commands:
        - test -f ${PREFIX}/lib/libcrypto.a                   # [unix]
        - test -f ${PREFIX}/lib/libssl.a                      # [unix]
        - if exist %LIBRARY_PREFIX%\lib\libcrypto_static.lib (exit 0) else (exit 1)  # [win]
        - if exist %LIBRARY_PREFIX%\lib\libssl_static.lib (exit 0) else (exit 1)     # [win]

about:
  home: http://www.openssl.org/
  license_file: LICENSE.txt
  license: Apache-2.0
  license_family: Apache
  summary: OpenSSL is an open-source implementation of the SSL and TLS protocols
  dev_url: https://github.com/openssl/openssl
  doc_url: https://www.openssl.org/docs/man3.0/

extra:
  recipe-maintainers:
    - jakirkham
    - msarahan
    - ocefpaf
    - pelson
    - carlodri
```
</details>
