### ISSUE TITLE
Overriding zip keys in local cbc.yaml not working as expected

### ISSUE THREAD

**Issue by tobijk** [conda/conda-build#4403]
### The following setup

aggregate/conda_build_config.yaml:
```
numpy:
  # python 3.7-3.9
  - 1.16    # [not (osx and arm64)]
  - 1.16    # [not (osx and arm64)]
  - 1.16    # [not (osx and arm64)]
  # python 3.8-3.9
  - 1.19    # [osx and arm64]
  - 1.19    # [osx and arm64]
  # python 3.10
  - 1.21
python:
  - 3.7      # [not arm64]
  - 3.8
  - 3.9
  - 3.10
zip_keys:
  -
    - python
    - numpy
```

dummy-feedstock/recipe/build.sh:
```
#!/bin/bash -e

echo "Building..."

cat << "EOF" >> "$PREFIX/bin/hello-world.py"
#!/usr/bin/env python

import sys
sys.write("Hello, World!\n")
EOF
```

dummy-feedstock/recipe/meta.yaml:
```
package:
  name: dummy
  version: 1

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - python
  host:
    - python
    - numpy
  run:
    - python

about:
  home: https://example.com
  summary: Dummy package
```

dummy-feedstock/recipe/conda_build_config.yaml:
```
numpy:
  # python 3.7-3.9
  - 1.17    # [linux64 or ppc64le or (osx and x86) or win]
  - 1.17    # [linux64 or ppc64le or (osx and x86) or win]
  - 1.17    # [linux64 or ppc64le or (osx and x86) or win]
  # python 3.7-3.9
  - 1.19    # [aarch64 or s390x]
  - 1.19    # [aarch64 or s390x]
  - 1.19    # [aarch64 or s390x]
  # python 3.8-3.9
  - 1.19    # [osx and arm64]
  - 1.19    # [osx and arm64]
  # python 3.10
  - 1.21
```

### Steps to reproduce

Using the provided global conda_build_config.yaml, run conda build for this feedstock on linux-64.

### Expected result

Packages are built for Python versions 3.7, 3.8, 3.9 and 3.10.

### Actual Result

Only the package for Python 3.10 is built.

### Tasks
- [x] #4519
- [ ] Determine whether conda-build is doing the "right" thing
- [ ] Propose a solution
