### ISSUE TITLE
List support in the about fields: dev_url, doc_url, license...

### ISSUE THREAD

**Issue by cbouss** [conda/conda-build#4447]
### Summary

When filling the about section, there are sometimes more than one relevant link applying to, let's say dev_url.
Likewise, a package, xz for example, may have parts covered by different licenses. 
home, license, license_family, license_file, doc_url, dev_url should support list values to provide the most accurate information to end users.
At the moment, this is rendered like this:
`<td>{% if [record.dev](http://record.dev/)_url %}<a href="{{ [record.dev](http://record.dev/)_url }}">dev</a>{% endif %}</td>
`

ca-certificates example:
```
about:
  home: https://curl.se/docs/caextract.html
  license: MPL-2.0
  license_file: LICENSE.txt
  license_family: Other
  summary: Certificates for use with other packages.
  doc_url: https://github.com/curl/curl/blob/master/docs/SSLCERTS.md
  dev_url: # mk-ca-bundle converts certdata.txt to cacert.pem
    - https://github.com/curl/curl/blob/master/scripts/mk-ca-bundle.pl
    - https://hg.mozilla.org/releases/mozilla-release/raw-file/default/security/nss/lib/ckfw/builtins/certdata.txt
```

xz example:
```
about:
  home: https://tukaani.org/xz/
  license: 
    - LGPL-2.1-or-later
    - GPL-2.0-or-later
  license_file: COPYING
  license_family: 
    - GPL2
    - LGPL
  summary: Data compression software with high compression ratio
  description: |
    XZ Utils is free general-purpose data compression software with a high
    compression ratio. XZ Utils were written for POSIX-like systems, but also
    work on some not-so-POSIX systems.
  doc_url: https://tukaani.org/xz/
  doc_source_url: https://github.com/xz-mirror/xz/blob/master/README
  dev_url: https://git.tukaani.org/
```
