### ISSUE TITLE
Unsatisfiable dependencies for platform linux-64: `{"pillow[version='9.3.0,9.4.0']"}`

### ISSUE THREAD

**Issue by divastar** [conda/conda-build#4770]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

working on latest containers : centos7, ubuntu
after creating conda python=3.9 env,installing conda and conda-build 
`conda-build -c conda-forge -c conda .`
with `meta.yaml`:

```
package:
  name: clip
  version: "1.0"

source:
  git_url: https://github.com/openai/CLIP.git
  git_rev: "main"

requirements:
  build:
    - ftfy==6.1.1
    - numpy==1.20.3
    - packaging==21.3
    - pillow==9.3.0
    - regex==2022.10.31
    - tokenizers==0.13.2
    - transformers==4.26.0
    - wcwidth==0.2.6
    - pytorch=1.7.1=cpu_py39h6a09485_0
    - tokenizers==0.13.2
    - ftfy==6.1.1
    - pillow==9.3.0
    - transformers==4.26.0
    - wcwidth==0.2.6
    - regex==2022.10.31
    - packaging==21.3
  run:
    - ftfy==6.1.1
    - numpy==1.20.3
    - packaging==21.3
    - pillow==9.3.0
    - regex==2022.10.31
    - tokenizers==0.13.2
    - transformers==4.26.0
    - wcwidth==0.2.6
    - pytorch=1.7.1=cpu_py39h6a09485_0
    - tokenizers==0.13.2
    - ftfy==6.1.1
    - pillow==9.4.0
    - transformers==4.26.0
    - wcwidth==0.2.6
    - regex==2022.10.31
    - packaging==21.3

    
build:
  script: |
    python setup.py install

test:
  imports:
    - clip

about:
  home: https://github.com/openai/CLIP
  license: MIT
```

always comes out with this error:
```
conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform linux-64: {"pillow[version='9.3.0,9.4.0']"}
```

### Conda Info

```shell
active environment : myenv
    active env location : /root/anaconda3/envs/myenv
            shell level : 2
       user config file : /root/.condarc
 populated config files :
          conda version : 23.1.0
    conda-build version : 3.23.3
         python version : 3.9.13.final.0
       virtual packages : __archspec=1=x86_64
                          __glibc=2.35=0
                          __linux=5.10.16.3=0
                          __unix=0=0
       base environment : /root/anaconda3  (writable)
      conda av data dir : /root/anaconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /root/anaconda3/pkgs
                          /root/.conda/pkgs
       envs directories : /root/anaconda3/envs
                          /root/.conda/envs
               platform : linux-64
             user-agent : conda/23.1.0 requests/2.28.1 CPython/3.9.13 Linux/5.10.16.3-microsoft-standard-WSL2 ubuntu/22.04.1 glibc/2.35
                UID:GID : 0:0
             netrc file : None
           offline mode : False
```

### Conda Config

```shell
gave nothing
```

### Conda list

```shell
# packages in environment at /root/anaconda3/envs/myenv:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    defaults
_openmp_mutex             5.1                       1_gnu    defaults
beautifulsoup4            4.11.1           py39h06a4308_0    defaults
brotlipy                  0.7.0           py39h27cfd23_1003    defaults
bzip2                     1.0.8                h7b6447c_0    defaults
ca-certificates           2023.01.10           h06a4308_0    defaults
certifi                   2022.12.7        py39h06a4308_0    defaults
cffi                      1.15.1           py39h5eee18b_3    defaults
chardet                   4.0.0           py39h06a4308_1003    defaults
charset-normalizer        2.0.4              pyhd3eb1b0_0    defaults
conda                     23.1.0           py39h06a4308_0    defaults
conda-build               3.23.3           py39h06a4308_0    defaults
conda-package-handling    2.0.2            py39h06a4308_0    defaults
conda-package-streaming   0.7.0            py39h06a4308_0    defaults
cryptography              38.0.4           py39h9ce1e76_0    defaults
filelock                  3.9.0            py39h06a4308_0    defaults
glob2                     0.7                pyhd3eb1b0_0    defaults
icu                       58.2                 he6710b0_3    defaults
idna                      3.4              py39h06a4308_0    defaults
jinja2                    3.1.2            py39h06a4308_0    defaults
ld_impl_linux-64          2.38                 h1181459_1    defaults
libarchive                3.6.2                hab531cd_0    defaults
libffi                    3.4.2                h6a678d5_6    defaults
libgcc-ng                 11.2.0               h1234567_1    defaults
libgomp                   11.2.0               h1234567_1    defaults
liblief                   0.12.3               h6a678d5_0    defaults
libstdcxx-ng              11.2.0               h1234567_1    defaults
libxml2                   2.9.14               h74e7548_0    defaults
lz4-c                     1.9.4                h6a678d5_0    defaults
markupsafe                2.1.1            py39h7f8727e_0    defaults
ncurses                   6.4                  h6a678d5_0    defaults
openssl                   1.1.1s               h7f8727e_0    defaults
patch                     2.7.6             h7b6447c_1001    defaults
patchelf                  0.17.2               h6a678d5_0    defaults
pip                       22.3.1           py39h06a4308_0    defaults
pkginfo                   1.8.3            py39h06a4308_0    defaults
pluggy                    1.0.0            py39h06a4308_1    defaults
psutil                    5.9.0            py39h5eee18b_0    defaults
py-lief                   0.12.3           py39h6a678d5_0    defaults
pycosat                   0.6.4            py39h5eee18b_0    defaults
pycparser                 2.21               pyhd3eb1b0_0    defaults
pyopenssl                 22.0.0             pyhd3eb1b0_0    defaults
pysocks                   1.7.1            py39h06a4308_0    defaults
python                    3.9.16               h7a1cb2a_0    defaults
python-libarchive-c       2.9                pyhd3eb1b0_1    defaults
pytz                      2022.7           py39h06a4308_0    defaults
pyyaml                    6.0              py39h5eee18b_1    defaults
readline                  8.2                  h5eee18b_0    defaults
requests                  2.28.1           py39h06a4308_0    defaults
ripgrep                   13.0.0               hbdeaff8_0    defaults
ruamel.yaml               0.17.21          py39h5eee18b_0    defaults
ruamel.yaml.clib          0.2.6            py39h5eee18b_1    defaults
setuptools                65.6.3           py39h06a4308_0    defaults
six                       1.16.0             pyhd3eb1b0_1    defaults
soupsieve                 2.3.2.post1      py39h06a4308_0    defaults
sqlite                    3.40.1               h5082296_0    defaults
tk                        8.6.12               h1ccaba5_0    defaults
toml                      0.10.2             pyhd3eb1b0_0    defaults
toolz                     0.12.0           py39h06a4308_0    defaults
tqdm                      4.64.1           py39h06a4308_0    defaults
tzdata                    2022g                h04d1e81_0    defaults
urllib3                   1.26.14          py39h06a4308_0    defaults
wheel                     0.37.1             pyhd3eb1b0_0    defaults
xz                        5.2.10               h5eee18b_1    defaults
yaml                      0.2.5                h7b6447c_0    defaults
zlib                      1.2.13               h5eee18b_0    defaults
zstandard                 0.18.0           py39h5eee18b_0    defaults
zstd                      1.5.2                ha4553b6_0    defaults
(
```
