### ISSUE TITLE
How to remove run requirements imposed by host requirements?

### ISSUE THREAD

**Issue by sdebionne** [conda/conda-build#4889]
From the doc:

> Some build or host [Requirements section](https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html?highlight=static%20libraries#requirements) will impose a runtime requirement.

How to remove these run requirements, when the target that requires it not part of the package? Is something like the following possible?

```yml
requirements:
  run:
    hdf5 # Used by some ancillary tool that we dont need in the package
  run:
    hdf5 None
```

Note: I recognize that the main issue is the flexibility of the build system of the project, that should allow more options to disable the unnecessary builds, but it's not always possible to hack it around...
