### ISSUE TITLE
Detect glibc version and warn if compiling on recent Ubuntu/Debian

### ISSUE THREAD

**Issue by bkreider** [conda/conda-build#503]
Centos6 is still a very popular platform, but you'll see this if someone has compiled a conda package on ubuntu/debian, that you try to run on Centos6.

```
/lib64/libc.so.6: version `GLIBC_2.14' not found
```

A perfect answer isn't very easy, but if we can warn people how to make it run most places.  The problem is the package maintainer/builder won't see this problem until far later when someone installs on Centos6.  If we can warn them immediately, they can plan for failures on Centos6 or other systems.

**Comment by xguse** [comment]
This glibc issue is driving me crazy.  I agree.  If when I build my packages I was warned which ones were going to kill me later when I try to load them on older hpc clusters, I would find other ways to do things.  This may ultimately be what keeps me from using conda for what I thought I was going to be able to use it for: SANE package management across systems.  So far it is turning out to be causing me much more heartache than just building everything on the system I was going to use it on like i was doing before.  I know its not a simple fix, but it certainly IS negating the promise of not having to care if/what compilers are on the target system.

**Comment by msarahan** [comment]
Not sure if this helps at all, but on Windows, we are having to compile specifically for each MSVC version.  We are achieving this with conda features.  Perhaps something similar could be used here?

See, for example: https://github.com/groutr/anaconda/blob/f941afd16c5f27faab0dbf747bdfbc492613b8e9/packages/hdf5/meta.yaml

**Comment by ericdill** [comment]
@msarahan that is a dead link

**Comment by xguse** [comment]
@ericdill, One thing that mitigates this a little for me is writing a recipe for glibc that basically clones my version and installs it in the conda env ([my recipe](https://github.com/xguse/conda-recipes/tree/f/personal_repo/glibc-2.22) adapted from @asmeurer's [recipe](https://github.com/conda/conda-recipes/tree/master/glibc)).  This is basically a bit of a kludge.  It means that the packages __I__ build for myself on my machine will usually run where ever I put them as long as I install ___my___ glibc in the env.  For me this seems to fix most of my issues but does not solve the issue of my packages being used on a more generic basis by other people.  But it might fix your pain if your main use-case is to make sure you can build your software once and use it where ever you need it to with the least wasted time?

Gus

**Comment by msarahan** [comment]
@ericdill sorry, that's not a dead link, it's a private one.  I don't have a public example right now.

Here's a paste from a simple recipe:

```
package:
  name: blosc
  version: 1.7.0

source:
  git_url: https://github.com/Blosc/c-blosc
  git_tag: v1.7.0

build:
  number: 1
  features:
    - vc9     [win and py27]
    - vc10    [win and py34]
    - vc14    [win and py35]

requirements:
  build:
    # HACK: this is here to get Windows features (vc??) to work
    - python  [win]
    - cmake

about:
  home: https://github.com/FrancescAlted/blosc
  license: MIT
  summary: Blosc data compressor

```

The HACK part is that only the Python package actually tracks the feature.  This is simpler overall, but certainly less explicit.  This is necessary if, for example, a library consumes other libraries that have features, but does not include anything that otherwise tracks the features.  If you do not add some mechanism for tracking, it will not look for the tracked feature, and it will either find an old build and maybe work, or not find a build at all and fail to build completely.
