### ISSUE TITLE
add `conda mambabuild` subcommand to aid transitioning away from `boa`

### ISSUE THREAD

**Issue by AaronOpfer** [conda/conda-build#5351]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

Add a subcommand to `conda` called `mambabuild` which is equivalent to performing `conda build --solver=libmamba`.

### Why is this needed?

My company wants to upgrade to the latest stable versions of `conda` and `conda-build`. We also want to off-board `boa` as it appears to a concluded project (development has switched to `rattler-build`).

However, my company has developed a large number of pipelines that invoke `mamba mambabuild` to get the build performance to an acceptable level. This was well before `conda` itself added the `--solver=libmamba` option.

If we attempt to upgrade `conda` and `conda-build` to the latest versions and remove `boa`, then all of these pipelines will break. We lack the CI robots that made this easy to fix for conda-forge.

### What should happen?

Performing:
```
conda mambabuild ...
```
should be equivalent to performing:
```
conda build --solver=libmamba ...
```
for a generous transition period.

### Additional Context

We discussed this in-person at the Conda open source room at PyCon 2024 with @wolfv and @beeankha and others.

**Comment by jaimergp** [comment]
conda-build could export a new subcommand plugin for this, setting the right context variables. I don't know if this might result into conflicts with boa's mambabuild subcommand (who wins a `conda mambabuild` parsing battle?). Safest way would be to implement this in a separate package that simply provides the right kind of subcommand plugin and can be safely uninstalled if problematic.

**Comment by AaronOpfer** [comment]
Yes, I agree that a separate package would work well.

**Comment by jaimergp** [comment]
This would be all the Python code you need:

In let's say `conda_mambabuild.py`:


```python
from conda import plugins
from conda.common.io import env_var

def mambabuild(*args):
    from conda_build.cli.main_build import execute

    with env_var("CONDA_SOLVER", "libmamba"):
        return execute(*args)

@plugins.hookimpl
def conda_subcommands():
    yield plugins.CondaSubcommand(
        name="mambabuild",
        summary="Run conda-build with forced solver=libmamba.",
        action=mambabuild,
    )
```

And then in your pyproject.toml:

```toml
[project.entry-points.conda]
conda-mambabuild = "conda_mambabuild"
```

**Comment by AaronOpfer** [comment]
That does indeed appear to work.
```yaml
package:
  name: fakeboa
  version: 0.0.1

source:
  path: .

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
  run:
    - python
    - conda
  run_constrained:
    - boa > 999.999.999
```

**Comment by AaronOpfer** [comment]
Ah, actually, playing around with this package installed in the base envrionment alongside conda 24.1.2 and mamba 1.5.7, `mamba mambabuild .` says:
```
$ mamba mambabuild x
Currently, only install, create, list, search, run, info, clean, remove, update, repoquery, activate and deactivate are supported through mamba.
```
so it seems as though I am missing some additional fakery.

**Comment by wolfv** [comment]
you wrote `mamba mambabuild` (did that ever work?)

**Comment by AaronOpfer** [comment]
Yes, most of my company's CI scripts invoke `mamba mambabuild recipe_dir/`, which works on conda 23.5.2 mamba 1.4.9 boa 0.14.0.

**Comment by AaronOpfer** [comment]
I have gotten it to work, but I had to ditch conda plugins and instead create a script named `conda-mambabuild` in `bin/`. It looks like this is necessary, as it allows `p.parse_args()` in `mamba`'s `do_call` to immediately pass execution to this binary through some mechanism that I do not understand, whereas the conda plugin instead returned a `argparse.Namespace` and then failed later on inside mamba.

`fakeboa/__init__.py`
```python
from conda.common.io import env_var


def main():
    from conda_build.cli.main_build import main

    with env_var("CONDA_SOLVER", "libmamba"):
        main()
```

`pyproject.toml`
```toml
[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "fakeboa"
version = "0.0.4"

[tool.setuptools]
packages = ["fakeboa"]

[project.scripts]
conda-mambabuild = "fakeboa:main"
```

`recipe/meta.yaml`
```yaml
package:
  name: fakeboa
  version: 0.0.4

source:
  path: ..

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - setuptools
    - python
    - pip
  run:
    - python
    - conda
  run_constrained:
    - boa > 999.999.999

test:
  import:
    - fakeboa
```
