### ISSUE TITLE
BUG: multi-output recipe fails to find one of its own outputs

### ISSUE THREAD

**Issue by h-vetinari** [conda/conda-build#5467]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

While trying to build https://github.com/conda-forge/autoawq-feedstock/pull/13, I'm running into a strange error:
```
BUILD START: ['autoawq_kernels-0.0.7-haac14e3_0.conda', 'autoawq-0.2.6-py312h3d36782_0.conda', 'autoawq-eval-0.2.6-pyhd8ed1ab_0.conda']
Reloading output folder: ...working... done
Solving environment (_h_env): ...working... failed
WARNING: failed to get package records, retrying.  exception was: Unsatisfiable dependencies for platform linux-64: {MatchSpec("autoawq_kernels=0.0.7[build=haac14e3_0]")}
Encountered problems while solving:
  - nothing provides requested autoawq_kernels 0.0.7.* haac14e3_0
```
Notice how `autoawq_kernels-0.0.7-haac14e3_0` appears under the list of packages being built, and immediately fails to be found. It is specified (as usual) using `pin_subpackage`:
```yaml
  - name: autoawq
    build:
      script:  {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
    requirements:
      build:
      host:
        - python
        - {{ pin_subpackage('autoawq_kernels', exact=True) }}
```

I've "saved" a state of the branch [here](https://github.com/h-vetinari/autoawq-feedstock/tree/bug) that reproduces the bug with conda-build 24.7.1.

### Conda Info

```shell
conda-forge CI
```

### Conda Config

```shell
conda-forge CI
```

### Conda list

```shell
conda-forge CI
```
