### ISSUE TITLE
git_url and Versioneer don't work together

### ISSUE THREAD

**Issue by richardotis** [conda/conda-build#552]
I'm not sure if this is a conda-build or Versioneer bug. This is my meta.yaml:
```
package:
  name: pycalphad
  version: {{ environ.get('GIT_DESCRIBE_TAG', 'failed')}}

source:
  git_url: https://github.com/richardotis/pycalphad.git
  git_tag: 0.2

requirements:
  build:
    - python
    - setuptools
    - matplotlib
    - pandas
    - nose
    - mock
    - xray
    - sympy
    - pyparsing
    - tinydb
    - scipy
    - numpy >=1.9

  run:
    - python
    - matplotlib
    - pandas
    - xray
    - sympy
    - pyparsing
    - tinydb
    - scipy
    - numpy >=1.9

test:
  # Python imports
  imports:
    - pycalphad
    - pycalphad.core
    - pycalphad.io
    - pycalphad.plot
    - pycalphad.plot.projections

about:
  home: https://github.com/richardotis/pycalphad
  license: MIT
  summary: 'CALPHAD tools for designing thermodynamic models, calculating phase diagrams and investigating phase equilibria.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
```

My build steps are to use `conda build --python 2.7 .` and then `conda install --use-local pycalphad`. Everything will build and install correctly, and the package is named with the correct version. However, if I `import pycalphad` and `print pycalphad.__version__`, I get `0+unknown`, indicating the _version.py isn't getting replaced with a static version.

If I change my meta.yaml to pull from PyPI, I get the expected behavior.
