### ISSUE TITLE
requirements/number is valid

### ISSUE THREAD

**Issue by pelson** [conda/conda-build#561]
I just had a moment, and did:

```
package:
   ...

requirements:
  number: 1
  build:
    - ...
```

But actually meant:

```
package:
   ...

build:
   number: 1

requirements:
  build:
    - ...
```

Unlike most other things, conda-build didn't care. It would be sensible to add some validation of the contents of requirements...
