### ISSUE TITLE
Git version is fetched too late for --skip-existing

### ISSUE THREAD

**Issue by frol** [conda/conda-build#574]
If I use `git_url` with version detection from git tags in combination with `conda build --skip-existing`, conda-build checks wrong package version for existence.

Here is a sample of a recipe:

```yaml
package:
  name: mypackage
  version: {{ environ.get('GIT_DESCRIBE_TAG', 'current') }}

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}

source:
  git_url: <git-repo>
  #path: ../
```

```
$ conda build --skip-existing ./conda.recipe
Fetching package metadata: ..................
mypackage-current-py27_0 is already built, skipping.
```

It should clone/copy sources and discover git env variables before it checks if a package version already exists.
