### ISSUE TITLE
Multi-line `script` values not behaving properly

### ISSUE THREAD

**Issue by mcg1969** [conda/conda-build#644]
The recipe below operates properly. However, as you can see, its `script` commands are rather long, so I wanted to take advantage of YAML's line continuation capability to clean it up.

However, if I split them up as follows, `conda build` on Linux seems to miss the final line of its recipe, and therefore does nothing during the build process. On the other hand, if I swap the `osx` and `linux` versions, it works just fine on Linux, and fails on Mac.

```
  script: CVXOPT_BUILD_GLPK=1 CVXOPT_BUILD_FFTW=1
        CVXOPT_GLPK_INC_DIR=$PREFIX/include CVXOPT_FFTW_INC_DIR=$PREFIX/include
        CVXOPT_BLAS_LIB='openblas' CVXOPT_LAPACK_LIB='openblas'
        python setup.py install [linux]
  script: CVXOPT_BUILD_GLPK=1 CVXOPT_BUILD_FFTW=1
        CVXOPT_GLPK_INC_DIR=$PREFIX/include CVXOPT_FFTW_INC_DIR=$PREFIX/include
        python setup.py install [osx]
```

```
package:
  name: cvxopt
  version: 1.1.8

source:
  git_url: https://github.com/cvxopt/cvxopt/
  git_rev: 1.1.8

requirements:
  build:
    - python
    - setuptools
    - openblas [linux]
    - glpk
    - fftw
  run:
    - python
    - openblas [linux]
    - glpk
    - fftw

build:
  number: 0
  script: CVXOPT_BUILD_GLPK=1 CVXOPT_BUILD_FFTW=1 CVXOPT_GLPK_INC_DIR=$PREFIX/include CVXOPT_FFTW_INC_DIR=$PREFIX/include CVXOPT_BLAS_LIB='openblas' CVXOPT_LAPACK_LIB='openblas' python setup.py install [linux]
  script: CVXOPT_BUILD_GLPK=1 CVXOPT_BUILD_FFTW=1 CVXOPT_GLPK_INC_DIR=$PREFIX/include CVXOPT_FFTW_INC_DIR=$PREFIX/include python setup.py install [osx]

about:
  home: http://cvxopt.org
  license: 'GNU General Public License 3.0'
  summary: 'CVXOPT is a free software package for convex optimization based on the Python programming language. It can be used with the interactive Python interpreter, on the command line by executing Python scripts, or integrated in other software via Python extension modules. Its main purpose is to make the development of software for convex optimization applications straightforward by building on Python’s extensive standard library and on the strengths of Python as a high-level programming language.'
```
