### ISSUE TITLE
`python` or `python_d` command does not work inside "test: commands:"

### ISSUE THREAD

**Issue by tadeu** [conda/conda-build#646]
In Windows, if I add commands like this to `meta.yaml`:

``` yaml
test:
  commands:
    - python -m something something
```

`conda build` won't find `python.exe` or `python_d.exe`, because they are in the environment root (`%PREFIX%`), and this isn't on `PATH`.
