### ISSUE TITLE
Features during conda-build tests

### ISSUE THREAD

**Issue by rmcgibbo** [conda/conda-build#656]
I think there might be an issue where conda-build does not correctly deal with features during the test step.

On win-64, I tried to make a minimal test case with

```
# meta.yaml
package:
  name: test
  version: "0.1"

build:
  features:
    - vc10

requirements:
  run:
    - hdf5

test:
  requires:
    - hdf5
  commands:
    - echo "hello"
```

Running the latest release of conda-build against (running in a py34 Miniconda3 root env) I get

```
TEST START: test-0.1-vc10_0
Fetching package metadata: ........
Solving package specifications: .....
Error: Unsatisfiable package specifications.
Generating hint:
[      COMPLETE      ]|##################################################| 100%

Hint: 'test' has unsatisfiable dependencies (see 'conda info test')
```

But conda search shows that the hdf5 package does have vc10-feature builds.

```
PS C:\Users\Administrator> conda search hdf5
Fetching package metadata: ......
hdf5                         1.8.9                         0  defaults
                             1.8.13                        0  defaults
                          .  1.8.15.1                      2  defaults
                             1.8.15.1                  vc9_3  defaults        [vc9]
                             1.8.15.1                 vc14_3  defaults        [vc14]
                          *  1.8.15.1                 vc10_3  defaults        [vc10]
```
