### ISSUE TITLE
selector and comment in one line: " ... [True] # comment" does not work

### ISSUE THREAD

**Issue by jankatins** [conda/conda-build#698]
When I try to add a patch like this

```
source:
  path: ../../

  patches:
    # don't run nosetest
    - cfg_notests.patch
    - osx-tk.patch        [osx] # test
```

[The first work, the second patch does not]

I get an error:

```
Applying patch: u'c:\\data\\external\\matplotlib\\ci\\conda_recipe\\osx-tk.patch        [osx]'
Error: no such patch: c:\data\external\matplotlib\ci\conda_recipe\osx-tk.patch        [osx]
```

This is unintuitive, as for me the selector is an active element (and it works if the selector is on a line without a trailing comment!) and comments work, so I expect(ed) that "patch followed by selector followed by comment" should also work.

It seems that the regex in https://github.com/conda/conda-build/blob/master/conda_build/metadata.py#L69 only understands `"   xxx.patch #[True] text"`
