### ISSUE TITLE
versioneer as getting the version

### ISSUE THREAD

**Issue by JanSchulz** [conda/conda-build#714]
matplotlibs setup.py is quite involved and it would be nice if there would be a way to get the version from versioneer instead of using the following:

```
{% set data = load_setuptools() %}
package:
   name: my_package
   version: {{ data.get('version') }}
```

```
{% set version = load_versioneer() %}
package:
   name: my_package
   version: {{ version  }}
```

The command could be more or less similar to the one in `load_setuptools()` (untested):

```
def load_versioneer()
    #Add current directory to path
    import sys
    sys.path.append('.')
    import versioneer
    __version__ = versioneer.get_version()
    del sys.path[-1]
    return __version__
```
