### ISSUE TITLE
conda-build not seeming to pick up git env variables

### ISSUE THREAD

**Issue by jreback** [conda/conda-build#764]
conda-build 1.19

I recall this working previously (3 mo ago)

``conda build conda.recipe --no-test --numpy 1.10 --python 2.7``

```
package:
    name: pandas
    version: {{ environ.get('GIT_DESCRIBE_TAG', '') }}

build:
    number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
    string: np{{ environ.get('NPY_VER').replace('.', '') }}py{{ environ.get('PY_VER').replace('.', '') }}_{{ environ.get('GIT_BUILD_STR', '') }}

source:
    git_url: ../

requirements:
  build:
    - python
    - cython
    - numpy x.x
    - setuptools
    - pytz
    - python-dateutil

  run:
    - python
    - numpy x.x
    - python-dateutil
    - pytz

test:
  imports:
    - pandas

about:
  home: http://pandas.pydata.org
  license: BSD
```

**Comment by msarahan** [comment]
Ping @stuarteberg - I think you know the most about this stuff.  It seems that none of these GIT_DESCRIBE_ variables are getting defined.  What are the requirements for those to be defined?

**Comment by stuarteberg** [comment]
I don't know exactly why conda-build 1.19 doesn't work for that recipe, but I did notice that my recent changes in #758 will also have trouble with a recipe like this.  Hence, I just submitted #765.

>What are the requirements for those to be defined?

The only requirement is that you define `git_url`.  As of 7689ae1e8a8965cec405f2a4db3f1f94c5d02ce5 (and a little fix in fddfb3209a85be286f013006f8c687e5a165ee72), the `path` field cannot be used if you want to use `GIT_` variables -- you have to use `git_url`.

**Comment by jreback** [comment]
@stuarteberg I just tried with conda-build master (where #765) is merged, does not appear to fix this issue (with my given recipe). Is there something I can tweek in the recipe to make the variables work?

**Comment by jreback** [comment]
```
conda-build               1.19.0+13.g48c3b7a           <pip>
```

```
[jreback-~/pandas] conda build conda.recipe --no-test --python 2.7 --numpy 1.10
Removing old build environment
Removing old work directory
BUILD START: pandas--np110py27_
Fetching package metadata: ................
WARNING: Could not detect installed version of conda-build
Solving package specifications: ................
The following NEW packages will be INSTALLED:

    cython:          0.23.4-py27_1
    mkl:             11.3.1-0     
    numpy:           1.10.4-py27_0
    openssl:         1.0.2d-0     
    pip:             8.0.2-py27_0 
    python:          2.7.11-0     
    python-dateutil: 2.4.2-py27_0 
    pytz:            2015.7-py27_0
    readline:        6.2-2        
    setuptools:      19.6.2-py27_0
    six:             1.10.0-py27_0
    sqlite:          3.9.2-0      
    tk:              8.5.18-0     
    wheel:           0.29.0-py27_0
    zlib:            1.2.8-0      

Linking packages ...
```

**Comment by stuarteberg** [comment]
It works for me, but I think I figured out why it's not working for you.  Your recipe provides `git_url`, but does not provide a `git_tag`.  Since `git_tag` is missing, we assume you meant `master`.  But if you are currently testing via a branch, then the commit of `conda-bld/work` won't match the name `master`.  My changes in #765 require that the checkout git tag matches the `git_tag` from your `meta.yaml` file, or else it refuses to define `GIT_DESCRIBE_TAG`, etc.

So... does it work if you add `git_tag` to your recipe?

**Comment by stuarteberg** [comment]
BTW, you can simplify the jinja templates in your `meta.yaml` file:

```yaml
package:
    name: pandas
    version: {{ GIT_DESCRIBE_TAG.replace('.dev', 'dev') }} # Requires #771

build:
    number: {{ GIT_DESCRIBE_NUMBER|int }}
    string: np{{ CONDA_NPY }}py{{ CONDA_PY }}_{{ GIT_BUILD_STR }}

```

Well, the syntax in the `version` field is using `.replace`, which won't work until #771 is merged.  But the rest of it already works.
