### ISSUE TITLE
Conda skeleton Cran error

### ISSUE THREAD

**Issue by GANDALF-THEGREY** [conda/conda-build#769]
Hi I get the following error when i run `conda skeleton cran r-rattle`

Traceback (most recent call last):
  File "/home/X/anaconda3/bin/conda-skeleton", line 5, in <module>
    sys.exit(main())
  File "/home/X/anaconda3/lib/python3.5/site-packages/conda_build/main_skeleton.py", line 272, in main
    args_func(args, p)
  File "/home/X/anaconda3/lib/python3.5/site-packages/conda_build/main_build.py", line 486, in args_func
    args.func(args, p)
  File "/home/X/anaconda3/lib/python3.5/site-packages/conda_build/main_skeleton.py", line 290, in execute
    cran.main(args, parser)
  File "/home/X/anaconda3/lib/python3.5/site-packages/conda_build/cran.py", line 574, in main
    d = {k:unicodedata.normalize("NFKD", compat.text_type(v)).encode('ascii', 'ignore') for k, v in d.iteritems()}
AttributeError: 'dict' object has no attribute 'iteritems'

This happens whenever I run conda skeleton cran for any package. I remember the skeleton cran command working a few days back, I have installed some packages before this way

**Comment by edurand** [comment]
Same error here.

**Comment by jameslamb** [comment]
I think this issue can be safely closed. The error has been fixed some time in the 4 years since it was opened.

```shell
conda skeleton cran r-rattle
```

The command for me works!

<details><summary>logs</summary>

```
Adding in variants from internal_defaults
INFO:conda_build.variants:Adding in variants from internal_defaults
Parsing input package r-rattle:
.. name: rattle location: None new_location: /Users/jlamb/repos/sandbox/stuff/r-rattle
Making/refreshing recipe for rattle
Tip: install CacheControl and lockfile (conda packages) to cache the CRAN metadata
Fetching main index from https://cran.r-project.org
/Users/jlamb/miniconda3/lib/python3.6/site-packages/urllib3/connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
/Users/jlamb/miniconda3/lib/python3.6/site-packages/urllib3/connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
Downloading source from https://cran.r-project.org/src/contrib/rattle_5.3.0.tar.gz
No hash (md5, sha1, sha256) provided for source-rattle_5.3.0.tar.gz.  Source download forced.  Add hash to recipe to use source cache.
WARNING:conda_build.source:No hash (md5, sha1, sha256) provided for source-rattle_5.3.0.tar.gz.  Source download forced.  Add hash to recipe to use source cache.
Reading package metadata from /Users/jlamb/miniconda3/conda-bld/src_cache/source-rattle_5.3.0_675cce1a6d.tar.gz
Writing recipe for rattle
--dirty flag and --keep-old-work not specified. Removing build/test folder after successful build/test.

INFO:conda_build.config:--dirty flag and --keep-old-work not specified. Removing build/test folder after successful build/test.
```

</details>

<details><summary>meta.yaml that was generated</summary>

```
{% set version = '5.3.0' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rattle
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/rattle_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rattle/rattle_{{ version }}.tar.gz
  sha256: 675cce1a6dd263ad59d9d34bbb378bca86e9dcf50a3549ca1846595f60b53cea

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0
  # no skip

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: pmml (>= 1.2.13), bitops, colorspace, ada, amap, arules, arulesViz, biclust, cairoDevice, cba, cluster, corrplot, descr, doBy, e1071, ellipse, fBasics, foreign, fpc, gdata, ggdendro, ggraptR, gplots, grid, gridExtra, gtools, gWidgetsRGtk2, hmeasure, Hmisc, kernlab, Matrix, mice, nnet, party, plyr, psych, randomForest, RColorBrewer, readxl, reshape, rggobi, RGtk2, ROCR, RODBC, rpart, scales, SnowballC, survival, timeDate, tm, verification, wskm, xgboost
requirements:
  build:
    - {{posix}}zip               # [win]

  host:
    - r-base
    - r-xml
    - r-dplyr
    - r-ggplot2
    - r-magrittr
    - r-rpart.plot
    - r-stringi
    - r-stringr
    - r-tidyr

  run:
    - r-base
    - r-xml
    - r-dplyr
    - r-ggplot2
    - r-magrittr
    - r-rpart.plot
    - r-stringi
    - r-stringr
    - r-tidyr

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('rattle')"           # [not win]
    - "\"%R%\" -e \"library('rattle')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://rattle.togaware.com/
  license: GPL-2
  summary: The R Analytic Tool To Learn Easily (Rattle) provides a collection of utilities functions
    for the data scientist. A Gnome (RGtk2) based graphical interface is included with
    the aim to provide a simple and intuitive introduction to R for data science, allowing
    a user to quickly load data from a CSV file (or via ODBC), transform and explore
    the data, build and evaluate models, and export models as PMML (predictive modelling
    markup language) or as scores. A key aspect of the GUI is that all R commands are
    logged and commented through the log tab. This can be saved as a standalone R script
    file and as an aid for the user to learn R or to copy-and-paste directly into R
    itself.
  license_family: GPL2
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

# The original CRAN metadata for this package was:

# Package: rattle
# Type: Package
# Title: Graphical User Interface for Data Science in R
# Version: 5.3.0
# Date: 2019-12-16
# Authors@R: c(person("Graham", "Williams", role=c("aut", "cph", "cre"), email="Graham.Williams@togaware.com"), person("Mark", "Vere Culp", role="cph"), person("Ed", "Cox", role="ctb"), person("Anthony", "Nolan", role="ctb"), person("Denis", "White", role="cph"), person("Daniele", "Medri", role="ctb"), person("Akbar", "Waljee", role="ctb", comment="OOB AUC for Random Forest"), person("Brian", "Ripley", role="cph", comment="print.summary.nnet"), person("Jose", "Magana", role="ctb", comment="ggpairs plots"), person("Surendra", "Tipparaju", role="ctb", comment="initial RevoScaleR/XDF"), person("Durga", "Prasad Chappidi", role="ctb", comment="initial RevoScaleR/XDF"), person("Dinesh", "Manyam Venkata", role="ctb", comment="initial RevoScaleR/XDF"), person("Mrinal", "Chakraborty", role="ctb", comment="initial RevoScaleR/XDF"), person("Fang", "Zhou", role="ctb", comment="initial xgboost"), person("Cameron", "Chisholm", role="ctb", comment="risk plot on risk chart"))
# Depends: R (>= 3.5.0)
# Imports: stats, utils, ggplot2, grDevices, graphics, magrittr, methods, stringi, stringr, tidyr, dplyr, XML, rpart.plot
# Suggests: pmml (>= 1.2.13), bitops, colorspace, ada, amap, arules, arulesViz, biclust, cairoDevice, cba, cluster, corrplot, descr, doBy, e1071, ellipse, fBasics, foreign, fpc, gdata, ggdendro, ggraptR, gplots, grid, gridExtra, gtools, gWidgetsRGtk2, hmeasure, Hmisc, kernlab, Matrix, mice, nnet, party, plyr, psych, randomForest, RColorBrewer, readxl, reshape, rggobi, RGtk2, ROCR, RODBC, rpart, scales, SnowballC, survival, timeDate, tm, verification, wskm, xgboost
# Description: The R Analytic Tool To Learn Easily (Rattle) provides a collection of utilities functions for the data scientist. A Gnome (RGtk2) based graphical interface is included with the aim to provide a simple and intuitive introduction to R for data science, allowing a user to quickly load data from a CSV file (or via ODBC), transform and explore the data, build and evaluate models, and export models as PMML (predictive modelling markup language) or as scores. A key aspect of the GUI is that all R commands are logged and commented through the log tab. This can be saved as a standalone R script file and as an aid for the user to learn R or to copy-and-paste directly into R itself.
# License: GPL (>= 2)
# LazyLoad: yes
# LazyData: yes
# URL: https://rattle.togaware.com/
# NeedsCompilation: no
# Packaged: 2019-12-16 02:56:19 UTC; gjw
# Author: Graham Williams [aut, cph, cre], Mark Vere Culp [cph], Ed Cox [ctb], Anthony Nolan [ctb], Denis White [cph], Daniele Medri [ctb], Akbar Waljee [ctb] (OOB AUC for Random Forest), Brian Ripley [cph] (print.summary.nnet), Jose Magana [ctb] (ggpairs plots), Surendra Tipparaju [ctb] (initial RevoScaleR/XDF), Durga Prasad Chappidi [ctb] (initial RevoScaleR/XDF), Dinesh Manyam Venkata [ctb] (initial RevoScaleR/XDF), Mrinal Chakraborty [ctb] (initial RevoScaleR/XDF), Fang Zhou [ctb] (initial xgboost), Cameron Chisholm [ctb] (risk plot on risk chart)
# Maintainer: Graham Williams <Graham.Williams@togaware.com>
# Repository: CRAN
# Date/Publication: 2019-12-16 06:20:03 UTC

# See
# https://docs.conda.io/projects/conda-build for
# more information about meta.yaml
```
</details>

<details><summary>Environment info</summary>

Python version: 3.6.10

`conda`  package versions:

```
conda==4.8.3
conda-build==3.19.2
conda-package-handling==1.6.0
conda-smithy==3.6.17
```

</details>
