### ISSUE TITLE
setting vc9 does not switch the vcvarsall.bat call to vs9

### ISSUE THREAD

**Issue by JanSchulz** [conda/conda-build#779]
I'm trying to compile python on appveyor via a conda-build-all setup and uses the recipe from conda-recipes with some changes:

```
source:
  fn: Python-2.7.8.tgz
[...]
build:
  features:
    - vc9  [win]
```

This results in the following build call:

```
...
Package: python-2.7.8-vc9_0
source tree in: C:\conda\conda-bld\work\Python-2.7.8
 
C:\conda\conda-bld\work\Python-2.7.8>call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86  
...
 ```

IMO the `vc9` feature should switch the vcvarsall.bat call to 9.0.
