### ISSUE TITLE
conda-build 0.19.1 breaks C compilation

### ISSUE THREAD

**Issue by jakevdp** [conda/conda-build#818]
I am using conda build on [this recipe]()

It works on 0.19.0, but on 0.19.1 fails with this message:
```
creating build/temp.macosx-10.5-x86_64-3.5
creating build/temp.macosx-10.5-x86_64-3.5/pyamg
creating build/temp.macosx-10.5-x86_64-3.5/pyamg/amg_core
compile options: '-D__STDC_FORMAT_MACROS=1 -I/Users/jakevdp/anaconda/envs/_build/lib/python3.5/site-packages/numpy/core/include -I/Users/jakevdp/anaconda/envs/_build/include/python3.5m -c'
g++: pyamg/amg_core/amg_core_wrap.cxx
g++ -bundle -undefined dynamic_lookup -L/Users/jakevdp/anaconda/envs/_build/lib -rpath /Users/jakevdp/anaconda/envs/_build/lib -rpath /Users/jakevdp/anaconda/envs/_build/lib -arch x86_64 build/temp.macosx-10.5-x86_64-3.5/pyamg/amg_core/amg_core_wrap.o -L/Users/jakevdp/anaconda/envs/_build/lib -o build/lib.macosx-10.5-x86_64-3.5/pyamg/amg_core/_amg_core.cpython-35m-darwin.so
g++: error: unrecognized command line option ‘-rpath’
g++: error: unrecognized command line option ‘-rpath’
g++: error: unrecognized command line option â-rpathâ
g++: error: unrecognized command line option â-rpathâ
error: Command "g++ -bundle -undefined dynamic_lookup -L/Users/jakevdp/anaconda/envs/_build/lib -rpath /Users/jakevdp/anaconda/envs/_build/lib -rpath /Users/jakevdp/anaconda/envs/_build/lib -arch x86_64 build/temp.macosx-10.5-x86_64-3.5/pyamg/amg_core/amg_core_wrap.o -L/Users/jakevdp/anaconda/envs/_build/lib -o build/lib.macosx-10.5-x86_64-3.5/pyamg/amg_core/_amg_core.cpython-35m-darwin.so" failed with exit status 1
Command failed: /bin/bash -x -e /Users/jakevdp/Opensource/megaman/conda_recipes/pyamg/build.sh
```

**Comment by stuarteberg** [comment]
Looks like #808 is the relevant changeset.

**Comment by stuarteberg** [comment]
If you could change your copy of `conda_build/environ.py`, line 212 from this:

```python
        rpath = ' -rpath %(PREFIX)s/lib' % d # SIP workaround, DYLD_* no longer works.
```

to this:

```python
        rpath = ' -Wl,-rpath,%(PREFIX)s/lib' % d # SIP workaround, DYLD_* no longer works.
```

and report back, that would be useful.

**Comment by jakevdp** [comment]
Everything works fine with that patch.

**Comment by stuarteberg** [comment]
BTW, there's a bug in your recipe:

If you're going to use conda's `gcc` package as a `build` dependency, then you should include `libgcc` as a `run` dependency.  Currently, it's missing from your `meta.yaml`:

```yaml
requirements:
    build:
        - python
        - numpy
        - scipy
        - nose
        - zlib  # [linux]
        - gcc # [osx]
    run:
        - python
        - numpy
        - scipy
        - zlib  # [linux]```

        - libgcc # [osx]       # <----  Add this line!
```

... and I strongly recommend specifying the version of gcc.  Someday when gcc-5 is added to the mix (which may or may not break ABI compatibility, at least for C++ packages), you'll be glad you did.

```yaml
requirements:
    build:
        - gcc 4.8.* # [osx]
    run:
        - libgcc 4.8.* # [osx]
```

And finally, I like to make it super clear in `build.sh` that I'm not using the system compiler:

```
#!/bin/bash

# On OSX, we need to ensure we're using conda's gcc/g++
if [[ `uname` == Darwin ]]; then
    export CC=${PREFIX}/bin/gcc
    export LD=${PREFIX}/bin/gcc
    export CXX=${PREFIX}/bin/g++
fi

$PYTHON setup.py install
```

BTW, I've never seen the `LD` variable set in a recipe before (which could just be lack of experience on my part).  I wonder if that's why you saw this error about `-rpath` while others haven't.

**Comment by stuarteberg** [comment]
>Everything works fine with that patch.

Good to hear.  I'll submit a PR later today.

**Comment by stuarteberg** [comment]
>would you mind glancing through the other three recipes here and letting me know if you see any glaring issues?

It looks like you're building C/C++/Cython extension modules which may depend on the numpy ABI.  (That is, if you build the package against numpy 1.9, you can't use it with numpy 1.10.)  If that's true, then it's very important that you nail down the numpy version in your recipes.

One way to do that is to hard-code the numpy version into the recipe:

```yaml
requirements:
    build:
        - python
        - cython
        - numpy 1.10*
        - flann
        - gcc 4.8.* [osx]
    run:
        - python
        - numpy 1.10*
        - scipy
        - scikit-learn
        - pyamg
        - pyflann
        - libgcc 4.8.* [osx]
```

That's a little annoying because you'll have to update the text in `meta.yaml` several times if you want to build your package for several versions of numpy.  One way of improving the situation is to replace the version number conda's hacky `x.x` syntax.  (This works for only python and numpy, so don't try it with anything else.)

```yaml
requirements:
    build:
        - python
        - cython
        - numpy x.x
        - flann
        - gcc 4.8* # [osx]
    run:
        - python
        - numpy x.x
        - scipy
        - scikit-learn
        - pyamg
        - pyflann
        - libgcc 4.8* # [osx]
```

Personally, I think it's clearer to use conda's built-in support for jinja templates, which have access to your environment variables (including the ones [defined by conda itself][1] during the build):

[1]: http://conda.pydata.org/docs/building/environment-vars.html#environment-variables

```yaml
requirements:
    build:
        - python {{PY_VER}}*
        - cython
        - numpy {{NPY_VER}}*
        - flann
        - gcc 4.8* # [osx]
    run:
        - python {{PY_VER}}*
        - numpy {{NPY_VER}}*
        - scipy
        - scikit-learn
        - pyamg
        - pyflann
        - libgcc 4.8* # [osx]
```

Either way, you can then specify which version of `numpy` (and/or python) to use on the command line when you build your recipe:

`conda build --python=3.5 --numpy=1.10 conda_recipes/megaman`

Since your [installation instructions][2] specify additional constraints on which python/numpy versions are acceptable, you should add those constraints to the requirements, too.

[2]: https://github.com/mmp2/megaman#installation-from-source

```yaml
requirements:
    build:
        - python >=2.7,<3|>=3.4,{{PY_VER}}*
        - cython
        - numpy >=1.8,{{NPY_VER}}*
        - flann
        - gcc 4.8* # [osx]
    run:
        - python {{PY_VER}}*
        - numpy {{NPY_VER}}*
        - scipy
        - scikit-learn
        - pyamg
        - pyflann
        - libgcc 4.8* # [osx]
```

Now, if someone tries to run `conda build --numpy=1.7 conda_recipes/megaman`, then `PY_VER` will conflict with the other constraints, and the resolver will kick back an error.

Finally, for consistency with the naming conventions that the Anaconda project uses, you should consider specifying a build string.  I suggest this:

```yaml
build:
  number: 2
  string: np{{CONDA_NPY}}py{{CONDA_PY}}_{{PKG_BUILDNUM}}
```

Which will result in a package name like `megaman-0.1.1-np110py27_2.tar.bz2`.  If you choose to use the `x.x` syntax mentioned above, then conda might be able to automatically format the build string like that.  But I like to follow "explicit is better than implicit".

For my own projects, in which I often build packages from a non-tagged version, I like to add a hint to the build string that tells me what commit I was using at the time:

```yaml
source:
  git_url: ../
  git_rev: HEAD

build:
  number: 2
  string: np{{CONDA_NPY}}py{{CONDA_PY}}_{{PKG_BUILDNUM}}_g{{GIT_FULL_HASH[:7]}}
```

Some additional, minor points:

I recommend always putting selectors in a comment:

```yaml
# Bad:
requirements:
    build:
      - gcc 4.8* [osx]

# Good:
requirements:
    build:
      - gcc 4.8* # [osx]
```

Also, IIUC, there is a slight difference between this:

```yaml
requirements:
    run:
      - numpy 1.9*
```

and this:

```
requirements:
    build:
      - numpy 1.9.*
```

The former can match 1.9 and 1.9.0, whereas the latter can only match 1.9.0.  Therefore, I think the former is preferred.
