### ISSUE TITLE
Conda needs to activate _build and _test environments - not monkey with PATH

### ISSUE THREAD

**Issue by jakirkham** [conda/conda-build#910]
When using the following recipe.

```
package:
  name: blas_openblas
  version: 1.0.0

build:
  number: 0
  track_features:
    - blas_openblas

test:
  commands:
    - conda list blas_openblas

about:
  home: NA
  license: NA
  summary: Metapackage to enable the use of OpenBLAS in an environment.

extra:
  recipe-maintainers:
    - jakirkham
```

I run the build, but it appears not to activate the `_test` environment during the testing phase, but remains in the `_build` environment. Here is a snippet that I see in the log.

```
TEST START: blas_openblas-1.0.0-0
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: ..............
.Solving package specifications: .........

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    blas_openblas-1.0.0        |                0          657 B  file:///zopt/conda2/conda-bld/osx-64/

The following NEW packages will be INSTALLED:

    blas_openblas: 1.0.0-0 file:///zopt/conda2/conda-bld/osx-64/

Fetching packages ...
blas_openblas- 100% |#############################################################################################################| Time: 0:00:00 947.94 kB/s
Extracting packages ...
[      COMPLETE      ]|################################################################################################################################| 100%
Linking packages ...
[      COMPLETE      ]|################################################################################################################################| 100%
+ conda list blas_openblas
Error: Error: environment does not exist: /zopt/conda2/envs/_build
#
# Use 'conda create' to create an environment before listing its packages.
TESTS FAILED: blas_openblas-1.0.0-0
```
